import Mathlib.CategoryTheory.Quotient.Linear
import Mathlib.LinearAlgebra.Span.Basic
import QuotientSubmoduleEquidistribution.CategoryTheory.IdealQuotient

/-!
# Linear two-sided Hom ideals generated by relations

This file constructs the Hom ideal linearly generated by a family of
categorical relations and equips its categorical quotient with the inherited
linear structure.
-/

noncomputable section

open CategoryTheory

namespace QuotientSubmoduleEquidistribution.CategoricalIdeal

universe w v u

variable {K : Type w} {C : Type u}
  [Ring K] [Category.{v} C] [Preadditive C] [Linear K C]

namespace HomIdeal

/-- Morphisms obtained by composing a specified relation on both sides. -/
def twoSidedCompositeSet
    (R : ∀ X Y : C, Set (X ⟶ Y)) (X Y : C) : Set (X ⟶ Y) :=
  {f | ∃ (A B : C) (r : A ⟶ B), r ∈ R A B ∧
      ∃ (a : X ⟶ A) (b : B ⟶ Y), f = a ≫ r ≫ b}

/-- The linear span of all two-sided composites through a relation generator. -/
def generatedHomSubmodule
    (𝕜 : Type w) [Ring 𝕜] [Linear 𝕜 C]
    (R : ∀ X Y : C, Set (X ⟶ Y)) (X Y : C) : Submodule 𝕜 (X ⟶ Y) :=
  Submodule.span 𝕜 (twoSidedCompositeSet R X Y)

/-- The two-sided additive Hom ideal linearly generated by `R`. -/
def linearSpan
    (𝕜 : Type w) [Ring 𝕜] [Linear 𝕜 C]
    (R : ∀ X Y : C, Set (X ⟶ Y)) : HomIdeal C where
  hom X Y := (generatedHomSubmodule 𝕜 R X Y).toAddSubgroup
  precomp := by
    intro X Y Z f g hg
    change f ≫ g ∈ generatedHomSubmodule 𝕜 R X Z
    change g ∈ generatedHomSubmodule 𝕜 R Y Z at hg
    induction hg using Submodule.span_induction with
    | mem g hg =>
        rcases hg with ⟨A, B, r, hr, a, b, rfl⟩
        apply Submodule.subset_span
        exact ⟨A, B, r, hr, f ≫ a, b, by simp [Category.assoc]⟩
    | zero => simp
    | add g h _ _ hg hh =>
        simpa using (generatedHomSubmodule 𝕜 R X Z).add_mem hg hh
    | smul k g _ hg =>
        simpa using (generatedHomSubmodule 𝕜 R X Z).smul_mem k hg
  postcomp := by
    intro X Y Z f g hf
    change f ≫ g ∈ generatedHomSubmodule 𝕜 R X Z
    change f ∈ generatedHomSubmodule 𝕜 R X Y at hf
    induction hf using Submodule.span_induction with
    | mem f hf =>
        rcases hf with ⟨A, B, r, hr, a, b, rfl⟩
        apply Submodule.subset_span
        exact ⟨A, B, r, hr, a, b ≫ g, by simp [Category.assoc]⟩
    | zero => simp
    | add f h _ _ hf hh =>
        simpa using (generatedHomSubmodule 𝕜 R X Z).add_mem hf hh
    | smul k f _ hf =>
        simpa using (generatedHomSubmodule 𝕜 R X Z).smul_mem k hf

@[simp]
theorem linearSpan_hom
    (R : ∀ X Y : C, Set (X ⟶ Y)) (X Y : C) :
    (linearSpan K R).hom X Y =
      (generatedHomSubmodule K R X Y).toAddSubgroup :=
  rfl

/-- Every specified relation belongs to its generated Hom ideal. -/
theorem relation_mem_linearSpan
    (R : ∀ X Y : C, Set (X ⟶ Y))
    {X Y : C} {r : X ⟶ Y} (hr : r ∈ R X Y) :
    r ∈ (linearSpan K R).hom X Y := by
  apply Submodule.subset_span
  exact ⟨X, Y, r, hr, 𝟙 X, 𝟙 Y, by simp⟩

/-- Every two-sided composite through a relation belongs to the generated ideal. -/
theorem composite_mem_linearSpan
    (R : ∀ X Y : C, Set (X ⟶ Y))
    {X Y A B : C} (a : X ⟶ A) {r : A ⟶ B} (hr : r ∈ R A B)
    (b : B ⟶ Y) :
    a ≫ r ≫ b ∈ (linearSpan K R).hom X Y := by
  apply Submodule.subset_span
  exact ⟨A, B, r, hr, a, b, rfl⟩

/-- A Hom ideal in a linear category is automatically closed under scalars. -/
theorem smul_mem
    (I : HomIdeal C) {X Y : C} (k : K) {f : X ⟶ Y}
    (hf : f ∈ I.hom X Y) :
    k • f ∈ I.hom X Y := by
  simpa using I.precomp (k • 𝟙 X) hf

/-- Minimality of the linearly generated Hom ideal. -/
theorem linearSpan_le
    (R : ∀ X Y : C, Set (X ⟶ Y)) (I : HomIdeal C)
    (hR : ∀ {X Y : C} {r : X ⟶ Y}, r ∈ R X Y → r ∈ I.hom X Y) :
    ∀ {X Y : C} {f : X ⟶ Y},
      f ∈ (linearSpan K R).hom X Y → f ∈ I.hom X Y := by
  intro X Y f hf
  change f ∈ generatedHomSubmodule K R X Y at hf
  induction hf using Submodule.span_induction with
  | mem f hf =>
      rcases hf with ⟨A, B, r, hr, a, b, rfl⟩
      simpa [Category.assoc] using I.postcomp b (I.precomp a (hR hr))
  | zero => exact (I.hom X Y).zero_mem
  | add f g _ _ hf hg => exact (I.hom X Y).add_mem hf hg
  | smul k f _ hf => exact I.smul_mem k hf

/-- Universal property of the generated ideal. -/
theorem linearSpan_le_iff
    (R : ∀ X Y : C, Set (X ⟶ Y)) (I : HomIdeal C) :
    (∀ {X Y : C} {f : X ⟶ Y},
        f ∈ (linearSpan K R).hom X Y → f ∈ I.hom X Y) ↔
      ∀ {X Y : C} {r : X ⟶ Y}, r ∈ R X Y → r ∈ I.hom X Y := by
  constructor
  · intro h X Y r hr
    exact h (relation_mem_linearSpan R hr)
  · exact linearSpan_le R I

/-- Congruence modulo a Hom ideal is compatible with scalar multiplication. -/
theorem rel_smul_compatible
    (I : HomIdeal C) (k : K) {X Y : C} (f g : X ⟶ Y)
    (hfg : I.rel f g) :
    I.rel (k • f) (k • g) := by
  change k • f - k • g ∈ I.hom X Y
  rw [← smul_sub]
  exact I.smul_mem k hfg

/-- The induced linear structure on a Hom-ideal quotient. -/
abbrev quotientLinear (I : HomIdeal C) :
    letI : Preadditive (CategoryTheory.Quotient I.rel) := I.quotientPreadditive
    letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
      CategoryTheory.Quotient.functor_additive I.rel
        (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
          I.add_compatible f₁ f₂ g₁ g₂ hf hg)
    Linear K (CategoryTheory.Quotient I.rel) :=
  letI : Preadditive (CategoryTheory.Quotient I.rel) := I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  CategoryTheory.Quotient.linear K I.rel
    (fun k {_ _} f g hfg ↦ I.rel_smul_compatible k f g hfg)

/-- The quotient functor is linear for the induced quotient structure. -/
abbrev quotientFunctorLinear (I : HomIdeal C) :
    letI : Preadditive (CategoryTheory.Quotient I.rel) := I.quotientPreadditive
    letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
      CategoryTheory.Quotient.functor_additive I.rel
        (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
          I.add_compatible f₁ f₂ g₁ g₂ hf hg)
    letI : Linear K (CategoryTheory.Quotient I.rel) := I.quotientLinear
    (CategoryTheory.Quotient.functor I.rel).Linear K :=
  letI : Preadditive (CategoryTheory.Quotient I.rel) := I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  letI : Linear K (CategoryTheory.Quotient I.rel) := I.quotientLinear
  CategoryTheory.Quotient.linear_functor K I.rel
    (fun k {_ _} f g hfg ↦ I.rel_smul_compatible k f g hfg)

end HomIdeal

end QuotientSubmoduleEquidistribution.CategoricalIdeal
