import MainResults

/-!
# Release audit

Compiling this file confirms that every advertised declaration is present in
the pinned environment.  `#print axioms` records the kernel-visible axiom
dependencies used by each theorem.
-/

#print axioms QuotientSubmoduleEquidistribution.MainTheoremEndpoint.rightQuotientSubmoduleEquidistribution
#print axioms QuotientSubmoduleEquidistribution.BottomLevels.FiniteDimensionalRecurrence.FirstLastFourEndpoint.bottom_top_four
#print axioms QuotientSubmoduleEquidistribution.BottomLevels.FiniteDimensionalRecurrence.FirstLastFourEndpoint.equidistribution_of_card_le_nine
#print axioms QuotientSubmoduleEquidistribution.NakayamaAlgebraProductFormula.rightRepresentationFinite_of_isRightNakayamaAlgebra
#print axioms QuotientSubmoduleEquidistribution.NakayamaAlgebraProductFormula.rightQuotientSubmoduleEquidistribution
#print axioms QuotientSubmoduleEquidistribution.RadicalSquareZero.rightQuotientSubmoduleEquidistribution_of_squareZero
#print axioms QuotientSubmoduleEquidistribution.rightRepresentationDirected_quotientSubmoduleEquidistribution
#print axioms QuotientSubmoduleEquidistribution.IndecomposableSkeleton.isPaperNormal_iff_isMinimalGenerator
#print axioms QuotientSubmoduleEquidistribution.IndecomposableSkeleton.intrinsicBasicNormalIsoClassEquivCompactClosed
#print axioms QuotientSubmoduleEquidistribution.rightModule_compact_iff_functoriallyFinite
#print axioms QuotientSubmoduleEquidistribution.IndecomposableSkeleton.qCompact_isMinimalGenerator_iff_eq_relativeSplitProjectives
