import QuotientSubmoduleEquidistribution.RepresentationTheory.MainTheoremEndpoint
import QuotientSubmoduleEquidistribution.RepresentationTheory.FirstLastFourEndpoint
import QuotientSubmoduleEquidistribution.RepresentationTheory.NakayamaAlgebraProductFormula
import QuotientSubmoduleEquidistribution.RadicalSquareZero.SeparatedDirectedInterface
import QuotientSubmoduleEquidistribution.RepresentationDirected.AlgebraEndpoint
import QuotientSubmoduleEquidistribution.RepresentationTheory.IntrinsicNormalModules
import QuotientSubmoduleEquidistribution.RepresentationTheory.ConvexStructure

/-!
# Main results

This file imports the theorem modules for the four-case main theorem and the
listed structural results, and checks their stable declaration names.
-/

#check QuotientSubmoduleEquidistribution.MainTheoremEndpoint.MainTheoremWitness
#check QuotientSubmoduleEquidistribution.MainTheoremEndpoint.rightQuotientSubmoduleEquidistribution
#check QuotientSubmoduleEquidistribution.BottomLevels.FiniteDimensionalRecurrence.FirstLastFourEndpoint.bottom_top_four
#check QuotientSubmoduleEquidistribution.BottomLevels.FiniteDimensionalRecurrence.FirstLastFourEndpoint.equidistribution_of_card_le_nine
#check QuotientSubmoduleEquidistribution.NakayamaAlgebraProductFormula.rightRepresentationFinite_of_isRightNakayamaAlgebra
#check QuotientSubmoduleEquidistribution.NakayamaAlgebraProductFormula.rightQuotientSubmoduleEquidistribution
#check QuotientSubmoduleEquidistribution.RadicalSquareZero.rightQuotientSubmoduleEquidistribution_of_squareZero
#check QuotientSubmoduleEquidistribution.rightRepresentationDirected_quotientSubmoduleEquidistribution
#check QuotientSubmoduleEquidistribution.rightRepresentationDirectedWord_isReduced
#check QuotientSubmoduleEquidistribution.rightRepresentationDirectedProfile
#check QuotientSubmoduleEquidistribution.rightRepresentationDirected_levelPolynomials_eq_bruhat
#check QuotientSubmoduleEquidistribution.RepresentationDirected.FactorARWord.selectedWordMixedMultiplicityFor_eq_factorHomDimension_of_reduced
#check QuotientSubmoduleEquidistribution.IndecomposableSkeleton.isPaperNormal_iff_isMinimalGenerator
#check QuotientSubmoduleEquidistribution.IndecomposableSkeleton.intrinsicBasicNormalIsoClassEquivCompactClosed
#check QuotientSubmoduleEquidistribution.rightModule_compact_iff_functoriallyFinite
#check QuotientSubmoduleEquidistribution.IndecomposableSkeleton.qCompact_isMinimalGenerator_iff_eq_relativeSplitProjectives
#check QuotientSubmoduleEquidistribution.SetClosure.finiteIndependentEquivCompactClosedSet
#check QuotientSubmoduleEquidistribution.SetClosure.finiteIntervalDeletionChain
#check QuotientSubmoduleEquidistribution.IndecomposableSkeleton.qClosed_finiteIntervalDeletionChain_of_finiteDimensional
