import OpConjecture.RepresentationTheory.MainTheoremEndpoint
import OpConjecture.RepresentationTheory.FirstLastFourEndpoint
import OpConjecture.RepresentationTheory.NakayamaAlgebraProductFormula
import OpConjecture.RadicalSquareZero.SeparatedDirectedInterface
import OpConjecture.RepresentationDirected.AlgebraEndpoint
import OpConjecture.RepresentationTheory.IntrinsicNormalModules

/-!
# Advertised results

This is the stable entry point for the manuscript's formalized main theorem.
It deliberately imports only the paper-facing endpoint modules.
-/

#check OpConjecture.MainTheoremEndpoint.MainTheoremWitness
#check OpConjecture.MainTheoremEndpoint.rightQuotientSubmoduleEquidistribution
#check OpConjecture.BottomLevels.FiniteDimensionalRecurrence.FirstLastFourEndpoint.bottom_top_four
#check OpConjecture.BottomLevels.FiniteDimensionalRecurrence.FirstLastFourEndpoint.equidistribution_of_card_le_nine
#check OpConjecture.NakayamaAlgebraProductFormula.rightRepresentationFinite_of_isRightNakayamaAlgebra
#check OpConjecture.NakayamaAlgebraProductFormula.rightQuotientSubmoduleEquidistribution
#check OpConjecture.RadicalSquareZero.rightQuotientSubmoduleEquidistribution_of_squareZero
#check OpConjecture.rightRepresentationDirected_quotientSubmoduleEquidistribution
#check OpConjecture.IndecomposableSkeleton.isPaperNormal_iff_isMinimalGenerator
#check OpConjecture.IndecomposableSkeleton.intrinsicBasicNormalIsoClassEquivCompactClosed
#check OpConjecture.rightModule_compact_iff_functoriallyFinite
#check OpConjecture.IndecomposableSkeleton.qCompact_isMinimalGenerator_iff_eq_relativeSplitProjectives
