import QuotientSubmoduleEquidistribution.RepresentationTheory.MainTheoremEndpoint
import QuotientSubmoduleEquidistribution.RepresentationTheory.FirstLastFourEndpoint
import QuotientSubmoduleEquidistribution.RepresentationTheory.NakayamaAlgebraProductFormula
import QuotientSubmoduleEquidistribution.RadicalSquareZero.SeparatedDirectedInterface
import QuotientSubmoduleEquidistribution.RepresentationDirected.AlgebraEndpoint
import QuotientSubmoduleEquidistribution.RepresentationTheory.IntrinsicNormalModules

/-!
# Advertised results

This is the stable entry point for the manuscript's formalized main theorem.
It deliberately imports only the paper-facing endpoint modules.
-/

#check QuotientSubmoduleEquidistribution.MainTheoremEndpoint.MainTheoremWitness
#check QuotientSubmoduleEquidistribution.MainTheoremEndpoint.rightQuotientSubmoduleEquidistribution
#check QuotientSubmoduleEquidistribution.BottomLevels.FiniteDimensionalRecurrence.FirstLastFourEndpoint.bottom_top_four
#check QuotientSubmoduleEquidistribution.BottomLevels.FiniteDimensionalRecurrence.FirstLastFourEndpoint.equidistribution_of_card_le_nine
#check QuotientSubmoduleEquidistribution.NakayamaAlgebraProductFormula.rightRepresentationFinite_of_isRightNakayamaAlgebra
#check QuotientSubmoduleEquidistribution.NakayamaAlgebraProductFormula.rightQuotientSubmoduleEquidistribution
#check QuotientSubmoduleEquidistribution.RadicalSquareZero.rightQuotientSubmoduleEquidistribution_of_squareZero
#check QuotientSubmoduleEquidistribution.rightRepresentationDirected_quotientSubmoduleEquidistribution
#check QuotientSubmoduleEquidistribution.IndecomposableSkeleton.isPaperNormal_iff_isMinimalGenerator
#check QuotientSubmoduleEquidistribution.IndecomposableSkeleton.intrinsicBasicNormalIsoClassEquivCompactClosed
#check QuotientSubmoduleEquidistribution.rightModule_compact_iff_functoriallyFinite
#check QuotientSubmoduleEquidistribution.IndecomposableSkeleton.qCompact_isMinimalGenerator_iff_eq_relativeSplitProjectives
