import OpConjecture.RepresentationTheory.EndomorphismRadical

/-!
# Anti-exchange for quotient closure

This file formalizes the trace-and-radical proof of anti-exchange from
the manuscript.  The proof works on a chosen indecomposable skeleton and
assumes that each indecomposable endomorphism ring is Artinian.  That is
the exact ring-theoretic input used to make its Jacobson radical
nilpotent.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace OpConjecture.IndecomposableSkeleton

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} (σ : IndecomposableSkeleton.{u, v, w} R ι)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- The sum of the ranges of all maps from one indecomposable
representative. -/
def pointTrace (i : ι) (X : FGModuleCat.{w} R) :
    Submodule R X :=
  ⨆ f : σ.obj i ⟶ X, LinearMap.range f.hom.hom

omit [IsNoetherianRing R] in
private theorem fg_hom_sum_apply {J : Type*} [Fintype J]
    {X Y : FGModuleCat.{w} R} (f : J → (X ⟶ Y)) (x : X) :
    ((∑ j, f j).hom.hom) x =
      ∑ j, (f j).hom.hom x := by
  have h₁ :
      (∑ j, f j).hom = ∑ j, (f j).hom :=
    map_sum
      (InducedCategory.homAddEquiv :
        (X ⟶ Y) ≃+ (X.obj ⟶ Y.obj))
      f Finset.univ
  rw [h₁, ModuleCat.hom_sum]
  exact LinearMap.sum_apply _ _ x

/-- A singleton trace is already generated by maps from the single
indecomposable, rather than requiring maps from arbitrary finite sums of
its copies. -/
theorem trace_singleton_eq_pointTrace (i : ι)
    (X : FGModuleCat.{w} R) :
    σ.trace {i} X = σ.pointTrace i X := by
  apply le_antisymm
  · apply iSup_le
    intro f
    letI : Fintype f.index := FintypeCat.fintype
    rintro x ⟨y, rfl⟩
    have hmap :
        f.map =
          ∑ t : f.index,
            biproduct.π
                (fun t : f.index ↦ σ.obj (f.label t)) t ≫
              (biproduct.ι
                  (fun t : f.index ↦ σ.obj (f.label t)) t ≫
                f.map) := by
      calc
        f.map = 𝟙 _ ≫ f.map := (Category.id_comp _).symm
        _ =
            (∑ t : f.index,
              biproduct.π
                  (fun t : f.index ↦ σ.obj (f.label t)) t ≫
                biproduct.ι
                  (fun t : f.index ↦ σ.obj (f.label t)) t) ≫
              f.map := by rw [biproduct.total]
        _ = _ := by
          rw [Preadditive.sum_comp]
          simp only [Category.assoc]
    rw [hmap, fg_hom_sum_apply]
    apply Submodule.sum_mem
    intro t _
    have ht : f.label t = i := by
      simpa using f.mem t
    let ft : σ.obj (f.label t) ⟶ X :=
      biproduct.ι (fun t : f.index ↦ σ.obj (f.label t)) t ≫ f.map
    let ft' : σ.obj i ⟶ X :=
      eqToHom (congrArg σ.obj ht.symm) ≫ ft
    have hcat :
        eqToHom (congrArg σ.obj ht) ≫ ft' = ft := by
      dsimp only [ft']
      simp
    have hvalue :
        ft
            ((biproduct.π
              (fun t : f.index ↦ σ.obj (f.label t)) t) y) =
          ft'
            ((eqToHom (congrArg σ.obj ht))
              ((biproduct.π
                (fun t : f.index ↦ σ.obj (f.label t)) t) y)) := by
      exact
        (congrArg
          (fun q : σ.obj (f.label t) ⟶ X ↦
            q
              ((biproduct.π
                (fun t : f.index ↦ σ.obj (f.label t)) t) y))
          hcat).symm
    change
      ft
          ((biproduct.π
            (fun t : f.index ↦ σ.obj (f.label t)) t) y) ∈
        σ.pointTrace i X
    rw [hvalue]
    exact le_iSup
      (fun g : σ.obj i ⟶ X ↦ LinearMap.range g.hom.hom) ft'
      (LinearMap.mem_range_self ft'.hom.hom _)
  · apply iSup_le
    intro f
    exact range_le_trace_of_mem σ (Set.mem_singleton i) f

/-- The selected trace is fully invariant under every underlying
endomorphism, not just an endomorphism already presented categorically. -/
theorem trace_fullyInvariant_linear {S : Set ι}
    (X : FGModuleCat.{w} R) (f : Module.End R X) :
    Submodule.map f (σ.trace S X) ≤ σ.trace S X := by
  let F := forget₂ (FGModuleCat R) (ModuleCat R)
  let fc : X ⟶ X := F.preimage (ModuleCat.ofHom f)
  have hfc : fc.hom.hom = f := by
    have h := F.map_preimage (ModuleCat.ofHom f)
    exact congrArg ModuleCat.Hom.hom h
  rw [← hfc]
  exact trace_fullyInvariant σ X fc

/-- Postcomposition sends the point trace of `i` into the point trace
of `i`. -/
theorem map_pointTrace_le {i : ι}
    {X Y : FGModuleCat.{w} R} (f : X ⟶ Y) :
    Submodule.map f.hom.hom (σ.pointTrace i X) ≤
      σ.pointTrace i Y := by
  rw [pointTrace, Submodule.map_iSup]
  apply iSup_le
  intro g
  rw [← LinearMap.range_comp]
  exact le_iSup
    (fun h : σ.obj i ⟶ Y ↦ LinearMap.range h.hom.hom)
    (g ≫ f)

/-- If `x` and `y` index nonisomorphic representatives, every
endomorphism of `X` factoring through `Y` belongs to the Jacobson
radical of `End(X)`. -/
theorem comp_mem_end_jacobson {x y : ι} (hxy : x ≠ y)
    (f : σ.obj y ⟶ σ.obj x) (g : σ.obj x ⟶ σ.obj y) :
    f.hom.hom.comp g.hom.hom ∈
      Ring.jacobson (Module.End R (σ.obj x)) := by
  apply
    (OpConjecture.mem_end_jacobson_iff_not_isUnit
      (σ.indecomposable x) (σ.finiteLength x)
      (f.hom.hom.comp g.hom.hom)).2
  intro hunit
  obtain ⟨e⟩ :=
    OpConjecture.nonempty_linearEquiv_of_isUnit_comp
      (σ.indecomposable x) (σ.indecomposable y)
      f.hom.hom g.hom.hom hunit
  exact hxy (σ.eq_of_iso ⟨e.toFGModuleCatIso⟩)

/-- Substituting generation of `Y` by `C` and `X` into all maps
`Y → X` shows that the point trace of `Y` in `X` is generated by the
trace of `C` and the Jacobson radical of `End(X)`. -/
theorem pointTrace_le_trace_sup_jacobson
    (C : Set ι) {x y : ι} (hxy : x ≠ y)
    (hY :
      σ.trace C (σ.obj y) ⊔
        σ.pointTrace x (σ.obj y) = ⊤) :
    σ.pointTrace y (σ.obj x) ≤
      σ.trace C (σ.obj x) ⊔
        OpConjecture.idealRange
          (Ring.jacobson (Module.End R (σ.obj x))) := by
  apply iSup_le
  intro f
  rw [← Submodule.map_top, ← hY, Submodule.map_sup]
  apply sup_le_sup
  · exact map_trace_le_trace σ f
  · rw [pointTrace, Submodule.map_iSup]
    apply iSup_le
    intro g
    rw [← LinearMap.range_comp]
    exact OpConjecture.range_le_idealRange _
      (comp_mem_end_jacobson σ hxy f g)

/-- Quotient closure satisfies anti-exchange whenever the relevant
endomorphism rings are Artinian. -/
theorem qClosure_isAntiExchange
    [∀ i : ι, IsArtinianRing (Module.End R (σ.obj i))] :
    σ.qClosure.IsAntiExchange := by
  intro C x y hC hxC _hyC hxy hxgen hygen
  have hxtrace :
      σ.trace C (σ.obj x) ⊔
        σ.pointTrace y (σ.obj x) = ⊤ := by
    have h :=
      (mem_qClosure_iff_trace_eq_top σ (insert y C) x).1 hxgen
    rw [trace_insert, trace_singleton_eq_pointTrace] at h
    exact h
  have hytrace :
      σ.trace C (σ.obj y) ⊔
        σ.pointTrace x (σ.obj y) = ⊤ := by
    have h :=
      (mem_qClosure_iff_trace_eq_top σ (insert x C) y).1 hygen
    rw [trace_insert, trace_singleton_eq_pointTrace] at h
    exact h
  let J := Ring.jacobson (Module.End R (σ.obj x))
  have hsup : σ.trace C (σ.obj x) ⊔
      OpConjecture.idealRange J = ⊤ := by
    apply top_unique
    rw [← hxtrace]
    exact sup_le le_sup_left
      (pointTrace_le_trace_sup_jacobson σ C hxy hytrace)
  have htraceTop : σ.trace C (σ.obj x) = ⊤ := by
    apply OpConjecture.eq_top_of_nilpotent_idealRange J
    · exact trace_fullyInvariant_linear σ (σ.obj x)
    · dsimp only [J]
      exact
        (Ideal.jacobson_bot (R :=
          Module.End R (σ.obj x))) ▸
            IsArtinianRing.isNilpotent_jacobson_bot
    · exact hsup
  apply hxC
  rw [← hC.closure_eq]
  exact (mem_qClosure_iff_trace_eq_top σ C x).2 htraceTop

/-- Under the Artinian endomorphism-ring hypothesis, quotient closure is
a convex geometry. -/
theorem qClosure_isConvexGeometry
    [∀ i : ι, IsArtinianRing (Module.End R (σ.obj i))] :
    σ.qClosure.IsConvexGeometry :=
  ⟨qClosure_isClosed_empty σ, qClosure_isAntiExchange σ⟩

/-- The manuscript's finite-dimensional-over-a-field hypothesis supplies
the Artinian endomorphism rings required for quotient anti-exchange. -/
theorem qClosure_isAntiExchange_of_finiteDimensional
    {K : Type*} [Field K] [Algebra K R]
    [∀ i : ι, Module K (σ.obj i)]
    [∀ i : ι, IsScalarTower K R (σ.obj i)]
    [∀ i : ι, FiniteDimensional K (σ.obj i)] :
    σ.qClosure.IsAntiExchange := by
  letI : ∀ i : ι,
      IsArtinianRing (Module.End R (σ.obj i)) :=
    fun i ↦
      OpConjecture.isArtinianRing_moduleEnd_of_finiteDimensional
        (K := K) (B := R) (M := σ.obj i)
  exact qClosure_isAntiExchange σ

/-- Quotient closure is a convex geometry for the finite-dimensional
module setup used in the manuscript. -/
theorem qClosure_isConvexGeometry_of_finiteDimensional
    {K : Type*} [Field K] [Algebra K R]
    [∀ i : ι, Module K (σ.obj i)]
    [∀ i : ι, IsScalarTower K R (σ.obj i)]
    [∀ i : ι, FiniteDimensional K (σ.obj i)] :
    σ.qClosure.IsConvexGeometry :=
  ⟨qClosure_isClosed_empty σ,
    qClosure_isAntiExchange_of_finiteDimensional (K := K) σ⟩

end OpConjecture.IndecomposableSkeleton
