import OpConjecture.RepresentationTheory.FiniteFacApproximation
import OpConjecture.RepresentationTheory.LiteralLattice
import OpConjecture.RepresentationTheory.NormalModules

/-!
# Finite generators and functorially finite quotient-closed subcategories

This file gives the literal-subcategory form of the Auslander--Smalø
classification: a quotient-closed additive subcategory is functorially finite
exactly when it is generated by one finite basic module.  It also identifies
this condition with compactness.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace OpConjecture.IndecomposableSkeleton

universe uK u v w

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} (σ : IndecomposableSkeleton.{u, v, w} R ι)

/-- The exact canonical form of a witness `C = Fac M` with `M ∈ C`.
The witness is taken basic: it contains each indecomposable in its finite
support once. -/
structure BasicFacGenerator
    (C : QuotientClosedAdditiveSubcategory.{u, w} (R := R)) where
  support : FiniteSupport (ι := ι)
  mem : C.1.carrier (σ.basicModule support)
  carrier_eq :
    C.1.carrier =
      InFacOfModule (σ.basicModule support)

/-- A functorially finite literal quotient-closed subcategory has one finite
basic generator, and conversely. -/
theorem quotientClosed_isFunctoriallyFinite_iff_basicFacGenerator
    (K : Type uK) [Field K] [Algebra K R] [FiniteDimensional K R]
    (G : FGModuleCat.{w} R) (hG : IsFiniteGenerator G)
    (C : QuotientClosedAdditiveSubcategory.{u, w} (R := R)) :
    IsFunctoriallyFinite C.1.carrier ↔
      Nonempty (BasicFacGenerator σ C) := by
  let S := σ.support C.1
  have hcarrier :
      C.1.carrier = σ.InFac S :=
    quotientClosedAdditiveSubcategory_carrier_eq_inFac_support σ C
  constructor
  · intro hff
    have hffS : IsFunctoriallyFinite (σ.InFac S) := by
      rw [← hcarrier]
      exact hff
    obtain ⟨B, hBfinite, hBS, hclosure⟩ :=
      isFunctoriallyFinite_inFac_imp_exists_finite_generator
        σ G hG hffS
    let Bfin : FiniteSupport (ι := ι) := ⟨B, hBfinite⟩
    have hbasicB : σ.InFac B (σ.basicModule Bfin) :=
      basicModule_inFac σ Bfin
    have hbasicS : σ.InFac S (σ.basicModule Bfin) := by
      obtain ⟨P⟩ := hbasicB
      exact ⟨{
        index := P.index
        label := P.label
        mem := fun t ↦ hBS (P.mem t)
        map := P.map
        epi := P.epi }⟩
    refine ⟨{
      support := Bfin
      mem := by
        rw [hcarrier]
        exact hbasicS
      carrier_eq := ?_ }⟩
    funext X
    apply propext
    constructor
    · intro hX
      have hXS : σ.InFac S X := by
        rw [← hcarrier]
        exact hX
      have hXB : σ.InFac B X :=
        (inFac_iff_of_qClosure_eq σ hclosure X).2 hXS
      exact
        (inFacOfModule_basicModule_iff σ Bfin X).2 hXB
    · intro hX
      have hXB : σ.InFac B X :=
        (inFacOfModule_basicModule_iff σ Bfin X).1 hX
      have hXS : σ.InFac S X :=
        (inFac_iff_of_qClosure_eq σ hclosure X).1 hXB
      rw [hcarrier]
      exact hXS
  · rintro ⟨W⟩
    have hbasic :
        InFacOfModule (σ.basicModule W.support) =
          σ.InFac W.support.1 := by
      funext X
      exact propext
        (inFacOfModule_basicModule_iff σ W.support X)
    rw [W.carrier_eq, hbasic]
    exact
      ⟨inFac_isContravariantlyFinite σ W.support.1,
        finiteFacCovariantlyFinite_of_finiteDimensional
          K σ W.support.1 W.support.2⟩

/-- Same-universe form using the regular module as the ambient finite
generator. -/
theorem quotientClosed_isFunctoriallyFinite_iff_basicFacGenerator_sameUniverse
    (K : Type uK) [Field K] [Algebra K R] [FiniteDimensional K R]
    (σ : IndecomposableSkeleton.{u, v, u} R ι)
    (C : QuotientClosedAdditiveSubcategory.{u, u} (R := R)) :
    IsFunctoriallyFinite C.1.carrier ↔
      Nonempty (BasicFacGenerator σ C) :=
  quotientClosed_isFunctoriallyFinite_iff_basicFacGenerator
    σ K (FGModuleCat.of R R)
      (regularObject_isFiniteGenerator R) C

/-- Literal quotient-closed subcategories are compact exactly when they are
functorially finite.  The complete lattice is the named structure transported
through the chosen skeleton. -/
theorem quotientClosed_isCompactElement_iff_isFunctoriallyFinite_sameUniverse
    (K : Type uK) [Field K] [Algebra K R] [FiniteDimensional K R]
    (σ : IndecomposableSkeleton.{u, v, u} R ι)
    (C : QuotientClosedAdditiveSubcategory.{u, u} (R := R)) :
    let _ := quotientClosedCompleteLattice σ
    IsCompactElement C ↔
      IsFunctoriallyFinite C.1.carrier := by
  letI := quotientClosedCompleteLattice σ
  calc
    IsCompactElement C ↔
        IsCompactElement (σ.quotientClosedSupportOrderIso C) :=
      QuotientLattice.isCompactElement_iff σ C
    _ ↔ IsFunctoriallyFinite
          (σ.InFac
            ((σ.quotientClosedSupportOrderIso C :
              σ.qClosure.Closeds) : Set ι)) :=
      isCompactElement_iff_inFac_functoriallyFinite_of_finiteDimensional_sameUniverse
        K σ
    _ ↔ IsFunctoriallyFinite C.1.carrier := by
      change IsFunctoriallyFinite (σ.InFac (σ.support C.1)) ↔
        IsFunctoriallyFinite C.1.carrier
      rw [quotientClosedAdditiveSubcategory_carrier_eq_inFac_support σ C]

/-- The three exact paper conditions on a literal quotient-closed
subcategory: compactness, generation by one module, and functorial
finiteness. -/
theorem quotientClosed_compact_iff_basicFacGenerator_iff_functoriallyFinite
    (K : Type uK) [Field K] [Algebra K R] [FiniteDimensional K R]
    (σ : IndecomposableSkeleton.{u, v, u} R ι)
    (C : QuotientClosedAdditiveSubcategory.{u, u} (R := R)) :
    let _ := quotientClosedCompleteLattice σ
    (IsCompactElement C ↔ Nonempty (BasicFacGenerator σ C)) ∧
      (Nonempty (BasicFacGenerator σ C) ↔
        IsFunctoriallyFinite C.1.carrier) := by
  letI := quotientClosedCompleteLattice σ
  have hcompact :=
    quotientClosed_isCompactElement_iff_isFunctoriallyFinite_sameUniverse
      K σ C
  have hgenerator :=
    quotientClosed_isFunctoriallyFinite_iff_basicFacGenerator_sameUniverse
      K σ C
  exact ⟨hcompact.trans hgenerator, hgenerator.symm⟩

end OpConjecture.IndecomposableSkeleton
