import OpConjecture.ConvexGeometry.Distributive
import OpConjecture.RepresentationTheory.SubmoduleAntiExchange

/-!
# Distributivity of quotient-closed subcategories

This is the module-skeleton specialization of the abstract distributivity
criterion, corresponding to `paper/op_conjecture/main.tex`,
Proposition `prop:distributive`.
-/

noncomputable section

namespace OpConjecture.IndecomposableSkeleton

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} (σ : IndecomposableSkeleton.{u, v, w} R ι)

/-- The quotient-closed lattice is distributive exactly when additive
unions of quotient-closed classes remain quotient-closed, equivalently when
every generated indecomposable is generated by one selected
indecomposable. -/
theorem qClosure_distributive_iff_union_iff_unaryGeneration
    {K : Type*} [Field K] [Algebra K R]
    [∀ i : ι, Module K (σ.obj i)]
    [∀ i : ι, IsScalarTower K R (σ.obj i)]
    [∀ i : ι, FiniteDimensional K (σ.obj i)] :
    σ.qClosure.ClosedsIsDistributive ↔
      σ.qClosure.IsClosedUnderBinaryUnion ∧
        σ.qClosure.IsUnaryGeneration := by
  exact
    OpConjecture.SetClosure.closedsIsDistributive_iff_closedUnderUnion_iff_unaryGeneration
      (qClosure_isFinitary σ)
      (qClosure_isAntiExchange_of_finiteDimensional (K := K) σ)
      (qClosure_isClosed_empty σ)

end OpConjecture.IndecomposableSkeleton
