import OpConjecture.RepresentationTheory.FactorHomRealization
import OpConjecture.RepresentationTheory.OnePointIdealQuotient

/-!
# The literal factor category on deleted indecomposables

This file identifies the factor-Hom predicate with actual morphisms in the
ideal quotient `add(ind R) / [add K]`.  It also proves that selected points
become zero while deleted points remain nonzero.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory CategoryTheory.Limits

namespace OpConjecture.IndecomposableSkeleton

universe u v

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v}
  (σ : IndecomposableSkeleton.{u, v, u} R ι)

/-- The full additive category generated by the complete skeleton, modulo
maps which factor through `add K`. -/
abbrev FactorCategory (K : Set ι) :=
  σ.FactorQuotient Set.univ K

/-- A skeleton label as an object of the full additive category `add(ind R)`. -/
def ambientAddPoint (i : ι) : σ.AddCategory Set.univ :=
  σ.addPoint (Set.mem_univ i)

/-- A deleted label as an object of `add(ind R)` before passage to the
factor quotient. -/
def deletedAddPoint {K : Set ι} (x : DeletedLabel K) :
    σ.AddCategory Set.univ :=
  σ.ambientAddPoint x.1

/-- The quotient functor from `add(ind R)` to the factor category. -/
abbrev factorFunctor (K : Set ι) :=
  CategoryTheory.Quotient.functor
    (σ.factorThroughAddIdeal Set.univ K).rel

/-- The object of the factor category represented by a deleted label. -/
abbrev factorObject (K : Set ι) (x : DeletedLabel K) :
    σ.FactorCategory K :=
  (σ.factorFunctor K).obj (σ.deletedAddPoint x)

/-- A selected point is zero in the factor category. -/
theorem factorObject_isZero_of_mem
    (K : Set ι) {i : ι} (hi : i ∈ K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
      CategoryTheory.Quotient.functor_additive I.rel
        (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
          I.add_compatible f₁ f₂ g₁ g₂ hf hg)
    IsZero ((σ.factorFunctor K).obj (σ.ambientAddPoint i)) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  let F := σ.factorFunctor K
  rw [IsZero.iff_id_eq_zero, ← F.map_id]
  apply (I.map_eq_zero_iff (𝟙 (σ.ambientAddPoint i))).2
  exact ⟨σ.obj i, inAdd_obj σ hi,
    𝟙 (σ.obj i), 𝟙 (σ.obj i), by
      change 𝟙 (σ.obj i) ≫ 𝟙 (σ.obj i) = 𝟙 (σ.obj i)
      simp⟩

/-- A deleted point remains nonzero in the factor category. -/
theorem factorObject_not_isZero
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
      CategoryTheory.Quotient.functor_additive I.rel
        (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
          I.add_compatible f₁ f₂ g₁ g₂ hf hg)
    ¬ IsZero (σ.factorObject K x) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  let F := σ.factorFunctor K
  intro hzero
  have hqid : 𝟙 (σ.factorObject K x) = 0 :=
    (IsZero.iff_id_eq_zero _).1 hzero
  have hidzero :
      F.map (𝟙 (σ.deletedAddPoint x)) = 0 := by
    simpa only [F.map_id] using hqid
  have hfac : FactorsThroughAdd σ K (𝟙 (σ.obj x.1)) :=
    (I.map_eq_zero_iff (𝟙 (σ.deletedAddPoint x))).1 hidzero
  rcases hfac with ⟨M, hM, left, right, hcomp⟩
  let rt : Retract (σ.obj x.1) M :=
    { i := left
      r := right
      retract := hcomp }
  exact x.2 (index_mem_of_retract_inAdd σ rt hM)

/-- The abstract factor-Hom predicate is literal nonvanishing of a Hom set in
the ideal quotient. -/
theorem factorHomNonzero_iff_exists_ne_zero_quotient_morphism
    (K : Set ι) (p x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
      CategoryTheory.Quotient.functor_additive I.rel
        (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
          I.add_compatible f₁ f₂ g₁ g₂ hf hg)
    factorHomNonzero σ K p x ↔
      ∃ q : σ.factorObject K p ⟶ σ.factorObject K x,
        q ≠ 0 := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  let F := σ.factorFunctor K
  constructor
  · rintro ⟨f, hf⟩
    let fAdd : σ.deletedAddPoint p ⟶ σ.deletedAddPoint x :=
      ObjectProperty.homMk f
    refine ⟨F.map fAdd, ?_⟩
    intro hzero
    apply hf
    exact (I.map_eq_zero_iff fAdd).1 hzero
  · rintro ⟨q, hq⟩
    obtain ⟨f, rfl⟩ := F.map_surjective q
    refine ⟨f.hom, ?_⟩
    intro hfac
    apply hq
    exact (I.map_eq_zero_iff f).2 hfac

end OpConjecture.IndecomposableSkeleton
