import OpConjecture.RepresentationTheory.LollipopB0Modules
import OpConjecture.RepresentationTheory.LollipopTableCertificates

/-!
# A genuine submodule-good row for the dead-path lollipop

For the four explicitly enumerated targets `P, S₂, S₁, X`, the vertex-two
line in `A` is a nonzero common submodule of the kernels of all maps from `A`
to those targets.  A generic finite-biproduct lemma then promotes such
pointwise kernel bounds to a common reject bound.

No completeness, indecomposability, projectivity, or bound-path-algebra claim
about the five named modules is used here.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits

namespace OpConjecture.LollipopConcrete.ModuleLayer.SubmoduleBounds

universe u v w

variable (K : Type u) [Field K]

/-- The vertex-two basis vector in the explicitly constructed module `A`. -/
def AStemGenerator : AModule K :=
  FiniteB0Rep.ofV₂ K (AData K) 1

/-- The `B₀`-submodule generated by the vertex-two basis vector of `A`. -/
def AStemLine : Submodule (B0Model K) (AModule K) :=
  Submodule.span (B0Model K) {AStemGenerator K}

theorem AStemGenerator_ne_zero : AStemGenerator K ≠ 0 := by
  intro h
  have hsnd := congrArg (fun z : AModule K => z.2) h
  change (1 : K) = 0 at hsnd
  exact one_ne_zero hsnd

theorem AStemGenerator_mem_line : AStemGenerator K ∈ AStemLine K := by
  exact Submodule.subset_span (Set.mem_singleton _)

theorem AStemLine_ne_bot : AStemLine K ≠ ⊥ := by
  intro h
  apply AStemGenerator_ne_zero K
  have : AStemGenerator K ∈ (⊥ : Submodule (B0Model K) (AModule K)) := by
    rw [← h]
    exact AStemGenerator_mem_line K
  simpa using this

/-- Maps from `A` to a representation with zero vertex-two space kill the
chosen vertex-two generator. -/
theorem map_AStemGenerator_eq_zero_of_subsingleton_V₂
    (D : FiniteB0Rep K) [Subsingleton D.V₂]
    (f : AModule K ⟶ FiniteB0Rep.asFGModule K D) :
    f.hom.hom (AStemGenerator K) = 0 := by
  have he2 : e2 K • AStemGenerator K = AStemGenerator K := by
    rw [FiniteB0Rep.e2_smul]
    rfl
  calc
    f.hom.hom (AStemGenerator K) = f.hom.hom (e2 K • AStemGenerator K) := by rw [he2]
    _ = e2 K • f.hom.hom (AStemGenerator K) := by rw [f.hom.hom.map_smul]
    _ = 0 := by
      rw [FiniteB0Rep.e2_smul]
      apply Prod.ext
      · rfl
      · exact Subsingleton.elim _ _

theorem map_AStemGenerator_to_S1_eq_zero
    (f : AModule K ⟶ S1Module K) :
    f.hom.hom (AStemGenerator K) = 0 :=
  map_AStemGenerator_eq_zero_of_subsingleton_V₂ K (S1Data K) f

theorem map_AStemGenerator_to_X_eq_zero
    (f : AModule K ⟶ XModule K) :
    f.hom.hom (AStemGenerator K) = 0 :=
  map_AStemGenerator_eq_zero_of_subsingleton_V₂ K (XData K) f

theorem map_AStemGenerator_to_S2_eq_zero
    (f : AModule K ⟶ S2Module K) :
    f.hom.hom (AStemGenerator K) = 0 := by
  rw [hom_A_S2_eq_zero K f]
  rfl

/-- Every map from `A` to `P` kills the vertex-two generator.  The equation
`x • g = 0` first forces the image of the vertex-one generator `g` into the
kernel of the Jordan loop of `P`; the stem of `P` then kills that image. -/
theorem map_AStemGenerator_to_P_eq_zero
    (f : AModule K ⟶ PModule K) :
    f.hom.hom (AStemGenerator K) = 0 := by
  let g : AModule K := FiniteB0Rep.ofV₁ K (AData K) 1
  have hxg : x K • g = 0 := by
    rw [FiniteB0Rep.x_smul]
    rfl
  have hximage : x K • f.hom.hom g = 0 := by
    calc
      x K • f.hom.hom g = f.hom.hom (x K • g) := by rw [f.hom.hom.map_smul]
      _ = 0 := by rw [hxg, map_zero]
  have hfirst : (f.hom.hom g).1.1 = 0 := by
    rw [FiniteB0Rep.x_smul] at hximage
    have hcoord := congrArg (fun z : PModule K => z.1.2) hximage
    change (f.hom.hom g).1.1 = 0 at hcoord
    exact hcoord
  have haimage : a K • f.hom.hom g = 0 := by
    rw [FiniteB0Rep.a_smul]
    change (0, (f.hom.hom g).1.1) = 0
    rw [hfirst]
    rfl
  calc
    f.hom.hom (AStemGenerator K) = f.hom.hom (a K • g) := by
      rw [FiniteB0Rep.a_smul_ofV₁]
      rfl
    _ = a K • f.hom.hom g := by rw [f.hom.hom.map_smul]
    _ = 0 := haimage

/-- The four explicitly enumerated targets when the omitted source is `A`. -/
inductive ASelectedLabel where
  | p
  | s2
  | s1
  | x

def aSelectedModule : ASelectedLabel → FGModuleCat (B0Model K)
  | .p => PModule K
  | .s2 => S2Module K
  | .s1 => S1Module K
  | .x => XModule K

theorem aSelected_map_AStemGenerator_eq_zero
    (i : ASelectedLabel)
    (f : AModule K ⟶ aSelectedModule K i) :
    f.hom.hom (AStemGenerator K) = 0 := by
  cases i with
  | p => exact map_AStemGenerator_to_P_eq_zero K f
  | s2 => exact map_AStemGenerator_to_S2_eq_zero K f
  | s1 => exact map_AStemGenerator_to_S1_eq_zero K f
  | x => exact map_AStemGenerator_to_X_eq_zero K f

theorem AStemLine_le_ker_aSelected
    (i : ASelectedLabel)
    (f : AModule K ⟶ aSelectedModule K i) :
    AStemLine K ≤ LinearMap.ker f.hom.hom := by
  rw [AStemLine, Submodule.span_le]
  intro z hz
  rw [Set.mem_singleton_iff] at hz
  subst z
  exact LinearMap.mem_ker.mpr (aSelected_map_AStemGenerator_eq_zero K i f)

/-- Common-kernel data for an explicitly enumerated family of targets. -/
structure EnumeratedCommonKernelCertificate
    {R : Type u} [Ring R]
    (I : Type v) (X : FGModuleCat.{w} R)
    (Y : I → FGModuleCat.{w} R) where
  witness : Submodule R X
  witness_ne_bot : witness ≠ ⊥
  witness_le_ker : ∀ i (f : X ⟶ Y i), witness ≤ LinearMap.ker f.hom.hom

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- A map from `X` to an explicitly presented finite sum of the enumerated
targets. -/
structure EnumeratedSelectedMapFrom
    {R : Type u} [Ring R]
    (I : Type v) (X : FGModuleCat.{w} R)
    (Y : I → FGModuleCat.{w} R) where
  index : FintypeCat.{0}
  label : index → I
  map : X ⟶ biproduct fun t ↦ Y (label t)

/-- The reject against finite sums of an explicitly enumerated family. -/
def enumeratedReject
    {R : Type u} [Ring R]
    {I : Type v} (X : FGModuleCat.{w} R)
    (Y : I → FGModuleCat.{w} R) : Submodule R X :=
  ⨅ f : EnumeratedSelectedMapFrom I X Y, LinearMap.ker f.map.hom.hom

private theorem biproduct_apply_eq_zero_of_components
    {R : Type u} [Ring R]
    {J : Type*} [Fintype J]
    {X : FGModuleCat.{w} R} {Y : J → FGModuleCat.{w} R}
    (g : X ⟶ ⨁ Y) (z : X)
    (h : ∀ j, (g ≫ biproduct.π Y j).hom.hom z = 0) :
    g.hom.hom z = 0 := by
  classical
  let C : Submodule R X := R ∙ z
  letI : Module.Finite R C :=
    Module.Finite.of_fg (Submodule.fg_span_singleton z)
  let e : FGModuleCat.of R C ⟶ X :=
    FGModuleCat.ofHom C.subtype
  have he : e ≫ g = 0 := by
    apply biproduct.hom_ext
    intro j
    simp only [Category.assoc, zero_comp]
    apply FGModuleCat.hom_ext
    ext y
    obtain ⟨r, hr⟩ := Submodule.mem_span_singleton.mp y.2
    change (g ≫ biproduct.π Y j).hom.hom y.1 = 0
    rw [← hr, map_smul, h j, smul_zero]
  let y : C := ⟨z, Submodule.mem_span_singleton_self z⟩
  have hy := congrArg
    (fun f : FGModuleCat.of R C ⟶ ⨁ Y ↦ f.hom.hom y) he
  change g.hom.hom (C.subtype y) = 0 at hy
  exact hy

namespace EnumeratedCommonKernelCertificate

/-- Killing the witness under every map to every individual target kills it
under every map to every finite direct sum of targets. -/
theorem witness_le_enumeratedReject
    {R : Type u} [Ring R]
    {I : Type v} {X : FGModuleCat.{w} R}
    {Y : I → FGModuleCat.{w} R}
    (C : EnumeratedCommonKernelCertificate I X Y) :
    C.witness ≤ enumeratedReject X Y := by
  apply le_iInf
  intro f
  letI : Fintype f.index := FintypeCat.fintype
  intro z hz
  rw [LinearMap.mem_ker]
  apply biproduct_apply_eq_zero_of_components f.map z
  intro t
  exact LinearMap.mem_ker.mp
    (C.witness_le_ker (f.label t)
      (f.map ≫ biproduct.π (fun s ↦ Y (f.label s)) t) hz)

end EnumeratedCommonKernelCertificate

def aSelected_commonKernelCertificate :
    EnumeratedCommonKernelCertificate
      (R := B0Model K) ASelectedLabel (AModule K) (aSelectedModule K) where
  witness := AStemLine K
  witness_ne_bot := AStemLine_ne_bot K
  witness_le_ker := AStemLine_le_ker_aSelected K

theorem AStemLine_le_aSelected_enumeratedReject :
    AStemLine K ≤ enumeratedReject (AModule K) (aSelectedModule K) :=
  (aSelected_commonKernelCertificate K).witness_le_enumeratedReject

/-- The loop-image basis vector `(0,1)` in the vertex-one space of `X`. -/
def xSocleGenerator : XModule K :=
  FiniteB0Rep.ofV₁ K (XData K) (0, 1)

/-- The genuine `B₀`-submodule generated by the loop-image vector of `X`. -/
def xSocleLine : Submodule (B0Model K) (XModule K) :=
  Submodule.span (B0Model K) {xSocleGenerator K}

theorem xSocleGenerator_ne_zero : xSocleGenerator K ≠ 0 := by
  intro h
  have hcoord := congrArg (fun z : XModule K => z.1.2) h
  change (1 : K) = 0 at hcoord
  exact one_ne_zero hcoord

theorem xSocleGenerator_mem_line : xSocleGenerator K ∈ xSocleLine K :=
  Submodule.subset_span (Set.mem_singleton _)

theorem xSocleLine_ne_bot : xSocleLine K ≠ ⊥ := by
  intro h
  apply xSocleGenerator_ne_zero K
  have : xSocleGenerator K ∈ (⊥ : Submodule (B0Model K) (XModule K)) := by
    rw [← h]
    exact xSocleGenerator_mem_line K
  simpa using this

/-- The displayed generator is the loop of the top generator. -/
theorem xSocleGenerator_eq_x_smul_top :
    xSocleGenerator K =
      x K • FiniteB0Rep.ofV₁ K (XData K) (1, 0) := by
  rw [FiniteB0Rep.x_smul]
  rfl

theorem x_smul_eq_zero_of_loop_eq_zero
    (D : FiniteB0Rep K)
    (hloop : ∀ z, D.loop.hom.hom z = 0)
    (z : FiniteB0Rep.Carrier K D) :
    x K • z = 0 := by
  rw [FiniteB0Rep.x_smul]
  apply FiniteB0Rep.carrier_ext K D
  · exact hloop _
  · rfl

/-- A map from `X` to a representation with zero loop kills the loop-image
generator. -/
theorem map_xSocleGenerator_eq_zero_of_target_loop_eq_zero
    (D : FiniteB0Rep K)
    (hloop : ∀ z, D.loop.hom.hom z = 0)
    (f : XModule K ⟶ FiniteB0Rep.asFGModule K D) :
    f.hom.hom (xSocleGenerator K) = 0 := by
  let g : XModule K := FiniteB0Rep.ofV₁ K (XData K) (1, 0)
  calc
    f.hom.hom (xSocleGenerator K) = f.hom.hom (x K • g) := by
      rw [xSocleGenerator_eq_x_smul_top]
    _ = x K • f.hom.hom g := by rw [f.hom.hom.map_smul]
    _ = 0 := x_smul_eq_zero_of_loop_eq_zero K D hloop _

theorem map_xSocleGenerator_to_A_eq_zero
    (f : XModule K ⟶ AModule K) :
    f.hom.hom (xSocleGenerator K) = 0 :=
  map_xSocleGenerator_eq_zero_of_target_loop_eq_zero K (AData K) (by intro z; rfl) f

theorem map_xSocleGenerator_to_S2_eq_zero
    (f : XModule K ⟶ S2Module K) :
    f.hom.hom (xSocleGenerator K) = 0 :=
  map_xSocleGenerator_eq_zero_of_target_loop_eq_zero K (S2Data K) (by intro z; rfl) f

theorem map_xSocleGenerator_to_S1_eq_zero
    (f : XModule K ⟶ S1Module K) :
    f.hom.hom (xSocleGenerator K) = 0 :=
  map_xSocleGenerator_eq_zero_of_target_loop_eq_zero K (S1Data K) (by intro z; rfl) f

/-- Every map from `X` to `P` kills the loop-image generator.  The zero stem
of `X` first forces the image of its top generator into the kernel of the
stem of `P`; the loop of `P` then kills that image. -/
theorem map_xSocleGenerator_to_P_eq_zero
    (f : XModule K ⟶ PModule K) :
    f.hom.hom (xSocleGenerator K) = 0 := by
  let g : XModule K := FiniteB0Rep.ofV₁ K (XData K) (1, 0)
  have hag : a K • g = 0 := by
    rw [FiniteB0Rep.a_smul]
    rfl
  have haimage : a K • f.hom.hom g = 0 := by
    calc
      a K • f.hom.hom g = f.hom.hom (a K • g) := by rw [f.hom.hom.map_smul]
      _ = 0 := by rw [hag, map_zero]
  have htop : (f.hom.hom g).1.1 = 0 := by
    rw [FiniteB0Rep.a_smul] at haimage
    have hcoord := congrArg (fun z : PModule K => z.2) haimage
    change (f.hom.hom g).1.1 = 0 at hcoord
    exact hcoord
  have hximage : x K • f.hom.hom g = 0 := by
    rw [FiniteB0Rep.x_smul]
    change ((0, (f.hom.hom g).1.1), 0) = 0
    rw [htop]
    rfl
  calc
    f.hom.hom (xSocleGenerator K) = f.hom.hom (x K • g) := by
      rw [xSocleGenerator_eq_x_smul_top]
    _ = x K • f.hom.hom g := by rw [f.hom.hom.map_smul]
    _ = 0 := hximage

/-- The four explicitly enumerated targets when the omitted source is `X`. -/
inductive XSelectedLabel where
  | a
  | p
  | s2
  | s1

def xSelectedModule : XSelectedLabel → FGModuleCat (B0Model K)
  | .a => AModule K
  | .p => PModule K
  | .s2 => S2Module K
  | .s1 => S1Module K

theorem xSelected_map_xSocleGenerator_eq_zero
    (i : XSelectedLabel)
    (f : XModule K ⟶ xSelectedModule K i) :
    f.hom.hom (xSocleGenerator K) = 0 := by
  cases i with
  | a => exact map_xSocleGenerator_to_A_eq_zero K f
  | p => exact map_xSocleGenerator_to_P_eq_zero K f
  | s2 => exact map_xSocleGenerator_to_S2_eq_zero K f
  | s1 => exact map_xSocleGenerator_to_S1_eq_zero K f

theorem xSocleLine_le_ker_xSelected
    (i : XSelectedLabel)
    (f : XModule K ⟶ xSelectedModule K i) :
    xSocleLine K ≤ LinearMap.ker f.hom.hom := by
  rw [xSocleLine, Submodule.span_le]
  intro z hz
  rw [Set.mem_singleton_iff] at hz
  subst z
  exact LinearMap.mem_ker.mpr (xSelected_map_xSocleGenerator_eq_zero K i f)

def xSelected_commonKernelCertificate :
    EnumeratedCommonKernelCertificate
      (R := B0Model K) XSelectedLabel (XModule K) (xSelectedModule K) where
  witness := xSocleLine K
  witness_ne_bot := xSocleLine_ne_bot K
  witness_le_ker := xSocleLine_le_ker_xSelected K

theorem xSocleLine_le_xSelected_enumeratedReject :
    xSocleLine K ≤ enumeratedReject (XModule K) (xSelectedModule K) :=
  (xSelected_commonKernelCertificate K).witness_le_enumeratedReject

end OpConjecture.LollipopConcrete.ModuleLayer.SubmoduleBounds
