import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.Ideal.Quotient.Operations
import OpConjecture.Foundation.RepresentationTheory.Quiver.PathAlgebra

/-!
# Ideals in the one-loop path algebra

The commutative algebra calculation behind the local Nakayama branch is
already available from Mathlib's PID API: an ideal of `K[X]` which contains
a power of `X` is generated by a power of `X`.
-/

noncomputable section

namespace OpConjecture.LocalNakayamaBranch

open Polynomial

universe u

/-- Every ideal of a polynomial ring over a field which contains `X^N` is
generated by `X^L` for some `L ≤ N`. -/
theorem polynomialIdeal_eq_span_X_pow_of_mem
    {K : Type u} [Field K]
    (I : Ideal K[X]) {N : ℕ} (hXN : X ^ N ∈ I) :
    ∃ L ≤ N, I = Ideal.span ({X ^ L} : Set K[X]) := by
  let f : K[X] := Submodule.IsPrincipal.generator I
  have hfdvd : f ∣ X ^ N :=
    (Submodule.IsPrincipal.mem_iff_generator_dvd I).mp hXN
  obtain ⟨L, hLN, hf⟩ :=
    (dvd_prime_pow (Polynomial.prime_X (R := K)) N).mp hfdvd
  refine ⟨L, hLN, ?_⟩
  calc
    I = Ideal.span ({f} : Set K[X]) :=
      (Ideal.span_singleton_generator I).symm
    _ = Ideal.span ({X ^ L} : Set K[X]) :=
      Ideal.span_singleton_eq_span_singleton.mpr hf

/-- The project foundation's one-loop path-algebra equivalence, followed by Mathlib's
identification of the additive monoid algebra on `ℕ` with `K[X]`. -/
def oneLoopPolynomialAlgEquiv
    (K : Type u) [Field K] :
    OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop ≃ₐ[K] K[X] :=
  (OpConjecture.Foundation.PathAlgebra.oneLoopAlgEquiv K).trans
    (Polynomial.toFinsuppIsoAlg K).symm

/-- The distinguished generator corresponding to `X` under the polynomial
form of the one-loop path-algebra equivalence. -/
def oneLoopGenerator
    (K : Type u) [Field K] :
    OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop :=
  (oneLoopPolynomialAlgEquiv K).symm Polynomial.X

@[simp]
theorem oneLoopPolynomialAlgEquiv_generator
    (K : Type u) [Field K] :
    oneLoopPolynomialAlgEquiv K (oneLoopGenerator K) =
      (Polynomial.X : K[X]) := by
  simp [oneLoopGenerator]

/-- Transporting an ideal containing a power of the distinguished one-loop
generator to `K[X]` produces a power ideal. -/
theorem map_oneLoopIdeal_eq_span_X_pow
    {K : Type u} [Field K]
    (I : Ideal (OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop))
    {N : ℕ} (hpow : oneLoopGenerator K ^ N ∈ I) :
    ∃ L ≤ N,
      I.map (oneLoopPolynomialAlgEquiv K).toRingEquiv.toRingHom =
        Ideal.span ({Polynomial.X ^ L} : Set K[X]) := by
  let e := oneLoopPolynomialAlgEquiv K
  let J : Ideal K[X] := I.map e.toRingEquiv.toRingHom
  have hmap : e (oneLoopGenerator K ^ N) ∈ J := by
    exact Ideal.mem_map_of_mem e.toRingEquiv.toRingHom hpow
  have hXN : Polynomial.X ^ N ∈ J := by
    simpa [e] using hmap
  simpa [J] using polynomialIdeal_eq_span_X_pow_of_mem J hXN

/-- Therefore every quotient of the one-loop path algebra whose relation
ideal contains a power of the distinguished loop is a truncated polynomial
algebra.  This is the entire ideal-classification half of the local
Nakayama argument; the missing input is the Gabriel presentation of the
original basic algebra. -/
theorem oneLoopQuotient_algEquiv_truncatedPolynomial
    {K : Type u} [Field K]
    (I : Ideal (OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop))
    [I.IsTwoSided]
    {N : ℕ} (hpow : oneLoopGenerator K ^ N ∈ I) :
    ∃ L ≤ N,
      Nonempty
        ((OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop ⧸ I) ≃ₐ[K]
          K[X] ⧸ Ideal.span ({Polynomial.X ^ L} : Set K[X])) := by
  obtain ⟨L, hLN, hI⟩ := map_oneLoopIdeal_eq_span_X_pow I hpow
  let e := oneLoopPolynomialAlgEquiv K
  let J : Ideal K[X] := I.map e.toRingEquiv.toRingHom
  let E₁ :
      (OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop ⧸ I) ≃ₐ[K]
        K[X] ⧸ J :=
    Ideal.quotientEquivAlg I J e rfl
  let E₂ :
      (K[X] ⧸ J) ≃ₐ[K]
        K[X] ⧸ Ideal.span ({Polynomial.X ^ L} : Set K[X]) :=
    Ideal.quotientEquivAlgOfEq K hI
  exact ⟨L, hLN, ⟨E₁.trans E₂⟩⟩

/-- The exact remaining presentation datum in the one-simple branch.

The Ext-Gabriel theorem for a basic algebra should construct this structure:
the unique vertex and unique possible loop give the one-loop path algebra,
and admissibility supplies `loopPower_mem`. -/
structure OneLoopPresentation
    (K B : Type u) [Field K] [Ring B] [Algebra K B] where
  relationIdeal : Ideal (OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop)
  relationIdeal_twoSided : relationIdeal.IsTwoSided
  exponent : ℕ
  loopPower_mem : oneLoopGenerator K ^ exponent ∈ relationIdeal
  quotientEquiv :
    letI : relationIdeal.IsTwoSided := relationIdeal_twoSided
    (OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop ⧸ relationIdeal) ≃ₐ[K] B

/-- Once the Gabriel presentation is supplied, no further ideal
classification is missing: the algebra is a truncated polynomial algebra. -/
theorem algEquiv_truncatedPolynomial_of_oneLoopPresentation
    {K B : Type u} [Field K] [Ring B] [Algebra K B]
    (P : OneLoopPresentation K B) :
    ∃ L ≤ P.exponent,
      Nonempty
        (B ≃ₐ[K]
          K[X] ⧸ Ideal.span ({Polynomial.X ^ L} : Set K[X])) := by
  letI : P.relationIdeal.IsTwoSided := P.relationIdeal_twoSided
  obtain ⟨L, hL, ⟨E⟩⟩ :=
    oneLoopQuotient_algEquiv_truncatedPolynomial
      P.relationIdeal P.loopPower_mem
  exact ⟨L, hL, ⟨P.quotientEquiv.symm.trans E⟩⟩

end OpConjecture.LocalNakayamaBranch
