import OpConjecture.RepresentationTheory.OneLoopProfileEquality
import OpConjecture.RepresentationTheory.BlockDecomposition
import OpConjecture.RepresentationTheory.OneSimpleNakayamaReduction

/-!
# Exact basicization interface for the one-simple branch

The maintained `AlgebraNode` contains a finite complete skeleton only for
its source algebra.  This file first shows that a Morita equivalence to any
other finite-dimensional algebra canonically supplies the target node, by
using its canonical skeleton and transporting finiteness of the label type.

It then packages the strictly weaker structural datum actually needed by
the OP-profile proof: a Morita-equivalent algebra which is a quotient of
`K[X]`.  A one-loop Gabriel quotient supplies precisely this datum.  Thus
no relation-ideal classification is needed at the profile endpoint.
-/

noncomputable section

open CategoryTheory

namespace OpConjecture.LocalNakayamaBranch

universe u

open OpConjecture.BottomLevels.FiniteDimensionalRecurrence

/-! ## From a cyclic radical cotangent space to a monogenic algebra -/

/-- Noncommutative Nakayama lifting in the exact form needed below.  If
the Jacobson radical is generated modulo its square by `x`, then it is
already the principal left ideal generated by `x`.

The quotient module by `D ∙ x` is essential here: Mathlib's
`FG.eq_bot_of_le_jacobson_smul` applies to arbitrary (not necessarily
commutative) rings. -/
theorem jacobson_le_span_singleton_of_cyclic_cotangent
    {D : Type u} [Ring D] [IsNoetherianRing D]
    (x : D)
    (h : (Ring.jacobson D : Submodule D D) ≤
      D ∙ x ⊔
        (Ring.jacobson D : Submodule D D) •
          (Ring.jacobson D : Submodule D D)) :
    (Ring.jacobson D : Submodule D D) ≤ D ∙ x := by
  let L : Submodule D D := D ∙ x
  let J : Submodule D D := Ring.jacobson D
  let N : Submodule D (D ⧸ L) := J.map L.mkQ
  have hN : N ≤ Ring.jacobson D • N := by
    calc
      N ≤ (L ⊔ J • J).map L.mkQ :=
        Submodule.map_mono h
      _ = L.map L.mkQ ⊔ (J • J).map L.mkQ := by
        rw [Submodule.map_sup]
      _ = ⊥ ⊔ Ring.jacobson D • N := by
        rw [Submodule.mkQ_map_self, Submodule.map_smul'']
      _ = Ring.jacobson D • N := by simp
  have hNzero : N = ⊥ :=
    (IsNoetherian.noetherian N).eq_bot_of_le_jacobson_smul hN
  have hle : J ≤ Submodule.comap L.mkQ N := by
    change J ≤ Submodule.comap L.mkQ (J.map L.mkQ)
    exact Submodule.le_comap_map L.mkQ J
  simpa [L, J, N, hNzero, Submodule.ker_mkQ] using hle

/-- A nilpotent element whose principal left span contains all elements
modulo scalars generates the algebra.  The proof descends through powers of
`x`; commutativity of `D` is not assumed. -/
theorem adjoin_singleton_eq_top_of_split_residue_of_principal_nilpotent
    {K D : Type u} [CommRing K] [Ring D] [Algebra K D]
    (J : Submodule D D) (x : D) (N : ℕ)
    (hsplit : ∀ d : D, ∃ k : K, d - algebraMap K D k ∈ J)
    (hprincipal : J ≤ D ∙ x)
    (hxN : x ^ N = 0) :
    Algebra.adjoin K ({x} : Set D) = ⊤ := by
  let S : Subalgebra K D := Algebra.adjoin K ({x} : Set D)
  have hxS : x ∈ S := Algebra.self_mem_adjoin_singleton K x
  have hdescending :
      ∀ n, n ≤ N → ∀ d : D, d * x ^ n ∈ S := by
    intro n hn
    induction hn using Nat.decreasingInduction with
    | self =>
        intro d
        rw [hxN, mul_zero]
        exact S.zero_mem
    | of_succ n hn ih =>
        intro d
        obtain ⟨k, hk⟩ := hsplit d
        obtain ⟨c, hc⟩ :=
          Submodule.mem_span_singleton.mp (hprincipal hk)
        have hc' : c * x = d - algebraMap K D k := by
          simpa only [smul_eq_mul] using hc
        have hd : d = algebraMap K D k + c * x := by
          calc
            d = algebraMap K D k + (d - algebraMap K D k) := by abel
            _ = algebraMap K D k + c * x := by rw [← hc']
        rw [hd, add_mul, mul_assoc, ← pow_succ']
        exact S.add_mem
          (S.mul_mem (S.algebraMap_mem k) (S.pow_mem hxS n))
          (ih c)
  apply top_unique
  intro d _
  simpa using hdescending 0 (Nat.zero_le N) d

/-- Over a field, a finite-dimensional algebra with split scalar residue
and cyclic Jacobson cotangent space is monogenic.  Concretely, evaluation
at the cotangent generator is a surjective algebra map `K[X] →ₐ[K] D`.

This packages all routine algebra after the classical basic-algebra and
Gabriel-cotangent identifications: Artinian radical nilpotence and the
noncommutative Nakayama lift are discharged here. -/
theorem aeval_surjective_of_split_jacobson_of_cyclic_cotangent
    {K D : Type u} [Field K] [Ring D] [Algebra K D]
    [FiniteDimensional K D]
    (x : D)
    (hx : x ∈ Ring.jacobson D)
    (hsplit : ∀ d : D, ∃ k : K,
      d - algebraMap K D k ∈ Ring.jacobson D)
    (hcotangent : (Ring.jacobson D : Submodule D D) ≤
      D ∙ x ⊔
        (Ring.jacobson D : Submodule D D) •
          (Ring.jacobson D : Submodule D D)) :
    Function.Surjective
      (Polynomial.aeval x : Polynomial K →ₐ[K] D) := by
  letI : IsArtinianRing D := IsArtinianRing.of_finite K D
  letI : IsNoetherianRing D := inferInstance
  have hprincipal :
      (Ring.jacobson D : Submodule D D) ≤ D ∙ x :=
    jacobson_le_span_singleton_of_cyclic_cotangent x hcotangent
  have hnil : IsNilpotent (Ring.jacobson D) := by
    rw [← Ideal.jacobson_bot]
    exact IsArtinianRing.isNilpotent_jacobson_bot
  obtain ⟨N, hN⟩ := hnil
  have hxN : x ^ N = 0 := by
    have hmem : x ^ N ∈ (Ring.jacobson D) ^ N :=
      Ideal.pow_mem_pow hx N
    rw [hN] at hmem
    exact hmem
  have hadjoin : Algebra.adjoin K ({x} : Set D) = ⊤ :=
    adjoin_singleton_eq_top_of_split_residue_of_principal_nilpotent
      (Ring.jacobson D : Submodule D D) x N hsplit hprincipal hxN
  apply (AlgHom.range_eq_top (Polynomial.aeval x)).mp
  exact (Algebra.adjoin_singleton_eq_range_aeval K x).symm.trans hadjoin

/-- A Morita equivalence from an `AlgebraNode` to a finite-dimensional
algebra makes the target into an `AlgebraNode` as well.  Finiteness of the
canonical target skeleton is transported from the given source skeleton.
-/
noncomputable def algebraNodeMoritaTarget
    {K D : Type u} [Field K]
    [Ring D] [Algebra K D] [FiniteDimensional K D]
    (B : AlgebraNode K)
    (M : MoritaEquivalence K B.Carrier D) :
    AlgebraNode K := by
  letI : IsArtinianRing B.Carrier :=
    IsArtinianRing.of_finite K B.Carrier
  letI : IsArtinianRing D := IsArtinianRing.of_finite K D
  letI hDNoetherian : IsNoetherianRing D := inferInstance
  letI hDOpNoetherian : IsNoetherianRing Dᵐᵒᵖ :=
    OpConjecture.isNoetherianRing_op_of_finiteDimensional K D
  let tau :=
    OpConjecture.BlockDecomposition.Node.canonicalLeftSkeleton K D
  let E :=
    OpConjecture.IndecomposableSkeleton.Equivalence.alignedEquivalence
      B.skeleton tau M.fgEquivalence
  letI hFiniteTarget :
      Finite (OpConjecture.CanonicalIndecomposableIndex.{u, u} D) :=
    E.labelEquiv.finite_iff.mp inferInstance
  exact
    { Carrier := D
      ring := inferInstance
      algebra := inferInstance
      finiteDimensional := inferInstance
      noetherian := hDNoetherian
      noetherianOpposite := hDOpNoetherian
      Index := OpConjecture.CanonicalIndecomposableIndex.{u, u} D
      finiteIndex := hFiniteTarget
      skeleton := tau }

/-- The exact algebraic model needed after basicization: the source node is
Morita equivalent to a finite-dimensional quotient of `K[X]`.  Storing the
surjection, rather than a chosen relation ideal, keeps this weaker than a
full Gabriel presentation. -/
structure MoritaPolynomialQuotientModel
    (K : Type u) [Field K] (B : AlgebraNode K) where
  Carrier : Type u
  [ring : Ring Carrier]
  [algebra : Algebra K Carrier]
  [finiteDimensional : FiniteDimensional K Carrier]
  morita : MoritaEquivalence K B.Carrier Carrier
  polynomialMap : Polynomial K →ₐ[K] Carrier
  polynomialMap_surjective : Function.Surjective polynomialMap

namespace MoritaPolynomialQuotientModel

variable {K : Type u} [Field K] {B : AlgebraNode K}

attribute [instance] ring algebra finiteDimensional

/-- The canonical finite target node attached to a polynomial-quotient
model. -/
noncomputable def targetNode
    (P : MoritaPolynomialQuotientModel K B) : AlgebraNode K :=
  algebraNodeMoritaTarget B P.morita

/-- Forget the arbitrary polynomial quotient map in favor of its image of
`X`.  Polynomial-algebra extensionality shows that this element generates
the target, so the model feeds the node-level monogenic interface directly. -/
theorem toHasMoritaMonogenicModel
    (P : MoritaPolynomialQuotientModel K B) :
    HasMoritaMonogenicModel B := by
  refine
    ⟨P.targetNode, ⟨P.morita⟩,
      P.polynomialMap Polynomial.X, ?_⟩
  change
    Algebra.adjoin K
      ({P.polynomialMap Polynomial.X} : Set P.Carrier) = ⊤
  rw [Algebra.adjoin_singleton_eq_range_aeval]
  have hmap :
      (Polynomial.aeval (P.polynomialMap Polynomial.X) :
          Polynomial K →ₐ[K] P.Carrier) =
        P.polynomialMap := by
    apply Polynomial.algHom_ext
    simp
  rw [hmap]
  exact (AlgHom.range_eq_top P.polynomialMap).2
    P.polynomialMap_surjective

/-- A Morita-equivalent polynomial quotient gives the source node's exact
quotient/submodule level-polynomial equality. -/
theorem levelPolynomial_eq
    (P : MoritaPolynomialQuotientModel K B) :
    (AlgebraNode.qClosure K B).levelPolynomial =
      (AlgebraNode.sClosure K B).levelPolynomial := by
  exact
    algebraNodeEquidistribution_of_morita_surjective_from_commutative
      B P.targetNode P.morita P.polynomialMap
        P.polynomialMap_surjective

end MoritaPolynomialQuotientModel

/-- A representation-theoretic input package strictly before the
polynomial quotient: a Morita-equivalent finite-dimensional algebra whose
residue modulo the Jacobson radical is supplied by scalar classes and whose
left cotangent space `J / J²` is generated by one radical element.

This is the natural landing point for basicization plus the one-loop
Ext/Gabriel calculation. -/
structure MoritaSplitCyclicCotangentModel
    (K : Type u) [Field K] (B : AlgebraNode K) where
  Carrier : Type u
  [ring : Ring Carrier]
  [algebra : Algebra K Carrier]
  [finiteDimensional : FiniteDimensional K Carrier]
  morita : MoritaEquivalence K B.Carrier Carrier
  generator : Carrier
  generator_mem_jacobson : generator ∈ Ring.jacobson Carrier
  splitResidue : ∀ d : Carrier, ∃ k : K,
    d - algebraMap K Carrier k ∈ Ring.jacobson Carrier
  cyclicCotangent :
    (Ring.jacobson Carrier : Submodule Carrier Carrier) ≤
      Carrier ∙ generator ⊔
        (Ring.jacobson Carrier : Submodule Carrier Carrier) •
          (Ring.jacobson Carrier : Submodule Carrier Carrier)

namespace MoritaSplitCyclicCotangentModel

variable {K : Type u} [Field K] {B : AlgebraNode K}

attribute [instance] ring algebra finiteDimensional

/-- The cyclic-cotangent package canonically produces the exact polynomial
quotient model needed by the profile proof. -/
noncomputable def toPolynomialQuotientModel
    (P : MoritaSplitCyclicCotangentModel K B) :
    MoritaPolynomialQuotientModel K B where
  Carrier := P.Carrier
  ring := inferInstance
  algebra := inferInstance
  finiteDimensional := inferInstance
  morita := P.morita
  polynomialMap := Polynomial.aeval P.generator
  polynomialMap_surjective :=
    aeval_surjective_of_split_jacobson_of_cyclic_cotangent
      P.generator P.generator_mem_jacobson P.splitResidue
        P.cyclicCotangent

/-- Thus split residue plus one cyclic radical-cotangent generator already
closes the OP profile branch. -/
theorem levelPolynomial_eq
    (P : MoritaSplitCyclicCotangentModel K B) :
    (AlgebraNode.qClosure K B).levelPolynomial =
      (AlgebraNode.sClosure K B).levelPolynomial :=
  P.toPolynomialQuotientModel.levelPolynomial_eq

end MoritaSplitCyclicCotangentModel

/-- An even more presentation-facing version: a Morita-equivalent algebra
is the target of a surjective map from the project foundation's one-loop path algebra. -/
structure MoritaOneLoopSurjectionModel
    (K : Type u) [Field K] (B : AlgebraNode K) where
  Carrier : Type u
  [ring : Ring Carrier]
  [algebra : Algebra K Carrier]
  [finiteDimensional : FiniteDimensional K Carrier]
  morita : MoritaEquivalence K B.Carrier Carrier
  oneLoopMap :
    OpConjecture.Foundation.pathAlgebra.{0, u, u} K OpConjecture.Foundation.Quiver.OneLoop →ₐ[K]
      Carrier
  oneLoopMap_surjective : Function.Surjective oneLoopMap

namespace MoritaOneLoopSurjectionModel

variable {K : Type u} [Field K] {B : AlgebraNode K}

attribute [instance] ring algebra finiteDimensional

/-- Composing a one-loop quotient map with the polynomial/one-loop
equivalence produces the weaker polynomial-quotient model. -/
noncomputable def toPolynomialQuotientModel
    (P : MoritaOneLoopSurjectionModel K B) :
    MoritaPolynomialQuotientModel K B where
  Carrier := P.Carrier
  ring := inferInstance
  algebra := inferInstance
  finiteDimensional := inferInstance
  morita := P.morita
  polynomialMap :=
    P.oneLoopMap.comp (oneLoopPolynomialAlgEquiv K).symm.toAlgHom
  polynomialMap_surjective :=
    P.oneLoopMap_surjective.comp
      (oneLoopPolynomialAlgEquiv K).symm.surjective

/-- Hence a Morita-equivalent one-loop quotient already closes the profile
branch. -/
theorem levelPolynomial_eq
    (P : MoritaOneLoopSurjectionModel K B) :
    (AlgebraNode.qClosure K B).levelPolynomial =
      (AlgebraNode.sClosure K B).levelPolynomial :=
  P.toPolynomialQuotientModel.levelPolynomial_eq

end MoritaOneLoopSurjectionModel

namespace MoritaSplitCyclicCotangentModel

variable {K : Type u} [Field K] {B : AlgebraNode K}

attribute [instance] ring algebra finiteDimensional

/-- The polynomial/one-loop equivalence also turns the derived monogenic
model into the exact one-loop surjection package. -/
noncomputable def toOneLoopSurjectionModel
    (P : MoritaSplitCyclicCotangentModel K B) :
    MoritaOneLoopSurjectionModel K B := by
  let Q := P.toPolynomialQuotientModel
  exact
    { Carrier := P.Carrier
      ring := inferInstance
      algebra := inferInstance
      finiteDimensional := inferInstance
      morita := P.morita
      oneLoopMap :=
        Q.polynomialMap.comp (oneLoopPolynomialAlgEquiv K).toAlgHom
      oneLoopMap_surjective :=
        Q.polynomialMap_surjective.comp
          (oneLoopPolynomialAlgEquiv K).surjective }

end MoritaSplitCyclicCotangentModel

/-- Classical one-loop Gabriel presentation, but only after Morita
basicization.  This is stronger than `MoritaOneLoopSurjectionModel` because
it additionally records a nilpotent loop relation. -/
structure MoritaOneLoopPresentationModel
    (K : Type u) [Field K] (B : AlgebraNode K) where
  Carrier : Type u
  [ring : Ring Carrier]
  [algebra : Algebra K Carrier]
  [finiteDimensional : FiniteDimensional K Carrier]
  morita : MoritaEquivalence K B.Carrier Carrier
  presentation : OneLoopPresentation K Carrier

namespace MoritaOneLoopPresentationModel

variable {K : Type u} [Field K] {B : AlgebraNode K}

attribute [instance] ring algebra finiteDimensional

/-- Forget the relation ideal but retain its canonical surjective quotient
map. -/
noncomputable def toOneLoopSurjectionModel
    (P : MoritaOneLoopPresentationModel K B) :
    MoritaOneLoopSurjectionModel K B := by
  letI : P.presentation.relationIdeal.IsTwoSided :=
    P.presentation.relationIdeal_twoSided
  let q :=
    Ideal.Quotient.mkₐ K P.presentation.relationIdeal
  let f :
      OpConjecture.Foundation.pathAlgebra K OpConjecture.Foundation.Quiver.OneLoop →ₐ[K]
        P.Carrier :=
    P.presentation.quotientEquiv.toAlgHom.comp q
  exact
    { Carrier := P.Carrier
      ring := inferInstance
      algebra := inferInstance
      finiteDimensional := inferInstance
      morita := P.morita
      oneLoopMap := f
      oneLoopMap_surjective :=
        P.presentation.quotientEquiv.surjective.comp
          (Ideal.Quotient.mkₐ_surjective K
            P.presentation.relationIdeal) }

/-- A Morita-basic one-loop Gabriel presentation closes the profile branch,
without invoking the classification of its relation ideal. -/
theorem levelPolynomial_eq
    (P : MoritaOneLoopPresentationModel K B) :
    (AlgebraNode.qClosure K B).levelPolynomial =
      (AlgebraNode.sClosure K B).levelPolynomial :=
  P.toOneLoopSurjectionModel.levelPolynomial_eq

end MoritaOneLoopPresentationModel

/-! ## Exact remaining one-simple classification seam -/

/-- The representation-theoretically structured residual input: projective
rank one admits a Morita basicization with split residue and a cyclic
Jacobson cotangent space.  All subsequent Nakayama, nilpotence, monogenicity,
and one-loop-surjection steps are compiled above. -/
def ProjectiveRankOneMoritaSplitCyclicCotangentClassification
    (K : Type u) [Field K] : Prop :=
  ∀ (B : AlgebraNode K),
    OpConjecture.IndecomposableSkeleton.FaithfulCore.ConnectedSmallCore.projectiveRank
        B.skeleton = 1 →
      Nonempty (MoritaSplitCyclicCotangentModel K B)

/-- The weakest classical input isolated by the compiled profile bridge:
projective rank one produces a Morita-equivalent one-loop quotient. -/
def ProjectiveRankOneMoritaOneLoopClassification
    (K : Type u) [Field K] : Prop :=
  ∀ (B : AlgebraNode K),
    OpConjecture.IndecomposableSkeleton.FaithfulCore.ConnectedSmallCore.projectiveRank
        B.skeleton = 1 →
      Nonempty (MoritaOneLoopSurjectionModel K B)

/-- Basicization with split cyclic cotangent data supplies the former
one-loop-surjection seam. -/
theorem projectiveRankOneMoritaOneLoopClassification_of_splitCyclicCotangent
    {K : Type u} [Field K]
    (hclassification :
      ProjectiveRankOneMoritaSplitCyclicCotangentClassification K) :
    ProjectiveRankOneMoritaOneLoopClassification K := by
  intro B hB
  obtain ⟨P⟩ := hclassification B hB
  exact ⟨P.toOneLoopSurjectionModel⟩

/-- Once the exact basicization/Gabriel-surjection input is supplied,
projective rank one has the full profile equality needed by `smallCore`. -/
theorem levelPolynomial_eq_of_projectiveRank_eq_one
    {K : Type u} [Field K]
    (hclassification :
      ProjectiveRankOneMoritaOneLoopClassification K)
    (B : AlgebraNode K)
    (hB :
      OpConjecture.IndecomposableSkeleton.FaithfulCore.ConnectedSmallCore.projectiveRank
          B.skeleton = 1) :
    (AlgebraNode.qClosure K B).levelPolynomial =
      (AlgebraNode.sClosure K B).levelPolynomial := by
  obtain ⟨P⟩ := hclassification B hB
  exact P.levelPolynomial_eq

/-- The exact endpoint using only the structured basicization/cotangent
classification input. -/
theorem levelPolynomial_eq_of_projectiveRank_eq_one_of_splitCyclicCotangent
    {K : Type u} [Field K]
    (hclassification :
      ProjectiveRankOneMoritaSplitCyclicCotangentClassification K)
    (B : AlgebraNode K)
    (hB :
      OpConjecture.IndecomposableSkeleton.FaithfulCore.ConnectedSmallCore.projectiveRank
          B.skeleton = 1) :
    (AlgebraNode.qClosure K B).levelPolynomial =
      (AlgebraNode.sClosure K B).levelPolynomial := by
  exact levelPolynomial_eq_of_projectiveRank_eq_one
    (projectiveRankOneMoritaOneLoopClassification_of_splitCyclicCotangent
      hclassification)
    B hB

/-- Projective rank one is already exactly the maintained one-simple
skeleton condition.  This records that the residual classification seam
does not contain an additional counting hypothesis. -/
theorem oneSimple_of_projectiveRank_eq_one
    {K : Type u} [Field K]
    (B : AlgebraNode K)
    (hB :
      OpConjecture.IndecomposableSkeleton.FaithfulCore.ConnectedSmallCore.projectiveRank
          B.skeleton = 1) :
    OneSimple B.skeleton :=
  (oneSimple_iff_projectiveRank_eq_one B.skeleton).2 hB

end OpConjecture.LocalNakayamaBranch
