import Mathlib.Order.CompactlyGenerated.Basic
import QuotientSubmoduleEquidistribution.ConvexGeometry.CompletelyJoinIrreducible

/-!
# Compact and algebraic closed-set lattices

For a finitary closure operator, point closures are compact.  Consequently
the closed-set lattice is compactly generated (algebraic), and compact
closed sets have finite extreme-point bases.
-/

open Set

namespace QuotientSubmoduleEquidistribution.SetClosure

variable {E : Type*} {c : SetClosure E}

/-- Finitarity makes every point closure a compact element of the
closed-set lattice. -/
theorem pointClosure_isCompactElement
    (hfin : c.IsFinitary) (x : E) :
    IsCompactElement (c.pointClosure x) := by
  classical
  rw [CompleteLattice.isCompactElement_iff_exists_le_sSup_of_le_sSup]
  intro S hxS
  have hxClosure : x ∈ c (⋃ C : S, (C.1 : Set E)) := by
    have hx : x ∈ ((sSup S : c.Closeds) : Set E) :=
      pointClosure_le_iff.1 hxS
    simpa using hx
  obtain ⟨Y, hYfin, hYsub, hxY⟩ := hfin hxClosure
  have hcover : ∀ y : Y, ∃ C : S, y.1 ∈ (C.1 : Set E) := by
    intro y
    have hy := hYsub y.2
    simpa only [Set.mem_iUnion] using hy
  choose f hf using hcover
  letI : Fintype Y := hYfin.fintype
  let T : Finset c.Closeds :=
    Finset.univ.image fun y : Y ↦ (f y).1
  have hTS : (T : Set c.Closeds) ⊆ S := by
    intro C hC
    obtain ⟨y, -, rfl⟩ := Finset.mem_image.mp hC
    exact (f y).2
  refine ⟨T, hTS, ?_⟩
  rw [pointClosure_le_iff]
  have hYsup : Y ⊆ ((T.sup id : c.Closeds) : Set E) := by
    intro y hyY
    let y' : Y := ⟨y, hyY⟩
    have hmem : (f y').1 ∈ T := by
      apply Finset.mem_image.mpr
      exact ⟨y', Finset.mem_univ _, rfl⟩
    have hle : (f y').1 ≤ T.sup id :=
      Finset.le_sup (s := T) (f := id) hmem
    exact hle (hf y')
  exact c.closure_min hYsup (T.sup id).2 hxY

/-- The closure of a finite set is a compact element of the closed-set
lattice. -/
theorem finiteClosure_isCompactElement
    (hfin : c.IsFinitary) {B : Set E} (hBfin : B.Finite) :
    IsCompactElement (c.toCloseds B) := by
  classical
  let s : Finset E := hBfin.toFinset
  have hclosure :
      c.toCloseds B = s.sup c.pointClosure := by
    apply le_antisymm
    · apply c.closure_min
      · intro x hxB
        have hxs : x ∈ s := by
          simpa [s] using hxB
        have hle : c.pointClosure x ≤ s.sup c.pointClosure :=
          Finset.le_sup (s := s) (f := c.pointClosure) hxs
        exact hle (c.le_closure ({x} : Set E) (mem_singleton x))
      · exact (s.sup c.pointClosure).2
    · apply Finset.sup_le
      intro x hxs
      rw [pointClosure_le_iff]
      apply c.le_closure B
      simpa [s] using hxs
  rw [hclosure]
  apply CompleteLattice.isCompactElement_finsetSup s
  intro x _
  exact pointClosure_isCompactElement hfin x

/-- Finite closures contained in `C`. -/
def finiteClosuresBelow (c : SetClosure E) (C : c.Closeds) :
    Set c.Closeds :=
  {K | ∃ B : Set E, B.Finite ∧ B ⊆ (C : Set E) ∧
    K = c.toCloseds B}

/-- Every closed set is the directed supremum of the closures of its
finite subsets.  Under finitarity, all members of this directed family
are compact. -/
theorem finiteClosuresBelow_directed_sSup
    (hfin : c.IsFinitary) (C : c.Closeds) :
    (c.finiteClosuresBelow C).Nonempty ∧
      DirectedOn (· ≤ ·) (c.finiteClosuresBelow C) ∧
      (∀ K ∈ c.finiteClosuresBelow C, IsCompactElement K) ∧
      sSup (c.finiteClosuresBelow C) = C := by
  classical
  constructor
  · refine ⟨c.toCloseds ∅, ∅, Set.finite_empty, empty_subset _, rfl⟩
  constructor
  · rintro K ⟨B, hBfin, hBC, rfl⟩ L ⟨D, hDfin, hDC, rfl⟩
    refine ⟨c.toCloseds (B ∪ D),
      ⟨B ∪ D, hBfin.union hDfin, union_subset hBC hDC, rfl⟩,
      c.monotone subset_union_left, c.monotone subset_union_right⟩
  constructor
  · intro K hK
    obtain ⟨B, hBfin, -, rfl⟩ := hK
    exact finiteClosure_isCompactElement hfin hBfin
  · apply le_antisymm
    · apply sSup_le
      intro K hK
      obtain ⟨B, -, hBC, rfl⟩ := hK
      exact c.closure_min hBC C.2
    · calc
        C = ⨆ x : (C : Set E), c.pointClosure x.1 :=
          (iSup_pointClosure C).symm
        _ ≤ sSup (c.finiteClosuresBelow C) := by
          apply iSup_le
          intro x
          apply le_sSup
          exact ⟨{x.1}, Set.finite_singleton x.1,
            singleton_subset_iff.mpr x.2, rfl⟩

/-- The closed-set lattice of a finitary closure operator is compactly
generated; this is the manuscript's algebraicity assertion. -/
theorem isCompactlyGenerated_closeds
    (hfin : c.IsFinitary) :
    IsCompactlyGenerated c.Closeds := by
  constructor
  intro C
  let P : Set c.Closeds :=
    c.pointClosure '' (C : Set E)
  refine ⟨P, ?_, ?_⟩
  · intro J hJ
    obtain ⟨x, -, rfl⟩ := hJ
    exact pointClosure_isCompactElement hfin x
  · apply le_antisymm
    · apply sSup_le
      intro J hJ
      obtain ⟨x, hxC, rfl⟩ := hJ
      exact pointClosure_le_iff.2 hxC
    · rw [← iSup_pointClosure C]
      apply iSup_le
      intro x
      exact le_sSup ⟨x.1, x.2, rfl⟩

/-- A compact closed set is generated by finitely many of its points. -/
theorem exists_finite_generator_of_isCompactElement
    {C : c.Closeds} (hcompact : IsCompactElement C) :
    ∃ B : Set E, B.Finite ∧ B ⊆ (C : Set E) ∧ c B = (C : Set E) := by
  classical
  have hdecomp : C ≤ ⨆ x : (C : Set E), c.pointClosure x.1 := by
    rw [iSup_pointClosure C]
  obtain ⟨s, hs⟩ :=
    CompleteLattice.IsCompactElement.exists_finset_of_le_iSup c.Closeds hcompact
      (fun x : (C : Set E) ↦ c.pointClosure x.1) hdecomp
  let B : Set E := Subtype.val '' (s : Set (C : Set E))
  have hBfin : B.Finite :=
    s.finite_toSet.image Subtype.val
  have hBC : B ⊆ (C : Set E) := by
    rintro x ⟨y, -, rfl⟩
    exact y.2
  let K : c.Closeds := c.toCloseds B
  have hsupK :
      (⨆ x ∈ s, c.pointClosure x.1) ≤ K := by
    apply iSup_le
    intro x
    apply iSup_le
    intro hxs
    rw [pointClosure_le_iff]
    exact c.le_closure B ⟨x, hxs, rfl⟩
  have hCK : C ≤ K := hs.trans hsupK
  have hKC : K ≤ C :=
    c.closure_min hBC C.2
  have hKCeq : K = C := le_antisymm hKC hCK
  refine ⟨B, hBfin, hBC, ?_⟩
  exact congrArg Subtype.val hKCeq

/-- For a finitary closure operator, compact closed sets are exactly the
closures of finite subsets.  The generator can always be chosen inside
the closed set. -/
theorem isCompactElement_iff_exists_finite_generator
    (hfin : c.IsFinitary) {C : c.Closeds} :
    IsCompactElement C ↔
      ∃ B : Set E, B.Finite ∧ B ⊆ (C : Set E) ∧
        c B = (C : Set E) := by
  constructor
  · exact exists_finite_generator_of_isCompactElement
  · rintro ⟨B, hBfin, -, hBC⟩
    have hcompact : IsCompactElement (c.toCloseds B) :=
      finiteClosure_isCompactElement hfin hBfin
    have hEq : c.toCloseds B = C :=
      Subtype.ext hBC
    exact hEq ▸ hcompact

/-- A finite generating set contains an inclusion-minimal finite
generating subset, without assuming that the entire ground type is finite.
-/
theorem exists_finite_isMinimalGenerator
    {B C : Set E} (hBfin : B.Finite) (hBC : c B = C) :
    ∃ B₀ : Set E, B₀.Finite ∧ B₀ ⊆ B ∧ c.IsMinimalGenerator B₀ C := by
  let P : Set (Set E) := {B₀ | B₀ ⊆ B ∧ c B₀ = C}
  have hPfin : P.Finite := by
    apply hBfin.powerset.subset
    intro B₀ hB₀
    exact hB₀.1
  have hPnonempty : P.Nonempty := ⟨B, subset_rfl, hBC⟩
  obtain ⟨B₀, hB₀min⟩ := hPfin.exists_minimal hPnonempty
  have hB₀fin : B₀.Finite :=
    hBfin.subset hB₀min.prop.1
  refine ⟨B₀, hB₀fin, hB₀min.prop.1, hB₀min.prop.2, ?_⟩
  intro b hb hdel
  have hproper : B₀ \ {b} ⊂ B₀ := by
    rw [Set.ssubset_iff_subset_ne]
    refine ⟨sdiff_subset, ?_⟩
    intro heq
    have : b ∈ B₀ \ {b} := heq.symm ▸ hb
    exact this.2 rfl
  apply hB₀min.not_prop_of_ssubset hproper
  exact ⟨sdiff_subset.trans hB₀min.prop.1, hdel⟩

/-- In the finitary setting, every finite minimal generator is the
extreme-point set, even when the ambient ground type is infinite. -/
theorem finite_minimalGenerator_eq_extremePoints
    (hfin : c.IsFinitary) (hae : c.IsAntiExchange)
    {B C : Set E} (hC : c.IsClosed C)
    (hB : c.IsMinimalGenerator B C) :
    B = c.extremePoints C := by
  apply Set.Subset.antisymm
  · intro b hbB
    rw [mem_extremePoints]
    have hbC : b ∈ C := hB.1 ▸ c.le_closure B hbB
    refine ⟨hbC, ?_⟩
    have hbK : b ∉ c (B \ {b}) := by
      intro hb
      apply hB.2 hbB
      apply Set.Subset.antisymm
      · exact c.closure_min
          (fun z hz ↦ hB.1 ▸ c.le_closure B (sdiff_subset hz)) hC
      · intro z hzC
        have hzClosureB : z ∈ c B := hB.1.symm ▸ hzC
        have hBsub : B ⊆ c (B \ {b}) := by
          intro w hwB
          by_cases hwb : w = b
          · subst w
            exact hb
          · exact c.le_closure (B \ {b}) ⟨hwB, by simpa using hwb⟩
        have hz := c.monotone hBsub hzClosureB
        simpa using hz
    let K : Set E := c (B \ {b})
    have hK : c.IsClosed K := c.isClosed_closure _
    have hBinsert : B ⊆ insert b K := by
      intro z hzB
      by_cases hzb : z = b
      · simp [hzb]
      · exact mem_insert_of_mem b
          (c.le_closure (B \ {b}) ⟨hzB, by simpa using hzb⟩)
    have hCavailable : C ⊆ c (insert b K) := by
      intro z hzC
      exact c.monotone hBinsert (hB.1.symm ▸ hzC)
    intro hb
    obtain ⟨Y, hYfin, hYC, hbY⟩ := hfin hb
    have hYb : b ∉ Y := by
      intro hb'
      exact (hYC hb').2 rfl
    have hnot : b ∉ c (K ∪ Y) :=
      not_mem_closure_union_of_finite hae hK hbK hYfin
        (fun z hz ↦ hCavailable (hYC hz).1) hYb
    exact hnot (c.monotone subset_union_right hbY)
  · exact extremePoints_subset_of_closure_eq hB.1

/-- A compact closed set in a finitary convex geometry has a finite
extreme-point set, and that set is its unique minimal generator. -/
theorem compact_extremePoints_basis
    (hfin : c.IsFinitary) (hae : c.IsAntiExchange)
    {C : c.Closeds} (hcompact : IsCompactElement C) :
    (c.extremePoints (C : Set E)).Finite ∧
      c.IsMinimalGenerator (c.extremePoints (C : Set E)) (C : Set E) := by
  obtain ⟨B, hBfin, -, hBC⟩ :=
    exists_finite_generator_of_isCompactElement hcompact
  obtain ⟨B₀, hB₀fin, -, hB₀⟩ :=
    exists_finite_isMinimalGenerator hBfin hBC
  have hEq :=
    finite_minimalGenerator_eq_extremePoints hfin hae C.2 hB₀
  constructor
  · exact hEq ▸ hB₀fin
  · exact hEq ▸ hB₀

/-- For a compact closed set in a finitary convex geometry, a set is a
minimal generator exactly when it is the extreme-point set.  In
particular, the minimal basis asserted above is unique. -/
theorem compact_isMinimalGenerator_iff_eq_extremePoints
    (hfin : c.IsFinitary) (hae : c.IsAntiExchange)
    {C : c.Closeds} (hcompact : IsCompactElement C) {B : Set E} :
    c.IsMinimalGenerator B (C : Set E) ↔
      B = c.extremePoints (C : Set E) := by
  constructor
  · exact finite_minimalGenerator_eq_extremePoints hfin hae C.2
  · intro hB
    rw [hB]
    exact (compact_extremePoints_basis hfin hae hcompact).2

end QuotientSubmoduleEquidistribution.SetClosure
