import QuotientSubmoduleEquidistribution.ConvexGeometry.Structure

/-!
# Distributivity and unary generation

This file formalizes the closure-theoretic core of
`paper/quotient_submodule_equidistribution/main.tex`, Proposition `prop:distributive`.
For a finitary convex geometry, distributivity of the closed-set lattice is
equivalent both to closure of unions and to the absence of genuinely
collective generation.
-/

open Set

namespace QuotientSubmoduleEquidistribution.SetClosure

variable {E : Type*} {c : SetClosure E}

/-- The distributive identity on the already constructed closed-set
lattice. -/
def ClosedsIsDistributive (c : SetClosure E) : Prop :=
  ∀ C D F : c.Closeds, C ⊓ (D ⊔ F) = C ⊓ D ⊔ C ⊓ F

/-- Binary unions of closed sets are closed. -/
def IsClosedUnderBinaryUnion (c : SetClosure E) : Prop :=
  ∀ C D : c.Closeds, c.IsClosed ((C : Set E) ∪ (D : Set E))

/-- Every point generated by a class is already generated by one member
of that class. -/
def IsUnaryGeneration (c : SetClosure E) : Prop :=
  ∀ ⦃S : Set E⦄ ⦃x : E⦄, x ∈ c S →
    ∃ y ∈ S, x ∈ c ({y} : Set E)

/-- If closed sets are closed under union, closure preserves binary unions
as literal unions. -/
theorem closure_union_eq_union_of_isClosedUnderBinaryUnion
    (hunion : c.IsClosedUnderBinaryUnion) (S T : Set E) :
    c (S ∪ T) = c S ∪ c T := by
  apply Set.Subset.antisymm
  · apply c.closure_min
    · exact union_subset_union (c.le_closure S) (c.le_closure T)
    · exact hunion (c.toCloseds S) (c.toCloseds T)
  · exact union_subset
      (c.monotone subset_union_left)
      (c.monotone subset_union_right)

/-- Closure under binary unions makes the closed-set lattice
distributive. -/
theorem closedsIsDistributive_of_isClosedUnderBinaryUnion
    (hunion : c.IsClosedUnderBinaryUnion) :
    c.ClosedsIsDistributive := by
  intro C D F
  apply Subtype.ext
  have hsup (A B : c.Closeds) :
      ((A ⊔ B : c.Closeds) : Set E) =
        (A : Set E) ∪ (B : Set E) := by
    rw [coe_sup, (hunion A B).closure_eq]
  rw [coe_inf, hsup, hsup, coe_inf, coe_inf]
  ext x
  simp only [mem_inter_iff, mem_union]
  tauto

/-- In a finitary convex geometry, distributivity forces binary unions of
closed sets to be closed.  The obstruction is the point closure of a new
point in the join and its greatest proper closed predecessor. -/
theorem isClosedUnderBinaryUnion_of_closedsIsDistributive
    (hfin : c.IsFinitary) (hae : c.IsAntiExchange)
    (hempty : c.IsClosed ∅)
    (hdistrib : c.ClosedsIsDistributive) :
    c.IsClosedUnderBinaryUnion := by
  intro C D
  rw [ClosureOperator.isClosed_iff_closure_le]
  intro x hx
  by_contra hxUnion
  have hxC : x ∉ (C : Set E) :=
    fun h ↦ hxUnion (Or.inl h)
  have hxD : x ∉ (D : Set E) :=
    fun h ↦ hxUnion (Or.inr h)
  let J : c.Closeds := c.pointClosure x
  let Jₛ : c.Closeds :=
    ⟨c ({x} : Set E) \ {x},
      isClosed_pointClosure_sdiff_singleton hfin hae hempty x⟩
  have hxJoin : x ∈ ((C ⊔ D : c.Closeds) : Set E) := by
    simpa using hx
  have hJle : J ≤ C ⊔ D :=
    pointClosure_le_iff.2 hxJoin
  have hleft : J ⊓ (C ⊔ D) = J :=
    inf_eq_left.mpr hJle
  have hJC : J ⊓ C ≤ Jₛ := by
    rintro y ⟨hyJ, hyC⟩
    exact ⟨hyJ, fun hyx ↦ hxC (hyx ▸ hyC)⟩
  have hJD : J ⊓ D ≤ Jₛ := by
    rintro y ⟨hyJ, hyD⟩
    exact ⟨hyJ, fun hyx ↦ hxD (hyx ▸ hyD)⟩
  have hJJs : J ≤ Jₛ := by
    rw [← hleft, hdistrib J C D]
    exact sup_le hJC hJD
  have hxJ : x ∈ (J : Set E) :=
    c.le_closure {x} (mem_singleton x)
  have hxJs := hJJs hxJ
  exact hxJs.2 (mem_singleton x)

/-- Unary generation immediately implies that unions of closed sets are
closed. -/
theorem isClosedUnderBinaryUnion_of_isUnaryGeneration
    (hunary : c.IsUnaryGeneration) :
    c.IsClosedUnderBinaryUnion := by
  intro C D
  rw [ClosureOperator.isClosed_iff_closure_le]
  intro x hx
  obtain ⟨y, hy, hxy⟩ := hunary hx
  rcases hy with hyC | hyD
  · exact Or.inl
      (c.closure_min (singleton_subset_iff.mpr hyC) C.2 hxy)
  · exact Or.inr
      (c.closure_min (singleton_subset_iff.mpr hyD) D.2 hxy)

/-- Finitarity turns closure under binary unions into unary generation:
first take a finite witness, then split it one point at a time. -/
theorem isUnaryGeneration_of_isClosedUnderBinaryUnion
    (hfin : c.IsFinitary) (hempty : c.IsClosed ∅)
    (hunion : c.IsClosedUnderBinaryUnion) :
    c.IsUnaryGeneration := by
  intro S x hx
  obtain ⟨T, hTfin, hTS, hxT⟩ := hfin hx
  have hfinite :
      ∀ (U : Set E), U.Finite → x ∈ c U →
        ∃ y ∈ U, x ∈ c ({y} : Set E) := by
    intro U hU
    induction U, hU using Set.Finite.induction_on with
    | empty =>
        intro hxEmpty
        have hxEmpty' : x ∈ (∅ : Set E) := by
          rw [← hempty.closure_eq]
          exact hxEmpty
        exact ((Set.mem_empty_iff_false x).mp hxEmpty').elim
    | @insert y U hyU hU ih =>
        intro hxInsert
        rw [show insert y U = ({y} : Set E) ∪ U by ext; simp,
          closure_union_eq_union_of_isClosedUnderBinaryUnion hunion] at hxInsert
        rcases hxInsert with hxy | hxU
        · exact ⟨y, mem_insert y U, hxy⟩
        · obtain ⟨z, hzU, hxz⟩ := ih hxU
          exact ⟨z, mem_insert_of_mem y hzU, hxz⟩
  obtain ⟨y, hyT, hxy⟩ := hfinite T hTfin hxT
  exact ⟨y, hTS hyT, hxy⟩

/-- Exact abstract form of the manuscript's distributivity criterion. -/
theorem closedsIsDistributive_iff_closedUnderUnion_iff_unaryGeneration
    (hfin : c.IsFinitary) (hae : c.IsAntiExchange)
    (hempty : c.IsClosed ∅) :
    c.ClosedsIsDistributive ↔
      c.IsClosedUnderBinaryUnion ∧ c.IsUnaryGeneration := by
  constructor
  · intro hdistrib
    have hunion :=
      isClosedUnderBinaryUnion_of_closedsIsDistributive
        hfin hae hempty hdistrib
    exact
      ⟨hunion,
        isUnaryGeneration_of_isClosedUnderBinaryUnion
          hfin hempty hunion⟩
  · rintro ⟨hunion, -⟩
    exact closedsIsDistributive_of_isClosedUnderBinaryUnion hunion

/-- Pairwise equivalence version matching the three numbered conditions in
the manuscript. -/
theorem closedsIsDistributive_iff_closedUnderBinaryUnion
    (hfin : c.IsFinitary) (hae : c.IsAntiExchange)
    (hempty : c.IsClosed ∅) :
    c.ClosedsIsDistributive ↔ c.IsClosedUnderBinaryUnion := by
  constructor
  · exact
      isClosedUnderBinaryUnion_of_closedsIsDistributive
        hfin hae hempty
  · exact closedsIsDistributive_of_isClosedUnderBinaryUnion

/-- Pairwise equivalence between union closure and absence of collective
generation. -/
theorem isClosedUnderBinaryUnion_iff_isUnaryGeneration
    (hfin : c.IsFinitary) (hempty : c.IsClosed ∅) :
    c.IsClosedUnderBinaryUnion ↔ c.IsUnaryGeneration := by
  constructor
  · exact isUnaryGeneration_of_isClosedUnderBinaryUnion hfin hempty
  · exact isClosedUnderBinaryUnion_of_isUnaryGeneration

end QuotientSubmoduleEquidistribution.SetClosure
