import QuotientSubmoduleEquidistribution.ConvexGeometry.Compact

/-!
# The structural theorem for finitary convex geometries

This file packages the abstract conclusions used in
`paper/quotient_submodule_equidistribution/main.tex`, Theorem `thm:infinite-convex-structure`.
The complete-lattice formulas themselves are supplied by
`ConvexGeometry.ClosedSets`; the structure below records the substantive
algebraicity, spatiality, irreducibility, compactness, and basis assertions.
-/

open Set

namespace QuotientSubmoduleEquidistribution.SetClosure

variable {E : Type*}

/-- A subset is independent when none of its points is generated by the
others.  This is the literal predicate in
`def:independent-extreme` of the frozen paper. -/
def IsIndependent (c : SetClosure E) (B : Set E) : Prop :=
  ∀ ⦃b : E⦄, b ∈ B → b ∉ c (B \ {b})

/-- Independence is exactly minimality as a generator of one's own closure. -/
theorem isIndependent_iff_isMinimalGenerator_closure
    (c : SetClosure E) (B : Set E) :
    c.IsIndependent B ↔ c.IsMinimalGenerator B (c B) := by
  constructor
  · intro h
    refine ⟨rfl, ?_⟩
    intro b hbB heq
    apply h hbB
    rw [heq]
    exact c.le_closure B hbB
  · intro h b hbB hb
    apply h.2 hbB
    apply Set.Subset.antisymm
    · exact c.monotone Set.sdiff_subset
    · apply c.closure_min
      · intro x hxB
        by_cases hxb : x = b
        · simpa [hxb] using hb
        · exact c.le_closure (B \ {b})
            ⟨hxB, by simpa using hxb⟩
      · exact c.isClosed_closure _

/-- Finite independent subsets, exactly as on the left side of the paper's
compact/extreme-point bijection. -/
abbrev FiniteIndependent (c : SetClosure E) :=
  {B : Set E // B.Finite ∧ c.IsIndependent B}

/-- Compact closed subsets, exactly as on the right side of the paper's
compact/extreme-point bijection. -/
abbrev CompactClosedSet (c : SetClosure E) :=
  {C : c.Closeds // IsCompactElement C}

/-- Closure and extreme points give the paper's inverse bijection between
finite independent sets and compact closed sets. -/
def finiteIndependentEquivCompactClosedSet
    {c : SetClosure E} (hfin : c.IsFinitary) (hae : c.IsAntiExchange) :
    c.FiniteIndependent ≃ c.CompactClosedSet where
  toFun B :=
    ⟨c.toCloseds B.1, finiteClosure_isCompactElement hfin B.2.1⟩
  invFun C :=
    ⟨c.extremePoints (C.1 : Set E), by
      have hbasis := compact_extremePoints_basis hfin hae C.2
      exact ⟨hbasis.1,
        (isIndependent_iff_isMinimalGenerator_closure c _).2 (by
          rw [hbasis.2.1]
          exact hbasis.2)⟩⟩
  left_inv B := by
    apply Subtype.ext
    exact
      (finite_minimalGenerator_eq_extremePoints hfin hae
        (c.isClosed_closure B.1)
        ((isIndependent_iff_isMinimalGenerator_closure c B.1).1 B.2.2)).symm
  right_inv C := by
    apply Subtype.ext
    apply Subtype.ext
    exact (compact_extremePoints_basis hfin hae C.2).2.1

/-- The abstract, representation-independent content of the manuscript's
infinite convex-structure theorem.

`IsCompactlyGenerated` is Mathlib's name for an algebraic complete lattice.
The final two fields say that the finite extreme-point set is the unique
inclusion-minimal generating set of every compact closed set. -/
structure InfiniteConvexStructure (c : SetClosure E) : Prop where
  algebraic : IsCompactlyGenerated c.Closeds
  spatial : QuotientSubmoduleEquidistribution.IsSpatial c.Closeds
  completelyJoinIrreducible_iff_pointClosure :
    ∀ J : c.Closeds,
      QuotientSubmoduleEquidistribution.IsCompletelyJoinIrreducible J ↔
        ∃ x : E, J = c.pointClosure x
  pointClosure_injective : Function.Injective c.pointClosure
  pointClosure_compact :
    ∀ x : E, IsCompactElement (c.pointClosure x)
  compact_extremePoints_basis :
    ∀ (C : c.Closeds), IsCompactElement C →
      (c.extremePoints (C : Set E)).Finite ∧
        c.IsMinimalGenerator
          (c.extremePoints (C : Set E)) (C : Set E)
  compact_minimalGenerator_unique :
    ∀ (C : c.Closeds), IsCompactElement C → ∀ B : Set E,
      c.IsMinimalGenerator B (C : Set E) ↔
        B = c.extremePoints (C : Set E)

/-- Every finitary anti-exchange closure with closed empty set has the full
abstract infinite convex structure asserted in the manuscript. -/
theorem infiniteConvexStructure
    {c : SetClosure E}
    (hfin : c.IsFinitary) (hae : c.IsAntiExchange)
    (hempty : c.IsClosed ∅) :
    c.InfiniteConvexStructure where
  algebraic := isCompactlyGenerated_closeds hfin
  spatial := isSpatial_closeds hfin hae hempty
  completelyJoinIrreducible_iff_pointClosure :=
    isCompletelyJoinIrreducible_iff_eq_pointClosure hfin hae hempty
  pointClosure_injective :=
    pointClosure_injective_closeds hae hempty
  pointClosure_compact :=
    pointClosure_isCompactElement hfin
  compact_extremePoints_basis := by
    intro C hC
    exact QuotientSubmoduleEquidistribution.SetClosure.compact_extremePoints_basis hfin hae hC
  compact_minimalGenerator_unique := by
    intro C hC B
    exact
      compact_isMinimalGenerator_iff_eq_extremePoints hfin hae hC

/-- The finite accessibility, cover, grading, and generation conclusions used
in `cor:finite-convex-consequences`, before identifying extreme points with
the relevant module-theoretic split objects. -/
structure FiniteConvexConsequences [Finite E] (c : SetClosure E) : Prop where
  extremePoints_nonempty :
    ∀ {C : Set E}, c.IsClosed C → C.Nonempty →
      (c.extremePoints C).Nonempty
  extreme_deletion_closed :
    ∀ {C : Set E} {x : E}, c.IsClosed C →
      x ∈ c.extremePoints C → c.IsClosed (C \ {x})
  generated_by_extremePoints :
    ∀ {C : Set E}, c.IsClosed C →
      c (c.extremePoints C) = C
  cover_adds_one :
    ∀ {C D : c.Closeds}, C ⋖ D →
      ∃ x : E, x ∉ (C : Set E) ∧
        (D : Set E) = insert x (C : Set E)
  cover_cardinality :
    ∀ {C D : c.Closeds}, C ⋖ D →
      (C : Set E).ncard + 1 = (D : Set E).ncard

/-- Every finite convex geometry has the paper's finite structural
consequences. -/
theorem finiteConvexConsequences [Finite E]
    {c : SetClosure E}
    (hae : c.IsAntiExchange) (hempty : c.IsClosed ∅) :
    c.FiniteConvexConsequences where
  extremePoints_nonempty := by
    intro C hC hCne
    exact QuotientSubmoduleEquidistribution.SetClosure.extremePoints_nonempty
      hae hempty hC hCne
  extreme_deletion_closed := by
    intro C x hC hx
    exact
      (mem_extremePoints_iff_isClosed_sdiff_singleton hC hx.1).1 hx
  generated_by_extremePoints :=
    closure_extremePoints hae
  cover_adds_one :=
    covBy_eq_insert hae
  cover_cardinality :=
    ncard_add_one_eq_of_covBy hae

end QuotientSubmoduleEquidistribution.SetClosure
