import QuotientSubmoduleEquidistribution.RepresentationDirected.EffectiveLiftingAdditive
import QuotientSubmoduleEquidistribution.RepresentationDirected.EffectiveLiftingCoordinates
import QuotientSubmoduleEquidistribution.RepresentationTheory.TraceRejective

/-!
# Quotient closure forces nonnegative mixed coordinates

For a representation-directed indecomposable skeleton, quotient closure of
the additive category generated by the labels outside `D` forces every mixed
coordinate relative to `D` to be nonnegative.  The proof compares a module
with its trace object.  It is entirely abstract and does not use a concrete
algebra or a classification of modules.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace QuotientSubmoduleEquidistribution.RepresentationDirected

universe u uIota

variable (K R : Type u) [Field K] [IsAlgClosed K]
  [Ring R] [Algebra K R] [FiniteDimensional K R] [IsNoetherianRing R]
  {Iota : Type uIota} [Fintype Iota]
  (sigma : IndecomposableSkeleton.{u, uIota, u} R Iota)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

omit [IsAlgClosed K] [FiniteDimensional K R] [Fintype Iota] in
/-- Postcomposition with the trace inclusion is bijective on every selected
indecomposable. -/
theorem postcompLinearMap_traceι_bijective_of_mem
    {S : Set Iota} {a : Iota} (ha : a ∈ S)
    (Y : FGModuleCat.{u} R) :
    Function.Bijective
      (postcompLinearMap (K := K) (X := sigma.obj a)
        (sigma.traceι S Y)) := by
  letI : Mono (sigma.traceι S Y) :=
    (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_mono_iff_injective
      (sigma.traceι S Y)).2 Subtype.val_injective
  constructor
  · intro f g hfg
    exact (cancel_mono (sigma.traceι S Y)).1 hfg
  · intro f
    let glin : sigma.obj a →ₗ[R] sigma.trace S Y :=
      f.hom.hom.codRestrict (sigma.trace S Y) fun y ↦
        sigma.range_le_trace_of_mem ha f ⟨y, rfl⟩
    let g : sigma.obj a ⟶ sigma.traceObject S Y :=
      ConcreteCategory.ofHom glin
    refine ⟨g, ?_⟩
    apply FGModuleCat.hom_ext
    ext y
    rfl

/-- Every object in the additive closure of the retained representatives has
nonnegative mixed coordinates. -/
theorem HasAcyclicNonzeroNonisomorphisms.mixedMultiplicity_nonnegative_of_inAdd
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (D : Finset Iota) {T : FGModuleCat.{u} R}
    (hT : sigma.InAdd {a | a ∉ D} T) (a : Iota) :
    0 ≤ mixedMultiplicity K R sigma H D T a := by
  classical
  obtain ⟨P⟩ := hT
  letI : Fintype P.index := FintypeCat.fintype
  have hcoord :
      mixedMultiplicity K R sigma H D T =
        ∑ t, mixedMultiplicity K R sigma H D
          (sigma.obj (P.label t)) := by
    calc
      mixedMultiplicity K R sigma H D T =
          mixedMultiplicity K R sigma H D
            (sigma.sumOver P.index P.label) :=
        mixedMultiplicity_iso K R sigma H D P.iso
      _ = ∑ t, mixedMultiplicity K R sigma H D
            (sigma.obj (P.label t)) :=
        mixedMultiplicity_biproduct_finite K R sigma H D _
  rw [congrFun hcoord a]
  simp only [Finset.sum_apply]
  apply Finset.sum_nonneg
  intro t _
  by_cases hat : a = P.label t
  · subst a
    rw [H.mixedMultiplicity_obj_self K R sigma D (P.mem t)]
    norm_num
  · rw [H.mixedMultiplicity_obj_ne K R sigma D (P.mem t) hat]

/-- An object in the additive closure of the retained representatives has
zero mixed coordinate at every omitted label. -/
theorem HasAcyclicNonzeroNonisomorphisms.mixedMultiplicity_eq_zero_of_inAdd_of_mem
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (D : Finset Iota) {T : FGModuleCat.{u} R}
    (hT : sigma.InAdd {a | a ∉ D} T) {a : Iota} (ha : a ∈ D) :
    mixedMultiplicity K R sigma H D T a = 0 := by
  classical
  obtain ⟨P⟩ := hT
  letI : Fintype P.index := FintypeCat.fintype
  calc
    mixedMultiplicity K R sigma H D T a =
        mixedMultiplicity K R sigma H D
          (sigma.sumOver P.index P.label) a :=
      congrFun (mixedMultiplicity_iso K R sigma H D P.iso) a
    _ = (∑ t, mixedMultiplicity K R sigma H D
          (sigma.obj (P.label t))) a :=
      congrFun (mixedMultiplicity_biproduct_finite K R sigma H D _) a
    _ = ∑ t, mixedMultiplicity K R sigma H D
          (sigma.obj (P.label t)) a := by
      simp only [Finset.sum_apply]
    _ = 0 := by
      apply Finset.sum_eq_zero
      intro t _
      apply H.mixedMultiplicity_obj_ne K R sigma D (P.mem t)
      intro hat
      subst a
      exact P.mem t ha

/-- Quotient closure of the retained support forces every mixed coordinate of
every finitely generated module to be nonnegative. -/
theorem HasAcyclicNonzeroNonisomorphisms.mixedMultiplicity_nonnegative_of_qClosed
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (D : Finset Iota)
    (hclosed : sigma.qClosure.IsClosed {a | a ∉ D})
    (Y : FGModuleCat.{u} R) (a : Iota) :
    0 ≤ mixedMultiplicity K R sigma H D Y a := by
  letI := directedLinearOrder sigma H
  classical
  let T := sigma.traceObject {a | a ∉ D} Y
  let f : T ⟶ Y := sigma.traceι {a | a ∉ D} Y
  have hT : sigma.InAdd {a | a ∉ D} T :=
    sigma.traceObject_inAdd_of_qClosed hclosed Y
  have hbij : ∀ b, b ∉ D → Function.Bijective
      (postcompLinearMap (K := K) (X := sigma.obj b) f) := by
    intro b hb
    exact postcompLinearMap_traceι_bijective_of_mem K R sigma hb Y
  have hHom : ∀ b, b ∉ D →
      homFinrankVector K R sigma Y b = homFinrankVector K R sigma T b := by
    intro b hb
    letI : FiniteDimensional K (sigma.obj b ⟶ T) :=
      finiteDimensional_hom_from_obj K R sigma b T
    letI : FiniteDimensional K (sigma.obj b ⟶ Y) :=
      finiteDimensional_hom_from_obj K R sigma b Y
    have hrank :=
      (LinearEquiv.ofBijective
        (postcompLinearMap (K := K) (X := sigma.obj b) f)
        (hbij b hb)).finrank_eq
    change (Module.finrank K (sigma.obj b ⟶ Y) : ℤ) =
      (Module.finrank K (sigma.obj b ⟶ T) : ℤ)
    exact_mod_cast hrank.symm
  by_cases ha : a ∈ D
  · have hTzero : mixedMultiplicity K R sigma H D T a = 0 :=
      H.mixedMultiplicity_eq_zero_of_inAdd_of_mem K R sigma D hT ha
    have hcoordinates : ∀ b, b ∉ insert a D →
        mixedMultiplicity K R sigma H D Y b =
          mixedMultiplicity K R sigma H D T b := by
      intro b hb
      have hbD : b ∉ D := fun h ↦ hb (Finset.mem_insert_of_mem h)
      have h := UpperUnitriangular.coordinates_eq_on_retained_of_eq_on_retained
        (homFinrankMatrix K R sigma) D
        (H.homFinrankMatrix_blockTriangular K R sigma)
        (H.homFinrankMatrix_diagonal K R sigma)
        (v := homFinrankVector K R sigma Y)
        (w := homFinrankVector K R sigma T)
        hHom hbD
      simpa only [mixedMultiplicity] using h
    have hrow := UpperUnitriangular.value_eq_add_coordinate_sub
      (homFinrankMatrix K R sigma) D
      (H.homFinrankMatrix_blockTriangular K R sigma)
      (H.homFinrankMatrix_diagonal K R sigma)
      (homFinrankVector K R sigma Y)
      (homFinrankVector K R sigma T)
      hcoordinates
    have hinj : Function.Injective
        (postcompLinearMap (K := K) (X := sigma.obj a) f) := by
      letI : Mono f :=
        (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_mono_iff_injective f).2
          Subtype.val_injective
      intro x y hxy
      exact (cancel_mono f).1 hxy
    letI : FiniteDimensional K (sigma.obj a ⟶ T) :=
      finiteDimensional_hom_from_obj K R sigma a T
    letI : FiniteDimensional K (sigma.obj a ⟶ Y) :=
      finiteDimensional_hom_from_obj K R sigma a Y
    have hleNat : Module.finrank K (sigma.obj a ⟶ T) ≤
        Module.finrank K (sigma.obj a ⟶ Y) :=
      LinearMap.finrank_le_finrank_of_injective hinj
    have hle : homFinrankVector K R sigma T a ≤
        homFinrankVector K R sigma Y a := by
      change (Module.finrank K (sigma.obj a ⟶ T) : ℤ) ≤
        (Module.finrank K (sigma.obj a ⟶ Y) : ℤ)
      exact_mod_cast hleNat
    have hrow' : homFinrankVector K R sigma Y a =
        homFinrankVector K R sigma T a +
          mixedMultiplicity K R sigma H D Y a -
          mixedMultiplicity K R sigma H D T a := by
      simpa only [mixedMultiplicity] using hrow
    rw [hTzero, sub_zero] at hrow'
    omega
  · have hcoord : mixedMultiplicity K R sigma H D Y a =
        mixedMultiplicity K R sigma H D T a := by
      have h := UpperUnitriangular.coordinates_eq_on_retained_of_eq_on_retained
        (homFinrankMatrix K R sigma) D
        (H.homFinrankMatrix_blockTriangular K R sigma)
        (H.homFinrankMatrix_diagonal K R sigma)
        (v := homFinrankVector K R sigma Y)
        (w := homFinrankVector K R sigma T)
        hHom ha
      simpa only [mixedMultiplicity] using h
    rw [hcoord]
    exact H.mixedMultiplicity_nonnegative_of_inAdd K R sigma D hT a

/-- In particular, quotient closure implies the pairwise nonnegativity
condition appearing in the paper. -/
theorem HasAcyclicNonzeroNonisomorphisms.mixedMultiplicity_obj_nonnegative_of_qClosed
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (D : Finset Iota)
    (hclosed : sigma.qClosure.IsClosed {a | a ∉ D})
    (j a : Iota) :
    0 ≤ mixedMultiplicity K R sigma H D (sigma.obj j) a :=
  H.mixedMultiplicity_nonnegative_of_qClosed K R sigma D hclosed
    (sigma.obj j) a

end QuotientSubmoduleEquidistribution.RepresentationDirected
