import Mathlib.Order.Extension.Linear
import QuotientSubmoduleEquidistribution.RepresentationDirected.AlmostSplitExtBridge

/-!
# The Hom order of a representation-directed skeleton

The manuscript orders its indecomposable representatives by linearly
extending reachability through nonzero nonisomorphisms.  This file formalizes
that construction.

The cycle-free hypothesis is exactly the nontrivial part of
representation-directedness.  Representation-finiteness is not needed for
the order construction itself.  No algebraic-closure, division-endomorphism,
or almost-split existence hypothesis is used.
-/

noncomputable section

open CategoryTheory

namespace QuotientSubmoduleEquidistribution.RepresentationDirected

universe uR uIota

variable {R : Type uR} [Ring R] [IsNoetherianRing R]
  {Iota : Type uIota}
  (sigma : IndecomposableSkeleton.{uR, uIota, uR} R Iota)

/-- A nonzero nonisomorphism between two chosen indecomposable modules. -/
def NonzeroNonisomorphism (i j : Iota) : Prop :=
  ∃ f : sigma.obj i ⟶ sigma.obj j, f ≠ 0 ∧ ¬ IsIso f

/-- The reflexive transitive relation generated by nonzero
nonisomorphisms. -/
def NonzeroNonisomorphismReachability (i j : Iota) : Prop :=
  Relation.ReflTransGen (NonzeroNonisomorphism sigma) i j

/-- The cycle-free part of representation-directedness, expressed on a
complete duplicate-free indecomposable skeleton. -/
def HasAcyclicNonzeroNonisomorphisms : Prop :=
  ∀ i : Iota,
    ¬ Relation.TransGen (NonzeroNonisomorphism sigma) i i

/-- Cycle-freeness makes nonzero-nonisomorphism reachability a partial
order. -/
theorem nonzeroNonisomorphismReachability_isPartialOrder
    (H : HasAcyclicNonzeroNonisomorphisms sigma) :
    IsPartialOrder Iota (NonzeroNonisomorphismReachability sigma) where
  refl _ := Relation.ReflTransGen.refl
  trans _ _ _ := Relation.ReflTransGen.trans
  antisymm := by
    intro i j hij hji
    by_contra hne
    have hij' : Relation.TransGen (NonzeroNonisomorphism sigma) i j :=
      (Relation.reflTransGen_iff_eq_or_transGen.mp hij).resolve_left
        (fun hji' => hne hji'.symm)
    exact H i (hij'.trans_left hji)

/-- A chosen linear extension of nonzero-nonisomorphism reachability. -/
@[reducible] noncomputable def directedLinearOrder
    (H : HasAcyclicNonzeroNonisomorphisms sigma) : LinearOrder Iota := by
  letI : IsPartialOrder Iota (NonzeroNonisomorphismReachability sigma) :=
    nonzeroNonisomorphismReachability_isPartialOrder sigma H
  let s := (extend_partialOrder
    (NonzeroNonisomorphismReachability sigma)).choose
  have hs : IsLinearOrder Iota s :=
    (extend_partialOrder
      (NonzeroNonisomorphismReachability sigma)).choose_spec.1
  exact
    { le := s
      le_refl := hs.refl
      le_trans := hs.trans
      le_antisymm := hs.antisymm
      le_total := hs.total
      toDecidableLE := Classical.decRel s }

/-- The chosen linear order extends directed reachability. -/
theorem le_directedLinearOrder_of_reachable
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    {i j : Iota} (h : NonzeroNonisomorphismReachability sigma i j) :
    letI := directedLinearOrder sigma H
    i ≤ j := by
  letI : IsPartialOrder Iota (NonzeroNonisomorphismReachability sigma) :=
    nonzeroNonisomorphismReachability_isPartialOrder sigma H
  exact (extend_partialOrder
    (NonzeroNonisomorphismReachability sigma)).choose_spec.2 i j h

/-- Every nonzero endomorphism of a chosen indecomposable is invertible under
the cycle-free condition: a noninvertible one would be a one-edge cycle. -/
theorem HasAcyclicNonzeroNonisomorphisms.isIso_of_ne_zero_endomorphism
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (i : Iota) (f : sigma.obj i ⟶ sigma.obj i) (hf : f ≠ 0) :
    IsIso f := by
  by_contra hfiso
  exact H i (Relation.TransGen.single ⟨f, hf, hfiso⟩)

/-- The manuscript's strict off-diagonal Hom-order condition. -/
def HomOrderProperty [Preorder Iota] : Prop :=
  ∀ {i j : Iota} (f : sigma.obj i ⟶ sigma.obj j),
    f ≠ 0 → i ≠ j → i < j

/-- An explicit choice of the manuscript's directed linear order.

Keeping the order as data is essential when two skeletons are related by a
duality: the target order can then be chosen to be literally the reverse of
the source order, rather than making two unrelated noncomputable choices. -/
structure DirectedOrderChoice where
  order : LinearOrder Iota
  homOrderProperty :
    letI := order
    HomOrderProperty sigma

/-- The chosen linear extension has the manuscript's Hom-order property. -/
theorem directedLinearOrder_homOrderProperty
    (H : HasAcyclicNonzeroNonisomorphisms sigma) :
    letI := directedLinearOrder sigma H
    HomOrderProperty sigma := by
  letI := directedLinearOrder sigma H
  intro i j f hf hij
  have hfnot : ¬ IsIso f := by
    intro hfiso
    letI : IsIso f := hfiso
    exact hij (sigma.eq_of_iso ⟨asIso f⟩)
  have hreach : NonzeroNonisomorphismReachability sigma i j :=
    Relation.ReflTransGen.single ⟨f, hf, hfnot⟩
  exact lt_of_le_of_ne
    (le_directedLinearOrder_of_reachable sigma H hreach) hij

/-- The default noncomputably chosen linear extension, bundled as an
explicit directed-order choice. -/
def DirectedOrderChoice.chosen
    (H : HasAcyclicNonzeroNonisomorphisms sigma) :
    DirectedOrderChoice sigma where
  order := directedLinearOrder sigma H
  homOrderProperty := directedLinearOrder_homOrderProperty sigma H

namespace DirectedHomOrder

/-- The manuscript's strict ordering condition constructs the weaker order
package consumed by the almost-split Ext argument.  Finite length rules out
the diagonal irreducible case. -/
theorem of_homOrderProperty [Preorder Iota]
    (H : HomOrderProperty sigma) : DirectedHomOrder sigma := by
  refine
    { le_of_nonzero := ?_
      lt_of_irreducible := ?_ }
  · intro i j f hf
    by_cases hij : i = j
    · subst j
      exact le_rfl
    · exact (H f hf hij).le
  · intro i j hij
    obtain ⟨f, hf⟩ := hij
    have hlabels : i ≠ j := by
      intro hEq
      subst j
      exact sigma.hasNoIrreducibleEndomorphism_obj i ⟨f, hf⟩
    have hf0 : f ≠ 0 := by
      intro hzero
      have hnotSquare :=
        ((sigma.isIrreducibleMorphism_iff_mem_radical_not_mem_radicalSquare
          f).1 hf).2
      apply hnotSquare
      rw [hzero]
      exact AddSubgroup.zero_mem _
    exact H f hf0 hlabels

/-- Paper-literal wrapper using nonisomorphism of the represented objects
instead of inequality of duplicate-free skeleton labels. -/
theorem of_nonzero_nonisomorphic [Preorder Iota]
    (H : ∀ {i j : Iota} (f : sigma.obj i ⟶ sigma.obj j),
      f ≠ 0 → ¬ Nonempty (sigma.obj i ≅ sigma.obj j) → i < j) :
    DirectedHomOrder sigma := by
  apply of_homOrderProperty sigma
  intro i j f hf hij
  apply H f hf
  intro hiso
  exact hij (sigma.eq_of_iso hiso)

/-- The chosen linear extension of a cycle-free skeleton automatically
supplies the directed Hom order used by the almost-split lifting bridge. -/
theorem of_acyclicNonzeroNonisomorphisms
    (H : HasAcyclicNonzeroNonisomorphisms sigma) :
    letI := directedLinearOrder sigma H
    DirectedHomOrder sigma := by
  letI := directedLinearOrder sigma H
  exact of_homOrderProperty sigma
    (directedLinearOrder_homOrderProperty sigma H)

end DirectedHomOrder

namespace DirectedOrderChoice

/-- An explicit Hom order supplies the weaker order package used by the
almost-split arguments. -/
theorem directedHomOrder (E : DirectedOrderChoice sigma) :
    letI := E.order
    DirectedHomOrder sigma := by
  letI := E.order
  exact DirectedHomOrder.of_homOrderProperty sigma E.homOrderProperty

end DirectedOrderChoice

end QuotientSubmoduleEquidistribution.RepresentationDirected
