import QuotientSubmoduleEquidistribution.CategoryTheory.LinearGeneratedHomIdeal
import QuotientSubmoduleEquidistribution.RepresentationDirected.IyamaWordPathCategory
import Mathlib.RingTheory.LocalRing.RingHom.Basic

/-!
# The finite linear word mesh category

This file quotients the free word-path category by the ordinary mesh
relations.  It proves that the quotient is linear and directed, that all Hom
spaces are finite-dimensional, and that every vertex endomorphism ring is the
coefficient field.  The additive hull and mesh exactness are subsequent
layers.

No concrete algebra, quiver instance, or module classification is used.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory

namespace QuotientSubmoduleEquidistribution.RepresentationDirected.IyamaMesh.WordMesh

open QuotientSubmoduleEquidistribution.CategoricalIdeal
open QuotientSubmoduleEquidistribution.RepresentationDirected.ARWord
open QuotientSubmoduleEquidistribution.RepresentationDirected.IyamaMesh.WordPath

universe uK uL

variable {K : Type uK} [Field K]
variable {L : Type uL}

/-- The family of ordinary mesh relations, indexed by their endpoints. -/
def meshGeneratorSet (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (X Y : WordPath.Category K G Q) : Set (X ⟶ Y) :=
  {f | ∃ hXY : IsPrevious Q (WordPath.position G Q X)
      (WordPath.position G Q Y),
    f = WordPath.meshRelation (K := K) G Q hAlt hXY}

/-- The two-sided linear ideal generated by the word mesh relations. -/
def meshIdeal (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) :
    HomIdeal (WordPath.Category K G Q) :=
  HomIdeal.linearSpan K (meshGeneratorSet (K := K) G Q hAlt)

/-- The raw categorical quotient by the word mesh ideal. -/
abbrev RawCategory (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) :=
  CategoryTheory.Quotient (meshIdeal (K := K) G Q hAlt).rel

/-- The quotient functor from paths to the raw mesh category. -/
abbrev quotientFunctor (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) :=
  CategoryTheory.Quotient.functor (meshIdeal (K := K) G Q hAlt).rel

instance rawPreadditive (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) :
    Preadditive (RawCategory (K := K) G Q hAlt) :=
  (meshIdeal (K := K) G Q hAlt).quotientPreadditive

instance quotientFunctorAdditive (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) :
    (quotientFunctor (K := K) G Q hAlt).Additive :=
  CategoryTheory.Quotient.functor_additive
    (meshIdeal (K := K) G Q hAlt).rel
    (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
      (meshIdeal (K := K) G Q hAlt).add_compatible
        f₁ f₂ g₁ g₂ hf hg)

instance rawLinear (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) :
    Linear K (RawCategory (K := K) G Q hAlt) :=
  (meshIdeal (K := K) G Q hAlt).quotientLinear

instance quotientFunctorLinear (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) :
    (quotientFunctor (K := K) G Q hAlt).Linear K :=
  (meshIdeal (K := K) G Q hAlt).quotientFunctorLinear

/-- A word position as an object of the raw quotient. -/
def rawObj (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    RawCategory (K := K) G Q hAlt :=
  (quotientFunctor (K := K) G Q hAlt).obj (WordPath.obj K G Q x)

/-- The mesh category, re-induced so that its object type is literally the
finite set of word positions. -/
abbrev Category (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) :=
  InducedCategory (RawCategory (K := K) G Q hAlt)
    (rawObj (K := K) G Q hAlt)

/-- A word position with the mesh-category structure made explicit. -/
def obj (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    Category (K := K) G Q hAlt :=
  x

/-- Map a path-category morphism to the mesh quotient. -/
def quotientHom (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {x y : Fin Q.length}
    (f : WordPath.obj K G Q x ⟶ WordPath.obj K G Q y) :
    obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt y :=
  InducedCategory.homMk ((quotientFunctor (K := K) G Q hAlt).map f)

@[simp]
theorem quotientHom_zero (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) {x y : Fin Q.length} :
    quotientHom (K := K) G Q hAlt
      (0 : WordPath.obj K G Q x ⟶ WordPath.obj K G Q y) = 0 := by
  apply InducedCategory.hom_ext
  change (quotientFunctor (K := K) G Q hAlt).map 0 = 0
  simp

@[simp]
theorem quotientHom_add (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) {x y : Fin Q.length}
    (f g : WordPath.obj K G Q x ⟶ WordPath.obj K G Q y) :
    quotientHom (K := K) G Q hAlt (f + g) =
      quotientHom (K := K) G Q hAlt f + quotientHom (K := K) G Q hAlt g := by
  apply InducedCategory.hom_ext
  change (quotientFunctor (K := K) G Q hAlt).map (f + g) =
    (quotientFunctor (K := K) G Q hAlt).map f +
      (quotientFunctor (K := K) G Q hAlt).map g
  simp

@[simp]
theorem quotientHom_smul (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) {x y : Fin Q.length}
    (k : K) (f : WordPath.obj K G Q x ⟶ WordPath.obj K G Q y) :
    quotientHom (K := K) G Q hAlt (k • f) =
      k • quotientHom (K := K) G Q hAlt f := by
  apply InducedCategory.hom_ext
  change (quotientFunctor (K := K) G Q hAlt).map (k • f) =
    k • (quotientFunctor (K := K) G Q hAlt).map f
  simp

@[simp]
theorem quotientHom_id (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    quotientHom (K := K) G Q hAlt (𝟙 (WordPath.obj K G Q x)) =
      𝟙 (obj (K := K) G Q hAlt x) := by
  apply InducedCategory.hom_ext
  change (quotientFunctor (K := K) G Q hAlt).map
    (𝟙 (WordPath.obj K G Q x)) = 𝟙 _
  simp

@[simp, reassoc]
theorem quotientHom_comp (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) {x y z : Fin Q.length}
    (f : WordPath.obj K G Q x ⟶ WordPath.obj K G Q y)
    (g : WordPath.obj K G Q y ⟶ WordPath.obj K G Q z) :
    quotientHom (K := K) G Q hAlt (f ≫ g) =
      quotientHom (K := K) G Q hAlt f ≫
        quotientHom (K := K) G Q hAlt g := by
  apply InducedCategory.hom_ext
  change (quotientFunctor (K := K) G Q hAlt).map (f ≫ g) =
    (quotientFunctor (K := K) G Q hAlt).map f ≫
      (quotientFunctor (K := K) G Q hAlt).map g
  simp

/-- Every defining mesh relation vanishes in the mesh category. -/
theorem quotientHom_meshRelation_eq_zero
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {p x : Fin Q.length} (hpx : IsPrevious Q p x) :
    quotientHom (K := K) G Q hAlt
      (WordPath.meshRelation (K := K) G Q hAlt hpx) = 0 := by
  ext
  apply ((meshIdeal (K := K) G Q hAlt).map_eq_zero_iff _).2
  apply HomIdeal.relation_mem_linearSpan
  exact ⟨hpx, rfl⟩

/-- The quotient map on each Hom space as a linear map. -/
def quotientHomLinearMap (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x y : Fin Q.length) :
    (WordPath.obj K G Q x ⟶ WordPath.obj K G Q y) →ₗ[K]
      (obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt y) where
  toFun := quotientHom (K := K) G Q hAlt
  map_add' := quotientHom_add G Q hAlt
  map_smul' := quotientHom_smul G Q hAlt

/-- The quotient map is surjective on every Hom space. -/
theorem quotientHom_surjective (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x y : Fin Q.length) :
    Function.Surjective (quotientHom (K := K) G Q hAlt :
      (WordPath.obj K G Q x ⟶ WordPath.obj K G Q y) →
        (obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt y)) := by
  intro f
  obtain ⟨g, hg⟩ :=
    (quotientFunctor (K := K) G Q hAlt).map_surjective f.hom
  exact ⟨g, InducedCategory.hom_ext hg⟩

/-- Mesh-category Hom spaces remain finite-dimensional. -/
instance homModuleFinite (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x y : Category (K := K) G Q hAlt) :
    Module.Finite K (x ⟶ y) :=
  Module.Finite.of_surjective
    (quotientHomLinearMap (K := K) G Q hAlt x y)
    (quotientHom_surjective (K := K) G Q hAlt x y)

/-- Directedness survives the mesh quotient. -/
theorem hom_eq_zero_of_not_le (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {x y : Fin Q.length} (hxy : ¬ x ≤ y)
    (f : obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt y) :
    f = 0 := by
  obtain ⟨g, rfl⟩ := quotientHom_surjective (K := K) G Q hAlt x y f
  have hg := WordPath.hom_eq_zero_of_not_le G Q hxy g
  subst g
  exact quotientHom_zero G Q hAlt

/-- The mesh ideal has zero component on every vertex endomorphism space. -/
theorem mem_meshIdeal_self_eq_zero
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length)
    {f : WordPath.obj K G Q x ⟶ WordPath.obj K G Q x}
    (hf : f ∈ (meshIdeal (K := K) G Q hAlt).hom
      (WordPath.obj K G Q x) (WordPath.obj K G Q x)) :
    f = 0 := by
  change f ∈ HomIdeal.generatedHomSubmodule K
    (meshGeneratorSet (K := K) G Q hAlt)
    (WordPath.obj K G Q x) (WordPath.obj K G Q x) at hf
  induction hf using Submodule.span_induction with
  | mem f hf =>
      rcases hf with ⟨A, B, r, ⟨hAB, hr⟩, a, b, rfl⟩
      by_cases hxA : x ≤ WordPath.position G Q A
      · have hxB : x < WordPath.position G Q B := hxA.trans_lt hAB.1
        have hb : b = 0 :=
          WordPath.hom_eq_zero_of_not_le G Q (not_le_of_gt hxB) b
        simp [hb]
      · have ha : a = 0 :=
          WordPath.hom_eq_zero_of_not_le G Q hxA a
        simp [ha]
  | zero => rfl
  | add f g _ _ hf hg => rw [hf, hg, add_zero]
  | smul k f _ hf => rw [hf, smul_zero]

/-- On vertex endomorphisms the quotient map is injective. -/
theorem quotientHom_self_injective
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    Function.Injective (quotientHom (K := K) G Q hAlt :
      (WordPath.obj K G Q x ⟶ WordPath.obj K G Q x) →
        (obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt x)) := by
  intro f g hfg
  have hmap :
      (quotientFunctor (K := K) G Q hAlt).map f =
        (quotientFunctor (K := K) G Q hAlt).map g :=
    congrArg InducedCategory.Hom.hom hfg
  have hrel :=
    (CategoryTheory.Quotient.functor_map_eq_iff
      (meshIdeal (K := K) G Q hAlt).rel f g).mp hmap
  have hzero := mem_meshIdeal_self_eq_zero G Q hAlt x hrel
  exact sub_eq_zero.mp hzero

/-- The quotient does not alter a vertex endomorphism space. -/
def quotientEndLinearEquiv
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    (WordPath.obj K G Q x ⟶ WordPath.obj K G Q x) ≃ₗ[K]
      (obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt x) :=
  LinearEquiv.ofBijective
    (quotientHomLinearMap (K := K) G Q hAlt x x)
    ⟨quotientHom_self_injective G Q hAlt x,
      quotientHom_surjective (K := K) G Q hAlt x x⟩

/-- Every vertex endomorphism space of the mesh quotient is the coefficient
field. -/
def selfHomLinearEquiv
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    (obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt x) ≃ₗ[K] K :=
  (quotientEndLinearEquiv (K := K) G Q hAlt x).symm.trans
    (WordPath.selfHomLinearEquiv (K := K) G Q x)

@[simp]
theorem selfHomLinearEquiv_id
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    selfHomLinearEquiv (K := K) G Q hAlt x
      (𝟙 (obj (K := K) G Q hAlt x)) = 1 := by
  have hpre :
      (quotientEndLinearEquiv (K := K) G Q hAlt x).symm
        (𝟙 (obj (K := K) G Q hAlt x)) =
          𝟙 (WordPath.obj K G Q x) := by
    apply (quotientEndLinearEquiv (K := K) G Q hAlt x).injective
    rw [LinearEquiv.apply_symm_apply]
    exact quotientHom_id G Q hAlt x
  rw [selfHomLinearEquiv, LinearEquiv.trans_apply, hpre,
    WordPath.selfHomLinearEquiv_id]

/-- Every mesh-category vertex endomorphism is its scalar coordinate times
the identity. -/
theorem eq_smul_id_selfHomLinearEquiv
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length)
    (f : obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt x) :
    f = selfHomLinearEquiv (K := K) G Q hAlt x f •
      𝟙 (obj (K := K) G Q hAlt x) := by
  apply (selfHomLinearEquiv (K := K) G Q hAlt x).injective
  rw [LinearEquiv.map_smul, selfHomLinearEquiv_id,
    smul_eq_mul, mul_one]

/-- Scalar coordinates respect composition of vertex endomorphisms. -/
theorem selfHomLinearEquiv_comp
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length)
    (f g : obj (K := K) G Q hAlt x ⟶ obj (K := K) G Q hAlt x) :
    selfHomLinearEquiv (K := K) G Q hAlt x (f ≫ g) =
      selfHomLinearEquiv (K := K) G Q hAlt x f *
        selfHomLinearEquiv (K := K) G Q hAlt x g := by
  rw [eq_smul_id_selfHomLinearEquiv G Q hAlt x f,
    eq_smul_id_selfHomLinearEquiv G Q hAlt x g]
  simp [selfHomLinearEquiv_id, smul_smul, mul_comm]

/-- Scalar coordinates as a homomorphism of endomorphism rings. -/
def selfHomRingHom
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    End (obj (K := K) G Q hAlt x) →+* K where
  toFun := selfHomLinearEquiv (K := K) G Q hAlt x
  map_zero' := (selfHomLinearEquiv (K := K) G Q hAlt x).map_zero
  map_one' := selfHomLinearEquiv_id G Q hAlt x
  map_add' := (selfHomLinearEquiv (K := K) G Q hAlt x).map_add
  map_mul' := by
    intro f g
    rw [End.mul_def, selfHomLinearEquiv_comp]
    exact mul_comm _ _

/-- The endomorphism ring of every mesh-category vertex is the coefficient
field. -/
def selfHomRingEquiv
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    End (obj (K := K) G Q hAlt x) ≃+* K :=
  RingEquiv.ofBijective
    (selfHomRingHom (K := K) G Q hAlt x)
    (selfHomLinearEquiv (K := K) G Q hAlt x).bijective

/-- Vertex endomorphism rings in the mesh category are local. -/
instance endIsLocalRing
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q) (x : Fin Q.length) :
    IsLocalRing (End (obj (K := K) G Q hAlt x)) :=
  (selfHomRingEquiv (K := K) G Q hAlt x).symm.isLocalRing

end QuotientSubmoduleEquidistribution.RepresentationDirected.IyamaMesh.WordMesh
