import QuotientSubmoduleEquidistribution.RepresentationTheory.NormalModules

/-!
# Finite supports and basic conormal modules

This is the exact submodule/cogeneration dual of `NormalModules.lean`.
It identifies paper-conormality of the canonical basic module attached to
a finite support with minimal generation for submodule closure.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton

universe u v w

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} (σ : IndecomposableSkeleton.{u, v, w} R ι)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- `X` belongs to `Sub M`: it embeds into a finite biproduct of copies
of the concrete module `M`. -/
def InSubOfModule
    (M X : FGModuleCat.{w} R) : Prop :=
  ∃ (J : FintypeCat.{0})
    (p : X ⟶ (⨁ fun _ : J ↦ M)), Mono p

/-- Submodule generation is closed under precomposition with a
monomorphism. -/
theorem inSub_of_mono
    {S : Set ι} {X Y : FGModuleCat.{w} R}
    (hY : σ.InSub S Y) (f : X ⟶ Y) [Mono f] :
    σ.InSub S X := by
  obtain ⟨P⟩ := hY
  letI : Mono P.map := P.mono
  exact ⟨{
    index := P.index
    label := P.label
    mem := P.mem
    map := f ≫ P.map
    mono := inferInstance }⟩

/-- A finite biproduct of submodule-generated objects is again
submodule-generated. -/
theorem inSub_biproduct
    {S : Set ι}
    (J : FintypeCat.{0}) (F : J → FGModuleCat.{w} R)
    (hF : ∀ j, σ.InSub S (F j)) :
    σ.InSub S (biproduct F) := by
  classical
  let inner : ∀ j : J, σ.SubPresentation S (F j) :=
    fun j ↦ Classical.choice (hF j)
  let K : FintypeCat.{0} :=
    FintypeCat.of (Σ j : J, (inner j).index)
  let a : K → ι :=
    fun p ↦ (inner p.1).label p.2
  let flattenIso :
      (⨁ fun j : J ↦
        σ.sumOver (inner j).index (inner j).label) ≅
        σ.sumOver K a :=
    biproductBiproductIso
      (fun j : J ↦ (inner j).index)
      (fun j t ↦ σ.obj ((inner j).label t))
  let q :
      biproduct F ⟶ σ.sumOver K a :=
    biproduct.map (fun j ↦ (inner j).map) ≫ flattenIso.hom
  refine ⟨{
    index := K
    label := a
    mem := fun p ↦ (inner p.1).mem p.2
    map := q
    mono := ?_ }⟩
  letI (j : J) : Mono (inner j).map := (inner j).mono
  dsimp only [q]
  infer_instance

/-- The canonical basic module is submodule-generated by its support. -/
theorem basicModule_inSub
    (B : FiniteSupport (ι := ι)) :
    σ.InSub B.1 (σ.basicModule B) := by
  exact ⟨{
    index := B.index
    label := B.label
    mem := B.label_mem
    map := 𝟙 _
    mono := inferInstance }⟩

/-- Submodules of finite sums of the basic module are generated by its
indecomposable support. -/
theorem inSub_of_inSubOfModule_basicModule
    (B : FiniteSupport (ι := ι)) {X : FGModuleCat.{w} R}
    (hX : InSubOfModule (σ.basicModule B) X) :
    σ.InSub B.1 X := by
  obtain ⟨J, p, hp⟩ := hX
  letI : Mono p := hp
  have htarget :
      σ.InSub B.1 (⨁ fun _ : J ↦ σ.basicModule B) :=
    inSub_biproduct σ J (fun _ ↦ σ.basicModule B)
      (fun _ ↦ basicModule_inSub σ B)
  exact inSub_of_mono σ htarget p

/-- Conversely, a submodule presentation by representatives in `B`
embeds into a finite sum of copies of the basic module attached to `B`. -/
theorem inSubOfModule_basicModule_of_inSub
    (B : FiniteSupport (ι := ι)) {X : FGModuleCat.{w} R}
    (hX : σ.InSub B.1 X) :
    InSubOfModule (σ.basicModule B) X := by
  classical
  obtain ⟨P⟩ := hX
  let coordinate
      (t : P.index) :
      σ.obj (P.label t) ⟶ σ.basicModule B :=
    eqToHom
        (congrArg σ.obj
          (B.label_equivFin ⟨P.label t, P.mem t⟩).symm) ≫
      biproduct.ι
        (fun s : B.index ↦ σ.obj (B.label s))
        (B.equivFin ⟨P.label t, P.mem t⟩)
  let q :
      X ⟶ (⨁ fun _ : P.index ↦ σ.basicModule B) :=
    P.map ≫ biproduct.map coordinate
  refine ⟨P.index, q, ?_⟩
  letI (t : P.index) : Mono (coordinate t) := by
    dsimp only [coordinate]
    infer_instance
  letI : Mono P.map := P.mono
  dsimp only [q]
  infer_instance

/-- Exact bridge between module-level cogeneration by the basic module
and support-level `Sub(add B)`. -/
theorem inSubOfModule_basicModule_iff
    (B : FiniteSupport (ι := ι)) (X : FGModuleCat.{w} R) :
    InSubOfModule (σ.basicModule B) X ↔ σ.InSub B.1 X :=
  ⟨inSub_of_inSubOfModule_basicModule σ B,
    inSubOfModule_basicModule_of_inSub σ B⟩

/-- Paper-conormality for the canonical basic module: after deleting an
indecomposable summand `X_b`, that summand is not in `Sub` of the concrete
complement module. -/
def IsPaperConormal (B : FiniteSupport (ι := ι)) : Prop :=
  ∀ b : B.1,
    ¬ InSubOfModule (σ.basicModuleWithout B b) (σ.obj b.1)

/-- Module-level paper-conormality is exactly pointwise irredundancy of
the finite support under submodule closure. -/
theorem isPaperConormal_iff_pointwise
    (B : FiniteSupport (ι := ι)) :
    IsPaperConormal σ B ↔
      ∀ ⦃b : ι⦄, b ∈ B.1 →
        b ∉ σ.sClosure (B.1 \ {b}) := by
  constructor
  · intro hconormal b hbB hbclosure
    let bB : B.1 := ⟨b, hbB⟩
    apply hconormal bB
    apply (inSubOfModule_basicModule_iff σ (B.erase bB)
      (σ.obj b)).2
    exact
      (mem_sClosure_iff_inSub σ (B.1 \ {b}) b).1
        hbclosure
  · intro hpoint b hsub
    apply hpoint b.2
    apply
      (mem_sClosure_iff_inSub σ (B.1 \ {b.1}) b.1).2
    exact
      (inSubOfModule_basicModule_iff σ (B.erase b)
        (σ.obj b.1)).1 hsub

/-- Equivalently, paper-conormality says that the support is an
inclusion-minimal generator of its own submodule closure. -/
theorem isPaperConormal_iff_isMinimalGenerator
    (B : FiniteSupport (ι := ι)) :
    IsPaperConormal σ B ↔
      σ.sClosure.IsMinimalGenerator B.1 (σ.sClosure B.1) := by
  rw [isPaperConormal_iff_pointwise σ B]
  exact
    (QuotientSubmoduleEquidistribution.SetClosure.isMinimalGenerator_closure_iff_pointwise
      σ.sClosure B.1).symm

/-- A finite support whose canonical basic module is paper-conormal. -/
abbrev BasicConormalModule :=
  {B : FiniteSupport (ι := ι) // IsPaperConormal σ B}

namespace BasicConormalModule

/-- The actual finitely generated module represented by a bundled basic
conormal support. -/
abbrev object (M : BasicConormalModule σ) : FGModuleCat.{w} R :=
  σ.basicModule M.1

/-- The image in the module skeleton of the canonical basic conormal
modules. -/
def IsoClass :=
  {X : Skeleton (FGModuleCat.{w} R) //
    ∃ M : BasicConormalModule σ,
      X = toSkeleton (object σ M)}

/-- Send a bundled canonical module to its module-isomorphism class. -/
def toIsoClass (M : BasicConormalModule σ) : IsoClass σ :=
  ⟨toSkeleton (object σ M), M, rfl⟩

namespace IsoClass

/-- Choose the unique canonical support represented by an isomorphism
class in the image. -/
noncomputable def representative (X : IsoClass σ) :
    BasicConormalModule σ :=
  Classical.choose X.2

theorem representative_spec (X : IsoClass σ) :
    X.1 = toSkeleton (object σ (representative σ X)) :=
  Classical.choose_spec X.2

end IsoClass

/-- Forget the concrete sum and retain the closure-theoretic conormal
support. -/
def toConormalFiniteSupport (M : BasicConormalModule σ) :
    σ.sClosure.NormalFiniteSupport :=
  ⟨M.1.1, M.1.2,
    (isPaperConormal_iff_isMinimalGenerator σ M.1).1 M.2⟩

/-- Build the canonical basic conormal module from a finite minimal
support. -/
def ofConormalFiniteSupport
    (B : σ.sClosure.NormalFiniteSupport) :
    BasicConormalModule σ :=
  ⟨⟨B.1, B.2.1⟩,
    (isPaperConormal_iff_isMinimalGenerator σ
      ⟨B.1, B.2.1⟩).2 B.2.2⟩

/-- Bundled module presentations and finite conormal supports contain
exactly the same data. -/
def equivConormalFiniteSupport :
    BasicConormalModule σ ≃
      σ.sClosure.NormalFiniteSupport where
  toFun := toConormalFiniteSupport σ
  invFun := ofConormalFiniteSupport σ
  left_inv M := by
    apply Subtype.ext
    apply Subtype.ext
    rfl
  right_inv B := by
    apply Subtype.ext
    rfl

/-- Passing to actual module isomorphism classes loses no support data. -/
noncomputable def equivIsoClass :
    BasicConormalModule σ ≃ IsoClass σ where
  toFun := toIsoClass σ
  invFun := IsoClass.representative σ
  left_inv M := by
    apply Subtype.ext
    apply finiteSupport_eq_of_basicModule_iso σ
    apply toSkeleton_eq_toSkeleton_iff.mp
    exact
      (IsoClass.representative_spec σ
        (toIsoClass σ M)).symm
  right_inv X := by
    apply Subtype.ext
    exact (IsoClass.representative_spec σ X).symm

/-- Canonical basic conormal modules are classified by compact
submodule-closed supports. -/
def equivCompactClosed
    (hfin : σ.sClosure.IsFinitary)
    (hae : σ.sClosure.IsAntiExchange) :
    BasicConormalModule σ ≃
      σ.sClosure.CompactClosed :=
  (equivConormalFiniteSupport σ).trans
    (σ.sClosure.normalFiniteSupportEquivCompactClosed hfin hae)

/-- Isomorphism classes of canonical basic conormal modules correspond to
compact submodule-closed supports. -/
noncomputable def isoClassEquivCompactClosed
    (hfin : σ.sClosure.IsFinitary)
    (hae : σ.sClosure.IsAntiExchange) :
    IsoClass σ ≃ σ.sClosure.CompactClosed :=
  (equivIsoClass σ).symm.trans
    (equivCompactClosed σ hfin hae)

end BasicConormalModule

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton
