import QuotientSubmoduleEquidistribution.RepresentationTheory.StableCoreCategories
import QuotientSubmoduleEquidistribution.RepresentationTheory.StrongHeredity

/-!
# Cyclic right ideals as finite torsionless modules

For an arbitrary ring element `a`, the principal right ideal `aA` is a
finitely generated right module and embeds in the regular right module.  No
idempotence hypothesis is needed.  These elementary facts are the concrete
module input for a future Gabriel-arrow realization theorem.
-/

noncomputable section

open CategoryTheory MulOpposite

namespace QuotientSubmoduleEquidistribution.Tsukamoto

universe u

variable {A : Type u} [Ring A]

instance principalRightIdeal_moduleFinite (a : A) :
    Module.Finite Aᵐᵒᵖ (principalRightIdeal a) :=
  Module.Finite.of_fg (Submodule.fg_span_singleton (op a))

/-- The cyclic right ideal generated by any element is finitely generated;
idempotence is needed for projectivity, but not for finiteness. -/
theorem principalRightIdeal_finite_of_element (a : A) :
    Module.Finite Aᵐᵒᵖ (principalRightIdeal a) :=
  inferInstance

/-- The cyclic right ideal `aA` as a finitely generated module over the
opposite ring. -/
def cyclicRightIdealFG (a : A) : FGModuleCat.{u} Aᵐᵒᵖ :=
  FGModuleCat.of Aᵐᵒᵖ (principalRightIdeal a)

/-- The literal inclusion `aA ↪ A` in the finitely generated right-module
category. -/
def cyclicRightIdealInclusion (a : A) :
    cyclicRightIdealFG a ⟶
      QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore.regularFGModule
        (R := Aᵐᵒᵖ) :=
  FGModuleCat.ofHom (Submodule.subtype (principalRightIdeal a))

/-- The literal cyclic-right-ideal inclusion is monic. -/
theorem cyclicRightIdealInclusion_mono (a : A) :
    Mono (cyclicRightIdealInclusion a) := by
  apply ConcreteCategory.mono_of_injective
  exact Submodule.subtype_injective _

/-- The literal inclusion `aA ↪ eA` induced by an inclusion of principal
right ideals. -/
def cyclicRightIdealInclusionOfLE {a e : A}
    (h : principalRightIdeal a ≤ principalRightIdeal e) :
    cyclicRightIdealFG a ⟶ cyclicRightIdealFG e :=
  FGModuleCat.ofHom (Submodule.inclusion h)

/-- Every literal inclusion between cyclic right ideals is monic. -/
theorem cyclicRightIdealInclusionOfLE_mono {a e : A}
    (h : principalRightIdeal a ≤ principalRightIdeal e) :
    Mono (cyclicRightIdealInclusionOfLE h) := by
  apply ConcreteCategory.mono_of_injective
  exact Submodule.inclusion_injective h

/-- Every cyclic right ideal is torsionless because it embeds into the
regular projective right module. -/
theorem cyclicRightIdeal_torsionless (a : A) :
    QuotientSubmoduleEquidistribution.RingelStable.FaithfulCoreAdapter.Torsionless
      (cyclicRightIdealFG a) := by
  refine ⟨
    QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore.regularFGModule
      (R := Aᵐᵒᵖ),
    cyclicRightIdealInclusion a,
    QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore.projective_regularFGModule,
    cyclicRightIdealInclusion_mono a⟩

/-- A nonzero idempotent does not belong to the Jacobson radical.  This
form works over an arbitrary ring: Nakayama's lemma is applied to the
finitely generated left ideal spanned by the idempotent. -/
theorem idempotent_eq_zero_of_mem_jacobson
    {e : A} (he : IsIdempotentElem e) (heJ : e ∈ Ring.jacobson A) :
    e = 0 := by
  let N : Submodule A A := Ideal.span {e}
  have hNfg : N.FG := Submodule.fg_span (Set.finite_singleton e)
  have hNJ : N ≤ Ring.jacobson A := by
    apply Ideal.span_le.mpr
    simpa using heJ
  have hfix : ∀ {x : A}, x ∈ N → x * e = x := by
    intro x hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
        rw [Set.mem_singleton_iff.mp hx]
        exact he.eq
    | zero => simp
    | add x y _ _ hx hy => rw [add_mul, hx, hy]
    | smul r x _ hx =>
        change (r * x) * e = r * x
        rw [mul_assoc, hx]
  have hle : N ≤ Ring.jacobson A • N := by
    intro x hx
    have hxJ : x ∈ Ring.jacobson A := hNJ hx
    have heN : e ∈ N :=
      Ideal.subset_span (Set.mem_singleton e)
    have hxe : x * e ∈ Ring.jacobson A • N :=
      Submodule.smul_mem_smul hxJ heN
    rw [hfix hx] at hxe
    exact hxe
  have hNbot : N = ⊥ := hNfg.eq_bot_of_le_jacobson_smul hle
  have heN : e ∈ N := Ideal.subset_span (Set.mem_singleton e)
  rw [hNbot, Submodule.mem_bot] at heN
  exact heN

/-- Every element of the cyclic right ideal `aA` lies in the Jacobson
radical when its generator does. -/
theorem unop_mem_jacobson_of_mem_principalRightIdeal
    {a : A} (haJ : a ∈ Ring.jacobson A)
    {x : Aᵐᵒᵖ} (hx : x ∈ principalRightIdeal a) :
    unop x ∈ Ring.jacobson A := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      rw [Set.mem_singleton_iff.mp hx]
      simpa using haJ
  | zero => simp
  | add x y _ _ hx hy =>
      simpa using (Ring.jacobson A).add_mem hx hy
  | smul r x _ hx =>
      change unop (r * x) ∈ Ring.jacobson A
      rw [unop_mul]
      exact (Ring.jacobson A).mul_mem_right (unop r) hx

/-- A radical-generated cyclic right ideal cannot contain a nonzero
idempotent generator. -/
theorem principalRightIdeal_not_ge_of_mem_jacobson
    {a e : A} (haJ : a ∈ Ring.jacobson A)
    (he : IsIdempotentElem e) (he0 : e ≠ 0) :
    ¬ principalRightIdeal e ≤ principalRightIdeal a := by
  intro h
  have heMem : op e ∈ principalRightIdeal e :=
    Ideal.subset_span (Set.mem_singleton (op e))
  have heJ : e ∈ Ring.jacobson A :=
    unop_mem_jacobson_of_mem_principalRightIdeal haJ (h heMem)
  exact he0 (idempotent_eq_zero_of_mem_jacobson he heJ)

/-- The literal inclusion `aA → eA` is not epic when `a` belongs to the
Jacobson radical and `e` is a nonzero idempotent. -/
theorem principalRightIdeal_inclusion_not_epi_of_mem_jacobson
    {a e : A} (haJ : a ∈ Ring.jacobson A)
    (he : IsIdempotentElem e) (he0 : e ≠ 0)
    (hae : principalRightIdeal a ≤ principalRightIdeal e) :
    ¬ Epi
      (FGModuleCat.ofHom
        (Submodule.inclusion hae) :
          cyclicRightIdealFG a ⟶ cyclicRightIdealFG e) := by
  intro hEpi
  have hsurj : Function.Surjective (Submodule.inclusion hae) :=
    (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_epi_iff_surjective _).mp hEpi
  let ee : principalRightIdeal e :=
    ⟨op e, Ideal.subset_span (Set.mem_singleton (op e))⟩
  obtain ⟨x, hx⟩ := hsurj ee
  have heMem : op e ∈ principalRightIdeal a := by
    have hval : x.1 = op e := congrArg Subtype.val hx
    rw [← hval]
    exact x.property
  have heJ : e ∈ Ring.jacobson A :=
    unop_mem_jacobson_of_mem_principalRightIdeal haJ heMem
  exact he0 (idempotent_eq_zero_of_mem_jacobson he heJ)

/-- Named-map form of
`principalRightIdeal_inclusion_not_epi_of_mem_jacobson`. -/
theorem cyclicRightIdealInclusionOfLE_not_epi_of_mem_jacobson
    {a e : A} (haJ : a ∈ Ring.jacobson A)
    (he : IsIdempotentElem e) (he0 : e ≠ 0)
    (hae : principalRightIdeal a ≤ principalRightIdeal e) :
    ¬ Epi (cyclicRightIdealInclusionOfLE hae) :=
  principalRightIdeal_inclusion_not_epi_of_mem_jacobson
    haJ he he0 hae

end QuotientSubmoduleEquidistribution.Tsukamoto
