import QuotientSubmoduleEquidistribution.RepresentationTheory.FactorCategoryRealization
import QuotientSubmoduleEquidistribution.RepresentationTheory.ModuleRightTauSequences

/-!
# Right tau meshes in the literal factor category

This file begins the transport of the ambient module Auslander--Reiten
meshes to `add(ind R) / [add K]`.  Every finitely generated module belongs to
the full additive category generated by the complete indecomposable
skeleton, so there is a canonical fully faithful inclusion with codomain
that explicit full subcategory.  Composing it with the ideal-quotient
functor gives the literal image of each ambient right mesh.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory CategoryTheory.Limits
open scoped ZeroObject

namespace QuotientSubmoduleEquidistribution.CategoricalRadical

universe uC vC

variable {C : Type uC} [Category.{vC} C] [Preadditive C]

/-- A radical split epimorphism can only end in a zero object. -/
theorem IsRadicalMorphism.isZero_target_of_isSplitEpi
    {X Y : C} {f : X ⟶ Y} (hf : IsRadicalMorphism f)
    [IsSplitEpi f] : IsZero Y := by
  let s : Y ⟶ X := section_ f
  have hs : s ≫ f = 𝟙 Y := IsSplitEpi.id f
  have hi : IsIso (𝟙 X - f ≫ s) := hf s
  have hzero : s ≫ (𝟙 X - f ≫ s) = 0 := by
    rw [Preadditive.comp_sub, Category.comp_id, ← Category.assoc, hs,
      Category.id_comp, sub_self]
  have hs0 : s = 0 := by
    rw [← cancel_mono (𝟙 X - f ≫ s)]
    simpa using hzero
  rw [IsZero.iff_id_eq_zero, ← hs, hs0, zero_comp]

/-- Explicit-witness form of
`IsRadicalMorphism.isZero_target_of_isSplitEpi`. -/
theorem IsRadicalMorphism.isZero_target_of_splitEpi
    {X Y : C} {f : X ⟶ Y} (hf : IsRadicalMorphism f)
    (s : SplitEpi f) : IsZero Y := by
  letI : IsSplitEpi f := IsSplitEpi.mk' s
  exact hf.isZero_target_of_isSplitEpi

/-- A radical split monomorphism can only start in a zero object. -/
theorem IsRadicalMorphism.isZero_source_of_isSplitMono
    {X Y : C} {f : X ⟶ Y} (hf : IsRadicalMorphism f)
    [IsSplitMono f] : IsZero X := by
  let r : Y ⟶ X := retraction f
  have hr : f ≫ r = 𝟙 X := IsSplitMono.id f
  have hi : IsIso (𝟙 X - f ≫ r) := hf r
  have hzero : 𝟙 X - f ≫ r = 0 := by rw [hr, sub_self]
  haveI : IsIso (0 : X ⟶ X) := hzero ▸ hi
  exact (IsZero.iff_isSplitEpi_eq_zero (0 : X ⟶ X)).2 rfl

/-- Explicit-witness form of
`IsRadicalMorphism.isZero_source_of_isSplitMono`. -/
theorem IsRadicalMorphism.isZero_source_of_splitMono
    {X Y : C} {f : X ⟶ Y} (hf : IsRadicalMorphism f)
    (s : SplitMono f) : IsZero X := by
  letI : IsSplitMono f := IsSplitMono.mk' s
  exact hf.isZero_source_of_isSplitMono

end QuotientSubmoduleEquidistribution.CategoricalRadical

namespace QuotientSubmoduleEquidistribution

universe uB vB

variable {C : Type uB} [Category.{vB} C] [Preadditive C]
  [HasFiniteBiproducts C]

/-- Removing zero summands from a finite biproduct does not change its
isomorphism type. -/
def biproductIsoSubtypeOfIsZero
    {J : Type*} [Fintype J] (f : J → C) (p : J → Prop)
    [DecidablePred p]
    (hzero : ∀ j, ¬ p j → IsZero (f j)) :
    (⨁ f) ≅ (⨁ Subtype.restrict p f) where
  hom := biproduct.toSubtype f p
  inv := biproduct.fromSubtype f p
  hom_inv_id := by
    classical
    rw [biproduct.toSubtype_fromSubtype]
    apply biproduct.hom_ext
    intro j
    by_cases hj : p j
    · simp [hj]
    · rw [biproduct.map_π, if_neg hj, comp_zero,
        Category.id_comp]
      exact (hzero j hj).eq_of_tgt 0 (biproduct.π f j)
  inv_hom_id := biproduct.fromSubtype_toSubtype f p

end QuotientSubmoduleEquidistribution

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton

open CategoricalRadical

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

universe u v

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v}
  (σ : IndecomposableSkeleton.{u, v, u} R ι)

omit [IsNoetherianRing R] in
/-- An invertible underlying module endomorphism gives an isomorphism in the
finitely generated module category. -/
theorem isIso_of_isUnit_hom_hom
    {X : FGModuleCat.{u} R} (f : X ⟶ X)
    (hf : IsUnit f.hom.hom) : IsIso f := by
  have hbij : Function.Bijective f.hom.hom :=
    (Module.End.isUnit_iff _).mp hf
  let U := forget₂ (FGModuleCat.{u} R) (ModuleCat.{u} R)
  haveI : IsIso (U.map f) := by
    change IsIso f.hom
    exact (ConcreteCategory.isIso_iff_bijective _).2 hbij
  exact isIso_of_reflects_iso f U

/-- Completeness of the skeleton puts every finitely generated module in
`add(ind R)`. -/
theorem inAdd_univ (X : FGModuleCat.{u} R) :
    σ.InAdd Set.univ X := by
  obtain ⟨n, a, ⟨e⟩⟩ := σ.decomposes X
  exact ⟨{
    index := FintypeCat.of (Fin n)
    label := a
    mem := fun _ ↦ Set.mem_univ _
    iso := e }⟩

/-- A module regarded canonically as an object of `add(ind R)`. -/
abbrev ambientAddObject (X : FGModuleCat.{u} R) :
    σ.AddCategory Set.univ :=
  ⟨X, σ.inAdd_univ X⟩

/-- The fully faithful functor from finitely generated modules to the
explicit full additive category `add(ind R)`. -/
abbrev ambientAddFunctor :
    FGModuleCat.{u} R ⥤ σ.AddCategory Set.univ where
  obj := ambientAddObject σ
  map f := ObjectProperty.homMk f
  map_id X := by
    apply ObjectProperty.hom_ext
    rfl
  map_comp f g := by
    apply ObjectProperty.hom_ext
    rfl

instance ambientAddFunctor_additive :
    (ambientAddFunctor σ).Additive where
  map_add := by
    intro X Y f g
    apply ObjectProperty.hom_ext
    rfl

/-- Passing to the full additive subcategory preserves a radical
morphism. -/
theorem ambientAddFunctor_map_isRadicalMorphism
    {X Y : FGModuleCat.{u} R} (f : X ⟶ Y)
    (hf : IsRadicalMorphism f) :
    IsRadicalMorphism ((ambientAddFunctor σ).map f) := by
  intro g
  let U := ObjectProperty.ι (σ.generated Set.univ).carrier
  let q := 𝟙 ((ambientAddFunctor σ).obj X) -
    (ambientAddFunctor σ).map f ≫ g
  have hq : IsIso (U.map q) := by
    dsimp only [U, q, ambientAddFunctor, ambientAddObject]
    exact hf g.hom
  letI : IsIso (U.map q) := hq
  exact Functor.ReflectsIsomorphisms.reflects U q

/-- The composite functor from modules to the literal factor category. -/
abbrev factorModuleFunctor (K : Set ι) :
    FGModuleCat.{u} R ⥤ σ.FactorCategory K :=
  ambientAddFunctor σ ⋙ σ.factorFunctor K

namespace FiniteARTranslationData

variable (D : σ.FiniteARTranslationData)

/-- Indices of the chosen right almost-split middle decomposition whose
labels survive the factor quotient. -/
abbrev factorCategoryMiddleIndex (K : Set ι) (x : DeletedLabel K) :=
  {t : (factorLadderRightARAt σ D x.1).index //
    (factorLadderRightARAt σ D x.1).label t ∉ K}

/-- The surviving deleted label carried by a restricted middle index. -/
def factorCategoryMiddleLabel (K : Set ι) (x : DeletedLabel K)
    (t : factorCategoryMiddleIndex σ D K x) : DeletedLabel K :=
  ⟨(factorLadderRightARAt σ D x.1).label t.1, t.2⟩

/-- Occurrences of `p` among the surviving middle indices are the same as
all occurrences of the underlying label upstairs, because `p` itself is
deleted. -/
def factorCategoryMiddleOccurrenceEquiv
    (K : Set ι) (x p : DeletedLabel K) :
    {t : factorCategoryMiddleIndex σ D K x //
      factorCategoryMiddleLabel σ D K x t = p} ≃
      {t : (factorLadderRightARAt σ D x.1).index //
        (factorLadderRightARAt σ D x.1).label t = p.1} where
  toFun t := ⟨t.1.1, congrArg Subtype.val t.2⟩
  invFun t := ⟨⟨t.1, by simpa [t.2] using p.2⟩,
    Subtype.ext t.2⟩
  left_inv t := by ext; rfl
  right_inv t := by ext; rfl

/-- Literal occurrence count of a deleted label in the factor-category
middle decomposition. -/
def factorCategoryMiddleMultiplicity
    (K : Set ι) (x p : DeletedLabel K) : ℕ := by
  classical
  letI : Fintype (factorLadderRightARAt σ D x.1).index :=
    FintypeCat.fintype
  exact (Finset.univ.filter fun t : factorCategoryMiddleIndex σ D K x ↦
    factorCategoryMiddleLabel σ D K x t = p).card

/-- The factor-category middle occurrence count is exactly the nonnegative
integer matrix entry used by `factorLadderTheta`. -/
theorem factorCategoryMiddleMultiplicity_eq_deletedMiddleMultiplicity
    (K : Set ι) (x p : DeletedLabel K) :
    (factorCategoryMiddleMultiplicity σ D K x p : ℤ) =
      deletedMiddleMultiplicity (σ := σ) (D := D) K x p := by
  classical
  let AR := factorLadderRightARAt σ D x.1
  letI : Fintype AR.index := FintypeCat.fintype
  change
    ((Finset.univ.filter fun t : factorCategoryMiddleIndex σ D K x ↦
      factorCategoryMiddleLabel σ D K x t = p).card : ℤ) =
      ((Finset.univ.filter fun t : AR.index ↦ AR.label t = p.1).card : ℤ)
  have hcard :
      (Finset.univ.filter fun t : factorCategoryMiddleIndex σ D K x ↦
        factorCategoryMiddleLabel σ D K x t = p).card =
      (Finset.univ.filter fun t : AR.index ↦ AR.label t = p.1).card := by
    rw [← Fintype.card_subtype, ← Fintype.card_subtype]
    exact Fintype.card_congr
      (factorCategoryMiddleOccurrenceEquiv σ D K x p)
  exact_mod_cast hcard

/-- The literal image in the factor category of the ambient module right
mesh at `x`.  Minimalization of this image is handled separately when its
left or middle object is killed by the quotient. -/
def factorCategoryRawRightMesh (K : Set ι) (x : ι) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    ShortComplex (σ.FactorCategory K) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  exact (moduleRightMesh σ D x).map (factorModuleFunctor σ K)

/-- Both arrows in the raw quotient mesh remain radical. -/
theorem factorCategoryRawRightMesh_radical
    (K : Set ι) (x : ι) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    let S := factorCategoryRawRightMesh σ D K x
    IsRadicalMorphism S.f ∧ IsRadicalMorphism S.g := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  let A := moduleRightTau σ D x
  constructor
  · exact I.map_isRadicalMorphism _
      (ambientAddFunctor_map_isRadicalMorphism σ _ A.f_radical)
  · exact I.map_isRadicalMorphism _
      (ambientAddFunctor_map_isRadicalMorphism σ _ A.g_radical)

/-- The right endpoint of the raw quotient mesh at a deleted label is the
literal factor object. -/
theorem factorCategoryRawRightMesh_X₃
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    (factorCategoryRawRightMesh σ D K x.1).X₃ =
      σ.factorObject K x := by
  dsimp only
  change
    (factorModuleFunctor σ K).obj (moduleRightMesh σ D x.1).X₃ =
      σ.factorObject K x
  rw [moduleRightMesh_X₃]
  rfl

/-- Radical maps into a surviving endpoint factor through the raw quotient
right-mesh map.  This is the quotient form of right almost-split
factorization; a split epimorphic lift would remain split epic after applying
the quotient functor, contradicting radicality because the endpoint is not
zero. -/
theorem factorCategoryRawRightMesh_factors_into_right
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    let S := factorCategoryRawRightMesh σ D K x.1
    ∀ {W : σ.FactorCategory K} (a : W ⟶ S.X₃),
      IsRadicalMorphism a →
        ∃ b : W ⟶ S.X₂, b ≫ S.g = a := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  let F := σ.factorFunctor K
  intro W a ha
  obtain ⟨a', rfl⟩ := F.map_surjective a
  have hnot : ¬ IsSplitEpi a'.hom := by
    intro hsplit
    letI : IsSplitEpi a'.hom := hsplit
    let se : SplitEpi a' := {
      section_ := ObjectProperty.homMk (section_ a'.hom)
      id := by
        apply ObjectProperty.hom_ext
        exact IsSplitEpi.id a'.hom }
    have hz : IsZero (factorCategoryRawRightMesh σ D K x.1).X₃ :=
      ha.isZero_target_of_splitEpi (se.map F)
    rw [factorCategoryRawRightMesh_X₃ σ D K x] at hz
    exact (σ.factorObject_not_isZero K x) hz
  let eX : (moduleRightMesh σ D x.1).X₃ ≅ σ.obj x.1 :=
    eqToIso (moduleRightMesh_X₃ σ D x.1)
  let aX : W.as.obj ⟶ σ.obj x.1 := a'.hom ≫ eX.hom
  have hnotX : ¬ IsSplitEpi aX := by
    intro hsplit
    letI : IsSplitEpi aX := hsplit
    letI : IsSplitEpi eX.inv := inferInstance
    have hs : IsSplitEpi (aX ≫ eX.inv) := inferInstance
    have heq : aX ≫ eX.inv = a'.hom := by
      simp [aX]
    exact hnot (heq ▸ hs)
  have haRad : IsRadicalMorphism a'.hom := by
    have haXRad : IsRadicalMorphism aX :=
      (σ.isRadicalMorphism_iff_not_isSplitEpi_to_obj aX).2 hnotX
    have h := isRadicalMorphism_postcomp eX.inv haXRad
    simpa [aX] using h
  obtain ⟨b, hb⟩ :=
    (moduleRightTau σ D x.1).factors_into_right a'.hom haRad
  refine ⟨F.map (ObjectProperty.homMk b), ?_⟩
  change F.map (ObjectProperty.homMk b) ≫
      F.map ((ambientAddFunctor σ).map
        (moduleRightMesh σ D x.1).g) = F.map a'
  rw [← F.map_comp]
  apply congrArg F.map
  apply ObjectProperty.hom_ext
  exact hb

/-- Radical maps out of the raw quotient mesh's left endpoint factor through
its first arrow.  If the ambient translate is projective-boundary zero or is
deleted by `K`, the source is zero in the quotient.  Otherwise a split-monic
lift would remain split monic in the quotient and force the surviving source
to be zero. -/
theorem factorCategoryRawRightMesh_factors_from_left
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    let S := factorCategoryRawRightMesh σ D K x.1
    ∀ {W : σ.FactorCategory K} (a : S.X₁ ⟶ W),
      IsRadicalMorphism a →
        ∃ b : S.X₂ ⟶ W, S.f ≫ b = a := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  let F := σ.factorFunctor K
  let S := moduleRightMesh σ D x.1
  let A := moduleRightTau σ D x.1
  intro W a ha
  classical
  by_cases hx : Projective (σ.obj x.1)
  · have hS₁ : IsZero S.X₁ := by
      rw [moduleRightMesh_X₁_of_projective σ D x.1 hx]
      exact isZero_zero _
    have hQ₁ : IsZero (factorCategoryRawRightMesh σ D K x.1).X₁ :=
      (factorModuleFunctor σ K).map_isZero hS₁
    refine ⟨0, ?_⟩
    have ha0 : a = 0 := hQ₁.eq_of_src a 0
    rw [ha0]
    simp
  · let tx : ι := (arTranslation σ D ⟨x.1, hx⟩).1
    by_cases htx : tx ∈ K
    · have hsource :
          (factorCategoryRawRightMesh σ D K x.1).X₁ =
            (F.obj (σ.ambientAddPoint tx)) := by
          change (factorModuleFunctor σ K).obj S.X₁ =
            F.obj (σ.ambientAddPoint tx)
          rw [moduleRightMesh_X₁_of_not_projective σ D x.1 hx]
          rfl
      have hQ₁ : IsZero (factorCategoryRawRightMesh σ D K x.1).X₁ := by
        rw [hsource]
        exact σ.factorObject_isZero_of_mem K htx
      refine ⟨0, ?_⟩
      have ha0 : a = 0 := hQ₁.eq_of_src a 0
      rw [ha0]
      simp
    · let y : DeletedLabel K := ⟨tx, htx⟩
      have hsource :
          (factorCategoryRawRightMesh σ D K x.1).X₁ =
            σ.factorObject K y := by
        change (factorModuleFunctor σ K).obj S.X₁ =
          σ.factorObject K y
        rw [moduleRightMesh_X₁_of_not_projective σ D x.1 hx]
        rfl
      obtain ⟨a', rfl⟩ := F.map_surjective a
      have hnot : ¬ IsSplitMono a'.hom := by
        intro hsplit
        letI : IsSplitMono a'.hom := hsplit
        let sm : SplitMono a' := {
          retraction := ObjectProperty.homMk (retraction a'.hom)
          id := by
            apply ObjectProperty.hom_ext
            exact IsSplitMono.id a'.hom }
        have hz : IsZero (factorCategoryRawRightMesh σ D K x.1).X₁ :=
          ha.isZero_source_of_splitMono (sm.map F)
        rw [hsource] at hz
        exact (σ.factorObject_not_isZero K y) hz
      let eT : S.X₁ ≅ σ.obj y.1 :=
        eqToIso (moduleRightMesh_X₁_of_not_projective σ D x.1 hx)
      let aY : σ.obj y.1 ⟶ W.as.obj := eT.inv ≫ a'.hom
      have hnotY : ¬ IsSplitMono aY := by
        intro hsplit
        letI : IsSplitMono aY := hsplit
        letI : IsSplitMono eT.hom := inferInstance
        have hs : IsSplitMono (eT.hom ≫ aY) := inferInstance
        have heq : eT.hom ≫ aY = a'.hom := by simp [aY]
        exact hnot (heq ▸ hs)
      have haRad : IsRadicalMorphism a'.hom := by
        have haYRad : IsRadicalMorphism aY :=
          (σ.isRadicalMorphism_iff_not_isSplitMono_from_obj aY).2 hnotY
        have hr := isRadicalMorphism_precomp eT.hom haYRad
        simpa [aY] using hr
      obtain ⟨b, hb⟩ := A.factors_from_left a'.hom haRad
      refine ⟨F.map ((ambientAddFunctor σ).map b), ?_⟩
      change F.map ((ambientAddFunctor σ).map S.f) ≫
          F.map ((ambientAddFunctor σ).map b) = F.map a'
      rw [← F.map_comp]
      apply congrArg F.map
      apply ObjectProperty.hom_ext
      exact hb

/-- The raw quotient mesh remains a weak kernel at every deleted endpoint.

If a lifted map has composite through `add K`, factor the final leg of that
error term through the ambient right almost-split map.  Subtracting this
correction makes the composite literally zero upstairs, where the ambient
weak-kernel property applies. -/
theorem factorCategoryRawRightMesh_isWeakKernel
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    Iyama.ShortComplex.IsWeakKernel
      (factorCategoryRawRightMesh σ D K x.1) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        I.add_compatible f₁ f₂ g₁ g₂ hf hg)
  let F := σ.factorFunctor K
  let S := moduleRightMesh σ D x.1
  let A := moduleRightTau σ D x.1
  rw [Iyama.ShortComplex.isWeakKernel_iff]
  intro W k hk
  obtain ⟨k', rfl⟩ := F.map_surjective k
  let gAdd := (ambientAddFunctor σ).map S.g
  have hkmap : F.map (k' ≫ gAdd) = 0 := by
    change F.map k' ≫ F.map gAdd = 0 at hk
    simpa only [← F.map_comp] using hk
  have hfac := (I.map_eq_zero_iff (k' ≫ gAdd)).1 hkmap
  rcases hfac with ⟨M, hM, left, right, hcomp⟩
  have hrightNot : ¬ IsSplitEpi right := by
    intro hsplit
    letI : IsSplitEpi right := hsplit
    let eX : S.X₃ ≅ σ.obj x.1 :=
      eqToIso (moduleRightMesh_X₃ σ D x.1)
    let rt : Retract (σ.obj x.1) M :=
      { i := eX.inv ≫ section_ right
        r := right ≫ eX.hom
        retract := by simp }
    exact x.2 (index_mem_of_retract_inAdd σ rt hM)
  let eX : S.X₃ ≅ σ.obj x.1 :=
    eqToIso (moduleRightMesh_X₃ σ D x.1)
  let rightX : M ⟶ σ.obj x.1 := right ≫ eX.hom
  have hrightXNot : ¬ IsSplitEpi rightX := by
    intro hsplit
    letI : IsSplitEpi rightX := hsplit
    letI : IsSplitEpi eX.inv := inferInstance
    have hs : IsSplitEpi (rightX ≫ eX.inv) := inferInstance
    have heq : rightX ≫ eX.inv = right := by simp [rightX]
    exact hrightNot (heq ▸ hs)
  have hrightRad : IsRadicalMorphism right := by
    have hrX : IsRadicalMorphism rightX :=
      (σ.isRadicalMorphism_iff_not_isSplitEpi_to_obj rightX).2
        hrightXNot
    have hr := isRadicalMorphism_postcomp eX.inv hrX
    simpa [rightX] using hr
  obtain ⟨v, hv⟩ := A.factors_into_right right hrightRad
  let k₀ : W.as.obj ⟶ S.X₂ := k'.hom - left ≫ v
  have hk₀ : k₀ ≫ S.g = 0 := by
    dsimp only [k₀]
    rw [Preadditive.sub_comp, Category.assoc, hv]
    have hc : left ≫ right = k'.hom ≫ S.g := by
      change left ≫ right = k'.hom ≫ S.g at hcomp
      exact hcomp
    rw [hc, sub_self]
  obtain ⟨l, hl⟩ :=
    (Iyama.ShortComplex.isWeakKernel_iff S).1 A.minimalWeakKernel.1 k₀ hk₀
  refine ⟨F.map ((ambientAddFunctor σ).map l), ?_⟩
  change F.map ((ambientAddFunctor σ).map l) ≫
      F.map ((ambientAddFunctor σ).map S.f) = F.map k'
  rw [← F.map_comp, ← sub_eq_zero, ← F.map_sub]
  apply (I.map_eq_zero_iff _).2
  refine ⟨M, hM, -left, v, ?_⟩
  change (-left) ≫ v = (l ≫ S.f) - k'.hom
  rw [hl]
  dsimp only [k₀]
  simp

/-- If the raw quotient mesh has a surviving indecomposable left endpoint
and a nonzero first arrow, that arrow is right minimal. -/
theorem factorCategoryRawRightMesh_isRightMinimal_of_source_eq
    (K : Set ι) (x : DeletedLabel K) (y : DeletedLabel K)
    (hsource :
      (moduleRightMesh σ D x.1).X₁ = σ.obj y.1) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    (factorCategoryRawRightMesh σ D K x.1).f ≠ 0 →
      IsRightMinimal
        (factorCategoryRawRightMesh σ D K x.1).f := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ h₁ h₂ ↦
        I.add_compatible f₁ f₂ g₁ g₂ h₁ h₂)
  let F := σ.factorFunctor K
  let S := moduleRightMesh σ D x.1
  intro hf e he
  obtain ⟨e', rfl⟩ := F.map_surjective e
  let eT : S.X₁ ≅ σ.obj y.1 := eqToIso hsource
  let eY : σ.obj y.1 ⟶ σ.obj y.1 :=
    eT.inv ≫ e'.hom ≫ eT.hom
  letI : IsLocalRing (Module.End R (σ.obj y.1)) :=
    QuotientSubmoduleEquidistribution.Foundation.isLocalRing_end_of_isIndecomposable
      (σ.finiteLength y.1) (σ.indecomposable y.1)
  have hsum : IsUnit (eY.hom.hom + (1 - eY.hom.hom)) := by
    rw [add_sub_cancel]
    exact isUnit_one
  rcases IsLocalRing.isUnit_or_isUnit_of_isUnit_add hsum with
    hunit | hsubunit
  · have hIsoY : IsIso eY := isIso_of_isUnit_hom_hom eY hunit
    letI : IsIso eY := hIsoY
    have heq : e'.hom = eT.hom ≫ eY ≫ eT.inv := by
      simp [eY]
    have hIsoUnderlying : IsIso e'.hom := heq ▸ inferInstance
    let U := ObjectProperty.ι (σ.generated Set.univ).carrier
    have hmap : IsIso (U.map e') := by
      change IsIso e'.hom
      exact hIsoUnderlying
    letI : IsIso (U.map e') := hmap
    have hIsoAdd : IsIso e' :=
      Functor.ReflectsIsomorphisms.reflects U e'
    letI : IsIso e' := hIsoAdd
    exact (F.mapIso (asIso e')).isIso_hom
  · have hIsoSubY : IsIso (𝟙 _ - eY) := by
      apply isIso_of_isUnit_hom_hom (𝟙 _ - eY)
      change IsUnit (1 - eY.hom.hom)
      exact hsubunit
    letI : IsIso (𝟙 _ - eY) := hIsoSubY
    have heq : 𝟙 S.X₁ - e'.hom =
        eT.hom ≫ (𝟙 _ - eY) ≫ eT.inv := by
      simp [eY, Preadditive.comp_sub, Preadditive.sub_comp]
    have hIsoUnderlying : IsIso (𝟙 S.X₁ - e'.hom) :=
      heq ▸ inferInstance
    let qAdd := 𝟙 _ - e'
    let U := ObjectProperty.ι (σ.generated Set.univ).carrier
    have hmap : IsIso (U.map qAdd) := by
      change IsIso (𝟙 S.X₁ - e'.hom)
      exact hIsoUnderlying
    letI : IsIso (U.map qAdd) := hmap
    have hIsoAdd : IsIso qAdd :=
      Functor.ReflectsIsomorphisms.reflects U qAdd
    letI : IsIso qAdd := hIsoAdd
    letI : IsIso (F.map qAdd) := inferInstance
    have hmapq : F.map qAdd = 𝟙 _ - F.map e' := by
      dsimp only [qAdd]
      rw [F.map_sub, F.map_id]
    have hqf : F.map qAdd ≫
        (factorCategoryRawRightMesh σ D K x.1).f = 0 := by
      rw [hmapq]
      rw [Preadditive.sub_comp, Category.id_comp]
      exact sub_eq_zero.mpr he.symm
    have hfzero :
        (factorCategoryRawRightMesh σ D K x.1).f = 0 := by
      calc
        (factorCategoryRawRightMesh σ D K x.1).f =
            inv (F.map qAdd) ≫ F.map qAdd ≫
              (factorCategoryRawRightMesh σ D K x.1).f := by simp
        _ = 0 := by rw [hqf, comp_zero]
    exact (hf hfzero).elim

/-- If the ordinary translate survives and the restricted AR middle is
nonzero, then the first arrow of the raw quotient mesh is nonzero. -/
theorem factorCategoryRawRightMesh_f_ne_zero_of_theta_ne_zero
    [Fintype ι]
    (K : Set ι) (x : DeletedLabel K)
    (hx : ¬ Projective (σ.obj x.1))
    (htx : (arTranslation σ D ⟨x.1, hx⟩).1 ∉ K)
    (hmiddle :
      factorLadderTheta (σ := σ) (D := D) K
        (FactorLadder.basis x) ≠ 0) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    (factorCategoryRawRightMesh σ D K x.1).f ≠ 0 := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ h₁ h₂ ↦
        I.add_compatible f₁ f₂ g₁ g₂ h₁ h₂)
  let F := σ.factorFunctor K
  let S := moduleRightMesh σ D x.1
  let A := moduleRightTau σ D x.1
  let tx : ι := (arTranslation σ D ⟨x.1, hx⟩).1
  let y : DeletedLabel K := ⟨tx, htx⟩
  intro hfzero
  let fAdd := (ambientAddFunctor σ).map S.f
  have hfmap : F.map fAdd = 0 := by
    change (factorCategoryRawRightMesh σ D K x.1).f = 0
    exact hfzero
  have hfac := (I.map_eq_zero_iff fAdd).1 hfmap
  rcases hfac with ⟨M, hM, left, right, hcomp⟩
  let eT : S.X₁ ≅ σ.obj y.1 :=
    eqToIso (moduleRightMesh_X₁_of_not_projective σ D x.1 hx)
  have hleftNot : ¬ IsSplitMono left := by
    intro hsplit
    letI : IsSplitMono left := hsplit
    let rt : Retract (σ.obj y.1) M :=
      { i := eT.inv ≫ left
        r := retraction left ≫ eT.hom
        retract := by simp }
    exact y.2 (index_mem_of_retract_inAdd σ rt hM)
  let leftY : σ.obj y.1 ⟶ M := eT.inv ≫ left
  have hleftYNot : ¬ IsSplitMono leftY := by
    intro hsplit
    letI : IsSplitMono leftY := hsplit
    letI : IsSplitMono eT.hom := inferInstance
    have hs : IsSplitMono (eT.hom ≫ leftY) := inferInstance
    have heq : eT.hom ≫ leftY = left := by simp [leftY]
    exact hleftNot (heq ▸ hs)
  have hleftRad : IsRadicalMorphism left := by
    have hrY : IsRadicalMorphism leftY :=
      (σ.isRadicalMorphism_iff_not_isSplitMono_from_obj leftY).2
        hleftYNot
    have hr := isRadicalMorphism_precomp eT.hom hrY
    simpa [leftY] using hr
  obtain ⟨t, ht⟩ := A.factors_from_left left hleftRad
  have hend : S.f ≫ (t ≫ right) = S.f := by
    rw [← Category.assoc, ht]
    change left ≫ right = S.f at hcomp
    exact hcomp
  have hleftMinimal : IsLeftMinimal S.f := by
    have hS : S = nonprojectiveRightMesh σ D ⟨x.1, hx⟩ := by
      simp [S, moduleRightMesh, hx]
    rw [hS]
    change IsLeftMinimal (arKernelMap σ D ⟨x.1, hx⟩)
    exact arKernelMap_leftMinimal σ D ⟨x.1, hx⟩
  have hIsoEnd : IsIso (t ≫ right) := hleftMinimal (t ≫ right) hend
  letI : IsIso (t ≫ right) := hIsoEnd
  let rtMiddle : Retract S.X₂ M :=
    { i := t
      r := right ≫ inv (t ≫ right)
      retract := by rw [← Category.assoc, IsIso.hom_inv_id] }
  have hMiddle : σ.InAdd K S.X₂ :=
    inAdd_of_retract σ rtMiddle hM
  obtain ⟨s, hs⟩ :=
    (factorLadderTheta_basis_ne_zero_iff σ D K x).1 hmiddle
  let AR := factorLadderRightARAt σ D x.1
  let rtLabel : Retract (σ.obj (AR.label s)) AR.middle :=
    { i := biproduct.ι (fun j : AR.index ↦ σ.obj (AR.label j)) s ≫
          AR.decomposition.inv
      r := AR.decomposition.hom ≫
          biproduct.π (fun j : AR.index ↦ σ.obj (AR.label j)) s
      retract := by simp }
  have hARMiddle : σ.InAdd K AR.middle := by
    change σ.InAdd K (factorLadderRightARAt σ D x.1).middle
    rw [← moduleRightMesh_X₂ σ D x.1]
    exact hMiddle
  exact hs (index_mem_of_retract_inAdd σ rtLabel hARMiddle)

/-- The raw quotient mesh satisfies the full radical approximation
condition.  Together with `factorCategoryRawRightMesh_isWeakKernel`, only
right-minimalization remains before it is a right tau-sequence. -/
theorem factorCategoryRawRightMesh_tauApproximation
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    Iyama.TauApproximation
      (factorCategoryRawRightMesh σ D K x.1) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  exact
    { f_radical := (factorCategoryRawRightMesh_radical σ D K x.1).1
      g_radical := (factorCategoryRawRightMesh_radical σ D K x.1).2
      factors_from_left :=
        factorCategoryRawRightMesh_factors_from_left σ D K x
      factors_into_right :=
        factorCategoryRawRightMesh_factors_into_right σ D K x }

/-- In the surviving-translate, nonzero-restricted-middle branch, the raw
quotient mesh is already right minimal and hence is a right tau-sequence. -/
theorem factorCategoryRawRightTau_of_survives
    [Fintype ι]
    (K : Set ι) (x : DeletedLabel K)
    (hx : ¬ Projective (σ.obj x.1))
    (htx : (arTranslation σ D ⟨x.1, hx⟩).1 ∉ K)
    (hmiddle :
      factorLadderTheta (σ := σ) (D := D) K
        (FactorLadder.basis x) ≠ 0) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    Iyama.RightTauSequence
      (factorCategoryRawRightMesh σ D K x.1) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  let y : DeletedLabel K :=
    ⟨(arTranslation σ D ⟨x.1, hx⟩).1, htx⟩
  let A := factorCategoryRawRightMesh_tauApproximation σ D K x
  exact
    { toTauApproximation := A
      minimalWeakKernel :=
        ⟨factorCategoryRawRightMesh_isWeakKernel σ D K x,
          factorCategoryRawRightMesh_isRightMinimal_of_source_eq
            σ D K x y
            (moduleRightMesh_X₁_of_not_projective σ D x.1 hx)
            (factorCategoryRawRightMesh_f_ne_zero_of_theta_ne_zero
              σ D K x hx htx hmiddle)⟩ }

/-- Paper-operator form of the surviving branch: whenever the restricted
translation target is `some y`, the raw quotient mesh is a right
tau-sequence. -/
theorem factorCategoryRawRightTau_of_tauTarget_eq_some
    [Fintype ι]
    (K : Set ι) (x y : DeletedLabel K)
    (hxy : factorLadderTauTarget (σ := σ) (D := D) K x = some y) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    Iyama.RightTauSequence
      (factorCategoryRawRightMesh σ D K x.1) := by
  classical
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  by_cases hx : Projective (σ.obj x.1)
  · simp [factorLadderTauTarget, hx] at hxy
  · by_cases htx : (arTranslation σ D ⟨x.1, hx⟩).1 ∈ K
    · simp [factorLadderTauTarget, hx, htx] at hxy
    · by_cases hmiddle :
        factorLadderTheta (σ := σ) (D := D) K
          (FactorLadder.basis x) = 0
      · simp [factorLadderTauTarget, hx, htx, hmiddle] at hxy
      · exact factorCategoryRawRightTau_of_survives
          σ D K x hx htx hmiddle

/-- A chosen zero object in the factor category, obtained as the image of
the zero module. -/
def factorCategoryZeroObject (K : Set ι) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    σ.FactorCategory K := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ h₁ h₂ ↦
        I.add_compatible f₁ f₂ g₁ g₂ h₁ h₂)
  exact (factorModuleFunctor σ K).obj (0 : FGModuleCat.{u} R)

/-- The chosen factor-category zero object is zero. -/
theorem factorCategoryZeroObject_isZero (K : Set ι) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    IsZero (factorCategoryZeroObject σ K) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ h₁ h₂ ↦
        I.add_compatible f₁ f₂ g₁ g₂ h₁ h₂)
  exact (factorModuleFunctor σ K).map_isZero
    (isZero_zero (FGModuleCat.{u} R))

/-- The raw quotient mesh with its left term replaced by a chosen zero
object. -/
def factorCategoryZeroLeftRightMesh (K : Set ι) (x : ι) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    ShortComplex (σ.FactorCategory K) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  let T := factorCategoryRawRightMesh σ D K x
  exact ShortComplex.mk
    (0 : factorCategoryZeroObject σ K ⟶ T.X₂) T.g (by simp)

/-- Replacing the left term by zero gives a right tau-sequence whenever the
raw first arrow is zero or its raw source is already a zero object. -/
theorem factorCategoryZeroLeftRightTau
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    (IsZero (factorCategoryRawRightMesh σ D K x.1).X₁ ∨
      (factorCategoryRawRightMesh σ D K x.1).f = 0) →
      Iyama.RightTauSequence
        (factorCategoryZeroLeftRightMesh σ D K x.1) := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  let T := factorCategoryRawRightMesh σ D K x.1
  let A := factorCategoryRawRightMesh_tauApproximation σ D K x
  have hZ : IsZero (factorCategoryZeroObject σ K) :=
    factorCategoryZeroObject_isZero σ K
  intro hzero
  refine
    { f_radical := isRadicalMorphism_zero
      g_radical := A.g_radical
      factors_from_left := ?_
      factors_into_right := A.factors_into_right
      minimalWeakKernel := ?_ }
  · intro W a _ha
    refine ⟨0, ?_⟩
    have ha0 : a = 0 := hZ.eq_of_src a 0
    rw [ha0]
    simp
  · constructor
    · rw [Iyama.ShortComplex.isWeakKernel_iff]
      intro W k hk
      obtain ⟨l, hl⟩ :=
        (Iyama.ShortComplex.isWeakKernel_iff T).1
          (factorCategoryRawRightMesh_isWeakKernel σ D K x) k hk
      have hk0 : k = 0 := by
        rcases hzero with hsource | hf
        · have hl0 : l = 0 := hsource.eq_of_tgt l 0
          rw [hl0, zero_comp] at hl
          exact hl.symm
        · rw [hf, comp_zero] at hl
          exact hl.symm
      refine ⟨0, ?_⟩
      rw [hk0]
      simp
    · intro e _he
      have heq : e = 𝟙 _ := hZ.eq_of_src e (𝟙 _)
      rw [heq]
      infer_instance

/-- A missing restricted translation target is exactly a branch in which
the raw source is zero in the quotient or the raw first arrow vanishes. -/
theorem factorCategoryRawRightMesh_zero_condition_of_tauTarget_eq_none
    [Fintype ι]
    (K : Set ι) (x : DeletedLabel K)
    (hnone : factorLadderTauTarget (σ := σ) (D := D) K x = none) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    IsZero (factorCategoryRawRightMesh σ D K x.1).X₁ ∨
      (factorCategoryRawRightMesh σ D K x.1).f = 0 := by
  classical
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ h₁ h₂ ↦
        I.add_compatible f₁ f₂ g₁ g₂ h₁ h₂)
  let F := σ.factorFunctor K
  let S := moduleRightMesh σ D x.1
  by_cases hx : Projective (σ.obj x.1)
  · left
    have hS₁ : IsZero S.X₁ := by
      rw [moduleRightMesh_X₁_of_projective σ D x.1 hx]
      exact isZero_zero _
    exact (factorModuleFunctor σ K).map_isZero hS₁
  · let tx : ι := (arTranslation σ D ⟨x.1, hx⟩).1
    by_cases htx : tx ∈ K
    · left
      have hsource :
          (factorCategoryRawRightMesh σ D K x.1).X₁ =
            F.obj (σ.ambientAddPoint tx) := by
        change (factorModuleFunctor σ K).obj S.X₁ =
          F.obj (σ.ambientAddPoint tx)
        rw [moduleRightMesh_X₁_of_not_projective σ D x.1 hx]
        rfl
      rw [hsource]
      exact σ.factorObject_isZero_of_mem K htx
    · right
      have hmiddle :
          factorLadderTheta (σ := σ) (D := D) K
            (FactorLadder.basis x) = 0 := by
        by_contra hm
        have hs := factorLadderTauTarget_eq_some
          σ D K x hx htx hm
        rw [hnone] at hs
        contradiction
      let AR := factorLadderRightARAt σ D x.1
      have hall : ∀ t : AR.index, AR.label t ∈ K := by
        intro t
        by_contra ht
        have hne :
            factorLadderTheta (σ := σ) (D := D) K
              (FactorLadder.basis x) ≠ 0 :=
          (factorLadderTheta_basis_ne_zero_iff σ D K x).2 ⟨t, ht⟩
        exact hne hmiddle
      have hAR : σ.InAdd K AR.middle := ⟨{
        index := AR.index
        label := AR.label
        mem := hall
        iso := AR.decomposition }⟩
      have hS₂ : σ.InAdd K S.X₂ := by
        rw [moduleRightMesh_X₂ σ D x.1]
        exact hAR
      have hQ₂ :
          IsZero (factorCategoryRawRightMesh σ D K x.1).X₂ := by
        rw [IsZero.iff_id_eq_zero]
        change 𝟙 (F.obj (ambientAddObject σ S.X₂)) = 0
        rw [← F.map_id]
        apply (I.map_eq_zero_iff _).2
        exact ⟨S.X₂, hS₂, 𝟙 S.X₂, 𝟙 S.X₂, by simp⟩
      exact hQ₂.eq_of_tgt
        (factorCategoryRawRightMesh σ D K x.1).f 0

/-- The minimal factor-category right mesh selected by the paper's
restricted translation operator. -/
def factorCategoryRightMesh [Fintype ι]
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    ShortComplex (σ.FactorCategory K) := by
  classical
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  match factorLadderTauTarget (σ := σ) (D := D) K x with
  | some _ => exact factorCategoryRawRightMesh σ D K x.1
  | none => exact factorCategoryZeroLeftRightMesh σ D K x.1

/-- Every minimal factor-category right mesh is a right tau-sequence. -/
theorem factorCategoryRightTau [Fintype ι]
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    Iyama.RightTauSequence (factorCategoryRightMesh σ D K x) := by
  classical
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  cases htarget : factorLadderTauTarget (σ := σ) (D := D) K x with
  | none =>
      simpa [factorCategoryRightMesh, htarget] using
        factorCategoryZeroLeftRightTau σ D K x
          (factorCategoryRawRightMesh_zero_condition_of_tauTarget_eq_none
            σ D K x htarget)
  | some y =>
      simpa [factorCategoryRightMesh, htarget] using
        factorCategoryRawRightTau_of_tauTarget_eq_some
          σ D K x y htarget

/-- Minimalization changes only the left term: the middle term is the raw
quotient image of the ambient AR middle in every branch. -/
theorem factorCategoryRightMesh_X₂_eq_raw [Fintype ι]
    (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    (factorCategoryRightMesh σ D K x).X₂ =
      (factorCategoryRawRightMesh σ D K x.1).X₂ := by
  classical
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  cases htarget : factorLadderTauTarget (σ := σ) (D := D) K x <;>
    simp [factorCategoryRightMesh, factorCategoryZeroLeftRightMesh, htarget]

/-- The minimal factor right mesh still ends at the literal factor object. -/
theorem factorCategoryRightMesh_X₃
    [Fintype ι] (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    (factorCategoryRightMesh σ D K x).X₃ =
      σ.factorObject K x := by
  dsimp only
  classical
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  cases htarget : factorLadderTauTarget (σ := σ) (D := D) K x <;>
    simp [factorCategoryRightMesh, factorCategoryZeroLeftRightMesh, htarget,
      factorCategoryRawRightMesh_X₃ σ D K x]

/-- When the restricted translation target is absent, the minimal factor
right mesh starts at zero. -/
theorem factorCategoryRightMesh_X₁_isZero_of_tauTarget_eq_none
    [Fintype ι] (K : Set ι) (x : DeletedLabel K)
    (hnone : factorLadderTauTarget (σ := σ) (D := D) K x = none) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    IsZero (factorCategoryRightMesh σ D K x).X₁ := by
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  simpa [factorCategoryRightMesh, factorCategoryZeroLeftRightMesh, hnone] using
    factorCategoryZeroObject_isZero σ K

/-- When the restricted translation target is `some y`, the minimal factor
right mesh starts at the literal factor object represented by `y`. -/
def factorCategoryRightMeshLeftIso_of_tauTarget_eq_some
    [Fintype ι] (K : Set ι) (x y : DeletedLabel K)
    (hxy : factorLadderTauTarget (σ := σ) (D := D) K x = some y) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    (factorCategoryRightMesh σ D K x).X₁ ≅
      σ.factorObject K y := by
  classical
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ h₁ h₂ ↦
        I.add_compatible f₁ f₂ g₁ g₂ h₁ h₂)
  by_cases hx : Projective (σ.obj x.1)
  · simp [factorLadderTauTarget, hx] at hxy
  · let tx : ι := (arTranslation σ D ⟨x.1, hx⟩).1
    by_cases htx : tx ∈ K
    · have hnone :
          factorLadderTauTarget (σ := σ) (D := D) K x = none :=
        factorLadderTauTarget_eq_none_of_translation_mem σ D K x hx htx
      rw [hxy] at hnone
      contradiction
    · by_cases hmiddle :
        factorLadderTheta (σ := σ) (D := D) K
          (FactorLadder.basis x) = 0
      · have hnone :
            factorLadderTauTarget (σ := σ) (D := D) K x = none :=
          factorLadderTauTarget_eq_none_of_theta_eq_zero
            σ D K x hx hmiddle
        rw [hxy] at hnone
        contradiction
      · let ty : DeletedLabel K := ⟨tx, htx⟩
        have htarget :
            factorLadderTauTarget (σ := σ) (D := D) K x = some ty :=
          factorLadderTauTarget_eq_some σ D K x hx htx hmiddle
        have hy : y = ty := by
          apply Option.some.inj
          rw [← hxy, htarget]
        subst y
        let eSource :
            (factorCategoryRightMesh σ D K x).X₁ ≅
              (factorCategoryRawRightMesh σ D K x.1).X₁ :=
          eqToIso (by simp [factorCategoryRightMesh, htarget])
        let eMiddle :
            (factorCategoryRawRightMesh σ D K x.1).X₁ ≅
              (factorModuleFunctor σ K).obj (σ.obj ty.1) := by
          change
            (factorModuleFunctor σ K).obj
                (moduleRightMesh σ D x.1).X₁ ≅
              (factorModuleFunctor σ K).obj (σ.obj ty.1)
          exact (factorModuleFunctor σ K).mapIso
            (eqToIso (moduleRightMesh_X₁_of_not_projective
              σ D x.1 hx))
        let eTarget :
            (factorModuleFunctor σ K).obj (σ.obj ty.1) ≅
              σ.factorObject K ty :=
          eqToIso (by rfl)
        exact eSource.trans (eMiddle.trans eTarget)

/-- The factor right mesh starts at zero exactly when the paper's restricted
translation is absent. -/
theorem factorCategoryRightMesh_X₁_isZero_iff_tauTarget_eq_none
    [Fintype ι] (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    IsZero (factorCategoryRightMesh σ D K x).X₁ ↔
      factorLadderTauTarget (σ := σ) (D := D) K x = none := by
  classical
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  constructor
  · intro hzero
    cases htarget : factorLadderTauTarget (σ := σ) (D := D) K x with
    | none => rfl
    | some y =>
        have hy : IsZero (σ.factorObject K y) :=
          hzero.of_iso
            (factorCategoryRightMeshLeftIso_of_tauTarget_eq_some
              σ D K x y htarget).symm
        exact ((σ.factorObject_not_isZero K y) hy).elim
  · exact factorCategoryRightMesh_X₁_isZero_of_tauTarget_eq_none
      σ D K x

/-- The middle term of the minimal factor right mesh is exactly the finite
biproduct of the surviving summands in the ambient minimal right
almost-split middle decomposition. -/
def factorCategoryRightMeshMiddleIso
    [Fintype ι] (K : Set ι) (x : DeletedLabel K) :
    let I := σ.factorThroughAddIdeal Set.univ K
    letI : Preadditive (CategoryTheory.Quotient I.rel) :=
      I.quotientPreadditive
    letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
      CategoryTheory.Quotient.functor_additive I.rel
        (fun {_ _} f₁ f₂ g₁ g₂ h₁ h₂ ↦
          I.add_compatible f₁ f₂ g₁ g₂ h₁ h₂)
    letI : HasFiniteBiproducts (σ.FactorCategory K) :=
      σ.factorQuotientHasFiniteBiproducts Set.univ K
    (factorCategoryRightMesh σ D K x).X₂ ≅
      ⨁ fun t : factorCategoryMiddleIndex σ D K x ↦
        σ.factorObject K (factorCategoryMiddleLabel σ D K x t) := by
  classical
  dsimp only
  let I := σ.factorThroughAddIdeal Set.univ K
  letI : Preadditive (CategoryTheory.Quotient I.rel) :=
    I.quotientPreadditive
  letI : (CategoryTheory.Quotient.functor I.rel).Additive :=
    CategoryTheory.Quotient.functor_additive I.rel
      (fun {_ _} f₁ f₂ g₁ g₂ h₁ h₂ ↦
        I.add_compatible f₁ f₂ g₁ g₂ h₁ h₂)
  letI : HasFiniteBiproducts (σ.FactorCategory K) :=
    σ.factorQuotientHasFiniteBiproducts Set.univ K
  let FM := factorModuleFunctor σ K
  let S := moduleRightMesh σ D x.1
  let AR := factorLadderRightARAt σ D x.1
  letI : Fintype AR.index := FintypeCat.fintype
  let full : AR.index → σ.FactorCategory K :=
    fun t ↦ FM.obj (σ.obj (AR.label t))
  let p : AR.index → Prop := fun t ↦ AR.label t ∉ K
  let e₀ : (factorCategoryRightMesh σ D K x).X₂ ≅
      (factorCategoryRawRightMesh σ D K x.1).X₂ :=
    eqToIso (factorCategoryRightMesh_X₂_eq_raw σ D K x)
  let e₁ : (factorCategoryRawRightMesh σ D K x.1).X₂ ≅
      FM.obj AR.middle :=
    FM.mapIso (eqToIso (moduleRightMesh_X₂ σ D x.1))
  let e₂ : FM.obj AR.middle ≅
      FM.obj (σ.sumOver AR.index AR.label) :=
    FM.mapIso AR.decomposition
  let e₃ : FM.obj (σ.sumOver AR.index AR.label) ≅ ⨁ full :=
    FM.mapBiproduct (fun t : AR.index ↦ σ.obj (AR.label t))
  have hzero : ∀ t, ¬ p t → IsZero (full t) := by
    intro t ht
    have hmem : AR.label t ∈ K := by simpa [p] using ht
    change IsZero ((σ.factorFunctor K).obj
      (σ.ambientAddPoint (AR.label t)))
    exact σ.factorObject_isZero_of_mem K hmem
  let e₄ : (⨁ full) ≅ (⨁ Subtype.restrict p full) :=
    biproductIsoSubtypeOfIsZero full p hzero
  let e₅ : (⨁ Subtype.restrict p full) ≅
      ⨁ fun t : factorCategoryMiddleIndex σ D K x ↦
        σ.factorObject K (factorCategoryMiddleLabel σ D K x t) :=
    biproduct.mapIso fun t ↦ eqToIso (by rfl)
  exact e₀.trans (e₁.trans (e₂.trans (e₃.trans (e₄.trans e₅))))

end FiniteARTranslationData

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton
