import QuotientSubmoduleEquidistribution.Combinatorics.BottomLevels
import QuotientSubmoduleEquidistribution.RepresentationTheory.ConormalModules
import QuotientSubmoduleEquidistribution.RepresentationTheory.ContragredientDuality
import QuotientSubmoduleEquidistribution.RepresentationTheory.IrreducibleCofinite
import QuotientSubmoduleEquidistribution.RepresentationTheory.SimpleLevels
import Mathlib.RingTheory.Ideal.Maps

/-!
# Module-facing faithful cores

This file constructs the two closure cores generated by the indecomposable
injective and projective labels, realizes them as `Fac`/`Sub` of finite basic
modules, and proves that those modules are an actual injective cogenerator
and projective generator.  It isolates the faithful-normal-form and Ringel
cardinality inputs as propositions rather than axioms.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore

universe u v

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} [Finite ι]
  (σ : IndecomposableSkeleton.{u, v, u} R ι)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- The chosen indecomposable categorical projectives. -/
def projectiveLabels : Set ι :=
  {i | Projective (σ.obj i)}

/-- The chosen indecomposable categorical injectives. -/
def injectiveLabels : Set ι :=
  {i | Injective (σ.obj i)}

/-- The finite basic sum of all chosen indecomposable projectives. -/
def projectiveGeneratorSupport :
    IndecomposableSkeleton.FiniteSupport (ι := ι) :=
  ⟨projectiveLabels σ, Set.toFinite _⟩

/-- The finite basic sum of all chosen indecomposable injectives. -/
def injectiveCogeneratorSupport :
    IndecomposableSkeleton.FiniteSupport (ι := ι) :=
  ⟨injectiveLabels σ, Set.toFinite _⟩

/-- The basic projective generator candidate. -/
abbrev projectiveGenerator : FGModuleCat.{u} R :=
  σ.basicModule (projectiveGeneratorSupport σ)

/-- The basic injective cogenerator candidate. -/
abbrev injectiveCogenerator : FGModuleCat.{u} R :=
  σ.basicModule (injectiveCogeneratorSupport σ)

/-- The left regular module in the same `FGModuleCat` as the skeleton. -/
abbrev regularFGModule : FGModuleCat.{u} R :=
  FGModuleCat.of R R

/-- The annihilator of a finite categorical biproduct is the intersection
of the annihilators of its terms. -/
theorem annihilator_biproduct
    (L : FintypeCat.{0}) (X : L → FGModuleCat.{u} R) :
    Module.annihilator R
        ((⨁ X : FGModuleCat.{u} R) : Type u) =
      ⨅ i, Module.annihilator R (X i) := by
  rw [(FGModuleCat.isoToLinearEquiv
    (IndecomposableSkeleton.biproductIsoPiFG X)).annihilator_eq]
  exact Module.annihilator_pi

omit [IsNoetherianRing R] [Finite ι] in
/-- The regular module has zero annihilator. -/
theorem annihilator_regularFGModule :
    Module.annihilator R (regularFGModule (R := R)) = ⊥ :=
  Module.annihilator_eq_bot.mpr inferInstance

/-- A finite module which cogenerates the regular module is faithful. -/
theorem annihilator_eq_bot_of_regular_inSubOfModule
    (J : FGModuleCat.{u} R)
    (hJ :
      IndecomposableSkeleton.InSubOfModule
        J (regularFGModule (R := R))) :
    Module.annihilator R J = ⊥ := by
  obtain ⟨L, m, hm⟩ := hJ
  have hinjective : Function.Injective m.hom.hom :=
    (IndecomposableSkeleton.fg_mono_iff_injective m).1 hm
  apply le_antisymm _ bot_le
  calc
    Module.annihilator R J ≤
        Module.annihilator R
          ((⨁ fun _ : L ↦ J : FGModuleCat.{u} R) : Type u) := by
      rw [annihilator_biproduct]
      exact le_iInf fun _ ↦ le_rfl
    _ ≤ Module.annihilator R (regularFGModule (R := R)) :=
      m.hom.hom.annihilator_le_of_injective hinjective
    _ = ⊥ := annihilator_regularFGModule

/-- A finite module which generates the regular module is faithful. -/
theorem annihilator_eq_bot_of_regular_inFacOfModule
    (G : FGModuleCat.{u} R)
    (hG :
      IndecomposableSkeleton.InFacOfModule
        G (regularFGModule (R := R))) :
    Module.annihilator R G = ⊥ := by
  obtain ⟨L, p, hp⟩ := hG
  have hsurjective : Function.Surjective p.hom.hom :=
    (IndecomposableSkeleton.fg_epi_iff_surjective p).1 hp
  apply le_antisymm _ bot_le
  calc
    Module.annihilator R G ≤
        Module.annihilator R
          ((⨁ fun _ : L ↦ G : FGModuleCat.{u} R) : Type u) := by
      rw [annihilator_biproduct]
      exact le_iInf fun _ ↦ le_rfl
    _ ≤ Module.annihilator R (regularFGModule (R := R)) :=
      p.hom.hom.annihilator_le_of_surjective hsurjective
    _ = ⊥ := annihilator_regularFGModule

/-- The quotient-side core candidate, literally the indecomposables in the
quotient closure of the injective labels. -/
def quotientCore : (σ.qClosure).Closeds :=
  ⟨σ.qClosure (injectiveLabels σ),
    σ.qClosure.isClosed_closure (injectiveLabels σ)⟩

/-- The submodule-side core candidate, literally the indecomposables in the
submodule closure of the projective labels. -/
def submoduleCore : (σ.sClosure).Closeds :=
  ⟨σ.sClosure (projectiveLabels σ),
    σ.sClosure.isClosed_closure (projectiveLabels σ)⟩

/-- Membership in the quotient core is concrete generation by the finite
basic injective module. -/
theorem mem_quotientCore_iff_inFacOfModule (i : ι) :
    i ∈ (quotientCore σ : Set ι) ↔
      IndecomposableSkeleton.InFacOfModule
        (injectiveCogenerator σ) (σ.obj i) := by
  change σ.InFac (injectiveLabels σ) (σ.obj i) ↔ _
  exact
    (σ.inFacOfModule_basicModule_iff
      (injectiveCogeneratorSupport σ) (σ.obj i)).symm

/-- Membership in the submodule core is concrete cogeneration by the finite
basic projective module. -/
theorem mem_submoduleCore_iff_inSubOfModule (i : ι) :
    i ∈ (submoduleCore σ : Set ι) ↔
      IndecomposableSkeleton.InSubOfModule
        (projectiveGenerator σ) (σ.obj i) := by
  change σ.InSub (projectiveLabels σ) (σ.obj i) ↔ _
  exact
    (σ.inSubOfModule_basicModule_iff
      (projectiveGeneratorSupport σ) (σ.obj i)).symm

/-- The basic sum of the projective labels is categorically projective. -/
theorem projective_projectiveGenerator :
    Projective (projectiveGenerator σ) := by
  change Projective
    (⨁ fun t : (projectiveGeneratorSupport σ).index ↦
      σ.obj ((projectiveGeneratorSupport σ).label t))
  letI (t : (projectiveGeneratorSupport σ).index) :
      Projective (σ.obj ((projectiveGeneratorSupport σ).label t)) :=
    (projectiveGeneratorSupport σ).label_mem t
  constructor
  intro E X f e _
  choose lift hlift using fun t : (projectiveGeneratorSupport σ).index ↦
    Projective.factors
      (biproduct.ι
        (fun t : (projectiveGeneratorSupport σ).index ↦
          σ.obj ((projectiveGeneratorSupport σ).label t)) t ≫ f) e
  refine ⟨biproduct.desc lift, ?_⟩
  apply biproduct.hom_ext'
  intro t
  simpa only [biproduct.ι_desc_assoc] using hlift t

/-- The basic sum of the injective labels is categorically injective. -/
theorem injective_injectiveCogenerator :
    Injective (injectiveCogenerator σ) := by
  change Injective
    (⨁ fun t : (injectiveCogeneratorSupport σ).index ↦
      σ.obj ((injectiveCogeneratorSupport σ).label t))
  letI (t : (injectiveCogeneratorSupport σ).index) :
      Injective (σ.obj ((injectiveCogeneratorSupport σ).label t)) :=
    (injectiveCogeneratorSupport σ).label_mem t
  infer_instance

/-- A finite injective cogenerator object, stated using the same concrete
finite-power `Sub` predicate as the closure package. -/
structure FiniteInjectiveCogeneratorData
    (J : FGModuleCat.{u} R) : Prop where
  injective : Injective J
  cogenerates :
    ∀ X : FGModuleCat.{u} R,
      IndecomposableSkeleton.InSubOfModule J X

omit [Finite ι] in
/-- Every finite injective object belongs to the additive closure of the
chosen indecomposable injective labels. -/
theorem inAdd_injectiveLabels_of_injective
    (J : FGModuleCat.{u} R) (hJ : Injective J) :
    σ.InAdd (injectiveLabels σ) J := by
  classical
  letI : Injective J := hJ
  obtain ⟨n, a, ⟨e⟩⟩ := σ.decomposes J
  refine ⟨{
    index := FintypeCat.of (Fin n)
    label := a
    mem := ?_
    iso := e }⟩
  intro t
  let r : Retract (σ.obj (a t)) J :=
    { i :=
        biproduct.ι (fun j : Fin n ↦ σ.obj (a j)) t ≫ e.inv
      r :=
        e.hom ≫ biproduct.π (fun j : Fin n ↦ σ.obj (a j)) t
      retract := by simp }
  exact r.injective

/-- Once one finite injective cogenerator exists, the duplicate-free basic
sum of all indecomposable injectives is itself a finite cogenerator. -/
theorem injectiveCogenerator_cogenerates_of
    (J : FGModuleCat.{u} R)
    (hJ : FiniteInjectiveCogeneratorData (R := R) J)
    (X : FGModuleCat.{u} R) :
    IndecomposableSkeleton.InSubOfModule
      (injectiveCogenerator σ) X := by
  classical
  obtain ⟨L, m, hm⟩ := hJ.cogenerates X
  have hJadd : σ.InAdd (injectiveLabels σ) J :=
    inAdd_injectiveLabels_of_injective σ J hJ.injective
  have htargetAdd :
      σ.InAdd (injectiveLabels σ) (⨁ fun _ : L ↦ J) :=
    σ.inAdd_biproduct L (fun _ : L ↦ J) (fun _ ↦ hJadd)
  obtain ⟨P⟩ := htargetAdd
  letI : Mono m := hm
  have hX : σ.InSub (injectiveLabels σ) X :=
    ⟨{
      index := P.index
      label := P.label
      mem := P.mem
      map := m ≫ P.iso.hom
      mono := inferInstance }⟩
  exact
    (σ.inSubOfModule_basicModule_iff
      (injectiveCogeneratorSupport σ) X).2 hX

/-- The basic injective object inherits a complete cogenerator package from
any concrete finite injective cogenerator. -/
theorem basicInjectiveCogeneratorDataOf
    (J : FGModuleCat.{u} R)
    (hJ : FiniteInjectiveCogeneratorData (R := R) J) :
    FiniteInjectiveCogeneratorData (R := R)
      (injectiveCogenerator σ) where
  injective := injective_injectiveCogenerator σ
  cogenerates := injectiveCogenerator_cogenerates_of σ J hJ

omit [IsNoetherianRing R] in
/-- The regular module is projective in the finitely generated module
category. -/
theorem projective_regularFGModule :
    Projective (regularFGModule (R := R)) := by
  constructor
  intro E X f e _
  letI : Module.Projective R R := inferInstance
  obtain ⟨g, hg⟩ :=
    Module.projective_lifting_property
      e.hom.hom f.hom.hom
      ((IndecomposableSkeleton.fg_epi_iff_surjective e).1 inferInstance)
  refine ⟨FGModuleCat.ofHom g, ?_⟩
  apply FGModuleCat.hom_ext
  exact hg

/-- The regular module is an actual finite generator, independently of any
choice of indecomposable skeleton. -/
theorem regularFGModule_generates
    (X : FGModuleCat.{u} R) :
    IndecomposableSkeleton.InFacOfModule
      (regularFGModule (R := R)) X := by
  classical
  obtain ⟨n, p, hp⟩ := Module.Finite.exists_fin' R X
  let free : FGModuleCat.{u} R := FGModuleCat.of R (Fin n → R)
  let freeIso :
      (⨁ fun _ : Fin n ↦ regularFGModule (R := R)) ≅ free :=
    biproductIsoPiFG
      (fun _ : Fin n ↦ regularFGModule (R := R))
  let q :
      (⨁ fun _ : Fin n ↦ regularFGModule (R := R)) ⟶ X :=
    freeIso.hom ≫ FGModuleCat.ofHom p
  refine ⟨FintypeCat.of (Fin n), q, ?_⟩
  haveI : Epi (FGModuleCat.ofHom p : free ⟶ X) :=
    (IndecomposableSkeleton.fg_epi_iff_surjective _).2 hp
  dsimp only [q]
  infer_instance

/-- If the regular module embeds into a finite power of `M`, then every
finite projective embeds into a finite power of `M`. -/
theorem projective_inSubOfModule_of_regular_inSub
    (M P : FGModuleCat.{u} R)
    (hM :
      IndecomposableSkeleton.InSubOfModule
        M (regularFGModule (R := R)))
    (hP : Projective P) :
    IndecomposableSkeleton.InSubOfModule M P := by
  classical
  obtain ⟨J, m, hm⟩ := hM
  obtain ⟨L, p, hp⟩ := regularFGModule_generates (R := R) P
  letI : Mono m := hm
  letI : Epi p := hp
  letI : Projective P := hP
  let lift : P ⟶ (⨁ fun _ : L ↦ regularFGModule (R := R)) :=
    Projective.factorThru (𝟙 P) p
  have hlift :
      lift ≫ p = 𝟙 P :=
    Projective.factorThru_comp (𝟙 P) p
  let K : FintypeCat.{0} := FintypeCat.of (Σ _ : L, J)
  let flattenIso :
      (⨁ fun _ : L ↦ (⨁ fun _ : J ↦ M)) ≅
        ⨁ fun _ : K ↦ M :=
    biproductBiproductIso
      (fun _ : L ↦ J) (fun _ _ ↦ M)
  let q : P ⟶ (⨁ fun _ : K ↦ M) :=
    lift ≫ biproduct.map (fun _ : L ↦ m) ≫ flattenIso.hom
  refine ⟨K, q, ?_⟩
  haveI : Mono lift :=
    mono_of_mono_fac hlift
  dsimp only [q]
  infer_instance

/-- If the regular module embeds into a finite power of `M`, then every
finite injective is a quotient of a finite power of `M`. -/
theorem injective_inFacOfModule_of_regular_inSub
    (M I : FGModuleCat.{u} R)
    (hM :
      IndecomposableSkeleton.InSubOfModule
        M (regularFGModule (R := R)))
    (hI : Injective I) :
    IndecomposableSkeleton.InFacOfModule M I := by
  classical
  obtain ⟨J, m, hm⟩ := hM
  obtain ⟨L, p, hp⟩ := regularFGModule_generates (R := R) I
  letI : Mono m := hm
  letI : Epi p := hp
  letI : Injective I := hI
  let sourceMap :
      (⨁ fun _ : L ↦ regularFGModule (R := R)) ⟶
        ⨁ fun _ : L ↦ (⨁ fun _ : J ↦ M) :=
    biproduct.map (fun _ : L ↦ m)
  let extension :
      (⨁ fun _ : L ↦ (⨁ fun _ : J ↦ M)) ⟶ I :=
    Injective.factorThru p sourceMap
  have hextension :
      sourceMap ≫ extension = p :=
    Injective.comp_factorThru p sourceMap
  let K : FintypeCat.{0} := FintypeCat.of (Σ _ : L, J)
  let flattenIso :
      (⨁ fun _ : L ↦ (⨁ fun _ : J ↦ M)) ≅
        ⨁ fun _ : K ↦ M :=
    biproductBiproductIso
      (fun _ : L ↦ J) (fun _ _ ↦ M)
  let q : (⨁ fun _ : K ↦ M) ⟶ I :=
    flattenIso.inv ≫ extension
  refine ⟨K, q, ?_⟩
  haveI : Epi extension :=
    epi_of_epi_fac hextension
  dsimp only [q]
  infer_instance

omit [Finite ι] in
/-- The regular module decomposes additively over the chosen projective
labels. -/
theorem regularFGModule_inAdd_projectiveLabels :
    σ.InAdd (projectiveLabels σ)
      (regularFGModule (R := R)) := by
  classical
  letI : Projective (regularFGModule (R := R)) :=
    projective_regularFGModule (R := R)
  obtain ⟨n, a, ⟨e⟩⟩ :=
    σ.decomposes (regularFGModule (R := R))
  refine ⟨{
    index := FintypeCat.of (Fin n)
    label := a
    mem := ?_
    iso := e }⟩
  intro t
  let r : Retract (σ.obj (a t))
      (regularFGModule (R := R)) :=
    { i :=
        biproduct.ι (fun j : Fin n ↦ σ.obj (a j)) t ≫ e.inv
      r :=
        e.hom ≫ biproduct.π (fun j : Fin n ↦ σ.obj (a j)) t
      retract := by simp }
  exact r.projective

omit [Finite ι] in
/-- Every finitely generated module is a quotient of a finite sum of the
chosen indecomposable projectives. -/
theorem inFac_projectiveLabels
    (X : FGModuleCat.{u} R) :
    σ.InFac (projectiveLabels σ) X := by
  classical
  obtain ⟨L, p, hp⟩ :=
    regularFGModule_generates (R := R) X
  have hsumAdd :
      σ.InAdd (projectiveLabels σ)
        (⨁ fun _ : L ↦ regularFGModule (R := R)) :=
    σ.inAdd_biproduct L
      (fun _ : L ↦ regularFGModule (R := R))
      (fun _ ↦ regularFGModule_inAdd_projectiveLabels σ)
  obtain ⟨P⟩ := hsumAdd
  letI : Epi p := hp
  exact ⟨{
    index := P.index
    label := P.label
    mem := P.mem
    map := P.iso.inv ≫ p
    epi := by infer_instance }⟩

/-- The basic sum of all indecomposable projectives is an actual finite
generator: every finitely generated module is a quotient of a finite sum of
copies of it. -/
theorem projectiveGenerator_generates
    (X : FGModuleCat.{u} R) :
    IndecomposableSkeleton.InFacOfModule
      (projectiveGenerator σ) X := by
  classical
  obtain ⟨n, p, hp⟩ := Module.Finite.exists_fin' R X
  let F : FGModuleCat.{u} R :=
    FGModuleCat.of R (Fin n → R)
  let e : F ⟶ X := FGModuleCat.ofHom p
  let regularSum : FGModuleCat.{u} R :=
    ⨁ fun _ : Fin n ↦ regularFGModule (R := R)
  let regularSumIsoFree : regularSum ≅ F :=
    biproductIsoPiFG
      (fun _ : Fin n ↦ regularFGModule (R := R))
  have hsumAdd :
      σ.InAdd (projectiveLabels σ) regularSum :=
    σ.inAdd_biproduct (FintypeCat.of (Fin n))
      (fun _ : Fin n ↦ regularFGModule (R := R))
      (fun _ ↦ regularFGModule_inAdd_projectiveLabels σ)
  have hfreeAdd : σ.InAdd (projectiveLabels σ) F :=
    (σ.inAdd_iff_of_iso regularSumIsoFree).1 hsumAdd
  have hfreeFac : σ.InFac (projectiveLabels σ) F := by
    obtain ⟨P⟩ := hfreeAdd
    exact ⟨{
      index := P.index
      label := P.label
      mem := P.mem
      map := P.iso.inv
      epi := inferInstance }⟩
  haveI : Epi e :=
    (IndecomposableSkeleton.fg_epi_iff_surjective e).2 hp
  have hX : σ.InFac (projectiveLabels σ) X :=
    σ.inFac_of_epi hfreeFac e
  exact
    (σ.inFacOfModule_basicModule_iff
      (projectiveGeneratorSupport σ) X).2 hX

/-- The basic projective generator is faithful. -/
theorem annihilator_projectiveGenerator_eq_bot :
    Module.annihilator R (projectiveGenerator σ) = ⊥ :=
  annihilator_eq_bot_of_regular_inFacOfModule
    (projectiveGenerator σ)
    (projectiveGenerator_generates σ
      (regularFGModule (R := R)))

/-! ## Concrete finite-dimensional injective cogenerator -/

section ContragredientCogenerator

variable (K : Type u)
  [Field K] [Algebra K R] [FiniteDimensional K R]

/-- The `K`-dual of the right regular module, regarded as a left
`R`-module by the maintained reverse contragredient functor. -/
abbrev dualRegular : FGModuleCat.{u} R :=
  (QuotientSubmoduleEquidistribution.Contragredient.reverseDualFunctor K R).obj
    (Opposite.op (regularFGModule (R := Rᵐᵒᵖ)))

/-- Reverse duality takes a finite biproduct of right regular modules to
the corresponding biproduct of dual regular modules. -/
def reverseDualRegularSumIso (L : FintypeCat.{0}) :
    (QuotientSubmoduleEquidistribution.Contragredient.reverseDualFunctor K R).obj
        (Opposite.op
          (⨁ fun _ : L ↦ regularFGModule (R := Rᵐᵒᵖ))) ≅
      ⨁ fun _ : L ↦ dualRegular (R := R) K :=
  let E := QuotientSubmoduleEquidistribution.Contragredient.reverseDualityEquivalence K R
  E.functor.mapIso
      ((biproduct.isoCoproduct
        (fun _ : L ↦ regularFGModule (R := Rᵐᵒᵖ))).op.symm ≪≫
        opCoproductIsoProduct
          (fun _ : L ↦ regularFGModule (R := Rᵐᵒᵖ))) ≪≫
    PreservesProduct.iso E.functor
      (fun _ : L ↦ Opposite.op (regularFGModule (R := Rᵐᵒᵖ))) ≪≫
    (biproduct.isoProduct
      (fun _ : L ↦ dualRegular (R := R) K)).symm

omit [IsNoetherianRing R] in
/-- The dual regular module is categorically injective. -/
theorem injective_dualRegular :
    Injective (dualRegular (R := R) K) := by
  let P : FGModuleCat.{u} Rᵐᵒᵖ :=
    regularFGModule (R := Rᵐᵒᵖ)
  letI : Projective P :=
    projective_regularFGModule (R := Rᵐᵒᵖ)
  have hP : Injective (Opposite.op P) := inferInstance
  let E := QuotientSubmoduleEquidistribution.Contragredient.reverseDualityEquivalence K R
  exact (E.map_injective_iff (Opposite.op P)).2 hP

/-- Every finitely generated left module embeds into a finite power of the
dual regular module. -/
theorem dualRegular_cogenerates
    [IsNoetherianRing Rᵐᵒᵖ]
    (X : FGModuleCat.{u} R) :
    IndecomposableSkeleton.InSubOfModule
      (dualRegular (R := R) K) X := by
  let DX : FGModuleCat.{u} Rᵐᵒᵖ :=
    (QuotientSubmoduleEquidistribution.Contragredient.dualFunctor K R).obj
      (Opposite.op X)
  obtain ⟨L, p, hp⟩ :=
    regularFGModule_generates (R := Rᵐᵒᵖ) DX
  letI : Epi p := hp
  let E := QuotientSubmoduleEquidistribution.Contragredient.reverseDualityEquivalence K R
  let dp := E.functor.map p.op
  letI : Mono p.op := inferInstance
  letI : Mono dp := by
    dsimp only [dp]
    infer_instance
  let fwd :=
    (QuotientSubmoduleEquidistribution.Contragredient.forwardBidualIso K R X).hom
  let out := (reverseDualRegularSumIso (R := R) K L).hom
  letI : Mono fwd := by
    dsimp only [fwd]
    infer_instance
  letI : Mono out := by
    dsimp only [out]
    infer_instance
  let m : X ⟶ (⨁ fun _ : L ↦ dualRegular (R := R) K) :=
    (fwd ≫ dp) ≫ out
  refine ⟨L, m, ?_⟩
  apply (IndecomposableSkeleton.fg_mono_iff_injective m).2
  intro x y hxy
  have hfwd : Function.Injective fwd.hom.hom :=
    (IndecomposableSkeleton.fg_mono_iff_injective fwd).1 inferInstance
  have hdp : Function.Injective dp.hom.hom :=
    (IndecomposableSkeleton.fg_mono_iff_injective dp).1 inferInstance
  have hout : Function.Injective out.hom.hom :=
    (IndecomposableSkeleton.fg_mono_iff_injective out).1 inferInstance
  apply hfwd
  apply hdp
  apply hout
  exact hxy

/-- The dual regular module is an explicit finite injective cogenerator. -/
theorem dualRegularCogeneratorData
    [IsNoetherianRing Rᵐᵒᵖ] :
    FiniteInjectiveCogeneratorData (R := R)
      (dualRegular (R := R) K) where
  injective := injective_dualRegular (R := R) K
  cogenerates := dualRegular_cogenerates (R := R) K

include K in
/-- Hence the duplicate-free basic sum of all chosen indecomposable
injectives is itself an actual finite injective cogenerator. -/
theorem concreteBasicInjectiveCogeneratorData
    [IsNoetherianRing Rᵐᵒᵖ] :
    FiniteInjectiveCogeneratorData (R := R)
      (injectiveCogenerator σ) :=
  basicInjectiveCogeneratorDataOf σ (dualRegular (R := R) K)
    (dualRegularCogeneratorData (R := R) K)

include K in
/-- The basic injective cogenerator is faithful. -/
theorem annihilator_injectiveCogenerator_eq_bot
    [IsNoetherianRing Rᵐᵒᵖ] :
    Module.annihilator R (injectiveCogenerator σ) = ⊥ :=
  annihilator_eq_bot_of_regular_inSubOfModule
    (injectiveCogenerator σ)
    ((concreteBasicInjectiveCogeneratorData σ K).cogenerates
      (regularFGModule (R := R)))

end ContragredientCogenerator

/-- A faithful-normal-form interface for closed supports.  In the actual
module application `Faithful C` is `ann(C)=0`. -/
structure ClosedFaithfulNormalForm
    (FaithfulQ FaithfulS : Set ι → Prop) : Prop where
  quotient_iff :
    ∀ C : (σ.qClosure).Closeds,
      FaithfulQ (C : Set ι) ↔ injectiveLabels σ ⊆ (C : Set ι)
  submodule_iff :
    ∀ C : (σ.sClosure).Closeds,
      FaithfulS (C : Set ι) ↔ projectiveLabels σ ⊆ (C : Set ι)

/-- Actual quotient-core data, conditional only on the faithful normal form. -/
def quotientCoreData
    {FaithfulQ FaithfulS : Set ι → Prop}
    (h : ClosedFaithfulNormalForm σ FaithfulQ FaithfulS) :
    QuotientSubmoduleEquidistribution.BottomLevels.MinimalFaithfulCore.Data
      σ.qClosure FaithfulQ :=
  QuotientSubmoduleEquidistribution.BottomLevels.MinimalFaithfulCore.Data.of_closed_iff_contains
    σ.qClosure FaithfulQ (injectiveLabels σ) h.quotient_iff

/-- Actual submodule-core data, conditional only on the faithful normal form. -/
def submoduleCoreData
    {FaithfulQ FaithfulS : Set ι → Prop}
    (h : ClosedFaithfulNormalForm σ FaithfulQ FaithfulS) :
    QuotientSubmoduleEquidistribution.BottomLevels.MinimalFaithfulCore.Data
      σ.sClosure FaithfulS :=
  QuotientSubmoduleEquidistribution.BottomLevels.MinimalFaithfulCore.Data.of_closed_iff_contains
    σ.sClosure FaithfulS (projectiveLabels σ) h.submodule_iff

omit [Finite ι] in
@[simp]
theorem quotientCoreData_core
    {FaithfulQ FaithfulS : Set ι → Prop}
    (h : ClosedFaithfulNormalForm σ FaithfulQ FaithfulS) :
    ((quotientCoreData σ h).core : Set ι) =
      (quotientCore σ : Set ι) :=
  rfl

omit [Finite ι] in
@[simp]
theorem submoduleCoreData_core
    {FaithfulQ FaithfulS : Set ι → Prop}
    (h : ClosedFaithfulNormalForm σ FaithfulQ FaithfulS) :
    ((submoduleCoreData σ h).core : Set ι) =
      (submoduleCore σ : Set ι) :=
  rfl

/-- Exact proposition corresponding to Ringel's core-cardinality theorem in
the chosen-skeleton language. -/
def RingelCoreCardinality : Prop :=
  (quotientCore σ : Set ι).ncard =
    (submoduleCore σ : Set ι).ncard

omit [Finite ι] in
/-- Ringel's statement supplies precisely the core-cardinality field needed
by the faithful recurrence. -/
theorem core_ncard_eq_of_ringel
    {FaithfulQ FaithfulS : Set ι → Prop}
    (hNormal : ClosedFaithfulNormalForm σ FaithfulQ FaithfulS)
    (hRingel : RingelCoreCardinality σ) :
    (((quotientCoreData σ hNormal).core : Set ι).ncard =
      ((submoduleCoreData σ hNormal).core : Set ι).ncard) := by
  simpa [RingelCoreCardinality] using hRingel

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore
