import QuotientSubmoduleEquidistribution.RepresentationTheory.TwoSourceExtBridge
import QuotientSubmoduleEquidistribution.RepresentationTheory.LevelThreeNonUniserialShapes
import QuotientSubmoduleEquidistribution.RepresentationTheory.LengthThreeUniserialCollective

/-!
# Collective reduction for the two-top family

The first section strengthens the two-source rank core in precisely the
direction needed for quotients of a finite power of a fork apex: an arbitrary
idempotent-indecomposable common-target fork has one-dimensional multiplicity
spaces whenever its target is nonzero.

The module specialization then proves that every nonsimple indecomposable
generated by an actual family-five apex again has radical multiplicity one,
one copy of each top type, and composition length three.  Identifying the
resulting extension with the original apex—and hence collective
quotient-closedness—is intentionally left as a separate theorem.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Abelian

namespace QuotientSubmoduleEquidistribution.LoewyTwoRankCore

universe u v w z

variable {K : Type u} [Field K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]
  {Z : Type z} [AddCommGroup Z] [Module K Z]

/-- A finite-dimensional vector space of dimension at least two has a
nonzero idempotent endomorphism different from the identity. -/
theorem exists_nontrivial_idempotent_of_two_le_finrank
    [FiniteDimensional K Z]
    (hZ : 2 ≤ Module.finrank K Z) :
    ∃ r : Z →ₗ[K] Z,
      r.comp r = r ∧ r ≠ 0 ∧ r ≠ LinearMap.id := by
  have hpos : 0 < Module.finrank K Z := by omega
  letI : Nontrivial Z :=
    Module.nontrivial_of_finrank_pos (R := K) (M := Z) hpos
  obtain ⟨z, hz⟩ := exists_ne (0 : Z)
  have hli : LinearIndependent K (fun _ : Unit ↦ z) :=
    LinearIndependent.of_subsingleton () hz
  obtain ⟨phi, hphi⟩ :=
    Module.exists_dual_forall_apply_eq_one
      (s := Set.univ) (hli.linearIndepOn Set.univ)
  have hphiz : phi z = 1 := hphi () (Set.mem_univ ())
  let r : Z →ₗ[K] Z := LinearMap.smulRight phi z
  have hridem : r.comp r = r := by
    ext x
    simp [r, LinearMap.comp_apply, hphiz]
  have hrne : r ≠ 0 := by
    intro hr
    have hrz := LinearMap.congr_fun hr z
    exact hz (by simpa [r, hphiz] using hrz)
  have hphiRange : Module.finrank K phi.range ≤ 1 := by
    calc
      Module.finrank K phi.range ≤ Module.finrank K K :=
        phi.range.finrank_le
      _ = 1 := Module.finrank_self K
  have hkerPos : 0 < Module.finrank K phi.ker := by
    have hsum := LinearMap.finrank_range_add_finrank_ker phi
    omega
  letI : Nontrivial phi.ker :=
    Module.nontrivial_of_finrank_pos (R := K) (M := phi.ker) hkerPos
  obtain ⟨w, hw⟩ := exists_ne (0 : phi.ker)
  have hwval : w.1 ≠ 0 := by
    intro hwzero
    apply hw
    apply Subtype.ext
    exact hwzero
  have hrnotid : r ≠ LinearMap.id := by
    intro hr
    have hrw := LinearMap.congr_fun hr w.1
    apply hwval
    simpa [r, w.2] using hrw.symm
  exact ⟨r, hridem, hrne, hrnotid⟩

/-- A surjective linear map admits an idempotent lift of every idempotent
endomorphism of its target. -/
theorem exists_idempotent_lift_of_surjective
    [FiniteDimensional K V] [FiniteDimensional K Z]
    (f : V →ₗ[K] Z) (hf : Function.Surjective f)
    (r : Z →ₗ[K] Z) (hr : r.comp r = r) :
    ∃ p : V →ₗ[K] V,
      p.comp p = p ∧ r.comp f = f.comp p := by
  obtain ⟨s, hs⟩ :=
    f.exists_rightInverse_of_surjective
      (LinearMap.range_eq_top.mpr hf)
  let p : V →ₗ[K] V := s.comp (r.comp f)
  have hfs : f.comp s = LinearMap.id := by
    exact hs
  refine ⟨p, ?_, ?_⟩
  · ext x
    simp only [p, LinearMap.comp_apply]
    have hfsx : f (s (r (f x))) = r (f x) := by
      have := LinearMap.congr_fun hfs (r (f x))
      simpa [LinearMap.comp_apply] using this
    rw [hfsx]
    have hrx := LinearMap.congr_fun hr (f x)
    simpa [LinearMap.comp_apply] using congrArg s hrx
  · ext x
    have hfsx : f (s (r (f x))) = r (f x) := by
      have := LinearMap.congr_fun hfs (r (f x))
      simpa [LinearMap.comp_apply] using this
    simpa [p, LinearMap.comp_apply] using hfsx.symm

/-- If both arrows in an idempotent-indecomposable two-source
representation are surjective, then the common target is at most
one-dimensional. -/
theorem twoSource_target_finrank_le_one_of_surjective
    [FiniteDimensional K V] [FiniteDimensional K W]
    [FiniteDimensional K Z]
    {f : V →ₗ[K] Z} {g : W →ₗ[K] Z}
    (hf : Function.Surjective f) (hg : Function.Surjective g)
    (hfg : IsTwoSourceIdempotentIndecomposable f g) :
    Module.finrank K Z ≤ 1 := by
  by_contra hle
  have htwo : 2 ≤ Module.finrank K Z := by omega
  obtain ⟨r, hr, hrne, hrnotid⟩ :=
    exists_nontrivial_idempotent_of_two_le_finrank htwo
  obtain ⟨p, hp, hfp⟩ :=
    exists_idempotent_lift_of_surjective f hf r hr
  obtain ⟨q, hq, hgq⟩ :=
    exists_idempotent_lift_of_surjective g hg r hr
  rcases hfg p q r hp hq hr hfp hgq with hzero | hone
  · exact hrne hzero.2.2
  · exact hrnotid hone.2.2

private theorem zero_ne_linearMap_id
    {M : Type*} [AddCommGroup M] [Module K M] [Nontrivial M] :
    (0 : M →ₗ[K] M) ≠ LinearMap.id := by
  intro h
  obtain ⟨m, hm⟩ := exists_ne (0 : M)
  have hmapped := LinearMap.congr_fun h m
  exact hm (by simpa using hmapped.symm)

/-- The common target of an arbitrary idempotent-indecomposable fork has
dimension at most one.  This is the linear dual of the corresponding
common-source theorem, proved directly so that no choices of dual bases
enter the maintained dependency path. -/
theorem twoSource_target_finrank_le_one
    [FiniteDimensional K V] [FiniteDimensional K W]
    [FiniteDimensional K Z]
    {f : V →ₗ[K] Z} {g : W →ₗ[K] Z}
    (hfg : IsTwoSourceIdempotentIndecomposable f g) :
    Module.finrank K Z ≤ 1 := by
  by_cases hV : Subsingleton V
  · letI : Subsingleton V := hV
    have hg : IsIdempotentIndecomposable g := by
      intro q r hq hr hcomm
      have hfcomm :
          r.comp f = f.comp (0 : V →ₗ[K] V) :=
        Subsingleton.elim _ _
      rcases hfg 0 q r (by ext; simp) hq hr hfcomm hcomm with
        hzero | hone
      · exact Or.inl ⟨hzero.2.1, hzero.2.2⟩
      · exact Or.inr ⟨hone.2.1, hone.2.2⟩
    exact target_finrank_le_one hg
  · letI : Nontrivial V := not_subsingleton_iff_nontrivial.mp hV
    by_contra hZle
    have hZ : 2 ≤ Module.finrank K Z := by omega
    letI : Nontrivial Z :=
      Module.nontrivial_of_finrank_pos (R := K) (M := Z) (by omega)
    have hzeroIdV : (0 : V →ₗ[K] V) ≠ LinearMap.id :=
      zero_ne_linearMap_id (K := K)
    have hzeroIdZ : (0 : Z →ₗ[K] Z) ≠ LinearMap.id :=
      zero_ne_linearMap_id (K := K)
    by_cases hfinj : Function.Injective f
    · by_cases hfsurj : Function.Surjective f
      · let ef : V ≃ₗ[K] Z :=
          LinearEquiv.ofBijective f ⟨hfinj, hfsurj⟩
        let a : W →ₗ[K] V := ef.symm.toLinearMap.comp g
        have ha : IsIdempotentIndecomposable a := by
          intro q p hq hp hcomm
          let r : Z →ₗ[K] Z :=
            ef.toLinearMap.comp (p.comp ef.symm.toLinearMap)
          have hr : r.comp r = r := by
            ext z
            have hpz := LinearMap.congr_fun hp (ef.symm z)
            simpa [r, LinearMap.comp_apply] using congrArg ef hpz
          have hrf : r.comp f = f.comp p := by
            ext x
            simp [r, LinearMap.comp_apply, ef]
          have hrg : r.comp g = g.comp q := by
            ext x
            have hx := LinearMap.congr_fun hcomm x
            simpa [a, r, LinearMap.comp_apply] using congrArg ef hx
          rcases hfg p q r hp hq hr hrf hrg with hzero | hone
          · exact Or.inl ⟨hzero.2.1, hzero.1⟩
          · exact Or.inr ⟨hone.2.1, hone.1⟩
        have hVle : Module.finrank K V ≤ 1 :=
          target_finrank_le_one ha
        have heq : Module.finrank K V = Module.finrank K Z :=
          ef.finrank_eq
        omega
      · have hrangeLt : f.range < ⊤ := by
          rw [lt_top_iff_ne_top]
          exact fun htop ↦ hfsurj (LinearMap.range_eq_top.mp htop)
        let Q := Z ⧸ f.range
        let uMap : W →ₗ[K] Q := f.range.mkQ.comp g
        by_cases hu : Function.Surjective uMap
        · obtain ⟨s, hs⟩ :=
            uMap.exists_rightInverse_of_surjective
              (LinearMap.range_eq_top.mpr hu)
          let q : W →ₗ[K] W := s.comp uMap
          let r : Z →ₗ[K] Z :=
            g.comp (s.comp f.range.mkQ)
          have hus : uMap.comp s = LinearMap.id := hs
          have hq : q.comp q = q := by
            ext x
            have hx := LinearMap.congr_fun hus (uMap x)
            simpa [q, LinearMap.comp_apply] using congrArg s hx
          have hr : r.comp r = r := by
            ext z
            have hz :
                uMap (s (f.range.mkQ z)) = f.range.mkQ z := by
              have := LinearMap.congr_fun hus (f.range.mkQ z)
              simpa [LinearMap.comp_apply] using this
            change
              g (s (f.range.mkQ (g (s (f.range.mkQ z))))) =
                g (s (f.range.mkQ z))
            simpa only [uMap, LinearMap.comp_apply] using
              congrArg (fun y ↦ g (s y)) hz
          have hrf : r.comp f = f.comp (0 : V →ₗ[K] V) := by
            ext x
            have hmk : f.range.mkQ (f x) = 0 := by
              rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
              exact LinearMap.mem_range_self f x
            simp [r, LinearMap.comp_apply, hmk]
          have hrg : r.comp g = g.comp q := by
            ext x
            rfl
          have hQnontrivial : Nontrivial Q := by
            rw [Submodule.Quotient.nontrivial_iff]
            exact hrangeLt.ne
          letI : Nontrivial Q := hQnontrivial
          obtain ⟨z, hz⟩ := exists_ne (0 : Q)
          have hrne : r ≠ 0 := by
            intro hrzero
            obtain ⟨x, hx⟩ := f.range.mkQ_surjective z
            have hrx := LinearMap.congr_fun hrzero x
            have husz := LinearMap.congr_fun hus z
            apply hz
            calc
              z = uMap (s z) := by simpa [LinearMap.comp_apply] using husz.symm
              _ = f.range.mkQ (g (s z)) := rfl
              _ = f.range.mkQ (r x) := by simp [r, LinearMap.comp_apply, hx]
              _ = 0 := by rw [hrx]; simp
          rcases hfg 0 q r (by ext; simp) hq hr hrf hrg with
            hzero | hone
          · exact hrne hzero.2.2
          · exact hzeroIdV hone.1
        · have huRangeLt : uMap.range < ⊤ := by
            rw [lt_top_iff_ne_top]
            exact fun htop ↦ hu (LinearMap.range_eq_top.mp htop)
          obtain ⟨y, -, hy⟩ := SetLike.exists_of_lt huRangeLt
          have hyQuot : uMap.range.mkQ y ≠ 0 := by
            simpa using hy
          have hli :
              LinearIndependent K (fun _ : Unit ↦ uMap.range.mkQ y) :=
            LinearIndependent.of_subsingleton () hyQuot
          obtain ⟨psi, hpsi⟩ :=
            Module.exists_dual_forall_apply_eq_one
              (s := Set.univ) (hli.linearIndepOn Set.univ)
          have hpsiy : psi (uMap.range.mkQ y) = 1 :=
            hpsi () (Set.mem_univ ())
          obtain ⟨z, hz⟩ := f.range.mkQ_surjective y
          let phi : Z →ₗ[K] K :=
            psi.comp (uMap.range.mkQ.comp f.range.mkQ)
          have hphiz : phi z = 1 := by
            simpa [phi, LinearMap.comp_apply, hz] using hpsiy
          let r : Z →ₗ[K] Z := LinearMap.smulRight phi z
          have hr : r.comp r = r := by
            ext x
            simp [r, LinearMap.comp_apply, hphiz]
          have hrne : r ≠ 0 := by
            intro hrzero
            have hrz := LinearMap.congr_fun hrzero z
            have hzval : z ≠ 0 := by
              intro hzzero
              have : phi z = 0 := by simp [hzzero]
              rw [hphiz] at this
              exact one_ne_zero this
            exact hzval (by simpa [r, hphiz] using hrz)
          have hrf : r.comp f = f.comp (0 : V →ₗ[K] V) := by
            ext x
            have hmk : f.range.mkQ (f x) = 0 := by
              rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
              exact LinearMap.mem_range_self f x
            simp [r, phi, LinearMap.comp_apply, hmk]
          have hrg : r.comp g = g.comp (0 : W →ₗ[K] W) := by
            ext x
            have hmem : uMap x ∈ uMap.range :=
              LinearMap.mem_range_self uMap x
            have hmk : uMap.range.mkQ (uMap x) = 0 := by
              rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
              exact hmem
            have hmk' :
                uMap.range.mkQ (f.range.mkQ (g x)) = 0 := by
              simpa only [uMap, LinearMap.comp_apply] using hmk
            have hphi : phi (g x) = 0 := by
              simp [phi, LinearMap.comp_apply, hmk']
            simp [r, LinearMap.comp_apply, hphi]
          rcases hfg 0 0 r (by ext; simp) (by ext; simp) hr hrf hrg with
            hzero | hone
          · exact hrne hzero.2.2
          · exact hzeroIdV hone.1
    · have hker : f.ker ≠ ⊥ := by
        intro hbot
        exact hfinj (LinearMap.ker_eq_bot.mp hbot)
      letI : Nontrivial f.ker :=
        (Submodule.nontrivial_iff_ne_bot).mpr hker
      obtain ⟨k, hk⟩ := exists_ne (0 : f.ker)
      let v : V := k.1
      have hv : v ≠ 0 := by
        intro hvzero
        apply hk
        apply Subtype.ext
        exact hvzero
      have hli : LinearIndependent K (fun _ : Unit ↦ v) :=
        LinearIndependent.of_subsingleton () hv
      obtain ⟨phi, hphi⟩ :=
        Module.exists_dual_forall_apply_eq_one
          (s := Set.univ) (hli.linearIndepOn Set.univ)
      have hphiv : phi v = 1 := hphi () (Set.mem_univ ())
      let p : V →ₗ[K] V := LinearMap.smulRight phi v
      have hp : p.comp p = p := by
        ext x
        simp [p, LinearMap.comp_apply, hphiv]
      have hpne : p ≠ 0 := by
        intro hpzero
        have hpv := LinearMap.congr_fun hpzero v
        exact hv (by simpa [p, hphiv] using hpv)
      have hfv : f v = 0 := k.2
      have hfp : (0 : Z →ₗ[K] Z).comp f = f.comp p := by
        ext x
        simp [p, LinearMap.comp_apply, hfv]
      have hgp :
          (0 : Z →ₗ[K] Z).comp g =
            g.comp (0 : W →ₗ[K] W) := by
        ext
        simp
      rcases hfg p 0 0 hp (by ext; simp) (by ext; simp)
          hfp hgp with hzero | hone
      · exact hpne hzero.1
      · exact hzeroIdZ hone.2.2

/-- The full positive-root bound for a quotient fork: surjectivity of both
arrows first forces the common target to be one-dimensional, after which
the existing two-source theorem controls both sources. -/
theorem twoSource_all_finrank_le_one_of_surjective
    [FiniteDimensional K V] [FiniteDimensional K W]
    [FiniteDimensional K Z]
    {f : V →ₗ[K] Z} {g : W →ₗ[K] Z}
    (hf : Function.Surjective f) (hg : Function.Surjective g)
    (hZpos : 0 < Module.finrank K Z)
    (hfg : IsTwoSourceIdempotentIndecomposable f g) :
    Module.finrank K V ≤ 1 ∧
      Module.finrank K W ≤ 1 ∧
        Module.finrank K Z ≤ 1 := by
  have hZ :=
    twoSource_target_finrank_le_one_of_surjective hf hg hfg
  have hZone : Module.finrank K Z = 1 := by omega
  have hsources := twoSource_source_finrank_le_one hZone hfg
  exact ⟨hsources.1, hsources.2, hZ⟩

/-- Once the common target is known to be nonzero, the arbitrary common-
target bound and the maintained conditional source bounds classify the
entire indecomposable fork without any surjectivity hypothesis. -/
theorem twoSource_all_finrank_le_one
    [FiniteDimensional K V] [FiniteDimensional K W]
    [FiniteDimensional K Z]
    {f : V →ₗ[K] Z} {g : W →ₗ[K] Z}
    (hZpos : 0 < Module.finrank K Z)
    (hfg : IsTwoSourceIdempotentIndecomposable f g) :
    Module.finrank K V ≤ 1 ∧
      Module.finrank K W ≤ 1 ∧
        Module.finrank K Z ≤ 1 := by
  have hZle := twoSource_target_finrank_le_one hfg
  have hZone : Module.finrank K Z = 1 := by omega
  have hsources := twoSource_source_finrank_le_one hZone hfg
  exact ⟨hsources.1, hsources.2, hZle⟩

end QuotientSubmoduleEquidistribution.LoewyTwoRankCore

namespace QuotientSubmoduleEquidistribution.YonedaExtReflection

universe w v u

variable {K : Type u} [Field K]
  {C : Type v} [Category.{w} C] [Abelian C] [Linear K C]
  [HasFiniteBiproducts C] [HasExt C]

/-!
The earlier two-source bridge fixes the common target multiplicity to
`Unit`.  Quotients of powers of a family-5 apex require the same bridge for
an arbitrary finite target multiplicity.  The proofs below are the literal
rectangular generalization.
-/

theorem ext_compatibility_of_two_scalarized_matrix_commute_generalTarget
    {I J L : Type} [Fintype I] [Fintype J] [Fintype L]
    (X X' Y : C)
    (ell : Ext X Y 1 →ₗ[K] K) (hell : Function.Injective ell)
    (ell' : Ext X' Y 1 →ₗ[K] K) (hell' : Function.Injective ell')
    (xi :
      Ext
        ((⨁ fun _ : I ↦ X) ⊞ (⨁ fun _ : J ↦ X'))
        (⨁ fun _ : L ↦ Y) 1)
    (P : Matrix I I K) (Q : Matrix J J K)
    (R : Matrix L L K)
    (hleft :
      R * scalarizedExtMatrix X Y ell (extBiprodLeft xi) =
        scalarizedExtMatrix X Y ell (extBiprodLeft xi) * P)
    (hright :
      R * scalarizedExtMatrix X' Y ell' (extBiprodRight xi) =
        scalarizedExtMatrix X' Y ell' (extBiprodRight xi) * Q) :
    xi.comp
          (Ext.mk₀ (scalarBiproductEnd Y R)) (add_zero 1) =
      (Ext.mk₀
          (blockDiagonalBiprodEnd
            (scalarBiproductEnd X P)
            (scalarBiproductEnd X' Q))).comp
        xi (zero_add 1) := by
  apply ext_eq_of_extBiprodLeft_right_eq
  · change
      extBiprodLeft
          (xi.comp (Ext.mk₀ (scalarBiproductEnd Y R)) (add_zero 1)) =
        extBiprodLeft
          ((Ext.mk₀
              (blockDiagonalBiprodEnd
                (scalarBiproductEnd X P)
                (scalarBiproductEnd X' Q))).comp
            xi (zero_add 1))
    calc
      _ = (extBiprodLeft xi).comp
          (Ext.mk₀ (scalarBiproductEnd Y R)) (add_zero 1) := by
        exact
          (Ext.comp_assoc_of_third_deg_zero
            (Ext.mk₀ biprod.inl) xi
            (Ext.mk₀ (scalarBiproductEnd Y R)) (zero_add 1)).symm
      _ = (Ext.mk₀ (scalarBiproductEnd X P)).comp
          (extBiprodLeft xi) (zero_add 1) :=
        ext_compatibility_of_scalarized_matrix_commute
          X Y ell hell (extBiprodLeft xi) P R hleft
      _ = _ := by
        unfold extBiprodLeft
        rw [← Ext.comp_assoc_of_second_deg_zero,
          Ext.mk₀_comp_mk₀]
        simp [blockDiagonalBiprodEnd]
  · change
      extBiprodRight
          (xi.comp (Ext.mk₀ (scalarBiproductEnd Y R)) (add_zero 1)) =
        extBiprodRight
          ((Ext.mk₀
              (blockDiagonalBiprodEnd
                (scalarBiproductEnd X P)
                (scalarBiproductEnd X' Q))).comp
            xi (zero_add 1))
    calc
      _ = (extBiprodRight xi).comp
          (Ext.mk₀ (scalarBiproductEnd Y R)) (add_zero 1) := by
        exact
          (Ext.comp_assoc_of_third_deg_zero
            (Ext.mk₀ biprod.inr) xi
            (Ext.mk₀ (scalarBiproductEnd Y R)) (zero_add 1)).symm
      _ = (Ext.mk₀ (scalarBiproductEnd X' Q)).comp
          (extBiprodRight xi) (zero_add 1) :=
        ext_compatibility_of_scalarized_matrix_commute
          X' Y ell' hell' (extBiprodRight xi) Q R hright
      _ = _ := by
        unfold extBiprodRight
        rw [← Ext.comp_assoc_of_second_deg_zero,
          Ext.mk₀_comp_mk₀]
        simp [blockDiagonalBiprodEnd]

theorem twoSource_scalarizedExtLinearMaps_isIdempotentIndecomposable_generalTarget
    {I J L : Type} [Fintype I] [Fintype J] [Fintype L]
    [DecidableEq I] [DecidableEq J] [DecidableEq L]
    (X X' Y : C) (hX : 𝟙 X ≠ 0) (hX' : 𝟙 X' ≠ 0)
    (hY : 𝟙 Y ≠ 0)
    (ell : Ext X Y 1 →ₗ[K] K) (hell : Function.Injective ell)
    (ell' : Ext X' Y 1 →ₗ[K] K) (hell' : Function.Injective ell')
    (xi :
      Ext
        ((⨁ fun _ : I ↦ X) ⊞ (⨁ fun _ : J ↦ X'))
        (⨁ fun _ : L ↦ Y) 1)
    (hendpoint :
      ∀ (a₁ :
          (⨁ fun _ : L ↦ Y) ⟶ (⨁ fun _ : L ↦ Y))
        (a₃ :
          ((⨁ fun _ : I ↦ X) ⊞ (⨁ fun _ : J ↦ X')) ⟶
            ((⨁ fun _ : I ↦ X) ⊞ (⨁ fun _ : J ↦ X'))),
        a₁ ≫ a₁ = a₁ →
        a₃ ≫ a₃ = a₃ →
        xi.comp (Ext.mk₀ a₁) (add_zero 1) =
          (Ext.mk₀ a₃).comp xi (zero_add 1) →
        (a₁ = 0 ∧ a₃ = 0) ∨
          (a₁ = 𝟙 _ ∧ a₃ = 𝟙 _)) :
    LoewyTwoRankCore.IsTwoSourceIdempotentIndecomposable
      (scalarizedExtLinearMap X Y ell (extBiprodLeft xi))
      (scalarizedExtLinearMap X' Y ell' (extBiprodRight xi)) := by
  classical
  intro p q r hp hq hr hrf hrg
  let P : Matrix I I K := LinearMap.toMatrix' p
  let Q : Matrix J J K := LinearMap.toMatrix' q
  let R : Matrix L L K := LinearMap.toMatrix' r
  have hP : P * P = P := by
    simpa only [P, LinearMap.toMatrix'_comp] using
      congrArg LinearMap.toMatrix' hp
  have hQ : Q * Q = Q := by
    simpa only [Q, LinearMap.toMatrix'_comp] using
      congrArg LinearMap.toMatrix' hq
  have hR : R * R = R := by
    simpa only [R, LinearMap.toMatrix'_comp] using
      congrArg LinearMap.toMatrix' hr
  have hleft :
      R * scalarizedExtMatrix X Y ell (extBiprodLeft xi) =
        scalarizedExtMatrix X Y ell (extBiprodLeft xi) * P := by
    simpa only [R, P, scalarizedExtLinearMap,
      LinearMap.toMatrix'_comp, LinearMap.toMatrix'_toLin'] using
      congrArg LinearMap.toMatrix' hrf
  have hright :
      R * scalarizedExtMatrix X' Y ell' (extBiprodRight xi) =
        scalarizedExtMatrix X' Y ell' (extBiprodRight xi) * Q := by
    simpa only [R, Q, scalarizedExtLinearMap,
      LinearMap.toMatrix'_comp, LinearMap.toMatrix'_toLin'] using
      congrArg LinearMap.toMatrix' hrg
  have hPend :
      scalarBiproductEnd X P ≫ scalarBiproductEnd X P =
        scalarBiproductEnd X P := by
    rw [scalarBiproductEnd_comp, hP]
  have hQend :
      scalarBiproductEnd X' Q ≫ scalarBiproductEnd X' Q =
        scalarBiproductEnd X' Q := by
    rw [scalarBiproductEnd_comp, hQ]
  have hRend :
      scalarBiproductEnd Y R ≫ scalarBiproductEnd Y R =
        scalarBiproductEnd Y R := by
    rw [scalarBiproductEnd_comp, hR]
  have hblock :
      blockDiagonalBiprodEnd
          (scalarBiproductEnd X P) (scalarBiproductEnd X' Q) ≫
        blockDiagonalBiprodEnd
          (scalarBiproductEnd X P) (scalarBiproductEnd X' Q) =
      blockDiagonalBiprodEnd
          (scalarBiproductEnd X P) (scalarBiproductEnd X' Q) := by
    rw [blockDiagonalBiprodEnd_comp, hPend, hQend]
  have hext :=
    ext_compatibility_of_two_scalarized_matrix_commute_generalTarget
      X X' Y ell hell ell' hell' xi P Q R hleft hright
  rcases hendpoint
      (scalarBiproductEnd Y R)
      (blockDiagonalBiprodEnd
        (scalarBiproductEnd X P) (scalarBiproductEnd X' Q))
      hRend hblock hext with hzero | hone
  · left
    have hRzero : R = 0 :=
      (scalarBiproductEnd_eq_zero_iff Y hY R).mp hzero.1
    have hblocks :=
      (blockDiagonalBiprodEnd_eq_zero_iff
        (scalarBiproductEnd X P) (scalarBiproductEnd X' Q)).mp hzero.2
    have hPzero : P = 0 :=
      (scalarBiproductEnd_eq_zero_iff X hX P).mp hblocks.1
    have hQzero : Q = 0 :=
      (scalarBiproductEnd_eq_zero_iff X' hX' Q).mp hblocks.2
    exact ⟨by
      apply LinearMap.toMatrix'.injective
      simpa only [P, map_zero] using hPzero, by
      apply LinearMap.toMatrix'.injective
      simpa only [Q, map_zero] using hQzero, by
      apply LinearMap.toMatrix'.injective
      simpa only [R, map_zero] using hRzero⟩
  · right
    have hRone : R = 1 :=
      (scalarBiproductEnd_eq_id_iff Y hY R).mp hone.1
    have hblocks :=
      (blockDiagonalBiprodEnd_eq_id_iff
        (scalarBiproductEnd X P) (scalarBiproductEnd X' Q)).mp hone.2
    have hPone : P = 1 :=
      (scalarBiproductEnd_eq_id_iff X hX P).mp hblocks.1
    have hQone : Q = 1 :=
      (scalarBiproductEnd_eq_id_iff X' hX' Q).mp hblocks.2
    exact ⟨by
      apply LinearMap.toMatrix'.injective
      simpa only [P, LinearMap.toMatrix'_id] using hPone, by
      apply LinearMap.toMatrix'.injective
      simpa only [Q, LinearMap.toMatrix'_id] using hQone, by
      apply LinearMap.toMatrix'.injective
      simpa only [R, LinearMap.toMatrix'_id] using hRone⟩

universe x

theorem shortExact_twoSource_scalarizedExtLinearMaps_isIdempotentIndecomposable_generalTarget
    {R₀ : Type x} [Ring R₀] [Algebra K R₀] [Small.{v} R₀]
    {I J L : Type} [Fintype I] [Fintype J] [Fintype L]
    [DecidableEq I] [DecidableEq J] [DecidableEq L]
    (X X' Y M : ModuleCat.{v} R₀)
    (hX : 𝟙 X ≠ 0) (hX' : 𝟙 X' ≠ 0) (hY : 𝟙 Y ≠ 0)
    (f : (⨁ fun _ : L ↦ Y) ⟶ M)
    (g : M ⟶ ((⨁ fun _ : I ↦ X) ⊞ (⨁ fun _ : J ↦ X')))
    (hfg : f ≫ g = 0)
    (hS : (ShortComplex.mk f g hfg).ShortExact)
    [IsNoetherian R₀ M] [IsArtinian R₀ M]
    (hM : QuotientSubmoduleEquidistribution.Foundation.IsIndecomposableModule R₀ M)
    (ell : Ext X Y 1 →ₗ[K] K) (hell : Function.Injective ell)
    (ell' : Ext X' Y 1 →ₗ[K] K) (hell' : Function.Injective ell') :
    LoewyTwoRankCore.IsTwoSourceIdempotentIndecomposable
      (scalarizedExtLinearMap X Y ell
        (extBiprodLeft hS.extClass))
      (scalarizedExtLinearMap X' Y ell'
        (extBiprodRight hS.extClass)) := by
  apply
    twoSource_scalarizedExtLinearMaps_isIdempotentIndecomposable_generalTarget
      X X' Y hX hX' hY ell hell ell' hell' hS.extClass
  intro a₁ a₃ ha₁ ha₃ hcompat
  exact endpoint_idempotents_trivial_of_extClass_compatibility
    hS hM a₁ a₃ ha₁ ha₃ hcompat

end QuotientSubmoduleEquidistribution.YonedaExtReflection

namespace QuotientSubmoduleEquidistribution.YonedaTwoSourceReduction

universe x

open LoewyTwoRankCore

variable {A : Type x} [Ring A]
  {iota : Type x} [IsNoetherianRing Aᵐᵒᵖ]
  (sigma :
    _root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.{x, x, x}
      Aᵐᵒᵖ iota)
  (K : Type x) [Field K]
  [Algebra K A] [FiniteDimensional K A]

open LoewyTwoRankCore

/-- Module-facing arbitrary-fork reduction.  If the top of an
indecomposable has two displayed isotypic simple blocks and its nonzero
semisimple radical has one displayed simple type, all three multiplicities
are at most one. -/
theorem forkMultiplicityBounds_of_threeTypeDecomposition
    (hnoParallel : NoParallelExtOne sigma K)
    {j s t r : iota}
    (hs : Simple (sigma.obj s))
    (ht : Simple (sigma.obj t))
    (hr : Simple (sigma.obj r))
    (k : ℕ)
    (eRadical :
      (Fin k → sigma.obj r) ≃ₗ[Aᵐᵒᵖ] sigma.moduleRadical j)
    (n m : ℕ)
    (eTop :
      ((Fin n → sigma.obj s) × (Fin m → sigma.obj t))
        ≃ₗ[Aᵐᵒᵖ] sigma.moduleTop j)
    (hk : 0 < k) :
    n ≤ 1 ∧ m ≤ 1 ∧ k ≤ 1 := by
  let leftIso :
      ((⨁ fun _ : Fin n ↦ (sigma.obj s).obj) :
          ModuleCat.{x} Aᵐᵒᵖ) ≅
        ModuleCat.of Aᵐᵒᵖ (Fin n → sigma.obj s) :=
    ModuleCat.biproductIsoPi
      (fun _ : Fin n ↦ (sigma.obj s).obj)
  let rightIso :
      ((⨁ fun _ : Fin m ↦ (sigma.obj t).obj) :
          ModuleCat.{x} Aᵐᵒᵖ) ≅
        ModuleCat.of Aᵐᵒᵖ (Fin m → sigma.obj t) :=
    ModuleCat.biproductIsoPi
      (fun _ : Fin m ↦ (sigma.obj t).obj)
  let topIso :
      (((⨁ fun _ : Fin n ↦ (sigma.obj s).obj) ⊞
          (⨁ fun _ : Fin m ↦ (sigma.obj t).obj)) :
          ModuleCat.{x} Aᵐᵒᵖ) ≅
        ModuleCat.of Aᵐᵒᵖ (sigma.moduleTop j) :=
    biprod.mapIso leftIso rightIso ≪≫
      ModuleCat.biprodIsoProd
        (ModuleCat.of Aᵐᵒᵖ (Fin n → sigma.obj s))
        (ModuleCat.of Aᵐᵒᵖ (Fin m → sigma.obj t)) ≪≫
      eTop.toModuleIso
  let radicalIso :
      ((⨁ fun _ : Fin k ↦ (sigma.obj r).obj) :
          ModuleCat.{x} Aᵐᵒᵖ) ≅
        ModuleCat.of Aᵐᵒᵖ (sigma.moduleRadical j) :=
    ModuleCat.biproductIsoPi
        (fun _ : Fin k ↦ (sigma.obj r).obj) ≪≫
      eRadical.toModuleIso
  let eRadical :
      ((⨁ fun _ : Fin k ↦ (sigma.obj r).obj) :
          ModuleCat.{x} Aᵐᵒᵖ) ≃ₗ[Aᵐᵒᵖ]
        sigma.moduleRadical j :=
    radicalIso.toLinearEquiv
  let eMiddle :
      (sigma.obj j) ≃ₗ[Aᵐᵒᵖ] (sigma.obj j) :=
    LinearEquiv.refl Aᵐᵒᵖ (sigma.obj j)
  let eTop :
      ((((⨁ fun _ : Fin n ↦ (sigma.obj s).obj) ⊞
          (⨁ fun _ : Fin m ↦ (sigma.obj t).obj)) :
          ModuleCat.{x} Aᵐᵒᵖ)) ≃ₗ[Aᵐᵒᵖ]
        sigma.moduleTop j :=
    topIso.toLinearEquiv
  let radicalInclusion :
      sigma.moduleRadical j →ₗ[Aᵐᵒᵖ] sigma.obj j :=
    (sigma.moduleRadical j).subtype
  let topProjection :
      sigma.obj j →ₗ[Aᵐᵒᵖ] sigma.moduleTop j :=
    (sigma.moduleRadical j).mkQ
  have hexact : Function.Exact radicalInclusion topProjection :=
    LinearMap.exact_subtype_mkQ (sigma.moduleRadical j)
  let SC : ShortComplex (ModuleCat.{x} Aᵐᵒᵖ) :=
    ModuleCat.shortComplexOfConj
      eRadical eMiddle eTop radicalInclusion topProjection
      hexact.linearMap_comp_eq_zero
  have hSC : SC.ShortExact :=
    ModuleCat.shortComplexOfConj_shortExact
      eRadical eMiddle eTop radicalInclusion topProjection
      hexact (sigma.moduleRadical j).subtype_injective
      (sigma.moduleRadical j).mkQ_surjective
  have hSC' :
      (ShortComplex.mk SC.f SC.g SC.zero).ShortExact := by
    simpa only [SC] using hSC
  letI : IsNoetherian Aᵐᵒᵖ (sigma.obj j) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength j)).1
  letI : IsArtinian Aᵐᵒᵖ (sigma.obj j) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength j)).2
  have hExtLeft := hnoParallel hs hr
  have hExtRight := hnoParallel ht hr
  letI : FiniteDimensional K
      (Ext (sigma.obj s).obj (sigma.obj r).obj 1) :=
    hExtLeft.1
  letI : FiniteDimensional K
      (Ext (sigma.obj t).obj (sigma.obj r).obj 1) :=
    hExtRight.1
  obtain ⟨ell, hell⟩ :=
    YonedaExtReflection.exists_injective_linearMap_to_field_of_finrank_le_one
      hExtLeft.2
  obtain ⟨ell', hell'⟩ :=
    YonedaExtReflection.exists_injective_linearMap_to_field_of_finrank_le_one
      hExtRight.2
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj s) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj s)).mp hs
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj t) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj t)).mp ht
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj r) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj r)).mp hr
  letI : Simple (sigma.obj s).obj :=
    (simple_iff_isSimpleModule' (sigma.obj s).obj).mpr inferInstance
  letI : Simple (sigma.obj t).obj :=
    (simple_iff_isSimpleModule' (sigma.obj t).obj).mpr inferInstance
  letI : Simple (sigma.obj r).obj :=
    (simple_iff_isSimpleModule' (sigma.obj r).obj).mpr inferInstance
  have hsNonzero : 𝟙 (sigma.obj s).obj ≠ 0 :=
    CategoryTheory.id_nonzero (sigma.obj s).obj
  have htNonzero : 𝟙 (sigma.obj t).obj ≠ 0 :=
    CategoryTheory.id_nonzero (sigma.obj t).obj
  have hrNonzero : 𝟙 (sigma.obj r).obj ≠ 0 :=
    CategoryTheory.id_nonzero (sigma.obj r).obj
  let leftArrow : (Fin n → K) →ₗ[K] (Fin k → K) :=
    YonedaExtReflection.scalarizedExtLinearMap
      (sigma.obj s).obj (sigma.obj r).obj ell
      (YonedaExtReflection.extBiprodLeft hSC'.extClass)
  let rightArrow : (Fin m → K) →ₗ[K] (Fin k → K) :=
    YonedaExtReflection.scalarizedExtLinearMap
      (sigma.obj t).obj (sigma.obj r).obj ell'
      (YonedaExtReflection.extBiprodRight hSC'.extClass)
  have harrows :
      IsTwoSourceIdempotentIndecomposable leftArrow rightArrow :=
    YonedaExtReflection.shortExact_twoSource_scalarizedExtLinearMaps_isIdempotentIndecomposable_generalTarget
      (sigma.obj s).obj (sigma.obj t).obj (sigma.obj r).obj
      (sigma.obj j).obj hsNonzero htNonzero hrNonzero
      SC.f SC.g SC.zero hSC' (sigma.indecomposable j)
      ell hell ell' hell'
  have htargetPos : 0 < Module.finrank K (Fin k → K) := by
    simpa using hk
  have hbounds :=
    twoSource_all_finrank_le_one htargetPos harrows
  simpa [leftArrow, rightArrow] using hbounds

end QuotientSubmoduleEquidistribution.YonedaTwoSourceReduction

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton

universe u v w

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {iota : Type v}
  (sigma : IndecomposableSkeleton.{u, v, w} R iota)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- Concrete Loewy data attached to an objectwise family-5 apex.  The
fields say that its radical is one simple type and its top is one copy of
each of two distinct simple quotient types. -/
structure ActualTwoTopApexData
    (x : sigma.TwoTopQuotientShapeIndex) where
  left : sigma.SimpleQuotient x.1
  right : sigma.SimpleQuotient x.1
  left_ne_right : left.index ≠ right.index
  radical : sigma.SimpleIndex
  radicalEquiv :
    sigma.obj radical.1 ≃ₗ[R] sigma.moduleRadical x.1
  topEquiv :
    (sigma.obj left.index × sigma.obj right.index) ≃ₗ[R]
      sigma.moduleTop x.1
  simpleQuotient_index_eq :
    ∀ Q : sigma.SimpleQuotient x.1,
      Q.index = left.index ∨ Q.index = right.index

/-- Every simple member of a two-top support is already a quotient of the
apex, so the collective closure of the support equals that of the singleton
apex. -/
theorem twoTopQuotientShapeSupport_subset_qClosure_singleton
    (x : sigma.TwoTopQuotientShapeIndex) :
    sigma.twoTopQuotientShapeSupport x ⊆
      sigma.qClosure ({x.1} : Set iota) := by
  intro i hi
  rcases (by
      simpa [twoTopQuotientShapeSupport] using hi) with rfl | hi
  · exact sigma.subset_qSet ({x.1} : Set iota) (by simp)
  · obtain ⟨Q, hQ⟩ := hi
    subst i
    let a : Fin 1 → iota := fun _ ↦ x.1
    let f :
        sigma.sumOver (FintypeCat.of (Fin 1)) a ⟶ sigma.obj Q.index :=
      (biproductUniqueIso fun t : Fin 1 ↦ sigma.obj (a t)).hom ≫ Q.map
    refine ⟨{
      index := FintypeCat.of (Fin 1)
      label := a
      mem := fun _ ↦ by simp [a]
      map := f
      epi := ?_ }⟩
    letI : Epi Q.map := Q.epi
    dsimp only [f]
    infer_instance

theorem qClosure_twoTopQuotientShapeSupport_eq_singleton
    (x : sigma.TwoTopQuotientShapeIndex) :
    sigma.qClosure (sigma.twoTopQuotientShapeSupport x) =
      sigma.qClosure ({x.1} : Set iota) := by
  apply Set.Subset.antisymm
  · intro i hi
    have hmono :=
      sigma.qClosure.monotone
        (sigma.twoTopQuotientShapeSupport_subset_qClosure_singleton x)
        hi
    simpa only [sigma.qClosure.idempotent] using hmono
  · apply sigma.qClosure.monotone
    intro i hi
    have hix : i = x.1 := by simpa using hi
    subst i
    simp [twoTopQuotientShapeSupport]

theorem inFac_singleton_apex_of_inFac_twoTopSupport
    (x : sigma.TwoTopQuotientShapeIndex)
    {j : iota}
    (hj : sigma.InFac (sigma.twoTopQuotientShapeSupport x)
      (sigma.obj j)) :
    sigma.InFac ({x.1} : Set iota) (sigma.obj j) := by
  have hj' : j ∈
      sigma.qClosure (sigma.twoTopQuotientShapeSupport x) := hj
  rw [sigma.qClosure_twoTopQuotientShapeSupport_eq_singleton x] at hj'
  exact hj'

/-- Any generated target has a presentation by a finite power of the apex
alone. -/
theorem exists_epi_power_apex_of_inFac_twoTopSupport
    (x : sigma.TwoTopQuotientShapeIndex)
    {j : iota}
    (hj : sigma.InFac (sigma.twoTopQuotientShapeSupport x)
      (sigma.obj j)) :
    ∃ (J : FintypeCat.{0})
        (f : sigma.sumOver J (fun _ : J ↦ x.1) ⟶ sigma.obj j),
      Epi f :=
  sigma.exists_epi_power_of_inFac_singleton
    (sigma.inFac_singleton_apex_of_inFac_twoTopSupport x hj)

/-- The radical of an actual apex is simple. -/
theorem ActualTwoTopApexData.radical_isSimple
    {x : sigma.TwoTopQuotientShapeIndex}
    (D : sigma.ActualTwoTopApexData x) :
    IsSimpleModule R (sigma.moduleRadical x.1) := by
  letI : IsSimpleModule R (sigma.obj D.radical.1) :=
    (simple_iff_isSimpleModule_fg _).mp D.radical.2
  exact IsSimpleModule.congr D.radicalEquiv.symm

/-- The radical of an actual apex is isotypic of its displayed radical
simple. -/
theorem ActualTwoTopApexData.radical_isIsotypic
    {x : sigma.TwoTopQuotientShapeIndex}
    (D : sigma.ActualTwoTopApexData x) :
    IsIsotypicOfType R
      (sigma.moduleRadical x.1) (sigma.obj D.radical.1) := by
  letI : IsSimpleModule R (sigma.moduleRadical x.1) :=
    D.radical_isSimple sigma
  intro L hL
  obtain ⟨e⟩ :=
    (IsIsotypicOfType.of_isSimpleModule R
      (sigma.moduleRadical x.1)) L
  exact ⟨e.trans D.radicalEquiv.symm⟩

/-- Radical information passes from a finite power of an actual apex to
every generated target: the target radical is semisimple and isotypic of
the one displayed radical type. -/
theorem radical_semisimple_and_isotypic_of_inFac_twoTopSupport
    {x : sigma.TwoTopQuotientShapeIndex}
    (D : sigma.ActualTwoTopApexData x)
    {j : iota}
    (hj : sigma.InFac (sigma.twoTopQuotientShapeSupport x)
      (sigma.obj j)) :
    IsSemisimpleModule R (sigma.moduleRadical j) ∧
      IsIsotypicOfType R
        (sigma.moduleRadical j) (sigma.obj D.radical.1) := by
  obtain ⟨J, f, hf⟩ :=
    sigma.exists_epi_power_apex_of_inFac_twoTopSupport x hj
  letI (t : J) : IsArtinian R (sigma.obj x.1) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength x.1)).2
  let e :
      sigma.sumOver J (fun _ : J ↦ x.1) ≅
        FGModuleCat.of R (∀ _ : J, sigma.obj x.1) :=
    biproductIsoPiFG _
  letI : IsArtinian R
      (sigma.sumOver J (fun _ : J ↦ x.1)) :=
    (LinearEquiv.isArtinian_iff
      (FGModuleCat.isoToLinearEquiv e)).mpr inferInstance
  letI : IsSimpleModule R
      (Module.jacobson R (sigma.obj x.1)) :=
    D.radical_isSimple sigma
  letI : IsSemisimpleModule R
      (Module.jacobson R (sigma.obj x.1)) := by
    infer_instance
  have hsourceSemisimple :
      IsSemisimpleModule R
        (Module.jacobson R
          (sigma.sumOver J (fun _ : J ↦ x.1))) :=
    QuotientSubmoduleEquidistribution.LengthTwoGabrielBridge.IndecomposableSkeleton.moduleRadical_sumOver_isSemisimple
      sigma J (fun _ : J ↦ x.1) (fun _ ↦ inferInstance)
  have hsourceIsotypic :
      IsIsotypicOfType R
        (Module.jacobson R
          (sigma.sumOver J (fun _ : J ↦ x.1)))
        (sigma.obj D.radical.1) :=
    QuotientSubmoduleEquidistribution.LengthTwoGabrielBridge.IndecomposableSkeleton.moduleRadical_sumOver_isIsotypicOfType
      sigma J (fun _ : J ↦ x.1) (fun _ ↦ D.radical_isIsotypic sigma)
  letI : Epi f := hf
  have hsurj : Function.Surjective f.hom.hom :=
    (fg_epi_iff_surjective f).mp inferInstance
  let radicalMap := radicalRestriction f.hom.hom
  have hradSurj : Function.Surjective radicalMap :=
    radicalRestriction_surjective f.hom.hom hsurj
  have htargetSemisimple :
      IsSemisimpleModule R (sigma.moduleRadical j) :=
    by
      letI : IsSemisimpleModule R
          (Module.jacobson R
            (sigma.sumOver J (fun _ : J ↦ x.1))) :=
        hsourceSemisimple
      exact IsSemisimpleModule.of_surjective radicalMap hradSurj
  exact ⟨htargetSemisimple,
    QuotientSubmoduleEquidistribution.LengthTwoGabrielBridge.IsIsotypicOfType.of_surjective_of_semisimple
      hsourceIsotypic radicalMap hradSurj⟩

/-- Every simple quotient of a generated target has one of the two apex
top types. -/
theorem simpleQuotient_index_eq_left_or_right_of_inFac_twoTopSupport
    {x : sigma.TwoTopQuotientShapeIndex}
    (D : sigma.ActualTwoTopApexData x)
    {j : iota}
    (hj : sigma.InFac (sigma.twoTopQuotientShapeSupport x)
      (sigma.obj j))
    (L : sigma.SimpleQuotient j) :
    L.index = D.left.index ∨ L.index = D.right.index := by
  classical
  obtain ⟨J, f, hf⟩ :=
    sigma.exists_epi_power_apex_of_inFac_twoTopSupport x hj
  let g :
      sigma.sumOver J (fun _ : J ↦ x.1) ⟶ sigma.obj L.index :=
    f ≫ L.map
  letI : Epi f := hf
  letI : Epi L.map := L.epi
  letI : Epi g := by dsimp only [g]; infer_instance
  letI : Simple (sigma.obj L.index) := L.simple
  have hg : g ≠ 0 := by
    intro hzero
    exact (Simple.not_isZero (sigma.obj L.index))
      (IsZero.of_epi_eq_zero g hzero)
  have hcomponent :
      ∃ t : J,
        biproduct.ι (fun _ : J ↦ sigma.obj x.1) t ≫ g ≠ 0 := by
    by_contra h
    push Not at h
    apply hg
    apply biproduct.hom_ext'
    intro t
    simpa using h t
  obtain ⟨t, ht⟩ := hcomponent
  let q : sigma.obj x.1 ⟶ sigma.obj L.index :=
    biproduct.ι (fun _ : J ↦ sigma.obj x.1) t ≫ g
  letI : Epi q := epi_of_nonzero_to_simple ht
  let Q : sigma.SimpleQuotient x.1 := {
    index := L.index
    simple := L.simple
    map := q
    epi := inferInstance }
  exact D.simpleQuotient_index_eq Q

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton

namespace QuotientSubmoduleEquidistribution.YonedaTwoSourceReduction

universe x

open LoewyTwoRankCore

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- Every nonsimple indecomposable generated by an actual family-5 apex has
exactly one copy of each displayed top simple and one copy of the displayed
radical simple.  In particular it again has composition length three.

This is not yet uniqueness of the middle extension: identifying the target
with the original apex is the final closure step. -/
theorem compositionLength_eq_three_of_nonsimple_inFac_actualTwoTopApex
    (K A : Type x)
    [Field K] [IsAlgClosed K]
    [Ring A] [Algebra K A] [FiniteDimensional K A] :
    letI : IsNoetherianRing Aᵐᵒᵖ :=
      QuotientSubmoduleEquidistribution.isNoetherianRing_op_of_finiteDimensional K A
    ∀ {iota : Type x} [Finite iota]
      (sigma :
        _root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.{x, x, x}
          Aᵐᵒᵖ iota)
      (apex : sigma.TwoTopQuotientShapeIndex)
      (_D : sigma.ActualTwoTopApexData apex)
      {j : iota},
      sigma.InFac (sigma.twoTopQuotientShapeSupport apex)
          (sigma.obj j) →
        (¬ IsSimpleModule Aᵐᵒᵖ (sigma.obj j)) →
          sigma.compositionLength j = 3 := by
  letI : IsNoetherianRing Aᵐᵒᵖ :=
    QuotientSubmoduleEquidistribution.isNoetherianRing_op_of_finiteDimensional K A
  intro iota _ sigma apex D j hj hjNonsimple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.left.index) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.left.index)).mp D.left.simple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.right.index) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.right.index)).mp D.right.simple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.radical.1) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.radical.1)).mp D.radical.2
  have hradData :=
    sigma.radical_semisimple_and_isotypic_of_inFac_twoTopSupport D hj
  letI : IsSemisimpleModule Aᵐᵒᵖ (sigma.moduleRadical j) :=
    hradData.1
  obtain ⟨k, eRadical, hkLength⟩ :=
    LoewyTwoRankCore.exists_isotypicMultiplicity hradData.2
  letI : IsArtinian Aᵐᵒᵖ (sigma.obj j) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength j)).2
  have hradNeBot : sigma.moduleRadical j ≠ ⊥ := by
    intro hbot
    letI : IsSemisimpleModule Aᵐᵒᵖ (sigma.obj j) := by
      rw [IsArtinian.isSemisimpleModule_iff_jacobson]
      exact hbot
    exact hjNonsimple
      (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.isSimpleModule_of_semisimple_of_indecomposable
        (sigma.indecomposable j))
  have hradPos :
      0 < Module.length Aᵐᵒᵖ (sigma.moduleRadical j) :=
    Module.length_pos_iff.mpr
      ((Submodule.nontrivial_iff_ne_bot).mpr hradNeBot)
  have hk : 0 < k := by
    by_contra hknot
    have hkzero : k = 0 := Nat.eq_zero_of_not_pos hknot
    have hlenzero :
        Module.length Aᵐᵒᵖ (sigma.moduleRadical j) = 0 := by
      rw [← hkLength, hkzero]
      rfl
    exact (ne_of_gt hradPos) hlenzero
  have hquotients :
      ∀ Q : sigma.SimpleQuotient j,
        Q.index = D.left.index ∨ Q.index = D.right.index :=
    fun Q ↦
      sigma.simpleQuotient_index_eq_left_or_right_of_inFac_twoTopSupport
        D hj Q
  letI : IsSemisimpleModule Aᵐᵒᵖ (sigma.moduleTop j) :=
    sigma.moduleTop_isSemisimple j
  obtain ⟨n, m, ⟨eTop⟩⟩ :=
    TwoTypeSemisimple.exists_twoTypeDecomposition
      (R := Aᵐᵒᵖ) (M := sigma.moduleTop j)
      (S := sigma.obj D.left.index)
      (T := sigma.obj D.right.index)
      (fun L hL ↦
        sigma.simpleTopSubmodule_type_eq_left_or_right
          hquotients L hL)
  have hnoParallel : NoParallelExtOne sigma K :=
    QuotientSubmoduleEquidistribution.NoParallelExtOne.noParallelExtOne_of_finiteDimensional_of_finiteSkeleton
      K A sigma
  have hbounds :=
    forkMultiplicityBounds_of_threeTypeDecomposition
      sigma K hnoParallel D.left.simple D.right.simple D.radical.2
      k eRadical.symm n m eTop.symm hk
  have hkOne : k = 1 := by omega
  have hradLength :
      Module.length Aᵐᵒᵖ (sigma.moduleRadical j) = 1 := by
    rw [← hkLength, hkOne]
    rfl
  have htopLengthFormula :
      Module.length Aᵐᵒᵖ (sigma.moduleTop j) =
        (n : ℕ∞) + (m : ℕ∞) := by
    rw [eTop.length_eq, Module.length_prod,
      Module.length_pi_of_fintype,
      Module.length_pi_of_fintype]
    simp [Module.length_eq_one]
  letI : Nontrivial (sigma.obj j) :=
    (sigma.indecomposable j).nontrivial
  have hJneTop : sigma.moduleRadical j ≠ ⊤ :=
    (Module.jacobson_lt_top Aᵐᵒᵖ (sigma.obj j)).ne
  letI : Nontrivial (sigma.moduleTop j) := by
    rw [← not_subsingleton_iff_nontrivial]
    intro hsub
    exact hJneTop (Submodule.Quotient.subsingleton_iff.mp hsub)
  have htopPos :
      0 < Module.length Aᵐᵒᵖ (sigma.moduleTop j) :=
    Module.length_pos_iff.mpr inferInstance
  have hnmPos : 0 < n + m := by
    by_contra hnot
    have hzero : n + m = 0 := Nat.eq_zero_of_not_pos hnot
    have hlenzero :
        Module.length Aᵐᵒᵖ (sigma.moduleTop j) = 0 := by
      rw [htopLengthFormula, ← ENat.coe_add, hzero]
      rfl
    exact (ne_of_gt htopPos) hlenzero
  have hnmNeOne : n + m ≠ 1 := by
    intro hnmOne
    have htopLengthOne :
        Module.length Aᵐᵒᵖ (sigma.moduleTop j) = 1 := by
      rw [htopLengthFormula, ← ENat.coe_add, hnmOne]
      rfl
    have htopSimple :
        IsSimpleModule Aᵐᵒᵖ (sigma.moduleTop j) :=
      Module.length_eq_one_iff.mp htopLengthOne
    have hjLengthModule :
        Module.length Aᵐᵒᵖ (sigma.obj j) = 2 := by
      rw [Module.length_eq_add_of_exact
        (sigma.moduleRadical j).subtype
        (sigma.moduleRadical j).mkQ
        (sigma.moduleRadical j).subtype_injective
        (sigma.moduleRadical j).mkQ_surjective
        (LinearMap.exact_subtype_mkQ (sigma.moduleRadical j)),
        hradLength, htopLengthOne]
      norm_num
    have hjLength : sigma.compositionLength j = 2 := by
      rw [← ENat.coe_inj, sigma.coe_compositionLength]
      exact hjLengthModule
    obtain ⟨J, f, hf⟩ :=
      sigma.exists_epi_power_apex_of_inFac_twoTopSupport apex hj
    letI : Epi f := hf
    obtain ⟨t, ht⟩ :=
      sigma.exists_epi_biproduct_component_of_simple_top
        J (fun _ : J ↦ apex.1) htopSimple f
    exact apex.2.2.2
      (biproduct.ι (fun _ : J ↦ sigma.obj apex.1) t ≫ f)
      ht hjLength
  have hnmTwo : n + m = 2 := by omega
  have htopLengthTwo :
      Module.length Aᵐᵒᵖ (sigma.moduleTop j) = 2 := by
    rw [htopLengthFormula, ← ENat.coe_add, hnmTwo]
    rfl
  have hjLengthModule :
      Module.length Aᵐᵒᵖ (sigma.obj j) = 3 := by
    rw [Module.length_eq_add_of_exact
      (sigma.moduleRadical j).subtype
      (sigma.moduleRadical j).mkQ
      (sigma.moduleRadical j).subtype_injective
      (sigma.moduleRadical j).mkQ_surjective
      (LinearMap.exact_subtype_mkQ (sigma.moduleRadical j)),
      hradLength, htopLengthTwo]
    norm_num
  rw [← ENat.coe_inj, sigma.coe_compositionLength]
  exact hjLengthModule

end QuotientSubmoduleEquidistribution.YonedaTwoSourceReduction
