import QuotientSubmoduleEquidistribution.RepresentationTheory.FamilyFiveCollectiveReduction

/-!
# Uniqueness and closure for the two-top family

This file completes the collective-closure argument beyond the preceding
family-five multiplicity reduction.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Abelian

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton

universe u v w

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {iota : Type v}
  (sigma : IndecomposableSkeleton.{u, v, w} R iota)

/-- The normalized radical and top identifications enjoyed by every
nonsimple target generated by an actual family-5 apex. -/
structure ActualTwoTopLoewyData
    {x : sigma.TwoTopQuotientShapeIndex}
    (D : sigma.ActualTwoTopApexData x) (j : iota) where
  radicalEquiv :
    sigma.obj D.radical.1 ≃ₗ[R] sigma.moduleRadical j
  topEquiv :
    (sigma.obj D.left.index × sigma.obj D.right.index) ≃ₗ[R]
      sigma.moduleTop j

def ActualTwoTopApexData.toLoewyData
    {x : sigma.TwoTopQuotientShapeIndex}
    (D : sigma.ActualTwoTopApexData x) :
    sigma.ActualTwoTopLoewyData D x.1 where
  radicalEquiv := D.radicalEquiv
  topEquiv := D.topEquiv

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- The radical sequence of a module with actual two-top Loewy data,
conjugated so that both endpoint objects are the same canonical Unit-indexed
biproducts for every such module. -/
def ActualTwoTopLoewyData.normalizedRadicalSequence
    {x : sigma.TwoTopQuotientShapeIndex}
    {D : sigma.ActualTwoTopApexData x} {j : iota}
    (L : sigma.ActualTwoTopLoewyData D j) :
    ShortComplex (ModuleCat.{w} R) := by
  let radicalIso :
      ((⨁ fun _ : Unit ↦ (sigma.obj D.radical.1).obj) :
          ModuleCat.{w} R) ≅
        ModuleCat.of R (sigma.moduleRadical j) :=
    ModuleCat.biproductIsoPi
        (fun _ : Unit ↦ (sigma.obj D.radical.1).obj) ≪≫
      (LinearEquiv.funUnique Unit R
        (sigma.obj D.radical.1)).toModuleIso ≪≫
      L.radicalEquiv.toModuleIso
  let leftIso :
      ((⨁ fun _ : Unit ↦ (sigma.obj D.left.index).obj) :
          ModuleCat.{w} R) ≅
        ModuleCat.of R (sigma.obj D.left.index) :=
    ModuleCat.biproductIsoPi
        (fun _ : Unit ↦ (sigma.obj D.left.index).obj) ≪≫
      (LinearEquiv.funUnique Unit R
        (sigma.obj D.left.index)).toModuleIso
  let rightIso :
      ((⨁ fun _ : Unit ↦ (sigma.obj D.right.index).obj) :
          ModuleCat.{w} R) ≅
        ModuleCat.of R (sigma.obj D.right.index) :=
    ModuleCat.biproductIsoPi
        (fun _ : Unit ↦ (sigma.obj D.right.index).obj) ≪≫
      (LinearEquiv.funUnique Unit R
        (sigma.obj D.right.index)).toModuleIso
  let topIso :
      (((⨁ fun _ : Unit ↦ (sigma.obj D.left.index).obj) ⊞
          (⨁ fun _ : Unit ↦ (sigma.obj D.right.index).obj)) :
          ModuleCat.{w} R) ≅
        ModuleCat.of R (sigma.moduleTop j) :=
    biprod.mapIso leftIso rightIso ≪≫
      ModuleCat.biprodIsoProd
        (ModuleCat.of R (sigma.obj D.left.index))
        (ModuleCat.of R (sigma.obj D.right.index)) ≪≫
      L.topEquiv.toModuleIso
  let eMiddle :
      (sigma.obj j) ≃ₗ[R] (sigma.obj j) :=
    LinearEquiv.refl R (sigma.obj j)
  let radicalInclusion :
      sigma.moduleRadical j →ₗ[R] sigma.obj j :=
    (sigma.moduleRadical j).subtype
  let topProjection :
      sigma.obj j →ₗ[R] sigma.moduleTop j :=
    (sigma.moduleRadical j).mkQ
  have hexact : Function.Exact radicalInclusion topProjection :=
    LinearMap.exact_subtype_mkQ (sigma.moduleRadical j)
  exact ModuleCat.shortComplexOfConj
    radicalIso.toLinearEquiv eMiddle topIso.toLinearEquiv
    radicalInclusion topProjection
    hexact.linearMap_comp_eq_zero

theorem ActualTwoTopLoewyData.normalizedRadicalSequence_shortExact
    {x : sigma.TwoTopQuotientShapeIndex}
    {D : sigma.ActualTwoTopApexData x} {j : iota}
    (L : sigma.ActualTwoTopLoewyData D j) :
    L.normalizedRadicalSequence sigma |>.ShortExact := by
  let radicalIso :
      ((⨁ fun _ : Unit ↦ (sigma.obj D.radical.1).obj) :
          ModuleCat.{w} R) ≅
        ModuleCat.of R (sigma.moduleRadical j) :=
    ModuleCat.biproductIsoPi
        (fun _ : Unit ↦ (sigma.obj D.radical.1).obj) ≪≫
      (LinearEquiv.funUnique Unit R
        (sigma.obj D.radical.1)).toModuleIso ≪≫
      L.radicalEquiv.toModuleIso
  let leftIso :
      ((⨁ fun _ : Unit ↦ (sigma.obj D.left.index).obj) :
          ModuleCat.{w} R) ≅
        ModuleCat.of R (sigma.obj D.left.index) :=
    ModuleCat.biproductIsoPi
        (fun _ : Unit ↦ (sigma.obj D.left.index).obj) ≪≫
      (LinearEquiv.funUnique Unit R
        (sigma.obj D.left.index)).toModuleIso
  let rightIso :
      ((⨁ fun _ : Unit ↦ (sigma.obj D.right.index).obj) :
          ModuleCat.{w} R) ≅
        ModuleCat.of R (sigma.obj D.right.index) :=
    ModuleCat.biproductIsoPi
        (fun _ : Unit ↦ (sigma.obj D.right.index).obj) ≪≫
      (LinearEquiv.funUnique Unit R
        (sigma.obj D.right.index)).toModuleIso
  let topIso :
      (((⨁ fun _ : Unit ↦ (sigma.obj D.left.index).obj) ⊞
          (⨁ fun _ : Unit ↦ (sigma.obj D.right.index).obj)) :
          ModuleCat.{w} R) ≅
        ModuleCat.of R (sigma.moduleTop j) :=
    biprod.mapIso leftIso rightIso ≪≫
      ModuleCat.biprodIsoProd
        (ModuleCat.of R (sigma.obj D.left.index))
        (ModuleCat.of R (sigma.obj D.right.index)) ≪≫
      L.topEquiv.toModuleIso
  let eMiddle :
      (sigma.obj j) ≃ₗ[R] (sigma.obj j) :=
    LinearEquiv.refl R (sigma.obj j)
  let radicalInclusion :
      sigma.moduleRadical j →ₗ[R] sigma.obj j :=
    (sigma.moduleRadical j).subtype
  let topProjection :
      sigma.obj j →ₗ[R] sigma.moduleTop j :=
    (sigma.moduleRadical j).mkQ
  have hexact : Function.Exact radicalInclusion topProjection :=
    LinearMap.exact_subtype_mkQ (sigma.moduleRadical j)
  apply ModuleCat.shortComplexOfConj_shortExact
    radicalIso.toLinearEquiv eMiddle topIso.toLinearEquiv
    radicalInclusion topProjection hexact
    (sigma.moduleRadical j).subtype_injective
    (sigma.moduleRadical j).mkQ_surjective

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton

namespace QuotientSubmoduleEquidistribution.YonedaTwoSourceReduction

universe x

open LoewyTwoRankCore

/-- A nonsimple indecomposable generated by an actual family-5 apex has the
same one-simple radical and the same two distinct one-copy top blocks as the
apex. -/
theorem exists_actualTwoTopLoewyData_of_nonsimple_inFac
    (K A : Type x)
    [Field K] [IsAlgClosed K]
    [Ring A] [Algebra K A] [FiniteDimensional K A] :
    letI : IsNoetherianRing Aᵐᵒᵖ :=
      QuotientSubmoduleEquidistribution.isNoetherianRing_op_of_finiteDimensional K A
    ∀ {iota : Type x} [Finite iota]
      (sigma :
        _root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.{x, x, x}
          Aᵐᵒᵖ iota)
      (apex : sigma.TwoTopQuotientShapeIndex)
      (D : sigma.ActualTwoTopApexData apex)
      {j : iota},
      sigma.InFac (sigma.twoTopQuotientShapeSupport apex)
          (sigma.obj j) →
        (¬ IsSimpleModule Aᵐᵒᵖ (sigma.obj j)) →
          Nonempty (sigma.ActualTwoTopLoewyData D j) := by
  letI : IsNoetherianRing Aᵐᵒᵖ :=
    QuotientSubmoduleEquidistribution.isNoetherianRing_op_of_finiteDimensional K A
  intro iota _ sigma apex D j hj hjNonsimple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.left.index) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.left.index)).mp D.left.simple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.right.index) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.right.index)).mp D.right.simple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.radical.1) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.radical.1)).mp D.radical.2
  have hradData :=
    sigma.radical_semisimple_and_isotypic_of_inFac_twoTopSupport D hj
  letI : IsSemisimpleModule Aᵐᵒᵖ (sigma.moduleRadical j) :=
    hradData.1
  obtain ⟨k, eRadical, hkLength⟩ :=
    LoewyTwoRankCore.exists_isotypicMultiplicity hradData.2
  letI : IsArtinian Aᵐᵒᵖ (sigma.obj j) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength j)).2
  have hradNeBot : sigma.moduleRadical j ≠ ⊥ := by
    intro hbot
    letI : IsSemisimpleModule Aᵐᵒᵖ (sigma.obj j) := by
      rw [IsArtinian.isSemisimpleModule_iff_jacobson]
      exact hbot
    exact hjNonsimple
      (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.isSimpleModule_of_semisimple_of_indecomposable
        (sigma.indecomposable j))
  have hradPos :
      0 < Module.length Aᵐᵒᵖ (sigma.moduleRadical j) :=
    Module.length_pos_iff.mpr
      ((Submodule.nontrivial_iff_ne_bot).mpr hradNeBot)
  have hk : 0 < k := by
    by_contra hknot
    have hkzero : k = 0 := Nat.eq_zero_of_not_pos hknot
    have hlenzero :
        Module.length Aᵐᵒᵖ (sigma.moduleRadical j) = 0 := by
      rw [← hkLength, hkzero]
      rfl
    exact (ne_of_gt hradPos) hlenzero
  have hquotients :
      ∀ Q : sigma.SimpleQuotient j,
        Q.index = D.left.index ∨ Q.index = D.right.index :=
    fun Q ↦
      sigma.simpleQuotient_index_eq_left_or_right_of_inFac_twoTopSupport
        D hj Q
  letI : IsSemisimpleModule Aᵐᵒᵖ (sigma.moduleTop j) :=
    sigma.moduleTop_isSemisimple j
  obtain ⟨n, m, ⟨eTop⟩⟩ :=
    TwoTypeSemisimple.exists_twoTypeDecomposition
      (R := Aᵐᵒᵖ) (M := sigma.moduleTop j)
      (S := sigma.obj D.left.index)
      (T := sigma.obj D.right.index)
      (fun L hL ↦
        sigma.simpleTopSubmodule_type_eq_left_or_right
          hquotients L hL)
  have hnoParallel : NoParallelExtOne sigma K :=
    QuotientSubmoduleEquidistribution.NoParallelExtOne.noParallelExtOne_of_finiteDimensional_of_finiteSkeleton
      K A sigma
  have hbounds :=
    forkMultiplicityBounds_of_threeTypeDecomposition
      sigma K hnoParallel D.left.simple D.right.simple D.radical.2
      k eRadical.symm n m eTop.symm hk
  have hkOne : k = 1 := by omega
  have hradLength :
      Module.length Aᵐᵒᵖ (sigma.moduleRadical j) = 1 := by
    rw [← hkLength, hkOne]
    rfl
  have hjLength : sigma.compositionLength j = 3 :=
    compositionLength_eq_three_of_nonsimple_inFac_actualTwoTopApex
      K A sigma apex D hj hjNonsimple
  have hjLengthModule :
      Module.length Aᵐᵒᵖ (sigma.obj j) = 3 := by
    rw [← sigma.coe_compositionLength, hjLength]
    rfl
  have htopLengthFormula :
      Module.length Aᵐᵒᵖ (sigma.moduleTop j) =
        (n : ℕ∞) + (m : ℕ∞) := by
    rw [eTop.length_eq, Module.length_prod,
      Module.length_pi_of_fintype,
      Module.length_pi_of_fintype]
    simp [Module.length_eq_one]
  have hnmTwo : n + m = 2 := by
    have hadd := Module.length_eq_add_of_exact
      (sigma.moduleRadical j).subtype
      (sigma.moduleRadical j).mkQ
      (sigma.moduleRadical j).subtype_injective
      (sigma.moduleRadical j).mkQ_surjective
      (LinearMap.exact_subtype_mkQ (sigma.moduleRadical j))
    have hcoe : (3 : ℕ∞) = ((1 + (n + m) : ℕ) : ℕ∞) := by
      calc
        (3 : ℕ∞) =
            Module.length Aᵐᵒᵖ (sigma.obj j) :=
          hjLengthModule.symm
        _ = Module.length Aᵐᵒᵖ (sigma.moduleRadical j) +
              Module.length Aᵐᵒᵖ (sigma.moduleTop j) := hadd
        _ = (1 : ℕ∞) + ((n : ℕ∞) + (m : ℕ∞)) := by
          rw [hradLength, htopLengthFormula]
        _ = ((1 + (n + m) : ℕ) : ℕ∞) := by
          norm_num
    have hnat : 3 = 1 + (n + m) := ENat.coe_inj.mp hcoe
    omega
  have hnOne : n = 1 := by omega
  have hmOne : m = 1 := by omega
  subst k
  subst n
  subst m
  let radicalEquiv :
      sigma.obj D.radical.1 ≃ₗ[Aᵐᵒᵖ] sigma.moduleRadical j :=
    (LinearEquiv.funUnique (Fin 1) Aᵐᵒᵖ
      (sigma.obj D.radical.1)).symm.trans eRadical.symm
  let topEquiv :
      (sigma.obj D.left.index × sigma.obj D.right.index) ≃ₗ[Aᵐᵒᵖ]
        sigma.moduleTop j :=
    ((LinearEquiv.funUnique (Fin 1) Aᵐᵒᵖ
        (sigma.obj D.left.index)).symm.prodCongr
      (LinearEquiv.funUnique (Fin 1) Aᵐᵒᵖ
        (sigma.obj D.right.index)).symm).trans eTop.symm
  exact ⟨⟨radicalEquiv, topEquiv⟩⟩

end QuotientSubmoduleEquidistribution.YonedaTwoSourceReduction
namespace QuotientSubmoduleEquidistribution.YonedaExtReflection

universe w v u

variable {K : Type u} [Field K]
  {C : Type v} [Category.{w} C] [Abelian C] [Linear K C]
  [HasFiniteBiproducts C] [HasExt C]

/-- Two heterogeneous extensions are equal when both of their injectively
scalarized blocks are equal. -/
theorem ext_eq_of_two_scalarizedExtMatrices_eq
    {I J L : Type} [Fintype I] [Fintype J] [Fintype L]
    (X X' Y : C)
    (ell : Ext X Y 1 →ₗ[K] K) (hell : Function.Injective ell)
    (ell' : Ext X' Y 1 →ₗ[K] K) (hell' : Function.Injective ell')
    {xi eta :
      Ext
        ((⨁ fun _ : I ↦ X) ⊞ (⨁ fun _ : J ↦ X'))
        (⨁ fun _ : L ↦ Y) 1}
    (hleft :
      scalarizedExtMatrix X Y ell (extBiprodLeft xi) =
        scalarizedExtMatrix X Y ell (extBiprodLeft eta))
    (hright :
      scalarizedExtMatrix X' Y ell' (extBiprodRight xi) =
        scalarizedExtMatrix X' Y ell' (extBiprodRight eta)) :
    xi = eta := by
  apply ext_eq_of_extBiprodLeft_right_eq
  · apply ext_eq_of_biproductExtComponent_eq X Y
    intro i l
    apply hell
    exact congrFun (congrFun hleft l) i
  · apply ext_eq_of_biproductExtComponent_eq X' Y
    intro j l
    apply hell'
    exact congrFun (congrFun hright l) j

/-- Precomposing the top of a heterogeneous extension by a block-diagonal
scalar matrix right-multiplies its left scalarized block. -/
theorem scalarizedExtMatrix_extBiprodLeft_pre_blockDiagonal
    {I J L : Type} [Fintype I] [Fintype J] [Fintype L]
    (X X' Y : C) (ell : Ext X Y 1 →ₗ[K] K)
    (xi :
      Ext
        ((⨁ fun _ : I ↦ X) ⊞ (⨁ fun _ : J ↦ X'))
        (⨁ fun _ : L ↦ Y) 1)
    (P : Matrix I I K) (Q : Matrix J J K) :
    scalarizedExtMatrix X Y ell
        (extBiprodLeft
          ((Ext.mk₀
            (blockDiagonalBiprodEnd
              (scalarBiproductEnd X P)
              (scalarBiproductEnd X' Q))).comp
            xi (zero_add 1))) =
      scalarizedExtMatrix X Y ell (extBiprodLeft xi) * P := by
  classical
  have hrestrict :
      extBiprodLeft
          ((Ext.mk₀
            (blockDiagonalBiprodEnd
              (scalarBiproductEnd X P)
              (scalarBiproductEnd X' Q))).comp
            xi (zero_add 1)) =
        (Ext.mk₀ (scalarBiproductEnd X P)).comp
          (extBiprodLeft xi) (zero_add 1) := by
    unfold extBiprodLeft
    rw [← Ext.comp_assoc_of_second_deg_zero, Ext.mk₀_comp_mk₀]
    simp [blockDiagonalBiprodEnd]
  rw [hrestrict]
  ext l i
  change
    ell
        (biproductExtComponent X Y
          ((Ext.mk₀ (scalarBiproductEnd X P)).comp
            (extBiprodLeft xi) (zero_add 1)) i l) =
      ∑ k,
        ell (biproductExtComponent X Y (extBiprodLeft xi) k l) *
          P k i
  rw [biproductExtComponent_pre_scalarBiproductEnd]
  simp only [map_sum, map_smul]
  apply Finset.sum_congr rfl
  intro k hk
  exact mul_comm _ _

/-- The corresponding right-block formula. -/
theorem scalarizedExtMatrix_extBiprodRight_pre_blockDiagonal
    {I J L : Type} [Fintype I] [Fintype J] [Fintype L]
    (X X' Y : C) (ell' : Ext X' Y 1 →ₗ[K] K)
    (xi :
      Ext
        ((⨁ fun _ : I ↦ X) ⊞ (⨁ fun _ : J ↦ X'))
        (⨁ fun _ : L ↦ Y) 1)
    (P : Matrix I I K) (Q : Matrix J J K) :
    scalarizedExtMatrix X' Y ell'
        (extBiprodRight
          ((Ext.mk₀
            (blockDiagonalBiprodEnd
              (scalarBiproductEnd X P)
              (scalarBiproductEnd X' Q))).comp
            xi (zero_add 1))) =
      scalarizedExtMatrix X' Y ell' (extBiprodRight xi) * Q := by
  classical
  have hrestrict :
      extBiprodRight
          ((Ext.mk₀
            (blockDiagonalBiprodEnd
              (scalarBiproductEnd X P)
              (scalarBiproductEnd X' Q))).comp
            xi (zero_add 1)) =
        (Ext.mk₀ (scalarBiproductEnd X' Q)).comp
          (extBiprodRight xi) (zero_add 1) := by
    unfold extBiprodRight
    rw [← Ext.comp_assoc_of_second_deg_zero, Ext.mk₀_comp_mk₀]
    simp [blockDiagonalBiprodEnd]
  rw [hrestrict]
  ext l j
  change
    ell'
        (biproductExtComponent X' Y
          ((Ext.mk₀ (scalarBiproductEnd X' Q)).comp
            (extBiprodRight xi) (zero_add 1)) j l) =
      ∑ k,
        ell' (biproductExtComponent X' Y (extBiprodRight xi) k l) *
          Q k j
  rw [biproductExtComponent_pre_scalarBiproductEnd]
  simp only [map_sum, map_smul]
  apply Finset.sum_congr rfl
  intro k hk
  exact mul_comm _ _

end QuotientSubmoduleEquidistribution.YonedaExtReflection
namespace QuotientSubmoduleEquidistribution.YonedaExtReflection

universe x

open LoewyTwoRankCore

private theorem unitFork_left_ne_zero
    {K : Type*} [Field K]
    {V W Z : Type*}
    [AddCommGroup V] [Module K V]
    [AddCommGroup W] [Module K W]
    [AddCommGroup Z] [Module K Z]
    [Nontrivial V] [Nontrivial Z]
    {f : V →ₗ[K] Z} {g : W →ₗ[K] Z}
    (hfg : IsTwoSourceIdempotentIndecomposable f g) :
    f ≠ 0 := by
  intro hf
  have hcommLeft :
      (0 : Z →ₗ[K] Z).comp f = f.comp LinearMap.id := by
    simp [hf]
  have hcommRight :
      (0 : Z →ₗ[K] Z).comp g =
        g.comp (0 : W →ₗ[K] W) := by
    ext
    simp
  rcases hfg LinearMap.id 0 0 (by ext; simp) (by ext; simp)
      (by ext; simp) hcommLeft hcommRight with hzero | hone
  · have hid : (LinearMap.id : V →ₗ[K] V) ≠ 0 := by
      intro h
      obtain ⟨v, hv⟩ := exists_ne (0 : V)
      have hv' := LinearMap.congr_fun h v
      exact hv (by simpa using hv')
    exact hid hzero.1
  · have hid : (LinearMap.id : Z →ₗ[K] Z) ≠ 0 := by
      intro h
      obtain ⟨z, hz⟩ := exists_ne (0 : Z)
      have hz' := LinearMap.congr_fun h z
      exact hz (by simpa using hz')
    exact hid hone.2.2.symm

private theorem unitFork_right_ne_zero
    {K : Type*} [Field K]
    {V W Z : Type*}
    [AddCommGroup V] [Module K V]
    [AddCommGroup W] [Module K W]
    [AddCommGroup Z] [Module K Z]
    [Nontrivial W] [Nontrivial Z]
    {f : V →ₗ[K] Z} {g : W →ₗ[K] Z}
    (hfg : IsTwoSourceIdempotentIndecomposable f g) :
    g ≠ 0 := by
  intro hg
  have hcommLeft :
      (0 : Z →ₗ[K] Z).comp f =
        f.comp (0 : V →ₗ[K] V) := by
    ext
    simp
  have hcommRight :
      (0 : Z →ₗ[K] Z).comp g = g.comp LinearMap.id := by
    simp [hg]
  rcases hfg 0 LinearMap.id 0 (by ext; simp) (by ext; simp)
      (by ext; simp) hcommLeft hcommRight with hzero | hone
  · have hid : (LinearMap.id : W →ₗ[K] W) ≠ 0 := by
      intro h
      obtain ⟨w, hw⟩ := exists_ne (0 : W)
      have hw' := LinearMap.congr_fun h w
      exact hw (by simpa using hw')
    exact hid hzero.2.1
  · have hid : (LinearMap.id : Z →ₗ[K] Z) ≠ 0 := by
      intro h
      obtain ⟨z, hz⟩ := exists_ne (0 : Z)
      have hz' := LinearMap.congr_fun h z
      exact hz (by simpa using hz')
    exact hid hone.2.2.symm

/-- Two normalized radical sequences with one copy at each vertex of a
nonzero two-source fork have isomorphic middle terms.  The proof compares
their two nonzero one-dimensional Ext rows and lifts the resulting endpoint
automorphisms. -/
theorem nonempty_middle_iso_of_unit_twoSource_shortExact
    (K R₀ : Type x) [Field K] [Ring R₀] [Algebra K R₀]
    (X X' Y M N : ModuleCat.{x} R₀)
    (hX : 𝟙 X ≠ 0) (hX' : 𝟙 X' ≠ 0) (hY : 𝟙 Y ≠ 0)
    (fM : (⨁ fun _ : Unit ↦ Y) ⟶ M)
    (gM : M ⟶ ((⨁ fun _ : Unit ↦ X) ⊞
      (⨁ fun _ : Unit ↦ X')))
    (hfgM : fM ≫ gM = 0)
    (hMseq : (ShortComplex.mk fM gM hfgM).ShortExact)
    (fN : (⨁ fun _ : Unit ↦ Y) ⟶ N)
    (gN : N ⟶ ((⨁ fun _ : Unit ↦ X) ⊞
      (⨁ fun _ : Unit ↦ X')))
    (hfgN : fN ≫ gN = 0)
    (hNseq : (ShortComplex.mk fN gN hfgN).ShortExact)
    [IsNoetherian R₀ M] [IsArtinian R₀ M]
    [IsNoetherian R₀ N] [IsArtinian R₀ N]
    (hM : QuotientSubmoduleEquidistribution.Foundation.IsIndecomposableModule R₀ M)
    (hN : QuotientSubmoduleEquidistribution.Foundation.IsIndecomposableModule R₀ N)
    (ell : Ext X Y 1 →ₗ[K] K) (hell : Function.Injective ell)
    (ell' : Ext X' Y 1 →ₗ[K] K) (hell' : Function.Injective ell') :
    Nonempty (M ≅ N) := by
  classical
  let SM := ShortComplex.mk fM gM hfgM
  let SN := ShortComplex.mk fN gN hfgN
  have hforkM :
      IsTwoSourceIdempotentIndecomposable
        (scalarizedExtLinearMap X Y ell
          (extBiprodLeft hMseq.extClass))
        (scalarizedExtLinearMap X' Y ell'
          (extBiprodRight hMseq.extClass)) :=
    shortExact_twoSource_scalarizedExtLinearMaps_isIdempotentIndecomposable
      X X' Y M hX hX' hY fM gM hfgM hMseq hM
      ell hell ell' hell'
  have hforkN :
      IsTwoSourceIdempotentIndecomposable
        (scalarizedExtLinearMap X Y ell
          (extBiprodLeft hNseq.extClass))
        (scalarizedExtLinearMap X' Y ell'
          (extBiprodRight hNseq.extClass)) :=
    shortExact_twoSource_scalarizedExtLinearMaps_isIdempotentIndecomposable
      X X' Y N hX hX' hY fN gN hfgN hNseq hN
      ell hell ell' hell'
  let AM : Matrix Unit Unit K :=
    scalarizedExtMatrix X Y ell (extBiprodLeft hMseq.extClass)
  let BM : Matrix Unit Unit K :=
    scalarizedExtMatrix X' Y ell' (extBiprodRight hMseq.extClass)
  let AN : Matrix Unit Unit K :=
    scalarizedExtMatrix X Y ell (extBiprodLeft hNseq.extClass)
  let BN : Matrix Unit Unit K :=
    scalarizedExtMatrix X' Y ell' (extBiprodRight hNseq.extClass)
  have hAM : AM () () ≠ 0 := by
    intro hzero
    apply unitFork_left_ne_zero hforkM
    have hmatrix : AM = 0 := by
      ext l i
      rcases l with ⟨⟩
      rcases i with ⟨⟩
      simpa using hzero
    simp [scalarizedExtLinearMap, AM, hmatrix]
  have hBM : BM () () ≠ 0 := by
    intro hzero
    apply unitFork_right_ne_zero hforkM
    have hmatrix : BM = 0 := by
      ext l i
      rcases l with ⟨⟩
      rcases i with ⟨⟩
      simpa using hzero
    simp [scalarizedExtLinearMap, BM, hmatrix]
  have hAN : AN () () ≠ 0 := by
    intro hzero
    apply unitFork_left_ne_zero hforkN
    have hmatrix : AN = 0 := by
      ext l i
      rcases l with ⟨⟩
      rcases i with ⟨⟩
      simpa using hzero
    simp [scalarizedExtLinearMap, AN, hmatrix]
  have hBN : BN () () ≠ 0 := by
    intro hzero
    apply unitFork_right_ne_zero hforkN
    have hmatrix : BN = 0 := by
      ext l i
      rcases l with ⟨⟩
      rcases i with ⟨⟩
      simpa using hzero
    simp [scalarizedExtLinearMap, BN, hmatrix]
  let P : Matrix Unit Unit K := fun _ _ ↦ AM () () / AN () ()
  let Q : Matrix Unit Unit K := fun _ _ ↦ BM () () / BN () ()
  let Pinv : Matrix Unit Unit K := fun _ _ ↦ AN () () / AM () ()
  let Qinv : Matrix Unit Unit K := fun _ _ ↦ BN () () / BM () ()
  have hANP : AN * P = AM := by
    funext l i
    rcases l with ⟨⟩
    rcases i with ⟨⟩
    simpa [Matrix.mul_apply, P] using
      (mul_div_cancel₀ (AM () ()) hAN)
  have hBNQ : BN * Q = BM := by
    funext l i
    rcases l with ⟨⟩
    rcases i with ⟨⟩
    simpa [Matrix.mul_apply, Q] using
      (mul_div_cancel₀ (BM () ()) hBN)
  have hPinvP : Pinv * P = 1 := by
    ext l i
    rcases l with ⟨⟩
    rcases i with ⟨⟩
    simp [Matrix.mul_apply, Pinv, P, hAM, hAN]
  have hPPinv : P * Pinv = 1 := by
    ext l i
    rcases l with ⟨⟩
    rcases i with ⟨⟩
    simp [Matrix.mul_apply, Pinv, P, hAM, hAN]
  have hQinvQ : Qinv * Q = 1 := by
    ext l i
    rcases l with ⟨⟩
    rcases i with ⟨⟩
    simp [Matrix.mul_apply, Qinv, Q, hBM, hBN]
  have hQQinv : Q * Qinv = 1 := by
    ext l i
    rcases l with ⟨⟩
    rcases i with ⟨⟩
    simp [Matrix.mul_apply, Qinv, Q, hBM, hBN]
  let pEnd : (⨁ fun _ : Unit ↦ X) ⟶ (⨁ fun _ : Unit ↦ X) :=
    scalarBiproductEnd X P
  let pInv : (⨁ fun _ : Unit ↦ X) ⟶ (⨁ fun _ : Unit ↦ X) :=
    scalarBiproductEnd X Pinv
  let qEnd : (⨁ fun _ : Unit ↦ X') ⟶ (⨁ fun _ : Unit ↦ X') :=
    scalarBiproductEnd X' Q
  let qInv : (⨁ fun _ : Unit ↦ X') ⟶ (⨁ fun _ : Unit ↦ X') :=
    scalarBiproductEnd X' Qinv
  let pIso : (⨁ fun _ : Unit ↦ X) ≅ (⨁ fun _ : Unit ↦ X) := {
    hom := pEnd
    inv := pInv
    hom_inv_id := by
      dsimp only [pEnd, pInv]
      rw [scalarBiproductEnd_comp, hPinvP,
        scalarBiproductEnd_one]
    inv_hom_id := by
      dsimp only [pEnd, pInv]
      rw [scalarBiproductEnd_comp, hPPinv,
        scalarBiproductEnd_one] }
  let qIso : (⨁ fun _ : Unit ↦ X') ≅ (⨁ fun _ : Unit ↦ X') := {
    hom := qEnd
    inv := qInv
    hom_inv_id := by
      dsimp only [qEnd, qInv]
      rw [scalarBiproductEnd_comp, hQinvQ,
        scalarBiproductEnd_one]
    inv_hom_id := by
      dsimp only [qEnd, qInv]
      rw [scalarBiproductEnd_comp, hQQinv,
        scalarBiproductEnd_one] }
  let topIso := biprod.mapIso pIso qIso
  have htopHom :
      topIso.hom =
        blockDiagonalBiprodEnd
          (scalarBiproductEnd X P)
          (scalarBiproductEnd X' Q) := by
    rfl
  have hext :
      hMseq.extClass =
        (Ext.mk₀ topIso.hom).comp hNseq.extClass (zero_add 1) := by
    apply ext_eq_of_two_scalarizedExtMatrices_eq
      X X' Y ell hell ell' hell'
    · rw [htopHom,
        scalarizedExtMatrix_extBiprodLeft_pre_blockDiagonal]
      exact hANP.symm
    · rw [htopHom,
        scalarizedExtMatrix_extBiprodRight_pre_blockDiagonal]
      exact hBNQ.symm
  have hcompat :
      hMseq.extClass.comp (Ext.mk₀ (𝟙 _)) (add_zero 1) =
        (Ext.mk₀ topIso.hom).comp hNseq.extClass (zero_add 1) := by
    simpa using hext
  obtain ⟨a₂, ha₁₂, ha₂₃⟩ :=
    exists_middle_morphism_of_extClass_compatibility
      hMseq hNseq (𝟙 _) topIso.hom hcompat
  let phi : SM ⟶ SN := {
    τ₁ := 𝟙 _
    τ₂ := a₂
    τ₃ := topIso.hom
    comm₁₂ := ha₁₂
    comm₂₃ := ha₂₃ }
  haveI : IsIso phi.τ₁ := by
    dsimp [phi]
    infer_instance
  haveI : IsIso phi.τ₃ := by
    dsimp [phi]
    infer_instance
  haveI : IsIso phi.τ₂ :=
    ShortComplex.isIso₂_of_shortExact_of_isIso₁₃
      phi hMseq hNseq
  exact ⟨asIso a₂⟩

end QuotientSubmoduleEquidistribution.YonedaExtReflection

namespace QuotientSubmoduleEquidistribution.YonedaTwoSourceReduction

universe x

open LoewyTwoRankCore

/-- Extension-class uniqueness for the fifth family: every nonsimple
indecomposable generated by an actual two-top apex is isomorphic to the
apex itself. -/
theorem nonempty_iso_apex_of_nonsimple_inFac_actualTwoTopApex
    (K A : Type x)
    [Field K] [IsAlgClosed K]
    [Ring A] [Algebra K A] [FiniteDimensional K A] :
    letI : IsNoetherianRing Aᵐᵒᵖ :=
      QuotientSubmoduleEquidistribution.isNoetherianRing_op_of_finiteDimensional K A
    ∀ {iota : Type x} [Finite iota]
      (sigma :
        _root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.{x, x, x}
          Aᵐᵒᵖ iota)
      (apex : sigma.TwoTopQuotientShapeIndex)
      (_D : sigma.ActualTwoTopApexData apex)
      {j : iota},
      sigma.InFac (sigma.twoTopQuotientShapeSupport apex)
          (sigma.obj j) →
        (¬ IsSimpleModule Aᵐᵒᵖ (sigma.obj j)) →
          Nonempty (sigma.obj apex.1 ≅ sigma.obj j) := by
  letI : IsNoetherianRing Aᵐᵒᵖ :=
    QuotientSubmoduleEquidistribution.isNoetherianRing_op_of_finiteDimensional K A
  intro iota _ sigma apex D j hj hjNonsimple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.left.index) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.left.index)).mp D.left.simple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.right.index) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.right.index)).mp D.right.simple
  letI : IsSimpleModule Aᵐᵒᵖ (sigma.obj D.radical.1) :=
    (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
      (sigma.obj D.radical.1)).mp D.radical.2
  letI : Simple (sigma.obj D.left.index).obj :=
    (simple_iff_isSimpleModule' (sigma.obj D.left.index).obj).mpr
      inferInstance
  letI : Simple (sigma.obj D.right.index).obj :=
    (simple_iff_isSimpleModule' (sigma.obj D.right.index).obj).mpr
      inferInstance
  letI : Simple (sigma.obj D.radical.1).obj :=
    (simple_iff_isSimpleModule' (sigma.obj D.radical.1).obj).mpr
      inferInstance
  let LA := D.toLoewyData sigma
  let LJ := Classical.choice
    (exists_actualTwoTopLoewyData_of_nonsimple_inFac
      K A sigma apex D hj hjNonsimple)
  let SA := LA.normalizedRadicalSequence sigma
  let SJ := LJ.normalizedRadicalSequence sigma
  have hSA : SA.ShortExact :=
    LA.normalizedRadicalSequence_shortExact sigma
  have hSJ : SJ.ShortExact :=
    LJ.normalizedRadicalSequence_shortExact sigma
  have hnoParallel : NoParallelExtOne sigma K :=
    QuotientSubmoduleEquidistribution.NoParallelExtOne.noParallelExtOne_of_finiteDimensional_of_finiteSkeleton
      K A sigma
  have hExtLeft := hnoParallel D.left.simple D.radical.2
  have hExtRight := hnoParallel D.right.simple D.radical.2
  letI : FiniteDimensional K
      (Ext (sigma.obj D.left.index).obj
        (sigma.obj D.radical.1).obj 1) :=
    hExtLeft.1
  letI : FiniteDimensional K
      (Ext (sigma.obj D.right.index).obj
        (sigma.obj D.radical.1).obj 1) :=
    hExtRight.1
  obtain ⟨ell, hell⟩ :=
    YonedaExtReflection.exists_injective_linearMap_to_field_of_finrank_le_one
      hExtLeft.2
  obtain ⟨ell', hell'⟩ :=
    YonedaExtReflection.exists_injective_linearMap_to_field_of_finrank_le_one
      hExtRight.2
  letI : IsNoetherian Aᵐᵒᵖ (sigma.obj apex.1) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength apex.1)).1
  letI : IsArtinian Aᵐᵒᵖ (sigma.obj apex.1) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength apex.1)).2
  letI : IsNoetherian Aᵐᵒᵖ (sigma.obj j) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength j)).1
  letI : IsArtinian Aᵐᵒᵖ (sigma.obj j) :=
    (isFiniteLength_iff_isNoetherian_isArtinian.mp
      (sigma.finiteLength j)).2
  have hleftNonzero : 𝟙 (sigma.obj D.left.index).obj ≠ 0 :=
    CategoryTheory.id_nonzero _
  have hrightNonzero : 𝟙 (sigma.obj D.right.index).obj ≠ 0 :=
    CategoryTheory.id_nonzero _
  have hradicalNonzero : 𝟙 (sigma.obj D.radical.1).obj ≠ 0 :=
    CategoryTheory.id_nonzero _
  obtain ⟨e⟩ :=
    YonedaExtReflection.nonempty_middle_iso_of_unit_twoSource_shortExact
      K Aᵐᵒᵖ
      (sigma.obj D.left.index).obj
      (sigma.obj D.right.index).obj
      (sigma.obj D.radical.1).obj
      (sigma.obj apex.1).obj (sigma.obj j).obj
      hleftNonzero hrightNonzero hradicalNonzero
      SA.f SA.g SA.zero hSA
      SJ.f SJ.g SJ.zero hSJ
      (sigma.indecomposable apex.1) (sigma.indecomposable j)
      ell hell ell' hell'
  exact ⟨e.toLinearEquiv.toFGModuleCatIso⟩

/-- The exact collective-closure endpoint for the fifth family in the
paper's finite-dimensional algebraically closed finite-skeleton scope. -/
theorem qClosure_isClosed_twoTopQuotientShapeSupport_actual
    (K A : Type x)
    [Field K] [IsAlgClosed K]
    [Ring A] [Algebra K A] [FiniteDimensional K A] :
    letI : IsNoetherianRing Aᵐᵒᵖ :=
      QuotientSubmoduleEquidistribution.isNoetherianRing_op_of_finiteDimensional K A
    ∀ {iota : Type x} [Finite iota]
      (sigma :
        _root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.{x, x, x}
          Aᵐᵒᵖ iota)
      (apex : sigma.TwoTopQuotientShapeIndex)
      (_D : sigma.ActualTwoTopApexData apex),
      sigma.qClosure.IsClosed
        (sigma.twoTopQuotientShapeSupport apex) := by
  letI : IsNoetherianRing Aᵐᵒᵖ :=
    QuotientSubmoduleEquidistribution.isNoetherianRing_op_of_finiteDimensional K A
  intro iota _ sigma apex D
  rw [sigma.qClosure.isClosed_iff]
  apply Set.Subset.antisymm
  · intro j hj
    by_cases hjSimple : IsSimpleModule Aᵐᵒᵖ (sigma.obj j)
    · have hjSimpleCat : Simple (sigma.obj j) :=
        (_root_.QuotientSubmoduleEquidistribution.IndecomposableSkeleton.simple_iff_isSimpleModule_fg
          (sigma.obj j)).mpr hjSimple
      let Q : sigma.SimpleQuotient j := {
        index := j
        simple := hjSimpleCat
        map := 𝟙 _
        epi := inferInstance }
      have htype :
          j = D.left.index ∨ j = D.right.index :=
        sigma.simpleQuotient_index_eq_left_or_right_of_inFac_twoTopSupport
          D hj Q
      rw [IndecomposableSkeleton.twoTopQuotientShapeSupport]
      right
      rcases htype with hleft | hright
      · exact ⟨D.left, hleft.symm⟩
      · exact ⟨D.right, hright.symm⟩
    · obtain ⟨e⟩ :=
        nonempty_iso_apex_of_nonsimple_inFac_actualTwoTopApex
          K A sigma apex D hj hjSimple
      have heq : apex.1 = j := sigma.eq_of_iso ⟨e⟩
      subst j
      simp [IndecomposableSkeleton.twoTopQuotientShapeSupport]
  · exact sigma.subset_qSet _

end QuotientSubmoduleEquidistribution.YonedaTwoSourceReduction
