import QuotientSubmoduleEquidistribution.Combinatorics.ConnectedSmallCore
import QuotientSubmoduleEquidistribution.RepresentationTheory.SubmoduleAntiExchange

/-!
# Source-facing certificates for the lollipop one-point tables

The paper's two lollipop calculations are Hom calculations.  On the
quotient side, a proposed one-point extension is closed precisely when the
trace in every omitted indecomposable remains proper.  On the submodule
side, the corresponding condition is that the reject in every omitted
indecomposable remains nonzero.  A nonclosed row is witnessed by an actual
finite-sum epimorphism or monomorphism producing an omitted indecomposable.

This file packages exactly those source-faithful certificates and proves
that they construct the `NamedTwoExtensionData` consumed by
`ConnectedSmallCore.LollipopTableData`.  It deliberately does not postulate
closure of a row as a field.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace QuotientSubmoduleEquidistribution.BottomLevels.LollipopTableCertificates

universe u v w

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} [Finite ι]
  (σ : IndecomposableSkeleton.{u, v, w} R ι)

namespace Quotient

/-- A source-faithful certificate that an omitted indecomposable is not
generated by a selected support.  In a concrete Hom-table verification,
`bound` is the span of all computed images. -/
structure OmissionCertificate (S : Set ι) (j : ι) where
  not_mem : j ∉ S
  bound : Submodule R (σ.obj j)
  bound_ne_top : bound ≠ ⊤
  trace_le_bound : σ.trace S (σ.obj j) ≤ bound

namespace OmissionCertificate

variable {σ}

omit [Finite ι] in
/-- The trace bound excludes the target from the actual finite-sum quotient
closure. -/
theorem not_mem_closure {S : Set ι} {j : ι}
    (C : OmissionCertificate σ S j) :
    j ∉ σ.qClosure S := by
  intro hj
  have htrace : σ.trace S (σ.obj j) = ⊤ :=
    (σ.mem_qClosure_iff_trace_eq_top S j).1 hj
  apply C.bound_ne_top
  apply top_unique
  rw [← htrace]
  exact C.trace_le_bound

end OmissionCertificate

omit [Finite ι] in
/-- If every omitted indecomposable has a proper trace bound, the support
is quotient-closed. -/
theorem isClosed_of_omissionCertificates
    {S : Set ι}
    (certificate : ∀ j : ι, j ∉ S → OmissionCertificate σ S j) :
    σ.qClosure.IsClosed S := by
  rw [ClosureOperator.isClosed_iff_closure_le]
  intro j hj
  by_contra hnot
  exact (certificate j hnot).not_mem_closure hj

/-- A complete source-faithful certificate for one quotient-closure row.
Selected labels are included automatically; every additional expected
label has an actual finite-sum epimorphism, and every omitted label has a
proper trace bound. -/
structure ExactRowCertificate (selected expected : Set ι) where
  selected_subset_expected : selected ⊆ expected
  extra_presentations :
    ∀ j : ι, j ∈ expected → j ∉ selected →
      σ.FacPresentation selected (σ.obj j)
  omissions :
    ∀ j : ι, j ∉ expected → OmissionCertificate σ selected j

namespace ExactRowCertificate

variable {σ}

omit [Finite ι] in
/-- The row certificate computes the actual finite-sum quotient closure
exactly. -/
theorem closure_eq {selected expected : Set ι}
    (C : ExactRowCertificate σ selected expected) :
    σ.qClosure selected = expected := by
  apply Set.Subset.antisymm
  · intro j hj
    by_contra hnot
    exact (C.omissions j hnot).not_mem_closure hj
  · intro j hj
    by_cases hselected : j ∈ selected
    · exact σ.qClosure.le_closure selected hselected
    · exact ⟨C.extra_presentations j hj hselected⟩

omit [Finite ι] in
/-- A row whose expected support is the selected support is closed. -/
theorem isClosed_of_expected_eq {selected expected : Set ι}
    (C : ExactRowCertificate σ selected expected)
    (h : expected = selected) :
    σ.qClosure.IsClosed selected := by
  apply σ.qClosure.isClosed_iff.mpr
  change σ.qClosure selected = selected
  rw [C.closure_eq, h]

end ExactRowCertificate

/-- A concrete witness that a proposed row is not quotient-closed: an
omitted indecomposable together with an actual finite-sum epimorphism from
the row. -/
structure NonclosureCertificate (S : Set ι) where
  target : ι
  target_not_mem : target ∉ S
  presentation : σ.FacPresentation S (σ.obj target)

namespace NonclosureCertificate

variable {σ}

omit [Finite ι] in
/-- The explicit epimorphism forces failure of closedness. -/
theorem not_isClosed {S : Set ι}
    (C : NonclosureCertificate σ S) :
    ¬ σ.qClosure.IsClosed S := by
  intro hclosed
  have htarget : C.target ∈ σ.qClosure S := ⟨C.presentation⟩
  rw [hclosed.closure_eq] at htarget
  exact C.target_not_mem htarget

end NonclosureCertificate

/-- Hom-table form of a named two-extension table on the quotient side.

The two good rows are certified target by target by proper trace bounds.
Every other outsider is certified bad by an actual quotient presentation
of an omitted indecomposable. -/
structure NamedTwoExtensionCertificates
    {Faithful : Set ι → Prop}
    (D : MinimalFaithfulCore.Data σ.qClosure Faithful) where
  faithful_monotone : Monotone Faithful
  core_ncard : (D.core : Set ι).ncard = 3
  good₀ : ι
  good₁ : ι
  good_ne : good₀ ≠ good₁
  good₀_not_core : good₀ ∉ (D.core : Set ι)
  good₁_not_core : good₁ ∉ (D.core : Set ι)
  good₀_omissions :
    ∀ j : ι, j ∉ insert good₀ (D.core : Set ι) →
      OmissionCertificate σ (insert good₀ (D.core : Set ι)) j
  good₁_omissions :
    ∀ j : ι, j ∉ insert good₁ (D.core : Set ι) →
      OmissionCertificate σ (insert good₁ (D.core : Set ι)) j
  other_nonclosed :
    ∀ z : ι, z ∉ (D.core : Set ι) → z ≠ good₀ → z ≠ good₁ →
      NonclosureCertificate σ (insert z (D.core : Set ι))

namespace NamedTwoExtensionCertificates

variable {σ} {Faithful : Set ι → Prop}
  {D : MinimalFaithfulCore.Data σ.qClosure Faithful}

/-- Convert Hom-trace and quotient-presentation certificates into the
closure-level table expected by the connected-small-core adapter. -/
def toNamedTwoExtensionData
    (T : NamedTwoExtensionCertificates σ D) :
    ConnectedSmallCore.OnePointTable.NamedTwoExtensionData D where
  faithful_monotone := T.faithful_monotone
  core_ncard := T.core_ncard
  good₀ := T.good₀
  good₁ := T.good₁
  good_ne := T.good_ne
  good₀_not_core := T.good₀_not_core
  good₁_not_core := T.good₁_not_core
  good₀_closed :=
    isClosed_of_omissionCertificates σ T.good₀_omissions
  good₁_closed :=
    isClosed_of_omissionCertificates σ T.good₁_omissions
  exhaustive := by
    intro z hz hclosed
    by_cases hz₀ : z = T.good₀
    · exact Or.inl hz₀
    by_cases hz₁ : z = T.good₁
    · exact Or.inr hz₁
    exact ((T.other_nonclosed z hz hz₀ hz₁).not_isClosed hclosed).elim

/-- Forget the named rows and obtain the exact `Fin 2` table. -/
def toTwoExtensionData
    (T : NamedTwoExtensionCertificates σ D) :
    ConnectedSmallCore.OnePointTable.TwoExtensionData D :=
  T.toNamedTwoExtensionData.toTwoExtensionData

end NamedTwoExtensionCertificates

end Quotient

namespace Submodule

/-- A source-faithful certificate that an omitted indecomposable does not
embed into a selected finite sum.  In a concrete Hom-table verification,
`witness` is a nonzero common submodule of all computed kernels. -/
structure OmissionCertificate (S : Set ι) (j : ι) where
  not_mem : j ∉ S
  witness : Submodule R (σ.obj j)
  witness_ne_bot : witness ≠ ⊥
  witness_le_reject : witness ≤ σ.reject S (σ.obj j)

namespace OmissionCertificate

variable {σ}

omit [Finite ι] in
/-- The nonzero common kernel excludes the target from the actual
finite-sum submodule closure. -/
theorem not_mem_closure {S : Set ι} {j : ι}
    (C : OmissionCertificate σ S j) :
    j ∉ σ.sClosure S := by
  intro hj
  have hreject : σ.reject S (σ.obj j) = ⊥ :=
    (σ.mem_sClosure_iff_reject_eq_bot S j).1 hj
  apply C.witness_ne_bot
  apply bot_unique
  rw [← hreject]
  exact C.witness_le_reject

end OmissionCertificate

omit [Finite ι] in
/-- If every omitted indecomposable has a nonzero common-kernel witness,
the support is submodule-closed. -/
theorem isClosed_of_omissionCertificates
    {S : Set ι}
    (certificate : ∀ j : ι, j ∉ S → OmissionCertificate σ S j) :
    σ.sClosure.IsClosed S := by
  rw [ClosureOperator.isClosed_iff_closure_le]
  intro j hj
  by_contra hnot
  exact (certificate j hnot).not_mem_closure hj

/-- A complete source-faithful certificate for one submodule-closure row.
Selected labels are included automatically; every additional expected
label has an actual finite-sum monomorphism, and every omitted label has a
nonzero common-kernel witness. -/
structure ExactRowCertificate (selected expected : Set ι) where
  selected_subset_expected : selected ⊆ expected
  extra_presentations :
    ∀ j : ι, j ∈ expected → j ∉ selected →
      σ.SubPresentation selected (σ.obj j)
  omissions :
    ∀ j : ι, j ∉ expected → OmissionCertificate σ selected j

namespace ExactRowCertificate

variable {σ}

omit [Finite ι] in
/-- The row certificate computes the actual finite-sum submodule closure
exactly. -/
theorem closure_eq {selected expected : Set ι}
    (C : ExactRowCertificate σ selected expected) :
    σ.sClosure selected = expected := by
  apply Set.Subset.antisymm
  · intro j hj
    by_contra hnot
    exact (C.omissions j hnot).not_mem_closure hj
  · intro j hj
    by_cases hselected : j ∈ selected
    · exact σ.sClosure.le_closure selected hselected
    · exact ⟨C.extra_presentations j hj hselected⟩

omit [Finite ι] in
/-- A row whose expected support is the selected support is closed. -/
theorem isClosed_of_expected_eq {selected expected : Set ι}
    (C : ExactRowCertificate σ selected expected)
    (h : expected = selected) :
    σ.sClosure.IsClosed selected := by
  apply σ.sClosure.isClosed_iff.mpr
  change σ.sClosure selected = selected
  rw [C.closure_eq, h]

end ExactRowCertificate

/-- A concrete witness that a proposed row is not submodule-closed: an
omitted indecomposable together with an actual finite-sum monomorphism into
the row. -/
structure NonclosureCertificate (S : Set ι) where
  target : ι
  target_not_mem : target ∉ S
  presentation : σ.SubPresentation S (σ.obj target)

namespace NonclosureCertificate

variable {σ}

omit [Finite ι] in
/-- The explicit monomorphism forces failure of closedness. -/
theorem not_isClosed {S : Set ι}
    (C : NonclosureCertificate σ S) :
    ¬ σ.sClosure.IsClosed S := by
  intro hclosed
  have htarget : C.target ∈ σ.sClosure S := ⟨C.presentation⟩
  rw [hclosed.closure_eq] at htarget
  exact C.target_not_mem htarget

end NonclosureCertificate

/-- Hom-table form of a named two-extension table on the submodule side.

The two good rows are certified target by target by nonzero common
kernels.  Every other outsider is certified bad by an actual submodule
presentation of an omitted indecomposable. -/
structure NamedTwoExtensionCertificates
    {Faithful : Set ι → Prop}
    (D : MinimalFaithfulCore.Data σ.sClosure Faithful) where
  faithful_monotone : Monotone Faithful
  core_ncard : (D.core : Set ι).ncard = 3
  good₀ : ι
  good₁ : ι
  good_ne : good₀ ≠ good₁
  good₀_not_core : good₀ ∉ (D.core : Set ι)
  good₁_not_core : good₁ ∉ (D.core : Set ι)
  good₀_omissions :
    ∀ j : ι, j ∉ insert good₀ (D.core : Set ι) →
      OmissionCertificate σ (insert good₀ (D.core : Set ι)) j
  good₁_omissions :
    ∀ j : ι, j ∉ insert good₁ (D.core : Set ι) →
      OmissionCertificate σ (insert good₁ (D.core : Set ι)) j
  other_nonclosed :
    ∀ z : ι, z ∉ (D.core : Set ι) → z ≠ good₀ → z ≠ good₁ →
      NonclosureCertificate σ (insert z (D.core : Set ι))

namespace NamedTwoExtensionCertificates

variable {σ} {Faithful : Set ι → Prop}
  {D : MinimalFaithfulCore.Data σ.sClosure Faithful}

/-- Convert Hom-kernel and submodule-presentation certificates into the
closure-level table expected by the connected-small-core adapter. -/
def toNamedTwoExtensionData
    (T : NamedTwoExtensionCertificates σ D) :
    ConnectedSmallCore.OnePointTable.NamedTwoExtensionData D where
  faithful_monotone := T.faithful_monotone
  core_ncard := T.core_ncard
  good₀ := T.good₀
  good₁ := T.good₁
  good_ne := T.good_ne
  good₀_not_core := T.good₀_not_core
  good₁_not_core := T.good₁_not_core
  good₀_closed :=
    isClosed_of_omissionCertificates σ T.good₀_omissions
  good₁_closed :=
    isClosed_of_omissionCertificates σ T.good₁_omissions
  exhaustive := by
    intro z hz hclosed
    by_cases hz₀ : z = T.good₀
    · exact Or.inl hz₀
    by_cases hz₁ : z = T.good₁
    · exact Or.inr hz₁
    exact ((T.other_nonclosed z hz hz₀ hz₁).not_isClosed hclosed).elim

/-- Forget the named rows and obtain the exact `Fin 2` table. -/
def toTwoExtensionData
    (T : NamedTwoExtensionCertificates σ D) :
    ConnectedSmallCore.OnePointTable.TwoExtensionData D :=
  T.toNamedTwoExtensionData.toTwoExtensionData

end NamedTwoExtensionCertificates

end Submodule

/-! ## Paired table and coefficient endpoint -/

variable {FaithfulQ FaithfulS : Set ι → Prop}
  {QCore : MinimalFaithfulCore.Data σ.qClosure FaithfulQ}
  {SCore : MinimalFaithfulCore.Data σ.sClosure FaithfulS}

/-- The exact source-facing certificate pair for one lollipop algebra.
It applies uniformly to the dead/live relation variants and their
opposites; only the names and concrete Hom certificates differ. -/
structure PairedCertificates where
  quotient : Quotient.NamedTwoExtensionCertificates σ QCore
  submodule : Submodule.NamedTwoExtensionCertificates σ SCore

namespace PairedCertificates

variable {σ}

/-- Convert the source-facing pair to the two closure-level tables consumed
by the recurrence adapter. -/
def toTablePair
    (T : PairedCertificates σ (QCore := QCore) (SCore := SCore)) :
    ConnectedSmallCore.OnePointTable.TwoExtensionData QCore ×
      ConnectedSmallCore.OnePointTable.TwoExtensionData SCore :=
  ⟨T.quotient.toTwoExtensionData, T.submodule.toTwoExtensionData⟩

/-- The paired Hom certificates prove equality of the faithful
degree-four coefficients, with each side computed as exactly two. -/
theorem faithfulLevelCount_four_eq
    (T : PairedCertificates σ (QCore := QCore) (SCore := SCore)) :
    MinimalFaithfulCore.faithfulLevelCount σ.qClosure FaithfulQ 4 =
      MinimalFaithfulCore.faithfulLevelCount σ.sClosure FaithfulS 4 := by
  rw [T.quotient.toTwoExtensionData.faithfulLevelCount_four_eq_two,
    T.submodule.toTwoExtensionData.faithfulLevelCount_four_eq_two]

end PairedCertificates

end QuotientSubmoduleEquidistribution.BottomLevels.LollipopTableCertificates
