import QuotientSubmoduleEquidistribution.RepresentationTheory.ConnectedSmallCoreExceptionalArrowIdeals
import QuotientSubmoduleEquidistribution.RepresentationTheory.CyclicRightIdealTop
import QuotientSubmoduleEquidistribution.RepresentationTheory.LengthThreeModules
import QuotientSubmoduleEquidistribution.RepresentationTheory.PeirceCotangentExtDimension
import QuotientSubmoduleEquidistribution.RepresentationTheory.SixCoordinateRelationQuotient

/-!
# Exclusion of the loop--two-cycle support

This file closes the last structural branch in the exceptional two-simple,
three-object faithful-core reduction.  Proper arrow-ideal embeddings first
identify the two cross-arrow ideals.  Multiplication by the outgoing arrow
then proves that the cyclic ideal generated by the two-cycle product is
isomorphic to the loop ideal.  The automatic coordinate realization feeds
that isomorphism into the six-coordinate representation-infinite quotient.

No concrete algebra or module classification is used.
-/

noncomputable section

open Set CategoryTheory MulOpposite

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore.ConnectedSmallCore

universe u v w

open QuotientSubmoduleEquidistribution.IndecomposableSkeleton.ProjectiveSimpleRank

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} [Finite ι]
  (σ : IndecomposableSkeleton.{u, v, u} R ι)

namespace ExceptionalArrowIdealData

variable {Arrow : Type w}
  {source target : Arrow → σ.SimpleIndex}
  (D : ExceptionalArrowIdealData σ source target)

omit [Finite ι] in
include D in
/-- Equal arrow-ideal labels have equal simple-top vertices. -/
theorem target_eq_of_idealLabel_eq
    {a b : Arrow} (h : D.idealLabel a = D.idealLabel b) :
    target a = target b := by
  obtain ⟨eA⟩ := D.topIso a
  obtain ⟨eB⟩ := D.topIso b
  apply Subtype.ext
  apply σ.eq_of_iso
  exact ⟨eA.symm ≪≫
    eqToIso (congrArg
      (fun i : ι ↦ FGModuleCat.of R (σ.moduleTop i)) h) ≪≫ eB⟩

/-- An arrow whose target differs from the loop vertex has projective arrow
ideal. -/
theorem idealLabel_eq_targetProjective_of_loop_of_target_ne
    (hRingel : RingelCoreCardinality σ)
    (hRank : projectiveRank σ = 2)
    (hCore : (quotientCore σ : Set ι).ncard = 3)
    (ell c : Arrow) (hLoop : source ell = target ell)
    (hne : target c ≠ target ell) :
    D.idealLabel c = projectiveLabelOfSimple σ (target c) := by
  rcases D.idealLabel_eq_targetProjective_or_exceptionalLabel σ
      hRingel hRank hCore c with hProjective | hExceptional
  · exact hProjective
  · exfalso
    apply hne
    apply D.target_eq_of_idealLabel_eq σ
    exact hExceptional.trans
      (D.loop_idealLabel_eq_exceptionalLabel σ
        hRingel hRank hCore ell hLoop).symm

/-- In a loop plus an oriented two-cycle, the arrow entering the loop vertex
has the same exceptional label as the loop. -/
theorem incoming_idealLabel_eq_exceptional_of_loopTwoCycle
    (hRingel : RingelCoreCardinality σ)
    (hRank : projectiveRank σ = 2)
    (hCore : (quotientCore σ : Set ι).ncard = 3)
    (ell incoming outgoing : Arrow)
    (hLoop : source ell = target ell)
    (hIncomingTarget : target incoming = target ell)
    (hOutgoingSource : source outgoing = target ell)
    (hOutgoingTarget : target outgoing = source incoming)
    (hne : target ell ≠ source incoming) :
    D.idealLabel incoming = exceptionalLabel σ hRingel hRank hCore := by
  have hOutgoingTargetNe : target outgoing ≠ target ell := by
    rw [hOutgoingTarget]
    exact hne.symm
  have hOutgoingLabel :
      D.idealLabel outgoing =
        projectiveLabelOfSimple σ (target outgoing) :=
    D.idealLabel_eq_targetProjective_of_loop_of_target_ne σ
      hRingel hRank hCore ell outgoing hLoop hOutgoingTargetNe
  rcases D.idealLabel_eq_targetProjective_or_exceptionalLabel σ
      hRingel hRank hCore incoming with hIncomingLabel | hExceptional
  · exfalso
    letI : Mono (D.inclusion incoming) := D.inclusion_mono incoming
    letI : Mono (D.inclusion outgoing) := D.inclusion_mono outgoing
    have hleIncoming := σ.compositionLength_le_of_mono (D.inclusion incoming)
    have hleOutgoing := σ.compositionLength_le_of_mono (D.inclusion outgoing)
    have hlength :
        σ.compositionLength (D.idealLabel incoming) =
          σ.compositionLength
            (projectiveLabelOfSimple σ (source incoming)) := by
      apply le_antisymm hleIncoming
      calc
        σ.compositionLength
              (projectiveLabelOfSimple σ (source incoming)) =
            σ.compositionLength (D.idealLabel outgoing) := by
              rw [hOutgoingLabel, hOutgoingTarget]
        _ ≤ σ.compositionLength
              (projectiveLabelOfSimple σ (source outgoing)) := hleOutgoing
        _ = σ.compositionLength (D.idealLabel incoming) := by
              rw [hIncomingLabel, hIncomingTarget, hOutgoingSource]
    letI : IsIso (D.inclusion incoming) :=
      σ.isIso_of_mono_of_compositionLength_eq
        (D.inclusion incoming) hlength
    exact (D.inclusion_not_epi incoming) inferInstance
  · exact hExceptional

end ExceptionalArrowIdealData

variable {K B : Type u} [Field K] [Ring B] [Algebra K B]
  [FiniteDimensional K B] [IsNoetherianRing Bᵐᵒᵖ]
  {kappa : Type v} [Finite kappa]
  (tau : IndecomposableSkeleton.{u, v, u} Bᵐᵒᵖ kappa)
  {Arrow : Type w}
  {source target : Arrow → tau.SimpleIndex}
  (G : SplitBasicGabrielArrowRealization tau source target)

include K in
/-- For a realized loop plus two-cycle, the product of the outgoing and
incoming representatives generates the same cyclic right ideal, up to
isomorphism, as the loop representative. -/
theorem cyclicProduct_iso_loop_of_loopTwoCycle
    (hRingel : RingelCoreCardinality tau)
    (hRank : projectiveRank tau = 2)
    (hCore : (quotientCore tau : Set kappa).ncard = 3)
    (ell incoming outgoing : Arrow)
    (hLoop : source ell = target ell)
    (hIncomingTarget : target incoming = target ell)
    (hOutgoingSource : source outgoing = target ell)
    (hOutgoingTarget : target outgoing = source incoming)
    (hne : target ell ≠ source incoming)
    (hIncomingRight :
      G.representative incoming * G.vertex (target incoming) =
        G.representative incoming)
    (hOutgoingRight :
      G.representative outgoing * G.vertex (target outgoing) =
        G.representative outgoing)
    (hIncomingNe : G.representative incoming ≠ 0) :
    Nonempty
      (QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
          (G.representative outgoing * G.representative incoming) ≅
        QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
          (G.representative ell)) := by
  let E := G.toExceptionalArrowIdealData
  have hLoopLabel :
      E.idealLabel ell = exceptionalLabel tau hRingel hRank hCore :=
    E.loop_idealLabel_eq_exceptionalLabel tau
      hRingel hRank hCore ell hLoop
  have hOutgoingTargetNe : target outgoing ≠ target ell := by
    rw [hOutgoingTarget]
    exact hne.symm
  have hOutgoingLabel :
      E.idealLabel outgoing =
        projectiveLabelOfSimple tau (target outgoing) :=
    E.idealLabel_eq_targetProjective_of_loop_of_target_ne tau
      hRingel hRank hCore ell outgoing hLoop hOutgoingTargetNe
  let eOutgoingProjective :
      QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
          (G.representative outgoing) ≅
        tau.obj (projectiveLabelOfSimple tau (target outgoing)) :=
    SplitBasicGabrielArrowRealization.arrowIso tau G outgoing ≪≫
      eqToIso (congrArg tau.obj hOutgoingLabel)
  let f := QuotientSubmoduleEquidistribution.Tsukamoto.principalRightIdealToCyclic
    (e := G.vertex (target outgoing))
    (c := G.representative outgoing)
  have hfSurjective : Function.Surjective f :=
    QuotientSubmoduleEquidistribution.Tsukamoto.principalRightIdealToCyclic_surjective
      hOutgoingRight
  let fFG :
      QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
          (G.vertex (target outgoing)) ⟶
        QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
          (G.representative outgoing) :=
    FGModuleCat.ofHom f
  letI : Epi fFG :=
    (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_epi_iff_surjective fFG).mpr
      hfSurjective
  let fSkeleton :
      tau.obj (projectiveLabelOfSimple tau (target outgoing)) ⟶
        tau.obj (projectiveLabelOfSimple tau (target outgoing)) :=
    (SplitBasicGabrielArrowRealization.vertexIso
      tau G (target outgoing)).inv ≫ fFG ≫ eOutgoingProjective.hom
  letI : Epi fSkeleton := by
    dsimp only [fSkeleton]
    infer_instance
  letI : IsIso fSkeleton :=
    tau.isIso_of_epi_of_compositionLength_eq fSkeleton rfl
  have hfEq :
      (SplitBasicGabrielArrowRealization.vertexIso
          tau G (target outgoing)).hom ≫
          fSkeleton ≫ eOutgoingProjective.inv = fFG := by
    simp [fSkeleton]
  letI : IsIso fFG := by
    rw [← hfEq]
    infer_instance
  have hfInjective : Function.Injective f := by
    exact (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_mono_iff_injective fFG).mp
      inferInstance
  let aInVertex :
      QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
        (G.vertex (target outgoing)) :=
    ⟨op (G.representative incoming), by
      have hmem := G.arrowIdeal_le_source incoming
        (Ideal.mem_span_singleton_self
          (op (G.representative incoming)))
      simpa [hOutgoingTarget] using hmem⟩
  have hProductNe :
      G.representative outgoing * G.representative incoming ≠ 0 := by
    intro hzero
    have hfa : f aInVertex = 0 := by
      apply Subtype.ext
      change op (G.representative incoming) *
          op (G.representative outgoing) = 0
      rw [← op_mul, hzero]
      simp
    have haZero : aInVertex = 0 := by
      apply hfInjective
      simpa using hfa
    apply hIncomingNe
    have hval := congrArg Subtype.val haZero
    have hval' : op (G.representative incoming) = (0 : Bᵐᵒᵖ) := by
      change op (G.representative incoming) = (0 : Bᵐᵒᵖ) at hval
      exact hval
    exact op_injective (by simpa using hval')
  have hIncomingRightLoop :
      G.representative incoming * G.vertex (target ell) =
        G.representative incoming := by
    simpa [hIncomingTarget] using hIncomingRight
  have hProductRight :
      (G.representative outgoing * G.representative incoming) *
          G.vertex (target ell) =
        G.representative outgoing * G.representative incoming := by
    rw [mul_assoc, hIncomingRightLoop]
  have eProductTop :=
    (cyclicRightIdeal_topIso_of_ne_zero_of_right_fixed
      (K := K) tau G (target ell) hProductNe hProductRight).some
  rcases CyclicRightIdeal.iso_targetProjective_or_exceptional_of_top_iso
      tau hRingel hRank hCore
        (G.representative outgoing * G.representative incoming)
        (target ell) eProductTop with
    hProductProjective | hProductExceptional
  · obtain ⟨eProductProjective⟩ := hProductProjective
    have hProductLeOutgoing :
        QuotientSubmoduleEquidistribution.Tsukamoto.principalRightIdeal
            (G.representative outgoing * G.representative incoming) ≤
          QuotientSubmoduleEquidistribution.Tsukamoto.principalRightIdeal
            (G.representative outgoing) :=
      QuotientSubmoduleEquidistribution.Tsukamoto.principalRightIdeal_le_of_eq_mul rfl
    let inc :=
      QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealInclusionOfLE
        hProductLeOutgoing
    letI : Mono inc :=
      QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealInclusionOfLE_mono
        hProductLeOutgoing
    let m :
        tau.obj (projectiveLabelOfSimple tau (target ell)) ⟶
          tau.obj (projectiveLabelOfSimple tau (target outgoing)) :=
      eProductProjective.inv ≫
        inc ≫
        eOutgoingProjective.hom
    letI : Mono m := by
      dsimp only [m]
      infer_instance
    have hForward := tau.compositionLength_le_of_mono m
    letI : Mono (E.inclusion outgoing) := E.inclusion_mono outgoing
    have hBackward :=
      tau.compositionLength_le_of_mono (E.inclusion outgoing)
    have hlength :
        tau.compositionLength (E.idealLabel outgoing) =
          tau.compositionLength
            (projectiveLabelOfSimple tau (source outgoing)) := by
      apply le_antisymm hBackward
      calc
        tau.compositionLength
              (projectiveLabelOfSimple tau (source outgoing)) =
            tau.compositionLength
              (projectiveLabelOfSimple tau (target ell)) := by
                rw [hOutgoingSource]
        _ ≤ tau.compositionLength
              (projectiveLabelOfSimple tau (target outgoing)) := hForward
        _ = tau.compositionLength (E.idealLabel outgoing) := by
              rw [hOutgoingLabel]
    letI : IsIso (E.inclusion outgoing) :=
      tau.isIso_of_mono_of_compositionLength_eq
        (E.inclusion outgoing) hlength
    exact False.elim ((E.inclusion_not_epi outgoing) inferInstance)
  · obtain ⟨eProductExceptional⟩ := hProductExceptional
    let eLoopExceptional :
        QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
            (G.representative ell) ≅
          tau.obj (exceptionalLabel tau hRingel hRank hCore) :=
      SplitBasicGabrielArrowRealization.arrowIso tau G ell ≪≫
        eqToIso (congrArg tau.obj hLoopLabel)
    exact ⟨eProductExceptional ≪≫ eLoopExceptional.symm⟩

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore.ConnectedSmallCore

namespace QuotientSubmoduleEquidistribution.QuotientSurvival.TwoCoordinateData

open QuotientSubmoduleEquidistribution.CotangentExtBridge
open QuotientSubmoduleEquidistribution.GabrielArrowBridge
open QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore
open QuotientSubmoduleEquidistribution.IndecomposableSkeleton.FaithfulCore.ConnectedSmallCore

universe u v

variable {K B : Type u}
  [Field K] [Ring B] [Algebra K B]
  [FiniteDimensional K B] [IsArtinianRing B]
  {kappa : Type v}
  [Small.{u} Bᵐᵒᵖ] [IsNoetherianRing Bᵐᵒᵖ]
  [IsArtinianRing Bᵐᵒᵖ] [Finite kappa]
  (D : QuotientSubmoduleEquidistribution.QuotientSurvival.TwoCoordinateData
    (K := K) (B := B))
  (tau : QuotientSubmoduleEquidistribution.IndecomposableSkeleton.{u, v, u} Bᵐᵒᵖ kappa)

omit [IsArtinianRing Bᵐᵒᵖ] in
/-- The loop-plus-two-cycle Ext support is impossible in an exceptional
three-object faithful core.  The Ext arrows automatically supply all Peirce
representatives, the cyclic-product theorem supplies `(ba)B ≅ xB`, and the
six-coordinate quotient supplies the representation-infinite contradiction. -/
theorem false_of_loopTwoCycleSupport
    [Infinite K]
    (hNoParallel : NoParallelExtSupport (K := K) tau)
    (hShape :
      (D.alignedExtTwoVertexSupport tau hNoParallel).IsLoopTwoCycleAt 0 1)
    (hRingel : RingelCoreCardinality tau)
    (hRank : projectiveRank tau = 2)
    (hCore : (quotientCore tau : Set kappa).ncard = 3) :
    False := by
  let E :=
    QuotientSubmoduleEquidistribution.CotangentExtBridge.CoordinateData.coordinateSimpleIndexEquiv
      D tau
  let R :=
    QuotientSubmoduleEquidistribution.CoordinateGabrielRealization.automaticExtArrowCotangentRepresentativeData
      D tau
  let G :=
    QuotientSubmoduleEquidistribution.CoordinateGabrielRealization.ExtArrowCotangentRepresentativeData.toSplitBasicGabrielArrowRealization
      R
  let loopArrow := hShape.2.1.choose
  have hLoopSpec := hShape.2.1.choose_spec
  let outgoingArrow := hShape.2.2.2.1.choose
  have hOutgoingSpec := hShape.2.2.2.1.choose_spec
  let incomingArrow := hShape.2.2.2.2.choose
  have hIncomingSpec := hShape.2.2.2.2.choose_spec
  have hLoopSource := hLoopSpec.1
  have hLoopTarget := hLoopSpec.2
  have hOutgoingSource := hOutgoingSpec.1
  have hOutgoingTarget := hOutgoingSpec.2
  have hIncomingSource := hIncomingSpec.1
  have hIncomingTarget := hIncomingSpec.2
  change E.symm (ExtGabrielArrowIndex.source tau loopArrow) = 0 at hLoopSource
  change E.symm (ExtGabrielArrowIndex.target tau loopArrow) = 0 at hLoopTarget
  change E.symm (ExtGabrielArrowIndex.source tau outgoingArrow) = 0 at hOutgoingSource
  change E.symm (ExtGabrielArrowIndex.target tau outgoingArrow) = 1 at hOutgoingTarget
  change E.symm (ExtGabrielArrowIndex.source tau incomingArrow) = 1 at hIncomingSource
  change E.symm (ExtGabrielArrowIndex.target tau incomingArrow) = 0 at hIncomingTarget
  have hLoop :
      ExtGabrielArrowIndex.source tau loopArrow =
        ExtGabrielArrowIndex.target tau loopArrow := by
    apply E.symm.injective
    exact hLoopSource.trans hLoopTarget.symm
  have hIncomingTargetLoop :
      ExtGabrielArrowIndex.target tau incomingArrow =
        ExtGabrielArrowIndex.target tau loopArrow := by
    apply E.symm.injective
    exact hIncomingTarget.trans hLoopTarget.symm
  have hOutgoingSourceLoop :
      ExtGabrielArrowIndex.source tau outgoingArrow =
        ExtGabrielArrowIndex.target tau loopArrow := by
    apply E.symm.injective
    exact hOutgoingSource.trans hLoopTarget.symm
  have hOutgoingTargetIncomingSource :
      ExtGabrielArrowIndex.target tau outgoingArrow =
        ExtGabrielArrowIndex.source tau incomingArrow := by
    apply E.symm.injective
    exact hOutgoingTarget.trans hIncomingSource.symm
  have hVerticesNe :
      ExtGabrielArrowIndex.target tau loopArrow ≠
        ExtGabrielArrowIndex.source tau incomingArrow := by
    intro heq
    have : (0 : Fin 2) = 1 :=
      hLoopTarget.symm.trans <|
        (congrArg E.symm heq).trans hIncomingSource
    exact (by decide : (0 : Fin 2) ≠ 1) this
  have hIncomingRight :
      G.representative incomingArrow *
          G.vertex (ExtGabrielArrowIndex.target tau incomingArrow) =
        G.representative incomingArrow := by
    simpa [G,
      QuotientSubmoduleEquidistribution.CoordinateGabrielRealization.ExtArrowCotangentRepresentativeData.toSplitBasicGabrielArrowRealization]
      using R.representative_right_fixed incomingArrow
  have hOutgoingRight :
      G.representative outgoingArrow *
          G.vertex (ExtGabrielArrowIndex.target tau outgoingArrow) =
        G.representative outgoingArrow := by
    simpa [G,
      QuotientSubmoduleEquidistribution.CoordinateGabrielRealization.ExtArrowCotangentRepresentativeData.toSplitBasicGabrielArrowRealization]
      using R.representative_right_fixed outgoingArrow
  have hIncomingNe : G.representative incomingArrow ≠ 0 := by
    intro hzero
    apply R.representative_not_mem_square incomingArrow
    change R.representative incomingArrow = 0 at hzero
    rw [hzero]
    exact Submodule.zero_mem _
  have hcyclic :
      QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
          (R.representative outgoingArrow * R.representative incomingArrow) ≅
        QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG
          (R.representative loopArrow) := by
    exact (cyclicProduct_iso_loop_of_loopTwoCycle
      (K := K) tau G hRingel hRank hCore loopArrow incomingArrow outgoingArrow
        hLoop hIncomingTargetLoop hOutgoingSourceLoop
        hOutgoingTargetIncomingSource hVerticesNe hIncomingRight hOutgoingRight
        hIncomingNe).some
  have hxL : D.liftedCoordinate 0 * R.representative loopArrow =
      R.representative loopArrow := by
    have h := R.representative_left_fixed loopArrow
    change D.liftedCoordinate
      (E.symm (ExtGabrielArrowIndex.source tau loopArrow)) *
        R.representative loopArrow = R.representative loopArrow at h
    rw [hLoopSource] at h
    exact h
  have hxR : R.representative loopArrow * D.liftedCoordinate 0 =
      R.representative loopArrow := by
    have h := R.representative_right_fixed loopArrow
    change R.representative loopArrow * D.liftedCoordinate
      (E.symm (ExtGabrielArrowIndex.target tau loopArrow)) =
        R.representative loopArrow at h
    rw [hLoopTarget] at h
    exact h
  have haL : D.liftedCoordinate 1 * R.representative incomingArrow =
      R.representative incomingArrow := by
    have h := R.representative_left_fixed incomingArrow
    change D.liftedCoordinate
      (E.symm (ExtGabrielArrowIndex.source tau incomingArrow)) *
        R.representative incomingArrow = R.representative incomingArrow at h
    rw [hIncomingSource] at h
    exact h
  have haR : R.representative incomingArrow * D.liftedCoordinate 0 =
      R.representative incomingArrow := by
    have h := R.representative_right_fixed incomingArrow
    change R.representative incomingArrow * D.liftedCoordinate
      (E.symm (ExtGabrielArrowIndex.target tau incomingArrow)) =
        R.representative incomingArrow at h
    rw [hIncomingTarget] at h
    exact h
  have hbL : D.liftedCoordinate 0 * R.representative outgoingArrow =
      R.representative outgoingArrow := by
    have h := R.representative_left_fixed outgoingArrow
    change D.liftedCoordinate
      (E.symm (ExtGabrielArrowIndex.source tau outgoingArrow)) *
        R.representative outgoingArrow = R.representative outgoingArrow at h
    rw [hOutgoingSource] at h
    exact h
  have hbR : R.representative outgoingArrow * D.liftedCoordinate 1 =
      R.representative outgoingArrow := by
    have h := R.representative_right_fixed outgoingArrow
    change R.representative outgoingArrow * D.liftedCoordinate
      (E.symm (ExtGabrielArrowIndex.target tau outgoingArrow)) =
        R.representative outgoingArrow at h
    rw [hOutgoingTarget] at h
    exact h
  have hdim :=
    D.cotangentDimensionAtMostThree_of_loopTwoCycleSupport_automatic
      tau hNoParallel hShape
  exact D.false_of_loopTwoCycle_of_finrank_le_three
    (R.representative_mem_jacobson loopArrow)
    (R.representative_mem_jacobson incomingArrow)
    (R.representative_mem_jacobson outgoingArrow)
    hxL hxR haL haR hbL hbR
    (R.representative_not_mem_square loopArrow)
    (R.representative_not_mem_square incomingArrow)
    (R.representative_not_mem_square outgoingArrow)
    hcyclic hdim tau

end QuotientSubmoduleEquidistribution.QuotientSurvival.TwoCoordinateData
