import Mathlib.Tactic
import Mathlib.CategoryTheory.Skeletal
import QuotientSubmoduleEquidistribution.RepresentationTheory.Approximation

/-!
# Finite supports and basic normal modules

This file realizes a finite indecomposable support as a duplicate-free
finite biproduct, expresses removal of one summand at module level, and
identifies paper-normality with minimality of the support as a generator.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton

universe u v w

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} (σ : IndecomposableSkeleton.{u, v, w} R ι)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- A finite set of chosen indecomposable representatives. -/
abbrev FiniteSupport := {B : Set ι // B.Finite}

namespace FiniteSupport

variable {σ}

/-- A small finite indexing type for a possibly large-universe finite
support. -/
def index (B : FiniteSupport (ι := ι)) : FintypeCat.{0} :=
  FintypeCat.of (Fin (Nat.card B.1))

/-- The choice equivalence used to enumerate a finite support. -/
noncomputable def equivFin (B : FiniteSupport (ι := ι)) :
    B.1 ≃ Fin (Nat.card B.1) := by
  letI : Finite B.1 := B.2.to_subtype
  exact Finite.equivFin B.1

/-- The label of an entry in the chosen small enumeration. -/
noncomputable def label (B : FiniteSupport (ι := ι)) :
    B.index → ι :=
  fun t ↦ (B.equivFin.symm t).1

@[simp]
theorem label_mem (B : FiniteSupport (ι := ι)) (t : B.index) :
    B.label t ∈ B.1 :=
  (B.equivFin.symm t).2

theorem label_injective (B : FiniteSupport (ι := ι)) :
    Function.Injective B.label := by
  intro s t h
  apply B.equivFin.symm.injective
  apply Subtype.ext
  exact h

theorem exists_label_eq (B : FiniteSupport (ι := ι))
    {i : ι} (hi : i ∈ B.1) :
    ∃ t : B.index, B.label t = i := by
  let b : B.1 := ⟨i, hi⟩
  exact ⟨B.equivFin b, by
    apply Subtype.ext_iff.mp
      (B.equivFin.symm_apply_apply b)⟩

@[simp]
theorem label_equivFin (B : FiniteSupport (ι := ι)) (b : B.1) :
    B.label (B.equivFin b) = b.1 := by
  exact congrArg Subtype.val (B.equivFin.symm_apply_apply b)

/-- Delete one selected representative from a finite support. -/
def erase (B : FiniteSupport (ι := ι)) (b : B.1) :
    FiniteSupport (ι := ι) :=
  ⟨B.1 \ {b.1}, B.2.sdiff⟩

@[simp]
theorem mem_erase_iff (B : FiniteSupport (ι := ι)) (b : B.1)
    (i : ι) :
    i ∈ (B.erase b).1 ↔ i ∈ B.1 ∧ i ≠ b.1 := by
  simp [erase]

end FiniteSupport

/-- The canonical basic module attached to a finite support: every chosen
indecomposable occurs exactly once. -/
abbrev basicModule (B : FiniteSupport (ι := ι)) :
    FGModuleCat.{w} R :=
  σ.sumOver B.index B.label

/-- The complement module after removing the summand indexed by `b`. -/
abbrev basicModuleWithout (B : FiniteSupport (ι := ι)) (b : B.1) :
    FGModuleCat.{w} R :=
  σ.basicModule (B.erase b)

/-- `X` belongs to `Fac M`: it is a quotient of a finite biproduct of
copies of the concrete module `M`. -/
def InFacOfModule
    (M X : FGModuleCat.{w} R) : Prop :=
  ∃ (J : FintypeCat.{0})
    (p : (⨁ fun _ : J ↦ M) ⟶ X), Epi p

/-- The canonical basic module is generated by its support. -/
theorem basicModule_inFac
    (B : FiniteSupport (ι := ι)) :
    σ.InFac B.1 (σ.basicModule B) := by
  exact ⟨{
    index := B.index
    label := B.label
    mem := B.label_mem
    map := 𝟙 _
    epi := inferInstance }⟩

/-- Quotients of finite sums of the basic module are generated by its
indecomposable support. -/
theorem inFac_of_inFacOfModule_basicModule
    (B : FiniteSupport (ι := ι)) {X : FGModuleCat.{w} R}
    (hX : InFacOfModule (σ.basicModule B) X) :
    σ.InFac B.1 X := by
  obtain ⟨J, p, hp⟩ := hX
  letI : Epi p := hp
  have hsource :
      σ.InFac B.1 (⨁ fun _ : J ↦ σ.basicModule B) :=
    inFac_biproduct σ J (fun _ ↦ σ.basicModule B)
      (fun _ ↦ basicModule_inFac σ B)
  exact inFac_of_epi σ hsource p

/-- Conversely, any quotient presentation by representatives in `B`
is a quotient of a finite sum of copies of the one basic module attached
to `B`. -/
theorem inFacOfModule_basicModule_of_inFac
    (B : FiniteSupport (ι := ι)) {X : FGModuleCat.{w} R}
    (hX : σ.InFac B.1 X) :
    InFacOfModule (σ.basicModule B) X := by
  classical
  obtain ⟨P⟩ := hX
  let coordinate
      (t : P.index) :
      σ.basicModule B ⟶ σ.obj (P.label t) :=
    biproduct.π
        (fun s : B.index ↦ σ.obj (B.label s))
        (B.equivFin ⟨P.label t, P.mem t⟩) ≫
      eqToHom
        (congrArg σ.obj
          (B.label_equivFin ⟨P.label t, P.mem t⟩))
  let q :
      (⨁ fun _ : P.index ↦ σ.basicModule B) ⟶ X :=
    biproduct.map coordinate ≫ P.map
  refine ⟨P.index, q, ?_⟩
  letI (t : P.index) : Epi (coordinate t) := by
    dsimp only [coordinate]
    infer_instance
  letI : Epi P.map := P.epi
  dsimp only [q]
  infer_instance

/-- Exact bridge between the support-level `Fac(add B)` predicate and the
usual module-level `Fac M_B` predicate. -/
theorem inFacOfModule_basicModule_iff
    (B : FiniteSupport (ι := ι)) (X : FGModuleCat.{w} R) :
    InFacOfModule (σ.basicModule B) X ↔ σ.InFac B.1 X :=
  ⟨inFac_of_inFacOfModule_basicModule σ B,
    inFacOfModule_basicModule_of_inFac σ B⟩

/-- Every displayed summand of the canonical module is indecomposable. -/
theorem basicModule_summand_indecomposable
    (B : FiniteSupport (ι := ι)) (t : B.index) :
    QuotientSubmoduleEquidistribution.Foundation.IsIndecomposableModule R (σ.obj (B.label t)) :=
  σ.indecomposable (B.label t)

/-- No two displayed summands are isomorphic: this is the precise
chosen-skeleton form of basicness. -/
theorem basicModule_labels_eq_of_iso
    (B : FiniteSupport (ι := ι)) {s t : B.index}
    (hiso :
      Nonempty (σ.obj (B.label s) ≅ σ.obj (B.label t))) :
    s = t :=
  B.label_injective (σ.eq_of_iso hiso)

/-- The coordinate indexed by `b` is a retract of the canonical basic
module.  Thus the terminology “remove the summand `b`” is literal, not
only support-level notation. -/
def basicModuleSummandRetract
    (B : FiniteSupport (ι := ι)) (b : B.1) :
    Retract (σ.obj b.1) (σ.basicModule B) := by
  let t : B.index := B.equivFin b
  let e : σ.obj (B.label t) ≅ σ.obj b.1 :=
    eqToIso (congrArg σ.obj (B.label_equivFin b))
  exact
    { i :=
        e.inv ≫
          biproduct.ι
            (fun s : B.index ↦ σ.obj (B.label s)) t
      r :=
        biproduct.π
            (fun s : B.index ↦ σ.obj (B.label s)) t ≫
          e.hom
      retract := by simp }

/-- The canonical basic module belongs to the additive closure of its
support. -/
theorem basicModule_inAdd
    (B : FiniteSupport (ι := ι)) :
    σ.InAdd B.1 (σ.basicModule B) :=
  ⟨{
    index := B.index
    label := B.label
    mem := B.label_mem
    iso := Iso.refl _ }⟩

/-- Canonical basic modules have no hidden quotient by multiplicity:
their isomorphism class determines the finite support exactly. -/
theorem finiteSupport_eq_of_basicModule_iso
    (B C : FiniteSupport (ι := ι))
    (hiso :
      Nonempty (σ.basicModule B ≅ σ.basicModule C)) :
    B = C := by
  classical
  let e : σ.basicModule B ≅ σ.basicModule C :=
    Classical.choice hiso
  apply Subtype.ext
  apply Set.Subset.antisymm
  · intro i hi
    let b : B.1 := ⟨i, hi⟩
    exact
      index_mem_of_retract_inAdd σ
        ((basicModuleSummandRetract σ B b).trans
          (Retract.ofIso e))
        (basicModule_inAdd σ C)
  · intro i hi
    let c : C.1 := ⟨i, hi⟩
    exact
      index_mem_of_retract_inAdd σ
        ((basicModuleSummandRetract σ C c).trans
          (Retract.ofIso e.symm))
        (basicModule_inAdd σ B)

/-- Paper-normality for the canonical basic module: after deleting any
indecomposable summand `X_b`, that summand is not in `Fac` of the concrete
complement module. -/
def IsPaperNormal (B : FiniteSupport (ι := ι)) : Prop :=
  ∀ b : B.1,
    ¬ InFacOfModule (σ.basicModuleWithout B b) (σ.obj b.1)

/-- Module-level paper-normality is exactly pointwise irredundancy of the
finite support under quotient closure. -/
theorem isPaperNormal_iff_pointwise
    (B : FiniteSupport (ι := ι)) :
    IsPaperNormal σ B ↔
      ∀ ⦃b : ι⦄, b ∈ B.1 →
        b ∉ σ.qClosure (B.1 \ {b}) := by
  constructor
  · intro hnormal b hbB hbclosure
    let bB : B.1 := ⟨b, hbB⟩
    apply hnormal bB
    apply (inFacOfModule_basicModule_iff σ (B.erase bB)
      (σ.obj b)).2
    exact
      (mem_qClosure_iff_inFac σ (B.1 \ {b}) b).1
        hbclosure
  · intro hpoint b hfac
    apply hpoint b.2
    apply
      (mem_qClosure_iff_inFac σ (B.1 \ {b.1}) b.1).2
    exact
      (inFacOfModule_basicModule_iff σ (B.erase b)
        (σ.obj b.1)).1 hfac

/-- Equivalently, paper-normality says that the support is an
inclusion-minimal generator of its own quotient closure. -/
theorem isPaperNormal_iff_isMinimalGenerator
    (B : FiniteSupport (ι := ι)) :
    IsPaperNormal σ B ↔
      σ.qClosure.IsMinimalGenerator B.1 (σ.qClosure B.1) := by
  rw [isPaperNormal_iff_pointwise σ B]
  exact
    (QuotientSubmoduleEquidistribution.SetClosure.isMinimalGenerator_closure_iff_pointwise
      σ.qClosure B.1).symm

/-- A finite support together with the assertion that its canonical basic
module is paper-normal. -/
abbrev BasicNormalModule :=
  {B : FiniteSupport (ι := ι) // IsPaperNormal σ B}

namespace BasicNormalModule

/-- The actual finitely generated module represented by a bundled basic
normal support. -/
abbrev object (M : BasicNormalModule σ) : FGModuleCat.{w} R :=
  σ.basicModule M.1

/-- The literal image in a skeleton of finitely generated modules of the
canonical basic normal modules.  This is a genuine quotient by module
isomorphism, restricted to the canonical modules classified here. -/
def IsoClass :=
  {X : Skeleton (FGModuleCat.{w} R) //
    ∃ M : BasicNormalModule σ,
      X = toSkeleton (object σ M)}

/-- Send a bundled canonical module to its module-isomorphism class. -/
def toIsoClass (M : BasicNormalModule σ) : IsoClass σ :=
  ⟨toSkeleton (object σ M), M, rfl⟩

namespace IsoClass

/-- Choose the unique canonical support represented by an isomorphism
class in the image. -/
noncomputable def representative (X : IsoClass σ) :
    BasicNormalModule σ :=
  Classical.choose X.2

theorem representative_spec (X : IsoClass σ) :
    X.1 = toSkeleton (object σ (representative σ X)) :=
  Classical.choose_spec X.2

end IsoClass

/-- Forget the concrete sum and retain the closure-theoretic normal
support. -/
def toNormalFiniteSupport (M : BasicNormalModule σ) :
    σ.qClosure.NormalFiniteSupport :=
  ⟨M.1.1, M.1.2,
    (isPaperNormal_iff_isMinimalGenerator σ M.1).1 M.2⟩

/-- Build the canonical basic normal module from a finite minimal support. -/
def ofNormalFiniteSupport
    (B : σ.qClosure.NormalFiniteSupport) :
    BasicNormalModule σ :=
  ⟨⟨B.1, B.2.1⟩,
    (isPaperNormal_iff_isMinimalGenerator σ
      ⟨B.1, B.2.1⟩).2 B.2.2⟩

/-- Bundled module presentations and finite normal supports contain exactly
the same data. -/
def equivNormalFiniteSupport :
    BasicNormalModule σ ≃
      σ.qClosure.NormalFiniteSupport where
  toFun := toNormalFiniteSupport σ
  invFun := ofNormalFiniteSupport σ
  left_inv M := by
    apply Subtype.ext
    apply Subtype.ext
    rfl
  right_inv B := by
    apply Subtype.ext
    rfl

/-- Passing from a canonical basic normal module to its actual module
isomorphism class loses no data: the support can be reconstructed uniquely. -/
noncomputable def equivIsoClass :
    BasicNormalModule σ ≃ IsoClass σ where
  toFun := toIsoClass σ
  invFun := IsoClass.representative σ
  left_inv M := by
    apply Subtype.ext
    apply finiteSupport_eq_of_basicModule_iso σ
    apply toSkeleton_eq_toSkeleton_iff.mp
    exact
      (IsoClass.representative_spec σ
        (toIsoClass σ M)).symm
  right_inv X := by
    apply Subtype.ext
    exact (IsoClass.representative_spec σ X).symm

/-- Composing with the production closure-theoretic equivalence classifies
canonical basic normal modules by compact quotient-closed supports. -/
def equivCompactClosed
    (hfin : σ.qClosure.IsFinitary)
    (hae : σ.qClosure.IsAntiExchange) :
    BasicNormalModule σ ≃
      σ.qClosure.CompactClosed :=
  (equivNormalFiniteSupport σ).trans
    (σ.qClosure.normalFiniteSupportEquivCompactClosed hfin hae)

/-- The quotient-by-isomorphism formulation of the classification:
isomorphism classes of canonical basic normal modules correspond to compact
quotient-closed supports. -/
noncomputable def isoClassEquivCompactClosed
    (hfin : σ.qClosure.IsFinitary)
    (hae : σ.qClosure.IsAntiExchange) :
    IsoClass σ ≃ σ.qClosure.CompactClosed :=
  (equivIsoClass σ).symm.trans
    (equivCompactClosed σ hfin hae)

end BasicNormalModule

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton
