import QuotientSubmoduleEquidistribution.RepresentationTheory.PeirceCotangentDetectors

/-!
# Peirce normal form for the loop--two-cycle relation ideal

This file isolates the abstract ring-theoretic normal form without constructing
a bound quiver algebra or classifying any modules.
-/

noncomputable section

namespace QuotientSubmoduleEquidistribution.QuotientSurvival

universe u

variable {K B : Type u}
  [Field K] [Ring B] [Algebra K B] [IsArtinianRing B]

private abbrev J (B : Type u) [Ring B] := Ring.jacobson B

/-- Exact right-generation form of cotangent exhaustion.  In an Artinian
algebra this follows from spanning `J/J^2` by the three displayed classes,
via nilpotence/Nakayama. -/
def JacobsonRightGeneratedBy (x a b : B) : Prop :=
  forall z : B, z ∈ J B ->
    exists rx ra rb : B, z = x * rx + a * ra + b * rb

omit [IsArtinianRing B] in
/-- The `(1,0)` Peirce corner of `J^2` is generated by `a` on the left.
This is the first exact consequence of right-generation of the radical. -/
theorem exists_eq_a_mul_of_mem_jacobsonSquare
    {e0 e1 x a b z : B}
    (he1x : e1 * x = 0)
    (he1a : e1 * a = a)
    (he1b : e1 * b = 0)
    (hgen : JacobsonRightGeneratedBy x a b)
    (hz : z ∈ (J B) ^ 2) :
    exists s : B, s ∈ J B ∧ e1 * z * e0 = a * s := by
  have hz' : z ∈ J B * J B := by
    rw [show (2 : Nat) = 1 + 1 by omega, Submodule.pow_succ,
      Submodule.pow_one] at hz
    exact hz
  refine Submodule.mul_induction_on hz' ?_ ?_
  · intro u hu v hv
    obtain ⟨rx, ra, rb, hu'⟩ := hgen u hu
    refine ⟨ra * v * e0, ?_, ?_⟩
    · exact (J B).mul_mem_right e0 ((J B).mul_mem_left ra hv)
    · calc
        e1 * (u * v) * e0 =
            (e1 * x) * (rx * v * e0) +
              (e1 * a) * (ra * v * e0) +
                (e1 * b) * (rb * v * e0) := by
          rw [hu']
          noncomm_ring
        _ = a * (ra * v * e0) := by rw [he1x, he1a, he1b]; simp
  · intro z w hz hw
    obtain ⟨s, hs, hzs⟩ := hz
    obtain ⟨t, ht, hwt⟩ := hw
    refine ⟨s + t, (J B).add_mem hs ht, ?_⟩
    calc
      e1 * (z + w) * e0 = e1 * z * e0 + e1 * w * e0 := by
        noncomm_ring
      _ = a * s + a * t := by rw [hzs, hwt]
      _ = a * (s + t) := by noncomm_ring

omit [IsArtinianRing B] in
/-- Under radical right-generation, every element of the `(0,0)` Peirce
corner of `J^3` has the exact form `x*t + (b*a)*s`, with `s` radical. -/
theorem exists_corner_normalForm_of_mem_jacobsonCube
    {e0 e1 x a b z : B}
    (he0x : e0 * x = x)
    (he0a : e0 * a = 0)
    (he0b : e0 * b = b)
    (he1x : e1 * x = 0)
    (he1a : e1 * a = a)
    (he1b : e1 * b = 0)
    (hbe1 : b * e1 = b)
    (hgen : JacobsonRightGeneratedBy x a b)
    (hz : z ∈ (J B) ^ 3) :
    exists t s : B, s ∈ J B ∧
      e0 * z * e0 = x * t + (b * a) * s := by
  have hz' : z ∈ J B * (J B) ^ 2 := by
    rw [show (3 : Nat) = 2 + 1 by omega,
      Ideal.IsTwoSided.pow_succ] at hz
    exact hz
  refine Submodule.mul_induction_on hz' ?_ ?_
  · intro u hu v hv
    obtain ⟨rx, ra, rb, hu'⟩ := hgen u hu
    have hrbv : rb * v ∈ (J B) ^ 2 :=
      ((J B) ^ 2).mul_mem_left rb hv
    obtain ⟨s, hs, hsEq⟩ :=
      exists_eq_a_mul_of_mem_jacobsonSquare
        (e0 := e0) he1x he1a he1b hgen hrbv
    refine ⟨rx * v * e0, s, hs, ?_⟩
    have hbcorner :
        b * (rb * v * e0) = b * (e1 * (rb * v) * e0) := by
      calc
        b * (rb * v * e0) = b * (rb * v) * e0 := by noncomm_ring
        _ = (b * e1) * (rb * v) * e0 := by rw [hbe1]
        _ = b * (e1 * (rb * v) * e0) := by noncomm_ring
    calc
      e0 * (u * v) * e0 =
          (e0 * x) * (rx * v * e0) +
            (e0 * a) * (ra * v * e0) +
              (e0 * b) * (rb * v * e0) := by
        rw [hu']
        noncomm_ring
      _ = x * (rx * v * e0) + b * (e1 * (rb * v) * e0) := by
        rw [he0x, he0a, he0b]
        simp only [zero_mul, add_zero, hbcorner]
      _ = x * (rx * v * e0) + b * (a * s) := by rw [hsEq]
      _ = x * (rx * v * e0) + (b * a) * s := by noncomm_ring
  · intro z w hz hw
    obtain ⟨tz, sz, hsz, hzEq⟩ := hz
    obtain ⟨tw, sw, hsw, hwEq⟩ := hw
    refine ⟨tz + tw, sz + sw, (J B).add_mem hsz hsw, ?_⟩
    calc
      e0 * (z + w) * e0 = e0 * z * e0 + e0 * w * e0 := by
        noncomm_ring
      _ = (x * tz + (b * a) * sz) +
          (x * tw + (b * a) * sw) := by rw [hzEq, hwEq]
      _ = x * (tz + tw) + (b * a) * (sz + sw) := by
        noncomm_ring

/-- A normal-form predicate stable under arbitrary multipliers. -/
private def UniversalCornerNormalForm
    (e0 x y : B) (z : B) : Prop :=
  forall p q : B, exists t s : B, s ∈ J B ∧
    e0 * p * z * q * e0 = x * t + y * s

omit [IsArtinianRing B] in
/-- Minimal abstract normal-form endpoint.  Besides the Peirce identities it
uses only:

* exact right-generation of `J` by `x,a,b` (the Nakayama lift of cotangent
  spanning),
* scalar-plus-radical exhaustion of the diagonal residue corner, and
* radicality of the off-diagonal residue corner.
-/
theorem relationIdeal_membership_normalForm_of_peirce
    {e0 e1 x a b : B}
    (he0idem : e0 * e0 = e0)
    (he0x : e0 * x = x)
    (he1a : e1 * a = a) (hae0 : a * e0 = a)
    (he0b : e0 * b = b) (hbe1 : b * e1 = b)
    (he0a : e0 * a = 0) (he1x : e1 * x = 0)
    (he1b : e1 * b = 0)
    (hxJ : x ∈ J B) (haJ : a ∈ J B) (hbJ : b ∈ J B)
    (hgen : JacobsonRightGeneratedBy x a b)
    (hdiag : forall p : B, exists c : K, exists r : B,
      r ∈ J B ∧ e0 * r = r ∧ e0 * p * e0 = c • e0 + r)
    (hoff : forall p : B, e0 * p * e1 ∈ J B)
    (hmem : b * a ∈
      TwoCoordinateData.loopTwoCycleRelationIdeal
        x a b) :
    exists t s : B, s ∈ J B ∧
      b * a = x * t + (b * a) * s := by
  let H : TwoSidedIdeal B :=
    TwoSidedIdeal.span
      (TwoCoordinateData.loopTwoCycleRelationSet x a b)
  have hmem' : b * a ∈ H := by simpa [H,
    TwoCoordinateData.loopTwoCycleRelationIdeal] using hmem
  have hspan : UniversalCornerNormalForm e0 x (b * a) (b * a) := by
    apply TwoSidedIdeal.span_induction (p := fun z _ =>
      UniversalCornerNormalForm e0 x (b * a) z) (s :=
        TwoCoordinateData.loopTwoCycleRelationSet x a b)
    · intro g hg p q
      rcases hg with hg3 | hg
      · have hpq : p * g * q ∈ (J B) ^ 3 :=
          ((J B) ^ 3).mul_mem_right q (((J B) ^ 3).mul_mem_left p hg3)
        obtain ⟨t, s, hs, hEq⟩ :=
          exists_corner_normalForm_of_mem_jacobsonCube
            he0x he0a he0b he1x he1a he1b hbe1 hgen hpq
        exact ⟨t, s, hs, by simpa only [mul_assoc] using hEq⟩
      · simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
        rcases hg with rfl | rfl | rfl | rfl
        · obtain ⟨c, r, hrJ, he0r, hpr⟩ := hdiag p
          have hcube : r * (x * x) * q ∈ (J B) ^ 3 := by
            have hxxx : r * (x * x) ∈ (J B) ^ 3 := by
              rw [show (3 : Nat) = 2 + 1 by omega,
                Ideal.IsTwoSided.pow_succ]
              exact Ideal.mul_mem_mul hrJ (by
                rw [show (2 : Nat) = 1 + 1 by omega,
                  Ideal.IsTwoSided.pow_succ, Submodule.pow_one]
                exact Ideal.mul_mem_mul hxJ hxJ)
            exact ((J B) ^ 3).mul_mem_right q hxxx
          obtain ⟨tr, sr, hsr, hrEq⟩ :=
            exists_corner_normalForm_of_mem_jacobsonCube
              he0x he0a he0b he1x he1a he1b hbe1 hgen hcube
          refine ⟨(algebraMap K B c) * x * q * e0 + tr, sr, hsr, ?_⟩
          calc
            e0 * p * (x * x) * q * e0 =
                (e0 * p * e0) * (x * x) * q * e0 := by
              calc
                e0 * p * (x * x) * q * e0 =
                    e0 * p * ((e0 * x) * x) * q * e0 := by rw [he0x]
                _ = (e0 * p * e0) * (x * x) * q * e0 := by
                  noncomm_ring
            _ = (c • e0 + r) * (x * x) * q * e0 := by rw [hpr]
            _ = (c • e0) * (x * x) * q * e0 +
                e0 * (r * (x * x) * q) * e0 := by
              calc
                (c • e0 + r) * (x * x) * q * e0 =
                    (c • e0) * (x * x) * q * e0 +
                      r * (x * x) * q * e0 := by noncomm_ring
                _ = (c • e0) * (x * x) * q * e0 +
                    (e0 * r) * (x * x) * q * e0 := by rw [he0r]
                _ = (c • e0) * (x * x) * q * e0 +
                    e0 * (r * (x * x) * q) * e0 := by noncomm_ring
            _ = (c • e0) * (x * x) * q * e0 +
                (x * tr + (b * a) * sr) := by rw [hrEq]
            _ = x * ((algebraMap K B c) * x * q * e0 + tr) +
                (b * a) * sr := by
              have hscalar :
                  (c • e0) * (x * x) * q * e0 =
                    x * ((algebraMap K B c) * x * q * e0) := by
                simp only [Algebra.smul_def]
                calc
                  (algebraMap K B c) * e0 * (x * x) * q * e0 =
                      (algebraMap K B c) * (e0 * x) * x * q * e0 := by
                    noncomm_ring
                  _ = (algebraMap K B c) * x * x * q * e0 := by rw [he0x]
                  _ = x * (algebraMap K B c) * x * q * e0 := by
                    rw [Algebra.commutes c x]
                  _ = x * ((algebraMap K B c) * x * q * e0) := by
                    noncomm_ring
              rw [hscalar]
              noncomm_ring
        · have hoffJ := hoff p
          have hcube : e0 * p * (a * x) * q ∈ (J B) ^ 3 := by
            have haxa : a * x ∈ (J B) ^ 2 := by
              rw [show (2 : Nat) = 1 + 1 by omega,
                Ideal.IsTwoSided.pow_succ, Submodule.pow_one]
              exact Ideal.mul_mem_mul haJ hxJ
            have hthree : (e0 * p * e1) * (a * x) ∈ (J B) ^ 3 := by
              rw [show (3 : Nat) = 2 + 1 by omega,
                Ideal.IsTwoSided.pow_succ]
              exact Ideal.mul_mem_mul hoffJ haxa
            have hthreeq := ((J B) ^ 3).mul_mem_right q hthree
            convert hthreeq using 1
            calc
              e0 * p * (a * x) * q =
                  e0 * p * ((e1 * a) * x) * q := by rw [he1a]
              _ = (e0 * p * e1) * (a * x) * q := by noncomm_ring
          obtain ⟨t, s, hs, hEq⟩ :=
            exists_corner_normalForm_of_mem_jacobsonCube
              he0x he0a he0b he1x he1a he1b hbe1 hgen hcube
          refine ⟨t, s, hs, ?_⟩
          calc
            e0 * p * (a * x) * q * e0 =
                e0 * (e0 * p * (a * x) * q) * e0 := by
              symm
              calc
                e0 * (e0 * p * (a * x) * q) * e0 =
                    (e0 * e0) * p * (a * x) * q * e0 := by noncomm_ring
                _ = e0 * p * (a * x) * q * e0 := by rw [he0idem]
            _ = x * t + (b * a) * s := hEq
        · obtain ⟨c, r, hrJ, he0r, hpr⟩ := hdiag p
          have hcube : r * (x * b) * q ∈ (J B) ^ 3 := by
            have hxxb : r * (x * b) ∈ (J B) ^ 3 := by
              rw [show (3 : Nat) = 2 + 1 by omega,
                Ideal.IsTwoSided.pow_succ]
              have hxb : x * b ∈ (J B) ^ 2 := by
                rw [show (2 : Nat) = 1 + 1 by omega,
                  Ideal.IsTwoSided.pow_succ, Submodule.pow_one]
                exact Ideal.mul_mem_mul hxJ hbJ
              exact Ideal.mul_mem_mul hrJ hxb
            exact ((J B) ^ 3).mul_mem_right q hxxb
          obtain ⟨tr, sr, hsr, hrEq⟩ :=
            exists_corner_normalForm_of_mem_jacobsonCube
              he0x he0a he0b he1x he1a he1b hbe1 hgen hcube
          refine ⟨(algebraMap K B c) * b * q * e0 + tr, sr, hsr, ?_⟩
          calc
            e0 * p * (x * b) * q * e0 =
                (e0 * p * e0) * (x * b) * q * e0 := by
              calc
                e0 * p * (x * b) * q * e0 =
                    e0 * p * ((e0 * x) * b) * q * e0 := by rw [he0x]
                _ = (e0 * p * e0) * (x * b) * q * e0 := by
                  noncomm_ring
            _ = (c • e0 + r) * (x * b) * q * e0 := by rw [hpr]
            _ = (c • e0) * (x * b) * q * e0 +
                e0 * (r * (x * b) * q) * e0 := by
              calc
                (c • e0 + r) * (x * b) * q * e0 =
                    (c • e0) * (x * b) * q * e0 +
                      r * (x * b) * q * e0 := by noncomm_ring
                _ = (c • e0) * (x * b) * q * e0 +
                    (e0 * r) * (x * b) * q * e0 := by rw [he0r]
                _ = (c • e0) * (x * b) * q * e0 +
                    e0 * (r * (x * b) * q) * e0 := by noncomm_ring
            _ = (c • e0) * (x * b) * q * e0 +
                (x * tr + (b * a) * sr) := by rw [hrEq]
            _ = x * ((algebraMap K B c) * b * q * e0 + tr) +
                (b * a) * sr := by
              have hscalar :
                  (c • e0) * (x * b) * q * e0 =
                    x * ((algebraMap K B c) * b * q * e0) := by
                simp only [Algebra.smul_def]
                calc
                  (algebraMap K B c) * e0 * (x * b) * q * e0 =
                      (algebraMap K B c) * (e0 * x) * b * q * e0 := by
                    noncomm_ring
                  _ = (algebraMap K B c) * x * b * q * e0 := by rw [he0x]
                  _ = x * (algebraMap K B c) * b * q * e0 := by
                    rw [Algebra.commutes c x]
                  _ = x * ((algebraMap K B c) * b * q * e0) := by
                    noncomm_ring
              rw [hscalar]
              noncomm_ring
        · have hoffJ := hoff p
          have hcube : e0 * p * (a * b) * q ∈ (J B) ^ 3 := by
            have hab2 : a * b ∈ (J B) ^ 2 := by
              rw [show (2 : Nat) = 1 + 1 by omega,
                Ideal.IsTwoSided.pow_succ, Submodule.pow_one]
              exact Ideal.mul_mem_mul haJ hbJ
            have hthree : (e0 * p * e1) * (a * b) ∈ (J B) ^ 3 := by
              rw [show (3 : Nat) = 2 + 1 by omega,
                Ideal.IsTwoSided.pow_succ]
              exact Ideal.mul_mem_mul hoffJ hab2
            have hthreeq := ((J B) ^ 3).mul_mem_right q hthree
            convert hthreeq using 1
            calc
              e0 * p * (a * b) * q =
                  e0 * p * ((e1 * a) * b) * q := by rw [he1a]
              _ = (e0 * p * e1) * (a * b) * q := by noncomm_ring
          obtain ⟨t, s, hs, hEq⟩ :=
            exists_corner_normalForm_of_mem_jacobsonCube
              he0x he0a he0b he1x he1a he1b hbe1 hgen hcube
          refine ⟨t, s, hs, ?_⟩
          calc
            e0 * p * (a * b) * q * e0 =
                e0 * (e0 * p * (a * b) * q) * e0 := by
              symm
              calc
                e0 * (e0 * p * (a * b) * q) * e0 =
                    (e0 * e0) * p * (a * b) * q * e0 := by noncomm_ring
                _ = e0 * p * (a * b) * q * e0 := by rw [he0idem]
            _ = x * t + (b * a) * s := hEq
    · intro p q
      exact ⟨0, 0, (J B).zero_mem, by simp⟩
    · intro z w _ _ hz hw p q
      obtain ⟨tz, sz, hsz, hzEq⟩ := hz p q
      obtain ⟨tw, sw, hsw, hwEq⟩ := hw p q
      refine ⟨tz + tw, sz + sw, (J B).add_mem hsz hsw, ?_⟩
      calc
        e0 * p * (z + w) * q * e0 =
            e0 * p * z * q * e0 + e0 * p * w * q * e0 := by
          noncomm_ring
        _ = (x * tz + (b * a) * sz) +
            (x * tw + (b * a) * sw) := by rw [hzEq, hwEq]
        _ = x * (tz + tw) + (b * a) * (sz + sw) := by
          noncomm_ring
    · intro z _ hz p q
      obtain ⟨t, s, hs, hEq⟩ := hz (-p) q
      refine ⟨t, s, hs, ?_⟩
      simpa only [mul_neg, neg_mul, neg_neg] using hEq
    · intro c z _ hz p q
      simpa only [mul_assoc] using hz (p * c) q
    · intro c z _ hz p q
      simpa only [mul_assoc] using hz p (c * q)
    · exact hmem'
  obtain ⟨t, s, hs, hEq⟩ := hspan 1 1
  refine ⟨t, s, hs, ?_⟩
  have hcorner : e0 * (b * a) * e0 = b * a := by
    rw [← mul_assoc, he0b, mul_assoc, hae0]
  simpa [hcorner] using hEq

/-! ## Lifting cotangent spanning to exact radical generation -/

/-- The three named radical classes span `J/J^2` over the ground field. -/
def JacobsonCotangentSpannedBy (x a b : B) : Prop :=
  forall z : B, z ∈ J B ->
    exists cx ca cb : K,
      z - (cx • x + ca • a + cb • b) ∈ (J B) ^ 2

private def IsRightGeneratedBy (x a b z : B) : Prop :=
  exists rx ra rb : B, z = x * rx + a * ra + b * rb

omit [IsArtinianRing B] in
private theorem isRightGeneratedBy_zero (x a b : B) :
    IsRightGeneratedBy x a b 0 := by
  exact ⟨0, 0, 0, by simp⟩

omit [IsArtinianRing B] in
private theorem IsRightGeneratedBy.add
    {x a b z w : B}
    (hz : IsRightGeneratedBy x a b z)
    (hw : IsRightGeneratedBy x a b w) :
    IsRightGeneratedBy x a b (z + w) := by
  obtain ⟨rx, ra, rb, rfl⟩ := hz
  obtain ⟨sx, sa, sb, rfl⟩ := hw
  refine ⟨rx + sx, ra + sa, rb + sb, ?_⟩
  noncomm_ring

omit [IsArtinianRing B] in
private theorem IsRightGeneratedBy.mul_right
    {x a b z : B}
    (hz : IsRightGeneratedBy x a b z) (w : B) :
    IsRightGeneratedBy x a b (z * w) := by
  obtain ⟨rx, ra, rb, rfl⟩ := hz
  refine ⟨rx * w, ra * w, rb * w, ?_⟩
  noncomm_ring

omit [IsArtinianRing B] in
private theorem exists_rightGenerated_add_square_of_cotangentSpanned
    {x a b z : B}
    (hspan : JacobsonCotangentSpannedBy (K := K) x a b)
    (hz : z ∈ J B) :
    exists g r : B,
      IsRightGeneratedBy x a b g ∧ r ∈ (J B) ^ 2 ∧ z = g + r := by
  obtain ⟨cx, ca, cb, hr⟩ := hspan z hz
  let g : B := cx • x + ca • a + cb • b
  let r : B := z - g
  have hg : IsRightGeneratedBy x a b g := by
    refine ⟨algebraMap K B cx, algebraMap K B ca,
      algebraMap K B cb, ?_⟩
    dsimp [g]
    simp only [Algebra.smul_def]
    rw [Algebra.commutes cx x, Algebra.commutes ca a,
      Algebra.commutes cb b]
  refine ⟨g, r, hg, ?_, ?_⟩
  · exact hr
  · dsimp [r]
    abel

omit [IsArtinianRing B] in
private theorem exists_rightGenerated_add_nextPower
    {x a b z : B}
    (hstep : forall u : B, u ∈ J B ->
      exists g r : B,
        IsRightGeneratedBy x a b g ∧
          r ∈ (J B) ^ 2 ∧ u = g + r)
    (n : Nat) (hz : z ∈ (J B) ^ (n + 1)) :
    exists g r : B,
      IsRightGeneratedBy x a b g ∧
        r ∈ (J B) ^ (n + 2) ∧ z = g + r := by
  have hz' : z ∈ J B * (J B) ^ n := by
    rw [Ideal.IsTwoSided.pow_succ] at hz
    exact hz
  refine Submodule.mul_induction_on hz' ?_ ?_
  · intro u hu v hv
    obtain ⟨g, r, hg, hr2, huEq⟩ := hstep u hu
    have hgr : IsRightGeneratedBy x a b (g * v) := hg.mul_right v
    have hrnext : r * v ∈ (J B) ^ (n + 2) := by
      have hprod : r * v ∈ (J B) ^ 2 * (J B) ^ n :=
        Ideal.mul_mem_mul hr2 hv
      have hp : r * v ∈ (J B) ^ (2 + n) := by
        rw [Ideal.IsTwoSided.pow_add]
        exact hprod
      simpa [Nat.add_comm] using hp
    refine ⟨g * v, r * v, hgr, hrnext, ?_⟩
    rw [huEq]
    noncomm_ring
  · intro z w hz hw
    obtain ⟨gz, rz, hgz, hrz, hzEq⟩ := hz
    obtain ⟨gw, rw, hgw, hrw, hwEq⟩ := hw
    refine ⟨gz + gw, rz + rw, hgz.add hgw,
      ((J B) ^ (n + 2)).add_mem hrz hrw, ?_⟩
    rw [hzEq, hwEq]
    abel

omit [IsArtinianRing B] in
private theorem exists_rightGenerated_add_power
    {x a b z : B}
    (hstep : forall u : B, u ∈ J B ->
      exists g r : B,
        IsRightGeneratedBy x a b g ∧
          r ∈ (J B) ^ 2 ∧ u = g + r)
    (hz : z ∈ J B) (n : Nat) :
    exists g r : B,
      IsRightGeneratedBy x a b g ∧
        r ∈ (J B) ^ (n + 1) ∧ z = g + r := by
  induction n with
  | zero =>
      refine ⟨0, z, isRightGeneratedBy_zero x a b, ?_, by simp⟩
      simpa [Submodule.pow_one] using hz
  | succ n ih =>
      obtain ⟨g, r, hg, hr, hzEq⟩ := ih
      obtain ⟨g', r', hg', hr', hrEq⟩ :=
        exists_rightGenerated_add_nextPower hstep n hr
      refine ⟨g + g', r', hg.add hg', ?_, ?_⟩
      · simpa [Nat.add_assoc] using hr'
      · rw [hzEq, hrEq]
        abel

/-- Nilpotence of the Artinian Jacobson radical lifts spanning of `J/J^2`
to exact right-generation of `J`.  This is the precise Nakayama step needed
by the Peirce normal-form proof. -/
theorem jacobsonRightGeneratedBy_of_cotangentSpanned
    {x a b : B}
    (hspan : JacobsonCotangentSpannedBy (K := K) x a b) :
    JacobsonRightGeneratedBy x a b := by
  intro z hz
  have hstep : forall u : B, u ∈ J B ->
      exists g r : B,
        IsRightGeneratedBy x a b g ∧
          r ∈ (J B) ^ 2 ∧ u = g + r := by
    intro u hu
    exact exists_rightGenerated_add_square_of_cotangentSpanned hspan hu
  obtain ⟨n, hn⟩ :=
    (IsArtinianRing.isNilpotent_jacobson_bot (R := B))
  have hn' : (J B) ^ n = 0 := by
    simpa only [J, Ideal.jacobson_bot] using hn
  obtain ⟨g, r, hg, hr, hzEq⟩ :=
    exists_rightGenerated_add_power hstep hz n
  have hrn : r ∈ (J B) ^ n :=
    Ideal.pow_le_pow_right (Nat.le_succ n) hr
  have hrzero : r = 0 := by
    rw [hn'] at hrn
    exact Ideal.mem_bot.mp hrn
  obtain ⟨rx, ra, rb, hgEq⟩ := hg
  refine ⟨rx, ra, rb, ?_⟩
  rw [hzEq, hrzero, add_zero, hgEq]

namespace TwoCoordinateData

variable (D : TwoCoordinateData (K := K) (B := B))

/-- The split-basic two-coordinate package supplies the residue-corner
hypotheses of `relationIdeal_membership_normalForm_of_peirce`.  Thus the only
new algebra hypothesis at this layer is exact right-generation of the
Jacobson radical by the three cotangent representatives. -/
theorem relationIdeal_membership_normalForm_of_jacobsonRightGenerated
    {x a b : B}
    (hxJ : x ∈ J B) (haJ : a ∈ J B) (hbJ : b ∈ J B)
    (hxleft : D.liftedCoordinate 0 * x = x)
    (haleft : D.liftedCoordinate 1 * a = a)
    (haright : a * D.liftedCoordinate 0 = a)
    (hbleft : D.liftedCoordinate 0 * b = b)
    (hbright : b * D.liftedCoordinate 1 = b)
    (hgen : JacobsonRightGeneratedBy x a b)
    (hmem : b * a ∈ loopTwoCycleRelationIdeal x a b) :
    exists t s : B, s ∈ J B ∧
      b * a = x * t + (b * a) * s := by
  let e0 := D.liftedCoordinate 0
  let e1 := D.liftedCoordinate 1
  have he0idem : e0 * e0 = e0 :=
    D.liftedCoordinate_complete.idem 0
  have he0a : e0 * a = 0 := by
    calc
      e0 * a = e0 * (e1 * a) := by rw [haleft]
      _ = (e0 * e1) * a := by rw [mul_assoc]
      _ = 0 := by
        rw [D.liftedCoordinate_complete.ortho (by decide : (0 : Fin 2) ≠ 1)]
        simp
  have he1x : e1 * x = 0 := by
    calc
      e1 * x = e1 * (e0 * x) := by rw [hxleft]
      _ = (e1 * e0) * x := by rw [mul_assoc]
      _ = 0 := by
        rw [D.liftedCoordinate_complete.ortho (by decide : (1 : Fin 2) ≠ 0)]
        simp
  have he1b : e1 * b = 0 := by
    calc
      e1 * b = e1 * (e0 * b) := by rw [hbleft]
      _ = (e1 * e0) * b := by rw [mul_assoc]
      _ = 0 := by
        rw [D.liftedCoordinate_complete.ortho (by decide : (1 : Fin 2) ≠ 0)]
        simp
  have hdiag : forall p : B, exists c : K, exists r : B,
      r ∈ J B ∧ e0 * r = r ∧ e0 * p * e0 = c • e0 + r := by
    intro p
    let c : K :=
      QuotientSubmoduleEquidistribution.CotangentExtBridge.CoordinateData.coordinateCharacter D 0 p
    let C : B := algebraMap K B c
    let r : B := e0 * p * e0 - c • e0
    have hscalar : e0 * C * e0 = C * e0 := by
      calc
        e0 * C * e0 = (C * e0) * e0 := by
          rw [← Algebra.commutes c e0]
        _ = C * (e0 * e0) := by rw [mul_assoc]
        _ = C * e0 := by rw [he0idem]
    have hbase : p * e0 - C * e0 ∈ J B := by
      simpa [e0, c, C] using
        QuotientSubmoduleEquidistribution.CotangentExtBridge.CoordinateData.mul_liftedCoordinate_sub_coordinate_mem_jacobson
          D 0 p
    have hleft : e0 * (p * e0 - C * e0) ∈ J B :=
      (J B).mul_mem_left e0 hbase
    have hrJ : r ∈ J B := by
      have heq : e0 * (p * e0 - C * e0) = r := by
        dsimp [r, C]
        simp only [Algebra.smul_def]
        calc
          e0 * (p * e0 - C * e0) =
              e0 * p * e0 - e0 * C * e0 := by noncomm_ring
          _ = e0 * p * e0 - C * e0 := by rw [hscalar]
      rw [heq] at hleft
      exact hleft
    have he0r : e0 * r = r := by
      dsimp [r, C]
      simp only [Algebra.smul_def]
      calc
        e0 * (e0 * p * e0 - C * e0) =
            (e0 * e0) * p * e0 - e0 * C * e0 := by noncomm_ring
        _ = e0 * p * e0 - C * e0 := by rw [he0idem, hscalar]
    refine ⟨c, r, hrJ, he0r, ?_⟩
    dsimp [r]
    abel
  have hoff : forall p : B, e0 * p * e1 ∈ J B := by
    intro p
    exact D.offDiagonal_mem_jacobson (by decide : (0 : Fin 2) ≠ 1) p
  exact relationIdeal_membership_normalForm_of_peirce
    he0idem hxleft haleft haright hbleft hbright he0a he1x he1b
      hxJ haJ hbJ hgen hdiag hoff hmem

/-- Paper-facing normal form from the natural cotangent-exhaustion
hypothesis.  There is no separate exact-generation premise: Artinian
nilpotence lifts the spanning statement automatically. -/
theorem relationIdeal_membership_normalForm_of_cotangentSpanned
    {x a b : B}
    (hxJ : x ∈ J B) (haJ : a ∈ J B) (hbJ : b ∈ J B)
    (hxleft : D.liftedCoordinate 0 * x = x)
    (haleft : D.liftedCoordinate 1 * a = a)
    (haright : a * D.liftedCoordinate 0 = a)
    (hbleft : D.liftedCoordinate 0 * b = b)
    (hbright : b * D.liftedCoordinate 1 = b)
    (hspan : JacobsonCotangentSpannedBy (K := K) x a b)
    (hmem : b * a ∈ loopTwoCycleRelationIdeal x a b) :
    exists t s : B, s ∈ J B ∧
      b * a = x * t + (b * a) * s :=
  D.relationIdeal_membership_normalForm_of_jacobsonRightGenerated
    hxJ haJ hbJ hxleft haleft haright hbleft hbright
      (jacobsonRightGeneratedBy_of_cotangentSpanned hspan) hmem

/-- Cotangent spanning removes the last survival premise from the filtered
six-class independence theorem.  The remaining inputs are exactly the
Peirce representatives, their nonzero cotangent classes, and the cyclic
right-ideal isomorphism used in the manuscript's contradiction. -/
theorem six_relationQuotientClasses_linearIndependent_of_cotangentSpanned
    [FiniteDimensional K B]
    {x a b : B}
    (hxJ : x ∈ J B) (haJ : a ∈ J B) (hbJ : b ∈ J B)
    (hxleft : D.liftedCoordinate 0 * x = x)
    (hxright : x * D.liftedCoordinate 0 = x)
    (haleft : D.liftedCoordinate 1 * a = a)
    (haright : a * D.liftedCoordinate 0 = a)
    (hbleft : D.liftedCoordinate 0 * b = b)
    (hbright : b * D.liftedCoordinate 1 = b)
    (hx2 : x ∉ (J B) ^ 2)
    (ha2 : a ∉ (J B) ^ 2)
    (hb2 : b ∉ (J B) ^ 2)
    (hcyclic : QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG (b * a) ≅
      QuotientSubmoduleEquidistribution.Tsukamoto.cyclicRightIdealFG x)
    (hspan : JacobsonCotangentSpannedBy (K := K) x a b) :
    LinearIndependent K
      (fun i ↦ Ideal.Quotient.mk (loopTwoCycleRelationIdeal x a b)
        (D.sixPeirceElements x a b i)) := by
  apply D.six_quotientClasses_linearIndependent_of_peirceCotangent_of_normalForm
    hxJ haJ hbJ hxleft hxright haleft haright hbleft hbright
      hx2 ha2 hb2 hcyclic (loopTwoCycleRelationIdeal x a b)
      (loopTwoCycleRelationIdeal_le_jacobsonSquare hxJ haJ hbJ)
  intro hmem
  exact D.relationIdeal_membership_normalForm_of_cotangentSpanned
    hxJ haJ hbJ hxleft haleft haright hbleft hbright hspan hmem

end TwoCoordinateData

end QuotientSubmoduleEquidistribution.QuotientSurvival
