import QuotientSubmoduleEquidistribution.RepresentationTheory.RingelComplexQuotient

/-!
# Strong Hom duality on Ringel's elementary quotient

Degreewise projective Hom duality reverses the four elementary
three-term complexes.  This file proves that it preserves and reflects
the finite additive ideal generated by those complexes, descends to the
factor category, and induces the anti-equivalence

`(E(H) / U)ᵒᵖ ≌ E(H.rightOp.symm) / U`.

The proof also supplies the explicit comparison between quotienting an
opposite category and taking the opposite of the quotient.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits Opposite

namespace QuotientSubmoduleEquidistribution.RingelEta

universe u u'

open QuotientSubmoduleEquidistribution.RingelStable

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {S : Type u'} [Ring S] [IsNoetherianRing S]

theorem targetStronglyExactProperty_eq
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    targetStronglyExactProperty H =
      stronglyExactProperty H.rightOp.symm := by
  rfl

@[simp]
theorem stronglyExactComplexAntiEquivalence_obj_obj
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (X : StronglyExactComplexCategory H) :
    ((stronglyExactComplexAntiEquivalence H).functor.obj
      (Opposite.op X)).obj =
        (mapShortComplexAntiEquivalence H).functor.obj
          (Opposite.op X.obj) := by
  rfl

/-- Degree reversal on the four elementary complexes. -/
def ElementaryKind.dual : ElementaryKind → ElementaryKind
  | .leftStalk => .rightStalk
  | .leftContractible => .rightContractible
  | .rightContractible => .leftContractible
  | .rightStalk => .leftStalk

/-- Hom duality identifies its image of the chosen zero projective with the
chosen zero projective on the target side. -/
def homDualZeroIso
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    H.functor.obj (Opposite.op (zeroFGProjective (R := R))) ≅
      zeroFGProjective (R := S) :=
  IsZero.iso
    (H.functor.map_isZero isZero_zeroFGProjective.op)
    isZero_zeroFGProjective

/-- Regard a target-side elementary complex as an object of the target
property used by the restricted anti-equivalence. -/
def targetElementaryStrongComplex
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) (P : FGProjectives (R := S)) :
    (targetStronglyExactProperty H).FullSubcategory :=
  ⟨elementaryProjectiveComplex k P,
    elementaryProjectiveComplex_stronglyExact H.rightOp.symm k P⟩

/-- Changing the projective parameter by an isomorphism changes the
corresponding elementary complex by an isomorphism. -/
def elementaryProjectiveComplexIso
    (k : ElementaryKind) {P Q : FGProjectives (R := S)}
    (e : P ≅ Q) :
    elementaryProjectiveComplex k P ≅ elementaryProjectiveComplex k Q := by
  cases k with
  | leftStalk =>
      exact ShortComplex.isoMk e (Iso.refl _) (Iso.refl _)
        (by simp [elementaryProjectiveComplex])
        (by simp [elementaryProjectiveComplex])
  | leftContractible =>
      exact ShortComplex.isoMk e e (Iso.refl _)
        (by simp [elementaryProjectiveComplex])
        (by simp [elementaryProjectiveComplex])
  | rightContractible =>
      exact ShortComplex.isoMk (Iso.refl _) e e
        (by simp [elementaryProjectiveComplex])
        (by simp [elementaryProjectiveComplex])
  | rightStalk =>
      exact ShortComplex.isoMk (Iso.refl _) (Iso.refl _) e
        (by simp [elementaryProjectiveComplex])
        (by simp [elementaryProjectiveComplex])

/-- Changing the projective parameter by an isomorphism changes the
corresponding target elementary complex by an isomorphism. -/
def targetElementaryStrongComplexIso
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) {P Q : FGProjectives (R := S)}
    (e : P ≅ Q) :
    targetElementaryStrongComplex H k P ≅
      targetElementaryStrongComplex H k Q :=
  ObjectProperty.isoMk _ (elementaryProjectiveComplexIso k e)

/-- Reversing the elementary shape twice is the identity. -/
@[simp]
theorem ElementaryKind.dual_dual (k : ElementaryKind) :
    k.dual.dual = k := by
  cases k <;> rfl

/-- The underlying short complex obtained by degreewise Hom from an
elementary complex is the reversed elementary complex, up to the unique
zero-object identifications. -/
def homDualElementaryUnderlyingIso
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) (P : FGProjectives (R := R)) :
    (mapShortComplexAntiEquivalence H).functor.obj
        (Opposite.op (elementaryProjectiveComplex k P)) ≅
      elementaryProjectiveComplex k.dual
        (H.functor.obj (Opposite.op P)) := by
  cases k with
  | leftStalk =>
      exact ShortComplex.isoMk
        (homDualZeroIso H) (homDualZeroIso H) (Iso.refl _)
        (by simp [ElementaryKind.dual, elementaryProjectiveComplex])
        (by simp [ElementaryKind.dual, elementaryProjectiveComplex])
  | leftContractible =>
      exact ShortComplex.isoMk
        (homDualZeroIso H) (Iso.refl _) (Iso.refl _)
        (by simp [ElementaryKind.dual, elementaryProjectiveComplex])
        (by simp [ElementaryKind.dual, elementaryProjectiveComplex])
  | rightContractible =>
      exact ShortComplex.isoMk
        (Iso.refl _) (Iso.refl _) (homDualZeroIso H)
        (by simp [ElementaryKind.dual, elementaryProjectiveComplex])
        (by simp [ElementaryKind.dual, elementaryProjectiveComplex])
  | rightStalk =>
      exact ShortComplex.isoMk
        (Iso.refl _) (homDualZeroIso H) (homDualZeroIso H)
        (by simp [ElementaryKind.dual, elementaryProjectiveComplex])
        (by simp [ElementaryKind.dual, elementaryProjectiveComplex])

/-- Degreewise Hom sends each elementary strongly exact complex to the
degree-reversed elementary complex, up to the unique zero-object
identifications. -/
def homDualElementaryIso
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) (P : FGProjectives (R := R)) :
    (stronglyExactComplexAntiEquivalence H).functor.obj
        (Opposite.op (elementaryStrongComplex H k P)) ≅
      targetElementaryStrongComplex H k.dual
        (H.functor.obj (Opposite.op P)) :=
  ObjectProperty.isoMk _
    (eqToIso (stronglyExactComplexAntiEquivalence_obj_obj H
        (elementaryStrongComplex H k P)) ≪≫
      homDualElementaryUnderlyingIso H k P)

/-! ## The target null ideal -/

/-- The finite additive ideal generated by the four elementary complexes
on the target side of the strong Hom anti-equivalence. -/
inductive FactorsThroughTargetRingelU
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    {X Y : (targetStronglyExactProperty H).FullSubcategory} :
    (X ⟶ Y) → Prop
  | zero : FactorsThroughTargetRingelU H 0
  | basic (k : ElementaryKind) (P : FGProjectives (R := S))
      (a : X ⟶ targetElementaryStrongComplex H k P)
      (b : targetElementaryStrongComplex H k P ⟶ Y) :
      FactorsThroughTargetRingelU H (a ≫ b)
  | add {f g : X ⟶ Y} :
      FactorsThroughTargetRingelU H f →
      FactorsThroughTargetRingelU H g →
      FactorsThroughTargetRingelU H (f + g)

instance stronglyExactComplexAntiEquivalence_functor_additive
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    (stronglyExactComplexAntiEquivalence H).functor.Additive where
  map_add {X Y} f g := by
    apply ObjectProperty.hom_ext
    apply ShortComplex.hom_ext
    · change H.functor.map
          ((f.unop.hom.τ₃ + g.unop.hom.τ₃).op) =
        H.functor.map f.unop.hom.τ₃.op +
          H.functor.map g.unop.hom.τ₃.op
      rw [op_add, H.functor.map_add]
    · change H.functor.map
          ((f.unop.hom.τ₂ + g.unop.hom.τ₂).op) =
        H.functor.map f.unop.hom.τ₂.op +
          H.functor.map g.unop.hom.τ₂.op
      rw [op_add, H.functor.map_add]
    · change H.functor.map
          ((f.unop.hom.τ₁ + g.unop.hom.τ₁).op) =
        H.functor.map f.unop.hom.τ₁.op +
          H.functor.map g.unop.hom.τ₁.op
      rw [op_add, H.functor.map_add]

/-- Strong Hom duality carries the source null ideal into the explicit
target null ideal. -/
theorem homDual_map_factorsThroughRingelU
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive]
    {X Y : StronglyExactComplexCategory H} {f : X ⟶ Y}
    (hf : FactorsThroughRingelU f) :
    FactorsThroughTargetRingelU H
      ((stronglyExactComplexAntiEquivalence H).functor.map f.op) := by
  let A := (stronglyExactComplexAntiEquivalence H).functor
  induction hf with
  | zero =>
      change FactorsThroughTargetRingelU H (A.map (0 : Opposite.op Y ⟶ Opposite.op X))
      rw [A.map_zero]
      exact FactorsThroughTargetRingelU.zero
  | basic k P a b =>
      let e := homDualElementaryIso H k P
      change FactorsThroughTargetRingelU H (A.map (b.op ≫ a.op))
      rw [A.map_comp]
      convert FactorsThroughTargetRingelU.basic k.dual
        (H.functor.obj (Opposite.op P))
        (A.map b.op ≫ e.hom) (e.inv ≫ A.map a.op) using 1
      simp [Category.assoc]
  | add hf hg ihf ihg =>
      rw [op_add, A.map_add]
      exact ihf.add ihg

/-- A target elementary complex is in the essential image of the
degree-reversed source elementary complex. -/
def homDualElementaryPreimageIso
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) (P : FGProjectives (R := S)) :
    (stronglyExactComplexAntiEquivalence H).functor.obj
        (Opposite.op
          (elementaryStrongComplex H k.dual
            (H.functor.objPreimage P).unop)) ≅
      targetElementaryStrongComplex H k P := by
  cases k <;>
    exact
      homDualElementaryIso H _ (H.functor.objPreimage P).unop ≪≫
        targetElementaryStrongComplexIso H _
          (H.functor.objObjPreimageIso P)

/-- Every target morphism in the elementary ideal has a source preimage in
the elementary ideal. -/
theorem homDual_preimage_factorsThroughTargetRingelU
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive]
    {X Y : (StronglyExactComplexCategory H)ᵒᵖ}
    {h :
      (stronglyExactComplexAntiEquivalence H).functor.obj X ⟶
        (stronglyExactComplexAntiEquivalence H).functor.obj Y}
    (hh : FactorsThroughTargetRingelU H h) :
    ∃ f : X ⟶ Y,
      (stronglyExactComplexAntiEquivalence H).functor.map f = h ∧
        FactorsThroughRingelU f.unop := by
  let A := (stronglyExactComplexAntiEquivalence H).functor
  induction hh with
  | zero =>
      refine ⟨0, ?_, ?_⟩
      · simp
      · exact FactorsThroughRingelU.zero
  | basic k P a b =>
      let e := homDualElementaryPreimageIso H k P
      let α := A.preimage (a ≫ e.inv)
      let β := A.preimage (e.hom ≫ b)
      refine ⟨α ≫ β, ?_, ?_⟩
      · rw [A.map_comp, A.map_preimage, A.map_preimage]
        simp [Category.assoc]
      · exact FactorsThroughRingelU.basic k.dual
          (H.functor.objPreimage P).unop β.unop α.unop
  | add hf hg ihf ihg =>
      rcases ihf with ⟨f, hmapf, hfU⟩
      rcases ihg with ⟨g, hmapg, hgU⟩
      refine ⟨f + g, ?_, ?_⟩
      · rw [A.map_add, hmapf, hmapg]
      · simpa only [unop_add] using hfU.add hgU

/-- Strong Hom duality reflects, as well as preserves, the elementary
null ideal. -/
theorem homDual_reflects_factorsThroughRingelU
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive]
    {X Y : (StronglyExactComplexCategory H)ᵒᵖ} {f : X ⟶ Y}
    (hf : FactorsThroughTargetRingelU H
      ((stronglyExactComplexAntiEquivalence H).functor.map f)) :
    FactorsThroughRingelU f.unop := by
  let A := (stronglyExactComplexAntiEquivalence H).functor
  rcases homDual_preimage_factorsThroughTargetRingelU H hf with
    ⟨g, hmap, hg⟩
  have hgf : g = f := A.map_injective hmap
  subst g
  exact hg

namespace FactorsThroughTargetRingelU

variable
  {H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)}

theorem neg
    {X Y : (targetStronglyExactProperty H).FullSubcategory}
    {f : X ⟶ Y} (hf : FactorsThroughTargetRingelU H f) :
    FactorsThroughTargetRingelU H (-f) := by
  induction hf with
  | zero =>
      simpa using
        (FactorsThroughTargetRingelU.zero :
          FactorsThroughTargetRingelU H (0 : X ⟶ Y))
  | basic k P a b =>
      simpa only [Preadditive.comp_neg] using
        (FactorsThroughTargetRingelU.basic k P a (-b))
  | add hf hg ihf ihg =>
      simpa only [neg_add_rev] using ihg.add ihf

theorem precomp
    {W X Y : (targetStronglyExactProperty H).FullSubcategory}
    (c : W ⟶ X) {f : X ⟶ Y}
    (hf : FactorsThroughTargetRingelU H f) :
    FactorsThroughTargetRingelU H (c ≫ f) := by
  induction hf with
  | zero =>
      simpa using
        (FactorsThroughTargetRingelU.zero :
          FactorsThroughTargetRingelU H (0 : W ⟶ Y))
  | basic k P a b =>
      simpa only [Category.assoc] using
        FactorsThroughTargetRingelU.basic k P (c ≫ a) b
  | add hf hg ihf ihg =>
      simpa only [Preadditive.comp_add] using ihf.add ihg

theorem postcomp
    {X Y Z : (targetStronglyExactProperty H).FullSubcategory}
    {f : X ⟶ Y} (hf : FactorsThroughTargetRingelU H f)
    (c : Y ⟶ Z) :
    FactorsThroughTargetRingelU H (f ≫ c) := by
  induction hf with
  | zero =>
      simpa using
        (FactorsThroughTargetRingelU.zero :
          FactorsThroughTargetRingelU H (0 : X ⟶ Z))
  | basic k P a b =>
      simpa only [← Category.assoc] using
        FactorsThroughTargetRingelU.basic k P a (b ≫ c)
  | add hf hg ihf ihg =>
      simpa only [Preadditive.add_comp] using ihf.add ihg

end FactorsThroughTargetRingelU

/-- Forget the target presentation of strong exactness in favor of the
ordinary strong-exactness property for the inverse anti-equivalence. -/
def targetStronglyExactToStandardFunctor
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetStronglyExactProperty H).FullSubcategory ⥤
      StronglyExactComplexCategory H.rightOp.symm where
  obj X := ⟨X.obj, X.property⟩
  map f := ObjectProperty.homMk f.hom
  map_id X := by
    apply ObjectProperty.hom_ext
    rfl
  map_comp f g := by
    apply ObjectProperty.hom_ext
    rfl

instance targetStronglyExactToStandardFunctor_additive
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetStronglyExactToStandardFunctor H).Additive where
  map_add {X Y} f g := by
    apply ObjectProperty.hom_ext
    rfl

instance targetStronglyExactToStandardFunctor_full
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetStronglyExactToStandardFunctor H).Full where
  map_surjective f := by
    refine ⟨ObjectProperty.homMk f.hom, ?_⟩
    apply ObjectProperty.hom_ext
    rfl

instance targetStronglyExactToStandardFunctor_faithful
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetStronglyExactToStandardFunctor H).Faithful where
  map_injective {X Y} f g hfg := by
    apply ObjectProperty.hom_ext
    exact congrArg (fun h ↦ h.hom) hfg

instance targetStronglyExactToStandardFunctor_essSurj
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetStronglyExactToStandardFunctor H).EssSurj where
  mem_essImage Y :=
    ⟨⟨Y.obj, Y.property⟩,
      ⟨ObjectProperty.isoMk _ (Iso.refl _)⟩⟩

instance targetStronglyExactToStandardFunctor_isEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetStronglyExactToStandardFunctor H).IsEquivalence where

/-- The target presentation of strong exactness is equivalent to the
ordinary presentation for the inverse projective anti-equivalence. -/
def targetStronglyExactEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetStronglyExactProperty H).FullSubcategory ≌
      StronglyExactComplexCategory H.rightOp.symm :=
  (targetStronglyExactToStandardFunctor H).asEquivalence

/-- Under the presentation equivalence, a target elementary complex is
the corresponding ordinary elementary complex. -/
def targetElementaryMappedIso
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) (P : FGProjectives (R := S)) :
    (targetStronglyExactToStandardFunctor H).obj
        (targetElementaryStrongComplex H k P) ≅
      elementaryStrongComplex H.rightOp.symm k P :=
  ObjectProperty.isoMk _ (Iso.refl _)

/-- The explicit target ideal is the ordinary Ringel elementary ideal for
the inverse projective anti-equivalence. -/
theorem factorsThroughTargetRingelU_iff
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    {X Y : StronglyExactComplexCategory H.rightOp.symm}
    (f : X ⟶ Y) :
    FactorsThroughTargetRingelU H f ↔
      FactorsThroughRingelU (H := H.rightOp.symm) f := by
  constructor
  · intro hf
    induction hf with
    | zero => exact FactorsThroughRingelU.zero
    | basic k P a b =>
        let a' :
            X ⟶ elementaryStrongComplex H.rightOp.symm k P :=
          ObjectProperty.homMk a.hom
        let b' :
            elementaryStrongComplex H.rightOp.symm k P ⟶ Y :=
          ObjectProperty.homMk b.hom
        convert FactorsThroughRingelU.basic k P a' b' using 1
        apply ObjectProperty.hom_ext
        rfl
    | add hf hg ihf ihg => exact ihf.add ihg
  · intro hf
    induction hf with
    | zero => exact FactorsThroughTargetRingelU.zero
    | basic k P a b =>
        let a' : X ⟶ targetElementaryStrongComplex H k P :=
          ObjectProperty.homMk a.hom
        let b' : targetElementaryStrongComplex H k P ⟶ Y :=
          ObjectProperty.homMk b.hom
        convert FactorsThroughTargetRingelU.basic k P a' b' using 1
        apply ObjectProperty.hom_ext
        rfl
    | add hf hg ihf ihg => exact ihf.add ihg

/-- The presentation equivalence carries the explicit target elementary
ideal into the ordinary elementary ideal. -/
theorem targetStronglyExact_map_factorsThroughRingelU
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    {X Y : (targetStronglyExactProperty H).FullSubcategory}
    {f : X ⟶ Y} (hf : FactorsThroughTargetRingelU H f) :
    FactorsThroughRingelU
      ((targetStronglyExactToStandardFunctor H).map f) := by
  let E := targetStronglyExactToStandardFunctor H
  induction hf with
  | zero =>
      change FactorsThroughRingelU (E.map (0 : X ⟶ Y))
      rw [E.map_zero]
      exact FactorsThroughRingelU.zero
  | basic k P a b =>
      let e := targetElementaryMappedIso H k P
      change FactorsThroughRingelU (E.map (a ≫ b))
      rw [E.map_comp]
      convert FactorsThroughRingelU.basic k P
        (E.map a ≫ e.hom) (e.inv ≫ E.map b) using 1
      simp [Category.assoc]
  | add hf hg ihf ihg =>
      rw [E.map_add]
      exact ihf.add ihg

/-- Every ordinary elementary-ideal morphism between objects in the image
has a target preimage in the explicit elementary ideal. -/
theorem targetStronglyExact_preimage_factorsThroughRingelU
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    {X Y : (targetStronglyExactProperty H).FullSubcategory}
    {h :
      (targetStronglyExactToStandardFunctor H).obj X ⟶
        (targetStronglyExactToStandardFunctor H).obj Y}
    (hh : FactorsThroughRingelU h) :
    ∃ f : X ⟶ Y,
      (targetStronglyExactToStandardFunctor H).map f = h ∧
        FactorsThroughTargetRingelU H f := by
  let E := targetStronglyExactToStandardFunctor H
  induction hh with
  | zero =>
      refine ⟨0, ?_, ?_⟩
      · simp
      · exact FactorsThroughTargetRingelU.zero
  | basic k P a b =>
      let e := targetElementaryMappedIso H k P
      let α := E.preimage (a ≫ e.inv)
      let β := E.preimage (e.hom ≫ b)
      refine ⟨α ≫ β, ?_, ?_⟩
      · rw [E.map_comp, E.map_preimage, E.map_preimage]
        simp [Category.assoc]
      · exact FactorsThroughTargetRingelU.basic k P α β
  | add hf hg ihf ihg =>
      rcases ihf with ⟨f, hmapf, hfU⟩
      rcases ihg with ⟨g, hmapg, hgU⟩
      refine ⟨f + g, ?_, ?_⟩
      · rw [E.map_add, hmapf, hmapg]
      · exact hfU.add hgU

/-- The presentation equivalence reflects the elementary ideal. -/
theorem targetStronglyExact_reflects_factorsThroughRingelU
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    {X Y : (targetStronglyExactProperty H).FullSubcategory}
    {f : X ⟶ Y}
    (hf : FactorsThroughRingelU
      ((targetStronglyExactToStandardFunctor H).map f)) :
    FactorsThroughTargetRingelU H f := by
  let E := targetStronglyExactToStandardFunctor H
  rcases targetStronglyExact_preimage_factorsThroughRingelU H hf with
    ⟨g, hmap, hg⟩
  have hgf : g = f := E.map_injective hmap
  subst g
  exact hg

/-- Equality modulo the target elementary ideal. -/
def targetRingelURel
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    HomRel (targetStronglyExactProperty H).FullSubcategory :=
  fun _ _ f g ↦ Nonempty (FactorsThroughTargetRingelU H (f - g))

instance targetRingelURel_congruence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    Congruence (targetRingelURel H) where
  equivalence :=
    { refl := fun f ↦ ⟨by
        simpa using
          (FactorsThroughTargetRingelU.zero :
            FactorsThroughTargetRingelU H (0 : _ ⟶ _))⟩
      symm := by
        rintro f g ⟨h⟩
        exact ⟨by
          convert h.neg using 1
          abel⟩
      trans := by
        rintro f g h ⟨hfg⟩ ⟨hgh⟩
        exact ⟨by
          convert hfg.add hgh using 1
          abel⟩ }
  comp_left := by
    rintro X Y Z a f g ⟨hfg⟩
    exact ⟨by
      simpa only [Preadditive.comp_sub] using hfg.precomp a⟩
  comp_right := by
    rintro X Y Z f g b ⟨hfg⟩
    exact ⟨by
      simpa only [Preadditive.sub_comp] using hfg.postcomp b⟩

/-- The presentation equivalence identifies exactly the target and
ordinary elementary congruences. -/
theorem targetStronglyExact_ringelURel_iff
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    {X Y : (targetStronglyExactProperty H).FullSubcategory}
    (f g : X ⟶ Y) :
    targetRingelURel H f g ↔
      ringelURel H.rightOp.symm
        ((targetStronglyExactToStandardFunctor H).map f)
        ((targetStronglyExactToStandardFunctor H).map g) := by
  constructor
  · rintro ⟨hfg⟩
    refine ⟨?_⟩
    have hmap :=
      targetStronglyExact_map_factorsThroughRingelU H hfg
    simpa only [
      (targetStronglyExactToStandardFunctor H).map_sub] using hmap
  · rintro ⟨hfg⟩
    refine ⟨targetStronglyExact_reflects_factorsThroughRingelU H ?_⟩
    simpa only [
      (targetStronglyExactToStandardFunctor H).map_sub] using hfg

/-- The source null relation viewed on the opposite strongly exact
category. -/
def sourceOpRingelURel
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    HomRel (StronglyExactComplexCategory H)ᵒᵖ :=
  fun _ _ f g ↦ ringelURel H f.unop g.unop

instance sourceOpRingelURel_congruence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    Congruence (sourceOpRingelURel H) where
  equivalence := by
    intro X Y
    exact
      { refl := fun f ↦ ⟨by
          simpa using
            (FactorsThroughRingelU.zero :
              FactorsThroughRingelU (0 : Y.unop ⟶ X.unop))⟩
        symm := by
          rintro f g ⟨h⟩
          exact ⟨by
            convert h.neg using 1
            abel⟩
        trans := by
          rintro f g h ⟨hfg⟩ ⟨hgh⟩
          exact ⟨by
            convert hfg.add hgh using 1
            abel⟩ }
  comp_left := by
    intro X Y Z f g g' h
    exact HomRel.comp_right f.unop h
  comp_right := by
    intro X Y Z f f' g h
    exact HomRel.comp_left g.unop h

/-- Opposite presentation of the source factor category. -/
abbrev RingelComplexOpQuotient
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :=
  CategoryTheory.Quotient (sourceOpRingelURel H)

/-- The target factor category by its explicit elementary ideal. -/
abbrev TargetRingelComplexQuotient
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :=
  CategoryTheory.Quotient (targetRingelURel H)

/-- The target elementary quotient maps to the ordinary Ringel quotient
for the inverse projective anti-equivalence. -/
def targetRingelQuotientComparisonFunctor
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    TargetRingelComplexQuotient H ⥤
      RingelComplexQuotient H.rightOp.symm :=
  CategoryTheory.Quotient.lift (targetRingelURel H)
    (targetStronglyExactToStandardFunctor H ⋙
      ringelComplexQuotientFunctor H.rightOp.symm) <| by
        intro X Y f g hfg
        apply CategoryTheory.Quotient.sound
          (ringelURel H.rightOp.symm)
        exact (targetStronglyExact_ringelURel_iff H f g).1 hfg

instance targetRingelQuotientComparisonFunctor_full
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetRingelQuotientComparisonFunctor H).Full where
  map_surjective {X Y} h := by
    obtain ⟨h, rfl⟩ :=
      (ringelComplexQuotientFunctor
        H.rightOp.symm).map_surjective h
    obtain ⟨f, rfl⟩ :=
      (targetStronglyExactToStandardFunctor H).map_surjective h
    exact ⟨(CategoryTheory.Quotient.functor
      (targetRingelURel H)).map f, rfl⟩

instance targetRingelQuotientComparisonFunctor_faithful
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetRingelQuotientComparisonFunctor H).Faithful where
  map_injective {X Y} f g hfg := by
    obtain ⟨f, rfl⟩ :=
      (CategoryTheory.Quotient.functor
        (targetRingelURel H)).map_surjective f
    obtain ⟨g, rfl⟩ :=
      (CategoryTheory.Quotient.functor
        (targetRingelURel H)).map_surjective g
    apply CategoryTheory.Quotient.sound (targetRingelURel H)
    exact (targetStronglyExact_ringelURel_iff H f g).2 <|
      (CategoryTheory.Quotient.functor_map_eq_iff
        (ringelURel H.rightOp.symm)
        ((targetStronglyExactToStandardFunctor H).map f)
        ((targetStronglyExactToStandardFunctor H).map g)).1 hfg

instance targetRingelQuotientComparisonFunctor_essSurj
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetRingelQuotientComparisonFunctor H).EssSurj where
  mem_essImage Y := by
    let E := targetStronglyExactToStandardFunctor H
    refine ⟨(CategoryTheory.Quotient.functor
      (targetRingelURel H)).obj (E.objPreimage Y.as), ?_⟩
    exact ⟨(ringelComplexQuotientFunctor
      H.rightOp.symm).mapIso (E.objObjPreimageIso Y.as)⟩

instance targetRingelQuotientComparisonFunctor_isEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (targetRingelQuotientComparisonFunctor H).IsEquivalence where

/-- The explicit target elementary quotient is equivalent to the ordinary
Ringel quotient for the inverse anti-equivalence. -/
def targetRingelQuotientComparisonEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    TargetRingelComplexQuotient H ≌
      RingelComplexQuotient H.rightOp.symm :=
  (targetRingelQuotientComparisonFunctor H).asEquivalence

/-- Strong Hom followed by the target quotient functor. -/
def strongHomTargetQuotientFunctor
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (StronglyExactComplexCategory H)ᵒᵖ ⥤
      TargetRingelComplexQuotient H :=
  (stronglyExactComplexAntiEquivalence H).functor ⋙
    CategoryTheory.Quotient.functor (targetRingelURel H)

/-- The strong Hom functor respects the source null congruence after
passing to the target quotient. -/
theorem strongHomTargetQuotient_respects_U
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive]
    (X Y : (StronglyExactComplexCategory H)ᵒᵖ)
    (f g : X ⟶ Y) (hfg : sourceOpRingelURel H f g) :
    (strongHomTargetQuotientFunctor H).map f =
      (strongHomTargetQuotientFunctor H).map g := by
  induction X with
  | op X =>
    induction Y with
    | op Y =>
  apply CategoryTheory.Quotient.sound (targetRingelURel H)
  rcases hfg with ⟨hfg⟩
  have hmap := homDual_map_factorsThroughRingelU H hfg
  change Nonempty (FactorsThroughTargetRingelU H
    ((stronglyExactComplexAntiEquivalence H).functor.map f -
      (stronglyExactComplexAntiEquivalence H).functor.map g))
  refine ⟨?_⟩
  simpa only [op_sub, Quiver.Hom.op_unop,
    (stronglyExactComplexAntiEquivalence H).functor.map_sub] using hmap

/-- Strong Hom identifies exactly the source and target elementary
congruences. -/
theorem strongHom_sourceOpRingelURel_iff
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive]
    {X Y : (StronglyExactComplexCategory H)ᵒᵖ}
    (f g : X ⟶ Y) :
    sourceOpRingelURel H f g ↔
      targetRingelURel H
        ((stronglyExactComplexAntiEquivalence H).functor.map f)
        ((stronglyExactComplexAntiEquivalence H).functor.map g) := by
  constructor
  · rintro ⟨hfg⟩
    refine ⟨?_⟩
    have hmap := homDual_map_factorsThroughRingelU H hfg
    simpa only [op_sub, Quiver.Hom.op_unop,
      (stronglyExactComplexAntiEquivalence H).functor.map_sub] using hmap
  · rintro ⟨hfg⟩
    refine ⟨?_⟩
    have hreflect :
        FactorsThroughRingelU ((f - g).unop) :=
      homDual_reflects_factorsThroughRingelU H <| by
        simpa only [
          (stronglyExactComplexAntiEquivalence H).functor.map_sub] using hfg
    simpa only [unop_sub] using hreflect

/-- Degreewise strong Hom descends through the explicit source and target
elementary ideals. -/
def strongHomQuotientFunctor
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    RingelComplexOpQuotient H ⥤ TargetRingelComplexQuotient H :=
  CategoryTheory.Quotient.lift (sourceOpRingelURel H)
    (strongHomTargetQuotientFunctor H)
    (strongHomTargetQuotient_respects_U H)

instance strongHomQuotientFunctor_full
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    (strongHomQuotientFunctor H).Full where
  map_surjective {X Y} h := by
    obtain ⟨h, rfl⟩ :=
      (CategoryTheory.Quotient.functor
        (targetRingelURel H)).map_surjective h
    obtain ⟨f, rfl⟩ :=
      (stronglyExactComplexAntiEquivalence H).functor.map_surjective h
    exact ⟨(CategoryTheory.Quotient.functor
      (sourceOpRingelURel H)).map f, rfl⟩

instance strongHomQuotientFunctor_faithful
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    (strongHomQuotientFunctor H).Faithful where
  map_injective {X Y} f g hfg := by
    obtain ⟨f, rfl⟩ :=
      (CategoryTheory.Quotient.functor
        (sourceOpRingelURel H)).map_surjective f
    obtain ⟨g, rfl⟩ :=
      (CategoryTheory.Quotient.functor
        (sourceOpRingelURel H)).map_surjective g
    apply CategoryTheory.Quotient.sound (sourceOpRingelURel H)
    exact (strongHom_sourceOpRingelURel_iff H f g).2 <|
      (CategoryTheory.Quotient.functor_map_eq_iff
        (targetRingelURel H)
        ((stronglyExactComplexAntiEquivalence H).functor.map f)
        ((stronglyExactComplexAntiEquivalence H).functor.map g)).1 hfg

instance strongHomQuotientFunctor_essSurj
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    (strongHomQuotientFunctor H).EssSurj where
  mem_essImage Y := by
    let A := (stronglyExactComplexAntiEquivalence H).functor
    refine ⟨(CategoryTheory.Quotient.functor
      (sourceOpRingelURel H)).obj (A.objPreimage Y.as), ?_⟩
    exact ⟨(CategoryTheory.Quotient.functor
      (targetRingelURel H)).mapIso (A.objObjPreimageIso Y.as)⟩

instance strongHomQuotientFunctor_isEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    (strongHomQuotientFunctor H).IsEquivalence where

/-- Strong Hom duality descends to an equivalence between the opposite
source elementary quotient and the target elementary quotient. -/
def strongHomQuotientEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    RingelComplexOpQuotient H ≌ TargetRingelComplexQuotient H :=
  (strongHomQuotientFunctor H).asEquivalence

/-! ## Comparison with the opposite of the source quotient -/

/-- The explicit quotient of the opposite source category maps to the
opposite of the ordinary source quotient. -/
def ringelComplexOpComparisonFunctor
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    RingelComplexOpQuotient H ⥤ (RingelComplexQuotient H)ᵒᵖ :=
  CategoryTheory.Quotient.lift (sourceOpRingelURel H)
    (ringelComplexQuotientFunctor H).op <| by
      intro X Y f g hfg
      apply Quiver.Hom.unop_inj
      exact CategoryTheory.Quotient.sound (ringelURel H) hfg

instance ringelComplexOpComparisonFunctor_full
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (ringelComplexOpComparisonFunctor H).Full where
  map_surjective {X Y} h := by
    obtain ⟨f, hf⟩ :=
      (ringelComplexQuotientFunctor H).map_surjective h.unop
    refine ⟨(CategoryTheory.Quotient.functor
      (sourceOpRingelURel H)).map f.op, ?_⟩
    apply Quiver.Hom.unop_inj
    exact hf

instance ringelComplexOpComparisonFunctor_faithful
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (ringelComplexOpComparisonFunctor H).Faithful where
  map_injective {X Y} f g hfg := by
    obtain ⟨f, rfl⟩ :=
      (CategoryTheory.Quotient.functor
        (sourceOpRingelURel H)).map_surjective f
    obtain ⟨g, rfl⟩ :=
      (CategoryTheory.Quotient.functor
        (sourceOpRingelURel H)).map_surjective g
    apply CategoryTheory.Quotient.sound (sourceOpRingelURel H)
    apply (CategoryTheory.Quotient.functor_map_eq_iff
      (ringelURel H) f.unop g.unop).1
    exact congrArg Quiver.Hom.unop hfg

instance ringelComplexOpComparisonFunctor_essSurj
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (ringelComplexOpComparisonFunctor H).EssSurj where
  mem_essImage Y := by
    rcases Y with ⟨⟨Y⟩⟩
    exact ⟨⟨Opposite.op Y⟩, ⟨Iso.refl _⟩⟩

instance ringelComplexOpComparisonFunctor_isEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    (ringelComplexOpComparisonFunctor H).IsEquivalence where

/-- Taking the elementary quotient commutes with passage to the opposite
category. -/
def ringelComplexOpComparisonEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    RingelComplexOpQuotient H ≌ (RingelComplexQuotient H)ᵒᵖ :=
  (ringelComplexOpComparisonFunctor H).asEquivalence

/-- Strong Hom duality on the elementary quotients, with the source
presented as the opposite of `E/U`. -/
def strongHomRingelComplexQuotientAntiEquivalence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    (RingelComplexQuotient H)ᵒᵖ ≌ TargetRingelComplexQuotient H :=
  (ringelComplexOpComparisonEquivalence H).symm.trans
    (strongHomQuotientEquivalence H)

/-- Strong Hom duality descends to the ordinary Ringel elementary
quotients on the two sides. -/
def strongHomRingelComplexQuotientAntiEquivalenceStandard
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    [H.functor.Additive] :
    (RingelComplexQuotient H)ᵒᵖ ≌
      RingelComplexQuotient H.rightOp.symm :=
  (strongHomRingelComplexQuotientAntiEquivalence H).trans
    (targetRingelQuotientComparisonEquivalence H)

end QuotientSubmoduleEquidistribution.RingelEta
