import QuotientSubmoduleEquidistribution.RepresentationTheory.StrongComplexDuality
import QuotientSubmoduleEquidistribution.RepresentationTheory.StableQuotients
import Mathlib.CategoryTheory.Quotient.Preadditive

/-!
# Ringel's null system and the quotient `E/U`

Ringel's subcategory `U` is the finite additive closure of four elementary
three-term projective complexes.  For the quotient, the equivalent datum is
the ideal generated by factorizations through those four families.  We define
that ideal inductively (including finite sums), prove all congruence laws, and
construct the quotient category `E/U` with its exact equality criterion.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits Opposite

namespace QuotientSubmoduleEquidistribution.RingelEta

universe u u'

open QuotientSubmoduleEquidistribution.RingelStable

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {S : Type u'} [Ring S] [IsNoetherianRing S]

/-! ## The four elementary complexes -/

/-- A chosen zero finitely generated projective module. -/
def zeroFGProjective : FGProjectives (R := R) :=
  ⟨zeroFGModule (R := R), isZero_zeroFGModule.projective⟩

omit [IsNoetherianRing R] in
/-- The chosen zero projective is a zero object inside the full projective
subcategory. -/
theorem isZero_zeroFGProjective :
    IsZero (zeroFGProjective (R := R)) where
  unique_to Y := ⟨{
    default := 0
    uniq := by
      intro f
      apply ObjectProperty.hom_ext
      exact isZero_zeroFGModule.eq_of_src f.hom 0 }⟩
  unique_from Y := ⟨{
    default := 0
    uniq := by
      intro f
      apply ObjectProperty.hom_ext
      exact isZero_zeroFGModule.eq_of_tgt f.hom 0 }⟩

/-- Ringel's four elementary shapes. -/
inductive ElementaryKind
  | leftStalk
  | leftContractible
  | rightContractible
  | rightStalk
  deriving DecidableEq

/-- One of Ringel's four elementary complexes, parametrized by a finite
projective module `P`:
`P→0→0`, `P→P→0`, `0→P→P`, or `0→0→P`. -/
def elementaryProjectiveComplex
    (k : ElementaryKind) (P : FGProjectives (R := R)) :
    ProjectiveComplex R :=
  match k with
  | .leftStalk =>
      ShortComplex.mk (0 : P ⟶ zeroFGProjective)
        (0 : zeroFGProjective ⟶ zeroFGProjective)
  | .leftContractible =>
      ShortComplex.mk (𝟙 P) (0 : P ⟶ zeroFGProjective)
  | .rightContractible =>
      ShortComplex.mk (0 : zeroFGProjective ⟶ P) (𝟙 P)
  | .rightStalk =>
      ShortComplex.mk
        (0 : zeroFGProjective ⟶ zeroFGProjective)
        (0 : zeroFGProjective ⟶ P)

private theorem elementaryProjectiveComplex_exact
    (k : ElementaryKind) (P : FGProjectives (R := R)) :
    (elementaryProjectiveComplex k P).Exact := by
  letI : HasZeroObject (FGModuleCat.{u} R) :=
    ⟨zeroFGModule (R := R), isZero_zeroFGModule⟩
  cases k with
  | leftStalk =>
      apply ShortComplex.exact_of_isZero_X₂
      exact isZero_zeroFGModule
  | leftContractible =>
      apply (ShortComplex.exact_iff_epi _ rfl).2
      change Epi
        ((ObjectProperty.ι (fgProjectiveProperty (R := R))).map (𝟙 P))
      rw [(ObjectProperty.ι
        (fgProjectiveProperty (R := R))).map_id P]
      infer_instance
  | rightContractible =>
      apply (ShortComplex.exact_iff_mono _ rfl).2
      change Mono
        ((ObjectProperty.ι (fgProjectiveProperty (R := R))).map (𝟙 P))
      rw [(ObjectProperty.ι
        (fgProjectiveProperty (R := R))).map_id P]
      infer_instance
  | rightStalk =>
      apply ShortComplex.exact_of_isZero_X₂
      exact isZero_zeroFGModule

private theorem homDual_elementary_exact
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) (P : FGProjectives (R := R)) :
    ((elementaryProjectiveComplex k P).homDual H).Exact := by
  letI : HasZeroObject (FGModuleCat.{u'} S) :=
    ⟨zeroFGModule (R := S), isZero_zeroFGModule⟩
  have hzProj :
      IsZero
        (H.functor.obj
          (Opposite.op (zeroFGProjective (R := R)))) :=
    H.functor.map_isZero isZero_zeroFGProjective.op
  have hz :
      IsZero
        ((ObjectProperty.ι (fgProjectiveProperty (R := S))).obj
          (H.functor.obj
            (Opposite.op (zeroFGProjective (R := R))))) :=
    (ObjectProperty.ι (fgProjectiveProperty (R := S))).map_isZero hzProj
  cases k with
  | leftStalk =>
      apply ShortComplex.exact_of_isZero_X₂
      exact hz
  | leftContractible =>
      have hf :
          ((forgetProjectiveComplex (R := S)).obj
            ((elementaryProjectiveComplex .leftContractible P).homDual H)).f = 0 := by
        change (ObjectProperty.ι (fgProjectiveProperty (R := S))).map
          ((mapShortComplexAntiEquivalence H).functor.obj
            (Opposite.op
              (elementaryProjectiveComplex .leftContractible P))).f = 0
        rw [mapShortComplexAntiEquivalence_obj_f]
        change (ObjectProperty.ι (fgProjectiveProperty (R := S))).map
          (H.functor.map
            (0 : Opposite.op (zeroFGProjective (R := R)) ⟶
              Opposite.op P)) = 0
        rw [H.functor.map_zero,
          (ObjectProperty.ι
            (fgProjectiveProperty (R := S))).map_zero]
      apply (ShortComplex.exact_iff_mono _ hf).2
      change Mono
        ((ObjectProperty.ι (fgProjectiveProperty (R := S))).map
          (H.functor.map (𝟙 (Opposite.op P))))
      rw [H.functor.map_id,
        (ObjectProperty.ι
          (fgProjectiveProperty (R := S))).map_id]
      infer_instance
  | rightContractible =>
      have hg :
          ((forgetProjectiveComplex (R := S)).obj
            ((elementaryProjectiveComplex .rightContractible P).homDual H)).g = 0 := by
        change (ObjectProperty.ι (fgProjectiveProperty (R := S))).map
          ((mapShortComplexAntiEquivalence H).functor.obj
            (Opposite.op
              (elementaryProjectiveComplex .rightContractible P))).g = 0
        rw [mapShortComplexAntiEquivalence_obj_g]
        change (ObjectProperty.ι (fgProjectiveProperty (R := S))).map
          (H.functor.map
            (0 : Opposite.op P ⟶
              Opposite.op (zeroFGProjective (R := R)))) = 0
        rw [H.functor.map_zero,
          (ObjectProperty.ι
            (fgProjectiveProperty (R := S))).map_zero]
      apply (ShortComplex.exact_iff_epi _ hg).2
      change Epi
        ((ObjectProperty.ι (fgProjectiveProperty (R := S))).map
          (H.functor.map (𝟙 (Opposite.op P))))
      rw [H.functor.map_id,
        (ObjectProperty.ι
          (fgProjectiveProperty (R := S))).map_id]
      infer_instance
  | rightStalk =>
      apply ShortComplex.exact_of_isZero_X₂
      exact hz

/-- Every elementary complex is strongly exact. -/
theorem elementaryProjectiveComplex_stronglyExact
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) (P : FGProjectives (R := R)) :
    (elementaryProjectiveComplex k P).StronglyExact H :=
  ⟨elementaryProjectiveComplex_exact k P,
    homDual_elementary_exact H k P⟩

/-- An elementary complex as an object of Ringel's strongly exact category
`E`. -/
def elementaryStrongComplex
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    (k : ElementaryKind) (P : FGProjectives (R := R)) :
    StronglyExactComplexCategory H :=
  ⟨elementaryProjectiveComplex k P,
    elementaryProjectiveComplex_stronglyExact H k P⟩

/-! ## The ideal generated by `U` -/

/-- A morphism belongs to Ringel's null ideal if it is a finite sum of
morphisms factoring through one of the four elementary complexes.  This is
exactly the ideal generated by the finite additive closure `U`. -/
inductive FactorsThroughRingelU
    {H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)}
    {X Y : StronglyExactComplexCategory H} : (X ⟶ Y) → Prop
  | zero : FactorsThroughRingelU 0
  | basic (k : ElementaryKind) (P : FGProjectives (R := R))
      (a : X ⟶ elementaryStrongComplex H k P)
      (b : elementaryStrongComplex H k P ⟶ Y) :
      FactorsThroughRingelU (a ≫ b)
  | add {f g : X ⟶ Y} :
      FactorsThroughRingelU f → FactorsThroughRingelU g →
      FactorsThroughRingelU (f + g)

namespace FactorsThroughRingelU

variable {H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)}

/-- The null ideal is closed under negation. -/
theorem neg {X Y : StronglyExactComplexCategory H} {f : X ⟶ Y}
    (hf : FactorsThroughRingelU f) :
    FactorsThroughRingelU (-f) := by
  induction hf with
  | zero => simpa using (zero : FactorsThroughRingelU (0 : X ⟶ Y))
  | basic k P a b =>
      simpa only [Preadditive.comp_neg] using
        (basic k P a (-b))
  | add hf hg ihf ihg =>
      simpa only [neg_add_rev] using ihg.add ihf

/-- Precomposition preserves the null ideal. -/
theorem precomp {W X Y : StronglyExactComplexCategory H}
    (c : W ⟶ X) {f : X ⟶ Y} (hf : FactorsThroughRingelU f) :
    FactorsThroughRingelU (c ≫ f) := by
  induction hf with
  | zero => simpa using (zero : FactorsThroughRingelU (0 : W ⟶ Y))
  | basic k P a b =>
      simpa only [Category.assoc] using basic k P (c ≫ a) b
  | add hf hg ihf ihg =>
      simpa only [Preadditive.comp_add] using ihf.add ihg

/-- Postcomposition preserves the null ideal. -/
theorem postcomp {X Y Z : StronglyExactComplexCategory H}
    {f : X ⟶ Y} (hf : FactorsThroughRingelU f) (c : Y ⟶ Z) :
    FactorsThroughRingelU (f ≫ c) := by
  induction hf with
  | zero => simpa using (zero : FactorsThroughRingelU (0 : X ⟶ Z))
  | basic k P a b =>
      simpa only [← Category.assoc] using basic k P a (b ≫ c)
  | add hf hg ihf ihg =>
      simpa only [Preadditive.add_comp] using ihf.add ihg

end FactorsThroughRingelU

/-- Equality modulo Ringel's null ideal. -/
def ringelURel
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    HomRel (StronglyExactComplexCategory H) :=
  fun _ _ f g ↦ Nonempty (FactorsThroughRingelU (f - g))

instance ringelURel_congruence
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    Congruence (ringelURel H) where
  equivalence :=
    { refl := fun f ↦ ⟨by
        simpa using
          (FactorsThroughRingelU.zero :
            FactorsThroughRingelU (0 : _ ⟶ _))⟩
      symm := by
        rintro f g ⟨h⟩
        exact ⟨by
          convert h.neg using 1
          abel⟩
      trans := by
        rintro f g h ⟨hfg⟩ ⟨hgh⟩
        exact ⟨by
          convert hfg.add hgh using 1
          abel⟩ }
  comp_left := by
    rintro X Y Z a f g ⟨hfg⟩
    exact ⟨by
      simpa only [Preadditive.comp_sub] using hfg.precomp a⟩
  comp_right := by
    rintro X Y Z f g b ⟨hfg⟩
    exact ⟨by
      simpa only [Preadditive.sub_comp] using hfg.postcomp b⟩

/-- Ringel's factor category `E/U`. -/
abbrev RingelComplexQuotient
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :=
  CategoryTheory.Quotient (ringelURel H)

/-- The canonical quotient functor `E ⟶ E/U`. -/
abbrev ringelComplexQuotientFunctor
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S)) :
    StronglyExactComplexCategory H ⥤ RingelComplexQuotient H :=
  CategoryTheory.Quotient.functor (ringelURel H)

/-- Exact equality criterion in `E/U`: two maps agree precisely when their
difference is a finite sum of maps through Ringel's four elementary
complexes. -/
theorem ringelComplexQuotient_map_eq_iff
    (H : (FGProjectives (R := R))ᵒᵖ ≌ FGProjectives (R := S))
    {X Y : StronglyExactComplexCategory H} (f g : X ⟶ Y) :
    (ringelComplexQuotientFunctor H).map f =
        (ringelComplexQuotientFunctor H).map g ↔
      Nonempty (FactorsThroughRingelU (f - g)) :=
  CategoryTheory.Quotient.functor_map_eq_iff (ringelURel H) f g

end QuotientSubmoduleEquidistribution.RingelEta
