import QuotientSubmoduleEquidistribution.RepresentationTheory.SeparatedTriangularAlgebra
import QuotientSubmoduleEquidistribution.RepresentationTheory.TrivSqZeroExtSeparatedTrace

/-!
# Trace generation in the triangular separated algebra

For a generated separated target, a family of triangular-algebra
realizations generates the entire module exactly when the induced family of
top maps fills the target top.  Generatedness supplies the radical after the
top has been filled.
-/

set_option autoImplicit false

noncomputable section

open CategoryTheory

namespace QuotientSubmoduleEquidistribution.SeparatedTriangularAlgebra

open TrivSqZeroExtSeparatedData
open TrivSqZeroExtSeparatedTrace

universe u v w x

variable {S : Type u} {J : Type v}
variable [CommRing S] [AddCommGroup J]
variable [Module S J] [Module Sᵐᵒᵖ J]
variable [SMulCommClass S Sᵐᵒᵖ J]

/-- The full triangular-module trace generated by a family of realized
separated data. -/
def realizedFamilyTrace
    {A : Type x} (D : A → SeparatedData.{u, v, w} (S := S) (J := J))
    (E : SeparatedData.{u, v, w} (S := S) (J := J)) :
    Submodule (Algebra S J) (Realized E) :=
  ⨆ a, ⨆ f : realizedModuleCat (D a) ⟶ realizedModuleCat E,
    LinearMap.range f.hom

/-- For a generated target, full generation by realized sources is
equivalent to top generation by the corresponding separated-data maps. -/
theorem realizedFamilyTrace_eq_top_iff_separatedDataFamilyTopTrace_eq_top
    {A : Type x} (D : A → SeparatedData.{u, v, w} (S := S) (J := J))
    (E : SeparatedData.{u, v, w} (S := S) (J := J))
    (hE : IsGenerated E) :
    realizedFamilyTrace D E = ⊤ ↔
      separatedDataFamilyTopTrace D E = ⊤ := by
  constructor
  · intro hfull
    let P : Submodule (Algebra S J) (Realized E) :=
      { carrier := {x | x.1 ∈ separatedDataFamilyTopTrace D E}
        zero_mem' := by
          change (0 : E.top) ∈ separatedDataFamilyTopTrace D E
          exact Submodule.zero_mem _
        add_mem' := by
          intro x y hx hy
          change x.1 + y.1 ∈ separatedDataFamilyTopTrace D E
          exact Submodule.add_mem _ hx hy
        smul_mem' := by
          intro r x hx
          change r.fst.2 • x.1 ∈ separatedDataFamilyTopTrace D E
          exact Submodule.smul_mem _ r.fst.2 hx }
    have htrace_le : realizedFamilyTrace D E ≤ P := by
      apply iSup_le
      intro a
      apply iSup_le
      intro f y hy
      rcases hy with ⟨x, rfl⟩
      obtain ⟨p, hp⟩ :=
        (realizationFunctor (S := S) (J := J)).map_surjective f
      change (f x).1 ∈ separatedDataFamilyTopTrace D E
      rw [← hp]
      change p.val.1 x.1 ∈ separatedDataFamilyTopTrace D E
      exact (le_iSup
        (fun a ↦ separatedDataTopTrace (D a) E) a)
        ((le_iSup
          (fun p : D a ⟶ E ↦ LinearMap.range p.val.1) p)
          ⟨x.1, rfl⟩)
    apply top_unique
    intro t _
    have ht : ((t, 0) : Realized E) ∈ realizedFamilyTrace D E := by
      rw [hfull]
      exact Submodule.mem_top
    exact htrace_le ht
  · intro htop
    let Q : Submodule S E.top :=
      { carrier := {t | ((t, 0) : Realized E) ∈ realizedFamilyTrace D E}
        zero_mem' := by
          change (((0 : E.top), 0) : Realized E) ∈
            realizedFamilyTrace D E
          exact Submodule.zero_mem _
        add_mem' := by
          intro t s ht hs
          have hadd := Submodule.add_mem (realizedFamilyTrace D E) ht hs
          simpa using hadd
        smul_mem' := by
          intro s t ht
          have hsmul := (realizedFamilyTrace D E).smul_mem
            (TrivSqZeroExt.inl ((0, s) : S × S)) ht
          simpa using hsmul }
    have htop_le : separatedDataFamilyTopTrace D E ≤ Q := by
      apply iSup_le
      intro a
      apply iSup_le
      intro p t ht
      rcases ht with ⟨x, rfl⟩
      let f : realizedModuleCat (D a) ⟶ realizedModuleCat E :=
        (realizationFunctor (S := S) (J := J)).map p
      have hrange : f (x, 0) ∈ LinearMap.range f.hom :=
        ⟨(x, 0), rfl⟩
      have hmem : f (x, 0) ∈ realizedFamilyTrace D E :=
        (le_iSup
          (fun a ↦ ⨆ f : realizedModuleCat (D a) ⟶
            realizedModuleCat E, LinearMap.range f.hom) a)
          ((le_iSup
            (fun f : realizedModuleCat (D a) ⟶ realizedModuleCat E ↦
              LinearMap.range f.hom) f) hrange)
      change ((p.val.1 x, 0) : Realized E) ∈ realizedFamilyTrace D E
      change ((p.val.1 x, p.val.2 0) : Realized E) ∈
        realizedFamilyTrace D E at hmem
      simpa using hmem
    have hQtop : Q = ⊤ := by
      apply top_unique
      rw [← htop]
      exact htop_le
    have top_mem (t : E.top) :
        ((t, 0) : Realized E) ∈ realizedFamilyTrace D E := by
      change t ∈ Q
      rw [hQtop]
      exact Submodule.mem_top
    have radical_mem (d : E.radical) :
        (((0 : E.top), d) : Realized E) ∈ realizedFamilyTrace D E := by
      have hd : d ∈ actionRange E := by
        rw [hE]
        exact Submodule.mem_top
      refine Submodule.span_induction ?_ ?_ ?_ ?_ hd
      · intro d hd
        rcases hd with ⟨j, t, rfl⟩
        have hsmul := (realizedFamilyTrace D E).smul_mem
          (TrivSqZeroExt.inr (⟨j⟩ : SeparatedIdeal S J)) (top_mem t)
        simpa using hsmul
      · exact Submodule.zero_mem _
      · intro d e _ _ hd he
        simpa using Submodule.add_mem (realizedFamilyTrace D E) hd he
      · intro s d _ hd
        have hsmul := (realizedFamilyTrace D E).smul_mem
          (TrivSqZeroExt.inl ((s, 0) : S × S)) hd
        simpa using hsmul
    apply top_unique
    intro x _
    have hsum := Submodule.add_mem (realizedFamilyTrace D E)
      (top_mem x.1) (radical_mem x.2)
    simpa using hsum

end QuotientSubmoduleEquidistribution.SeparatedTriangularAlgebra
