import Mathlib.Algebra.Category.ModuleCat.Biproducts
import Mathlib.Algebra.Category.ModuleCat.Simple
import Mathlib.CategoryTheory.Preadditive.Schur
import Mathlib.RingTheory.Finiteness.Basic
import QuotientSubmoduleEquidistribution.ConvexGeometry.BottomLevels
import QuotientSubmoduleEquidistribution.RepresentationTheory.Trace

/-!
# Simple representatives and closed singleton supports

This file gives the exact bottom-level identification. The closure
definitions used here are the collective ones: `FacPresentation` and
`SubPresentation` allow arbitrary finite biproducts of the selected
representative.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton

universe u v w

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} (σ : IndecomposableSkeleton.{u, v, w} R ι)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-!
The Mathlib simple-module bridge is stated for `ModuleCat`.  Over a
left-Noetherian ring, every submodule of a finitely generated module is again
finitely generated, so the same characterization holds in `FGModuleCat`.
-/

theorem simple_iff_isSimpleModule_fg (X : FGModuleCat.{w} R) :
    Simple X ↔ IsSimpleModule R X := by
  constructor
  · intro hX
    letI : Simple X := hX
    letI : Nontrivial X := by
      rw [← not_subsingleton_iff_nontrivial]
      intro hsub
      apply CategoryTheory.id_nonzero X
      apply FGModuleCat.hom_ext
      apply LinearMap.ext
      intro x
      exact Subsingleton.elim _ _
    letI : IsSimpleOrder (Submodule R X) := {
      exists_pair_ne := exists_pair_ne (α := Submodule R X)
      eq_bot_or_eq_top := fun N ↦ by
        let Y : FGModuleCat.{w} R := FGModuleCat.of R N
        let f : Y ⟶ X := FGModuleCat.ofHom N.subtype
        letI : Mono f :=
          ConcreteCategory.mono_of_injective f N.subtype_injective
        by_cases hf : f = 0
        · left
          rw [← N.range_subtype]
          apply LinearMap.range_eq_bot.mpr
          have hflinear :=
            congrArg (fun g : Y ⟶ X ↦ g.hom.hom) hf
          change N.subtype = 0 at hflinear
          exact hflinear
        · right
          rw [← N.range_subtype]
          apply LinearMap.range_eq_top.mpr
          haveI : IsIso f :=
            (Simple.mono_isIso_iff_nonzero f).mpr hf
          have hfbij : Function.Bijective f :=
            ConcreteCategory.bijective_of_isIso f
          change Function.Bijective N.subtype at hfbij
          exact hfbij.surjective }
    exact IsSimpleModule.mk
  · intro hX
    letI : IsSimpleModule R X := hX
    let F :=
      forget₂ (FGModuleCat.{w} R) (ModuleCat.{w} R)
    letI : Simple (F.obj X) :=
      (simple_iff_isSimpleModule' (F.obj X)).mpr (by
        change IsSimpleModule R X
        exact hX)
    exact F.simple_of_simple_obj X

/-- The concrete finite-product model of a finite biproduct in
`FGModuleCat`. -/
def biproductIsoPiFG
    {J : Type} [Finite J] (f : J → FGModuleCat.{w} R) :
    biproduct f ≅ FGModuleCat.of R (∀ j, f j) := by
  let F :=
    forget₂ (FGModuleCat.{w} R) (ModuleCat.{w} R)
  letI : PreservesBiproduct f F :=
    preservesBiproduct_of_preservesProduct F
  exact
    F.preimageIso
      (F.mapBiproduct f ≪≫
        ModuleCat.biproductIsoPi (fun j ↦ F.obj (f j)))

omit [IsNoetherianRing R] in
/-- A nonzero indecomposable semisimple module is simple. -/
theorem isSimpleModule_of_semisimple_of_indecomposable
    {M : Type w} [AddCommGroup M] [Module R M]
    (hM : QuotientSubmoduleEquidistribution.Foundation.IsIndecomposableModule R M)
    [IsSemisimpleModule R M] :
    IsSimpleModule R M := by
  letI : Nontrivial M := hM.nontrivial
  letI : IsSimpleOrder (Submodule R M) := {
    exists_pair_ne := exists_pair_ne (α := Submodule R M)
    eq_bot_or_eq_top := fun N ↦ by
      obtain ⟨P, hNP⟩ := exists_isCompl N
      rcases hM.eq_bot_or_eq_bot hNP with hN | hP
      · exact Or.inl hN
      · exact Or.inr (by
          have hsup := hNP.sup_eq_top
          simpa [hP] using hsup) }
  exact IsSimpleModule.mk

/-! ## Collective singleton closure generated by a simple representative -/

/-- Every indecomposable in the collective quotient closure of a simple
representative is that representative itself. -/
theorem mem_qClosure_singleton_iff_of_simple
    {i j : ι} (hi : Simple (σ.obj i)) :
    j ∈ σ.qClosure ({i} : Set ι) ↔ j = i := by
  constructor
  · rintro ⟨P⟩
    letI : Simple (σ.obj i) := hi
    have hlabel (t : P.index) : P.label t = i := by
      simpa using P.mem t
    letI (t : P.index) : Simple (σ.obj (P.label t)) :=
      by simpa [hlabel t] using hi
    letI (t : P.index) :
        IsSimpleModule R (σ.obj (P.label t)) :=
      (simple_iff_isSimpleModule_fg _).mp inferInstance
    letI : IsSemisimpleModule R
        (∀ t : P.index, σ.obj (P.label t)) :=
      inferInstance
    let e :
        σ.sumOver P.index P.label ≅
          FGModuleCat.of R
            (∀ t : P.index, σ.obj (P.label t)) :=
      biproductIsoPiFG _
    letI : IsSemisimpleModule R (σ.sumOver P.index P.label) :=
      (LinearEquiv.isSemisimpleModule_iff
        (FGModuleCat.isoToLinearEquiv e)).mpr inferInstance
    letI : Epi P.map := P.epi
    have hsurj : Function.Surjective P.map.hom.hom :=
      (fg_epi_iff_surjective P.map).mp inferInstance
    letI : IsSemisimpleModule R (σ.obj j) :=
      IsSemisimpleModule.of_surjective P.map.hom.hom hsurj
    letI : IsSimpleModule R (σ.obj j) :=
      isSimpleModule_of_semisimple_of_indecomposable
        (σ.indecomposable j)
    letI : Simple (σ.obj j) :=
      (simple_iff_isSimpleModule_fg _).mpr inferInstance
    have hmap : P.map ≠ 0 := by
      intro hzero
      exact
        (Simple.not_isZero (σ.obj j))
          (IsZero.of_epi_eq_zero P.map hzero)
    have hcomponent :
        ∃ t : P.index,
          biproduct.ι (fun t : P.index ↦
            σ.obj (P.label t)) t ≫ P.map ≠ 0 := by
      by_contra h
      push Not at h
      apply hmap
      apply biproduct.hom_ext'
      intro t
      simpa using h t
    obtain ⟨t, ht⟩ := hcomponent
    let g :
        σ.obj (P.label t) ⟶ σ.obj j :=
      biproduct.ι (fun s : P.index ↦
        σ.obj (P.label s)) t ≫ P.map
    have hg : g ≠ 0 := ht
    haveI : IsIso g := isIso_of_hom_simple hg
    have hindex : P.label t = j :=
      σ.eq_of_iso ⟨asIso g⟩
    exact hindex.symm.trans (hlabel t)
  · rintro rfl
    exact σ.subset_qSet ({j} : Set ι) (by simp)

/-- Every indecomposable in the collective submodule closure of a simple
representative is that representative itself. -/
theorem mem_sClosure_singleton_iff_of_simple
    {i j : ι} (hi : Simple (σ.obj i)) :
    j ∈ σ.sClosure ({i} : Set ι) ↔ j = i := by
  constructor
  · rintro ⟨P⟩
    letI : Simple (σ.obj i) := hi
    have hlabel (t : P.index) : P.label t = i := by
      simpa using P.mem t
    letI (t : P.index) : Simple (σ.obj (P.label t)) :=
      by simpa [hlabel t] using hi
    letI (t : P.index) :
        IsSimpleModule R (σ.obj (P.label t)) :=
      (simple_iff_isSimpleModule_fg _).mp inferInstance
    letI : IsSemisimpleModule R
        (∀ t : P.index, σ.obj (P.label t)) :=
      inferInstance
    let e :
        σ.sumOver P.index P.label ≅
          FGModuleCat.of R
            (∀ t : P.index, σ.obj (P.label t)) :=
      biproductIsoPiFG _
    letI : IsSemisimpleModule R (σ.sumOver P.index P.label) :=
      (LinearEquiv.isSemisimpleModule_iff
        (FGModuleCat.isoToLinearEquiv e)).mpr inferInstance
    letI : Mono P.map := P.mono
    have hinj : Function.Injective P.map.hom.hom :=
      (fg_mono_iff_injective P.map).mp inferInstance
    letI : IsSemisimpleModule R (σ.obj j) :=
      IsSemisimpleModule.of_injective P.map.hom.hom hinj
    letI : IsSimpleModule R (σ.obj j) :=
      isSimpleModule_of_semisimple_of_indecomposable
        (σ.indecomposable j)
    letI : Simple (σ.obj j) :=
      (simple_iff_isSimpleModule_fg _).mpr inferInstance
    have hmap : P.map ≠ 0 := by
      intro hzero
      exact
        (Simple.not_isZero (σ.obj j))
          (IsZero.of_mono_eq_zero P.map hzero)
    have hcomponent :
        ∃ t : P.index,
          P.map ≫ biproduct.π (fun t : P.index ↦
            σ.obj (P.label t)) t ≠ 0 := by
      by_contra h
      push Not at h
      apply hmap
      apply biproduct.hom_ext
      intro t
      simpa using h t
    obtain ⟨t, ht⟩ := hcomponent
    let g :
        σ.obj j ⟶ σ.obj (P.label t) :=
      P.map ≫ biproduct.π (fun s : P.index ↦
        σ.obj (P.label s)) t
    have hg : g ≠ 0 := ht
    haveI : IsIso g := isIso_of_hom_simple hg
    have hindex : j = P.label t :=
      σ.eq_of_iso ⟨asIso g⟩
    exact hindex.trans (hlabel t)
  · rintro rfl
    exact σ.subset_sSet ({j} : Set ι) (by simp)

/-! ## Closed singleton supports are exactly the simple representatives -/

/-- A quotient-closed singleton support is exactly a simple representative.

The forward proof chooses a simple quotient of the representative, places its
indecomposable skeleton index in the collective quotient closure, and uses
closedness to identify that index with the original one.
-/
theorem qClosure_isClosed_singleton_iff_simple {i : ι} :
    σ.qClosure.IsClosed ({i} : Set ι) ↔ Simple (σ.obj i) := by
  constructor
  · intro hclosed
    letI : Nontrivial (σ.obj i) :=
      (σ.indecomposable i).nontrivial
    obtain ⟨N, hNcoatom, -⟩ :=
      (eq_top_or_exists_le_coatom
        (⊥ : Submodule R (σ.obj i))).resolve_left bot_ne_top
    let Q : FGModuleCat.{w} R :=
      FGModuleCat.of R ((σ.obj i) ⧸ N)
    have hQsimpleModule : IsSimpleModule R Q := by
      change IsSimpleModule R ((σ.obj i) ⧸ N)
      exact isSimpleModule_iff_isCoatom.mpr hNcoatom
    letI : IsSimpleModule R Q := hQsimpleModule
    have hQindecomposable :
        QuotientSubmoduleEquidistribution.Foundation.IsIndecomposableModule R Q :=
      QuotientSubmoduleEquidistribution.Foundation.IsSimpleModule.isIndecomposableModule
    obtain ⟨j, ⟨e⟩⟩ :=
      σ.complete Q hQindecomposable
    let q : σ.obj i ⟶ Q :=
      FGModuleCat.ofHom N.mkQ
    letI : Epi q :=
      (fg_epi_iff_surjective q).mpr (by
        change Function.Surjective N.mkQ
        exact Submodule.mkQ_surjective N)
    let a : Fin 1 → ι := fun _ ↦ i
    let f :
        σ.sumOver (FintypeCat.of (Fin 1)) a ⟶ σ.obj j :=
      (biproductUniqueIso fun t : Fin 1 ↦
          σ.obj (a t)).hom ≫ q ≫ e.hom
    letI : Epi f := by
      dsimp only [f]
      infer_instance
    have hjclosure :
        j ∈ σ.qClosure ({i} : Set ι) :=
      ⟨{
        index := FintypeCat.of (Fin 1)
        label := a
        mem := fun _ ↦ by simp [a]
        map := f
        epi := inferInstance }⟩
    have hjmem : j ∈ ({i} : Set ι) := by
      rw [← hclosed.closure_eq]
      exact hjclosure
    have hji : j = i := by
      simpa using hjmem
    have hQsimple : Simple Q :=
      (simple_iff_isSimpleModule_fg Q).mpr hQsimpleModule
    have hjSimple : Simple (σ.obj j) :=
      (Simple.iff_of_iso e).mp hQsimple
    simpa [hji] using hjSimple
  · intro hi
    rw [σ.qClosure.isClosed_iff]
    change σ.qSet ({i} : Set ι) = {i}
    ext j
    exact mem_qClosure_singleton_iff_of_simple σ hi (j := j)

/-- A submodule-closed singleton support is exactly a simple representative.

The forward proof chooses a simple submodule using the finite-length
hypothesis on the skeleton representative.
-/
theorem sClosure_isClosed_singleton_iff_simple {i : ι} :
    σ.sClosure.IsClosed ({i} : Set ι) ↔ Simple (σ.obj i) := by
  constructor
  · intro hclosed
    letI : Nontrivial (σ.obj i) :=
      (σ.indecomposable i).nontrivial
    letI : IsArtinian R (σ.obj i) :=
      (isFiniteLength_iff_isNoetherian_isArtinian.mp
        (σ.finiteLength i)).2
    obtain ⟨N, hNatom, -⟩ :=
      (eq_bot_or_exists_atom_le
        (⊤ : Submodule R (σ.obj i))).resolve_left top_ne_bot
    let Q : FGModuleCat.{w} R :=
      FGModuleCat.of R N
    have hQsimpleModule : IsSimpleModule R Q := by
      change IsSimpleModule R N
      exact isSimpleModule_iff_isAtom.mpr hNatom
    letI : IsSimpleModule R Q := hQsimpleModule
    have hQindecomposable :
        QuotientSubmoduleEquidistribution.Foundation.IsIndecomposableModule R Q :=
      QuotientSubmoduleEquidistribution.Foundation.IsSimpleModule.isIndecomposableModule
    obtain ⟨j, ⟨e⟩⟩ :=
      σ.complete Q hQindecomposable
    let m : Q ⟶ σ.obj i :=
      FGModuleCat.ofHom N.subtype
    letI : Mono m :=
      ConcreteCategory.mono_of_injective m
        N.subtype_injective
    let a : Fin 1 → ι := fun _ ↦ i
    let f :
        σ.obj j ⟶
          σ.sumOver (FintypeCat.of (Fin 1)) a :=
      e.inv ≫ m ≫
        (biproductUniqueIso fun t : Fin 1 ↦
          σ.obj (a t)).inv
    letI : Mono f := by
      dsimp only [f]
      infer_instance
    have hjclosure :
        j ∈ σ.sClosure ({i} : Set ι) :=
      ⟨{
        index := FintypeCat.of (Fin 1)
        label := a
        mem := fun _ ↦ by simp [a]
        map := f
        mono := inferInstance }⟩
    have hjmem : j ∈ ({i} : Set ι) := by
      rw [← hclosed.closure_eq]
      exact hjclosure
    have hji : j = i := by
      simpa using hjmem
    have hQsimple : Simple Q :=
      (simple_iff_isSimpleModule_fg Q).mpr hQsimpleModule
    have hjSimple : Simple (σ.obj j) :=
      (Simple.iff_of_iso e).mp hQsimple
    simpa [hji] using hjSimple
  · intro hi
    rw [σ.sClosure.isClosed_iff]
    change σ.sSet ({i} : Set ι) = {i}
    ext j
    exact mem_sClosure_singleton_iff_of_simple σ hi (j := j)

/-! ## Exact level-one counts -/

/-- The finite type of skeleton indices represented by simple objects. -/
def SimpleIndex :=
  {i : ι // Simple (σ.obj i)}

/-- Quotient-closed singleton points are the simple skeleton indices. -/
def qClosedSingletonEquivSimpleIndex :
    QuotientSubmoduleEquidistribution.SetClosure.ClosedSingletons σ.qClosure ≃
      SimpleIndex σ where
  toFun x :=
    ⟨x.1,
      (qClosure_isClosed_singleton_iff_simple σ).mp x.2⟩
  invFun x :=
    ⟨x.1,
      (qClosure_isClosed_singleton_iff_simple σ).mpr x.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

/-- Submodule-closed singleton points are the same simple skeleton
indices. -/
def sClosedSingletonEquivSimpleIndex :
    QuotientSubmoduleEquidistribution.SetClosure.ClosedSingletons σ.sClosure ≃
      SimpleIndex σ where
  toFun x :=
    ⟨x.1,
      (sClosure_isClosed_singleton_iff_simple σ).mp x.2⟩
  invFun x :=
    ⟨x.1,
      (sClosure_isClosed_singleton_iff_simple σ).mpr x.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

variable [Finite ι]

/-- The quotient-closed level zero consists only of the empty support. -/
theorem qLevelCount_zero_eq_one :
    σ.qClosure.levelCount 0 = 1 :=
  QuotientSubmoduleEquidistribution.SetClosure.levelCount_zero_eq_one_of_isClosed_empty
    σ.qClosure (qClosure_isClosed_empty σ)

/-- The submodule-closed level zero consists only of the empty support. -/
theorem sLevelCount_zero_eq_one :
    σ.sClosure.levelCount 0 = 1 :=
  QuotientSubmoduleEquidistribution.SetClosure.levelCount_zero_eq_one_of_isClosed_empty
    σ.sClosure (sClosure_isClosed_empty σ)

/-- Hence the two level-zero counts agree exactly. -/
theorem qLevelCount_zero_eq_sLevelCount_zero :
    σ.qClosure.levelCount 0 =
      σ.sClosure.levelCount 0 := by
  rw [qLevelCount_zero_eq_one, sLevelCount_zero_eq_one]

/-- The quotient-closed level one is counted by the finite type of simple
skeleton indices. -/
theorem qLevelCount_one_eq_natCard_simpleIndex :
    σ.qClosure.levelCount 1 =
      Nat.card (SimpleIndex σ) := by
  rw [QuotientSubmoduleEquidistribution.SetClosure.levelCount_one_eq_natCard_closedSingletons]
  exact Nat.card_congr (qClosedSingletonEquivSimpleIndex σ)

/-- The submodule-closed level one is counted by the same finite type of
simple skeleton indices. -/
theorem sLevelCount_one_eq_natCard_simpleIndex :
    σ.sClosure.levelCount 1 =
      Nat.card (SimpleIndex σ) := by
  rw [QuotientSubmoduleEquidistribution.SetClosure.levelCount_one_eq_natCard_closedSingletons]
  exact Nat.card_congr (sClosedSingletonEquivSimpleIndex σ)

/-- Hence the quotient and submodule level-one counts agree exactly. -/
theorem qLevelCount_one_eq_sLevelCount_one :
    σ.qClosure.levelCount 1 =
      σ.sClosure.levelCount 1 := by
  rw [qLevelCount_one_eq_natCard_simpleIndex,
    sLevelCount_one_eq_natCard_simpleIndex]

/-- The quotient and submodule level counts agree in every degree at most
one. -/
theorem qLevelCount_eq_sLevelCount_of_le_one
    {n : ℕ} (hn : n ≤ 1) :
    σ.qClosure.levelCount n =
      σ.sClosure.levelCount n := by
  have hn' : n = 0 ∨ n = 1 := by omega
  rcases hn' with rfl | rfl
  · exact qLevelCount_zero_eq_sLevelCount_zero σ
  · exact qLevelCount_one_eq_sLevelCount_one σ

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton
