import QuotientSubmoduleEquidistribution.RepresentationTheory.AntiExchange

/-!
# Extremality and relative split projectivity

For an indecomposable representative `x`, failure of `x` to be generated by
`C \ {x}` is equivalent to every epimorphism from an explicitly presented
object of `add C` to `x` splitting.

The difficult implication uses nilpotence of the Jacobson radical of
`End(x)`.  In the current skeleton this is supplied by the same Artinian
endomorphism-ring hypothesis used for anti-exchange.
-/

noncomputable section

open Set
open CategoryTheory CategoryTheory.Limits

namespace QuotientSubmoduleEquidistribution.IndecomposableSkeleton

variable {R : Type u} [Ring R] [IsNoetherianRing R]
  {ι : Type v} (σ : IndecomposableSkeleton.{u, v, w} R ι)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

/-- Relative split projectivity with respect to `add C`, expressed on the
explicit finite-sum skeleton: every epimorphic presentation from `add C`
admits a section. -/
def IsRelativeSplitProjective (C : Set ι) (x : ι) : Prop :=
  ∀ P : σ.FacPresentation C (σ.obj x), IsSplitEpi P.map

namespace FacPresentation

/-- The map from one summand of a quotient presentation to its target. -/
def component
    {S : Set ι} {X : FGModuleCat.{w} R}
    (P : σ.FacPresentation S X) (t : P.index) :
    σ.obj (P.label t) ⟶ X :=
  biproduct.ι (fun t : P.index ↦ σ.obj (P.label t)) t ≫ P.map

/-- A quotient presentation is pointwise the sum of its component maps. -/
theorem map_apply_eq_sum_components
    {S : Set ι} {X : FGModuleCat.{w} R}
    (P : σ.FacPresentation S X)
    [Fintype P.index]
    (z : σ.sumOver P.index P.label) :
    P.map.hom.hom z =
      ∑ t : P.index,
        (P.component σ t).hom.hom
          ((biproduct.π
            (fun t : P.index ↦ σ.obj (P.label t)) t).hom.hom z) := by
  have hcat :
      P.map =
        ∑ t : P.index,
          biproduct.π (fun t : P.index ↦ σ.obj (P.label t)) t ≫
            P.component σ t := by
    calc
      P.map = 𝟙 _ ≫ P.map := (Category.id_comp _).symm
      _ =
          (∑ t : P.index,
            biproduct.π (fun t : P.index ↦ σ.obj (P.label t)) t ≫
              biproduct.ι (fun t : P.index ↦ σ.obj (P.label t)) t) ≫
            P.map := by rw [biproduct.total]
      _ =
          ∑ t : P.index,
            biproduct.π (fun t : P.index ↦ σ.obj (P.label t)) t ≫
              P.component σ t := by
        simp only [Preadditive.sum_comp, component, Category.assoc]
  let q : P.index → (σ.sumOver P.index P.label ⟶ X) :=
    fun t ↦
      biproduct.π (fun t : P.index ↦ σ.obj (P.label t)) t ≫
        P.component σ t
  let underlying :
      (σ.sumOver P.index P.label ⟶ X) →+
        (σ.sumOver P.index P.label →ₗ[R] X) :=
    { toFun := fun f ↦ f.hom.hom
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  have hmodule :
      (∑ t : P.index, q t).hom.hom =
        ∑ t : P.index, (q t).hom.hom := by
    change underlying (∑ t : P.index, q t) =
      ∑ t : P.index, underlying (q t)
    exact map_sum underlying q Finset.univ
  have hlinear := congrArg (fun q ↦ q.hom.hom) hcat
  change P.map.hom.hom = (∑ t : P.index, q t).hom.hom at hlinear
  rw [hmodule] at hlinear
  have happ := LinearMap.congr_fun hlinear z
  let eval :
      (σ.sumOver P.index P.label →ₗ[R] X) →+ X :=
    { toFun := fun f ↦ f z
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  have heval :
      (∑ t : P.index, (q t).hom.hom) z =
        ∑ t : P.index, (q t).hom.hom z := by
    change eval (∑ t : P.index, (q t).hom.hom) =
      ∑ t : P.index, eval ((q t).hom.hom)
    exact map_sum eval (fun t : P.index ↦ (q t).hom.hom) Finset.univ
  rw [heval] at happ
  simpa only [q, FGModuleCat.hom_hom_comp, LinearMap.comp_apply] using happ

/-- If one component, transported to an endomorphism of the target
representative, is a unit, the whole presentation splits. -/
theorem isSplitEpi_of_isUnit_component
    {S : Set ι} {x : ι}
    (P : σ.FacPresentation S (σ.obj x)) (t : P.index)
    (ht : P.label t = x)
    (hunit :
      IsUnit
        ((eqToHom (congrArg σ.obj ht.symm) ≫
          P.component σ t).hom.hom)) :
    IsSplitEpi P.map := by
  let a : Module.End R (σ.obj x) :=
    (eqToHom (congrArg σ.obj ht.symm) ≫
      P.component σ t).hom.hom
  let e : σ.obj x ≃ₗ[R] σ.obj x :=
    { toLinearMap := a
      invFun := (Equiv.ofBijective a
        ((Module.End.isUnit_iff a).mp hunit)).invFun
      left_inv := (Equiv.ofBijective a
        ((Module.End.isUnit_iff a).mp hunit)).left_inv
      right_inv := (Equiv.ofBijective a
        ((Module.End.isUnit_iff a).mp hunit)).right_inv }
  let s : σ.obj x ⟶ σ.sumOver P.index P.label :=
    FGModuleCat.ofHom e.symm.toLinearMap ≫
      eqToHom (congrArg σ.obj ht.symm) ≫
        biproduct.ι (fun t : P.index ↦ σ.obj (P.label t)) t
  have hinv :
      FGModuleCat.ofHom e.symm.toLinearMap ≫
          (eqToHom (congrArg σ.obj ht.symm) ≫
            P.component σ t) =
        𝟙 (σ.obj x) := by
    apply FGModuleCat.hom_ext
    ext z
    change
      ((eqToHom (congrArg σ.obj ht.symm) ≫
        P.component σ t).hom.hom) (e.symm z) = z
    change a (e.symm z) = z
    change e (e.symm z) = z
    exact e.apply_symm_apply z
  apply IsSplitEpi.mk'
  refine { section_ := s, id := ?_ }
  calc
    s ≫ P.map =
        FGModuleCat.ofHom e.symm.toLinearMap ≫
          (eqToHom (congrArg σ.obj ht.symm) ≫
            P.component σ t) := by
      dsimp only [s, component]
      simp only [Category.assoc]
    _ = 𝟙 (σ.obj x) := hinv

/-- If a presentation does not split, every component labelled by the
target representative becomes a nonunit endomorphism after transport. -/
theorem not_isUnit_component_of_not_isSplitEpi
    {S : Set ι} {x : ι}
    (P : σ.FacPresentation S (σ.obj x))
    (hP : ¬ IsSplitEpi P.map)
    (t : P.index) (ht : P.label t = x) :
    ¬ IsUnit
      ((eqToHom (congrArg σ.obj ht.symm) ≫
        P.component σ t).hom.hom) :=
  fun hunit ↦ hP (P.isSplitEpi_of_isUnit_component σ t ht hunit)

/-- A nonsplit quotient presentation from `add C` has range contained in
the trace of `C \ {x}` plus the ranges of radical endomorphisms of `x`. -/
theorem range_le_trace_sdiff_sup_idealRange
    {C : Set ι} {x : ι}
    (P : σ.FacPresentation C (σ.obj x))
    (hP : ¬ IsSplitEpi P.map) :
    LinearMap.range P.map.hom.hom ≤
      σ.trace (C \ {x}) (σ.obj x) ⊔
        QuotientSubmoduleEquidistribution.idealRange
          (Ring.jacobson (Module.End R (σ.obj x))) := by
  letI : Fintype P.index := FintypeCat.fintype
  rintro z ⟨a, rfl⟩
  rw [P.map_apply_eq_sum_components σ a]
  apply Submodule.sum_mem
  intro t _
  by_cases ht : P.label t = x
  · let f : σ.obj x ⟶ σ.obj x :=
      eqToHom (congrArg σ.obj ht.symm) ≫ P.component σ t
    have hfRad :
        f.hom.hom ∈
          Ring.jacobson (Module.End R (σ.obj x)) := by
      apply
        (QuotientSubmoduleEquidistribution.mem_end_jacobson_iff_not_isUnit
          (σ.indecomposable x) (σ.finiteLength x) f.hom.hom).2
      exact P.not_isUnit_component_of_not_isSplitEpi σ hP t ht
    have hrange :
        LinearMap.range (P.component σ t).hom.hom ≤
          LinearMap.range f.hom.hom := by
      let e : σ.obj x ≅ σ.obj (P.label t) :=
        eqToIso (congrArg σ.obj ht.symm)
      have hfac : e.inv ≫ f = P.component σ t := by
        dsimp only [e, f]
        simp
      have hlinear := congrArg (fun q ↦ q.hom.hom) hfac
      rw [← hlinear]
      exact LinearMap.range_comp_le_range e.inv.hom.hom f.hom.hom
    exact
      (le_sup_of_le_right
        (hrange.trans
          (QuotientSubmoduleEquidistribution.range_le_idealRange f.hom.hom hfRad)))
        ⟨_, rfl⟩
  · have hmem : P.label t ∈ C \ {x} := by
      exact ⟨P.mem t, by simpa using ht⟩
    exact le_sup_of_le_left
      (σ.range_le_trace_of_mem hmem (P.component σ t))
      ⟨_, rfl⟩

end FacPresentation

/-- Extremality implies relative split projectivity.  Nilpotence of the
Jacobson radical (here obtained from Artinianness of the endomorphism ring)
is the extra input needed to discard nonsplit copies of `x` in a source. -/
theorem isRelativeSplitProjective_of_not_mem_qClosure_sdiff
    (C : Set ι) (x : ι)
    [IsArtinianRing (Module.End R (σ.obj x))]
    (hx : x ∉ σ.qClosure (C \ {x})) :
    σ.IsRelativeSplitProjective C x := by
  intro P
  by_contra hP
  let J := Ring.jacobson (Module.End R (σ.obj x))
  have hsup :
      σ.trace (C \ {x}) (σ.obj x) ⊔
        QuotientSubmoduleEquidistribution.idealRange J = ⊤ := by
    letI : Epi P.map := P.epi
    apply top_unique
    rw [← range_eq_top_of_epi P.map]
    exact P.range_le_trace_sdiff_sup_idealRange σ hP
  have htrace : σ.trace (C \ {x}) (σ.obj x) = ⊤ := by
    apply QuotientSubmoduleEquidistribution.eq_top_of_nilpotent_idealRange J
    · exact trace_fullyInvariant_linear σ (σ.obj x)
    · dsimp only [J]
      exact
        (Ideal.jacobson_bot (R :=
          Module.End R (σ.obj x))) ▸
            IsArtinianRing.isNilpotent_jacobson_bot
    · exact hsup
  exact hx ((mem_qClosure_iff_trace_eq_top σ (C \ {x}) x).2 htrace)

/-- Relative split projectivity prevents generation by the other selected
representatives.  This direction only uses locality of `End(x)`, which
comes from indecomposability and finite length. -/
theorem not_mem_qClosure_sdiff_of_isRelativeSplitProjective
    (C : Set ι) (x : ι)
    (hproj : σ.IsRelativeSplitProjective C x) :
    x ∉ σ.qClosure (C \ {x}) := by
  intro hx
  rw [mem_qClosure_iff_inFac] at hx
  obtain ⟨P⟩ := hx
  let PC : σ.FacPresentation C (σ.obj x) :=
    P.of_subset σ (by intro y hy; exact hy.1)
  have hsplit : IsSplitEpi P.map := hproj PC
  letI : IsSplitEpi P.map := hsplit
  letI : Fintype P.index := FintypeCat.fintype
  let comp : P.index → Module.End R (σ.obj x) :=
    fun t ↦
      (P.component σ t).hom.hom.comp
        (CategoryTheory.section_ P.map ≫
          biproduct.π
            (fun t : P.index ↦ σ.obj (P.label t)) t).hom.hom
  have hcat :
      ∑ t : P.index,
          (CategoryTheory.section_ P.map ≫
            biproduct.π
              (fun t : P.index ↦ σ.obj (P.label t)) t) ≫
            P.component σ t =
        𝟙 (σ.obj x) := by
    calc
      (∑ t : P.index,
          (CategoryTheory.section_ P.map ≫
            biproduct.π
              (fun t : P.index ↦ σ.obj (P.label t)) t) ≫
            P.component σ t) =
          CategoryTheory.section_ P.map ≫
            (∑ t : P.index,
              biproduct.π
                (fun t : P.index ↦ σ.obj (P.label t)) t ≫
              biproduct.ι
                (fun t : P.index ↦ σ.obj (P.label t)) t) ≫
            P.map := by
        simp only [FacPresentation.component, Category.assoc,
          Preadditive.comp_sum, Preadditive.sum_comp]
      _ = CategoryTheory.section_ P.map ≫ P.map := by
        rw [biproduct.total]
        simp
      _ = 𝟙 (σ.obj x) := IsSplitEpi.id P.map
  let underlying :
      (σ.obj x ⟶ σ.obj x) →+
        Module.End R (σ.obj x) :=
    { toFun := fun f ↦ f.hom.hom
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  have hsum :
      (∑ t : P.index,
          ((CategoryTheory.section_ P.map ≫
            biproduct.π
              (fun t : P.index ↦ σ.obj (P.label t)) t) ≫
            P.component σ t)).hom.hom =
        ∑ t : P.index, comp t := by
    change
      underlying
          (∑ t : P.index,
            (CategoryTheory.section_ P.map ≫
              biproduct.π
                (fun t : P.index ↦ σ.obj (P.label t)) t) ≫
              P.component σ t) =
        ∑ t : P.index,
          underlying
            ((CategoryTheory.section_ P.map ≫
              biproduct.π
                (fun t : P.index ↦ σ.obj (P.label t)) t) ≫
              P.component σ t)
    simpa only [comp, FGModuleCat.hom_hom_comp] using
      map_sum underlying
        (fun t : P.index ↦
          (CategoryTheory.section_ P.map ≫
            biproduct.π
              (fun t : P.index ↦ σ.obj (P.label t)) t) ≫
            P.component σ t)
        Finset.univ
  have hcompSum : (∑ t : P.index, comp t) = 1 := by
    rw [← hsum]
    rw [hcat]
    rfl
  letI : IsLocalRing (Module.End R (σ.obj x)) :=
    QuotientSubmoduleEquidistribution.Foundation.isLocalRing_end_of_isIndecomposable
      (σ.finiteLength x) (σ.indecomposable x)
  have hunit : IsUnit (∑ t : P.index, comp t) := by
    rw [hcompSum]
    exact isUnit_one
  obtain ⟨t, _, htunit⟩ :=
    IsLocalRing.exists_of_isUnit_sum
      (s := Finset.univ) (f := comp) hunit
  obtain ⟨e⟩ :=
    QuotientSubmoduleEquidistribution.nonempty_linearEquiv_of_isUnit_comp
      (σ.indecomposable x) (σ.indecomposable (P.label t))
      (P.component σ t).hom.hom
      (CategoryTheory.section_ P.map ≫
        biproduct.π
          (fun t : P.index ↦ σ.obj (P.label t)) t).hom.hom
      htunit
  have heq : x = P.label t :=
    σ.eq_of_iso ⟨e.toFGModuleCatIso⟩
  apply (P.mem t).2
  exact Set.mem_singleton_iff.mpr heq.symm

/-- The module-theoretic extremality equivalence.  It holds for an arbitrary
selected set `C`; only Artinianness of `End(x)` is used in the difficult
implication. -/
theorem not_mem_qClosure_sdiff_iff_isRelativeSplitProjective
    (C : Set ι) (x : ι)
    [IsArtinianRing (Module.End R (σ.obj x))] :
    x ∉ σ.qClosure (C \ {x}) ↔
      σ.IsRelativeSplitProjective C x :=
  ⟨σ.isRelativeSplitProjective_of_not_mem_qClosure_sdiff C x,
    σ.not_mem_qClosure_sdiff_of_isRelativeSplitProjective C x⟩

/-- The manuscript-context wrapper: `C` is quotient-closed and contains
`x`.  The stronger theorem above shows that these two assumptions locate
the statement inside the closed set but are not needed by the equivalence. -/
theorem extremal_iff_isRelativeSplitProjective_of_qClosed
    (C : Set ι) (x : ι)
    [IsArtinianRing (Module.End R (σ.obj x))]
    (_hC : σ.qClosure.IsClosed C) (_hxC : x ∈ C) :
    x ∉ σ.qClosure (C \ {x}) ↔
      σ.IsRelativeSplitProjective C x :=
  σ.not_mem_qClosure_sdiff_iff_isRelativeSplitProjective C x

end QuotientSubmoduleEquidistribution.IndecomposableSkeleton
