import Mathlib.Algebra.TrivSqZeroExt.Basic
import Mathlib.RingTheory.Jacobson.Ideal
import Mathlib.RingTheory.Jacobson.Semiprimary

/-!
# Radicals of modules over a trivial square-zero extension

Let `R = S ⋉ J` be a trivial square-zero extension with semisimple base ring
`S`.  This file proves two structural identities needed by the separated-quiver
argument:

* the augmentation ideal `0 ⊕ J` is the Jacobson radical of `R`;
* for every left `R`-module `X`, its module Jacobson radical is exactly
  `(0 ⊕ J) • X`.

No finiteness hypothesis on `X` is needed.  The quotient by `(0 ⊕ J) • X` is
shown semisimple by transporting its `S`-module structure along the surjective
augmentation `R → S`.  The final annihilation theorem says that the
augmentation ideal kills the module radical, so radical action descends to the
module top.
-/

set_option autoImplicit false

noncomputable section

namespace QuotientSubmoduleEquidistribution.TrivSqZeroExtRadical

universe u v w

variable {S : Type u} {J : Type v}
variable [CommRing S] [AddCommGroup J]
variable [Module S J] [Module Sᵐᵒᵖ J]
variable [SMulCommClass S Sᵐᵒᵖ J]

/-- The canonical augmentation from a trivial square-zero extension to its
base ring, viewed as a ring homomorphism. -/
def augmentation : TrivSqZeroExt S J →+* S where
  toFun := TrivSqZeroExt.fst
  map_one' := TrivSqZeroExt.fst_one
  map_mul' := TrivSqZeroExt.fst_mul
  map_zero' := TrivSqZeroExt.fst_zero
  map_add' := TrivSqZeroExt.fst_add

/-- The augmentation ideal `0 ⊕ J`. -/
def augmentationIdeal : Ideal (TrivSqZeroExt S J) :=
  RingHom.ker augmentation

@[simp]
theorem mem_augmentationIdeal_iff (x : TrivSqZeroExt S J) :
    x ∈ augmentationIdeal ↔ x.fst = 0 := by
  rfl

instance augmentationIdeal_isTwoSided :
    (augmentationIdeal (S := S) (J := J)).IsTwoSided :=
  ⟨fun {x} y hx ↦ by
    apply (mem_augmentationIdeal_iff (x * y)).mpr
    rw [TrivSqZeroExt.fst_mul,
      (mem_augmentationIdeal_iff x).mp hx, zero_mul]⟩

/-- Every element of the augmentation ideal is its own `inr` presentation. -/
theorem eq_inr_snd_of_mem_augmentationIdeal
    {x : TrivSqZeroExt S J} (hx : x ∈ augmentationIdeal) :
    x = TrivSqZeroExt.inr x.snd := by
  apply TrivSqZeroExt.ext
  · exact (mem_augmentationIdeal_iff x).mp hx
  · rfl

/-- The augmentation ideal is square-zero. -/
theorem augmentationIdeal_sq_eq_bot :
    augmentationIdeal (S := S) (J := J) ^ 2 = ⊥ := by
  rw [show (2 : ℕ) = 1 + 1 by omega,
    Ideal.IsTwoSided.pow_succ, Submodule.pow_one]
  apply le_antisymm
  · rw [Ideal.mul_le]
    intro x hx y hy
    rw [eq_inr_snd_of_mem_augmentationIdeal hx,
      eq_inr_snd_of_mem_augmentationIdeal hy,
      TrivSqZeroExt.inr_mul_inr]
    exact Submodule.zero_mem _
  · exact bot_le

/-- If the base is semisimple, the augmentation ideal is exactly the ring
Jacobson radical. -/
theorem augmentationIdeal_eq_jacobson [IsSemisimpleRing S] :
    augmentationIdeal (S := S) (J := J) =
      Ring.jacobson (TrivSqZeroExt S J) := by
  letI : RingHomSurjective (augmentation (S := S) (J := J)) :=
    ⟨TrivSqZeroExt.fst_surjective⟩
  apply le_antisymm
  · intro x hx
    rw [← Ideal.jacobson_bot]
    apply Ideal.mem_jacobson_iff.mpr
    intro y
    let n := y * x
    have hn : n ∈ augmentationIdeal (S := S) (J := J) :=
      (augmentationIdeal (S := S) (J := J)).mul_mem_left y hx
    have hsquare : n * n = 0 := by
      have hmem : n * n ∈
          augmentationIdeal (S := S) (J := J) *
            augmentationIdeal (S := S) (J := J) :=
        Ideal.mul_mem_mul hn hn
      have hI := augmentationIdeal_sq_eq_bot (S := S) (J := J)
      rw [show (2 : ℕ) = 1 + 1 by omega,
        Ideal.IsTwoSided.pow_succ, Submodule.pow_one] at hI
      rw [hI] at hmem
      exact hmem
    refine ⟨1 - n, ?_⟩
    rw [mul_assoc, show y * x = n from rfl]
    rw [sub_mul, one_mul, hsquare, sub_zero]
    simp
  · intro x hx
    have hfst : augmentation x ∈ Ring.jacobson S :=
      (Ring.le_comap_jacobson
        (augmentation (S := S) (J := J))) hx
    rw [IsSemisimpleRing.jacobson_eq_bot S] at hfst
    exact (mem_augmentationIdeal_iff x).mpr hfst

section Module

variable {X : Type w} [AddCommGroup X]
variable [Module (TrivSqZeroExt S J) X]

/-- The part of a module generated by the augmentation ideal. -/
def radicalPart : Submodule (TrivSqZeroExt S J) X :=
  augmentationIdeal (S := S) (J := J) • ⊤

/-- The quotient by the augmentation-generated part is semisimple. -/
theorem quotient_radicalPart_isSemisimple [IsSemisimpleRing S] :
    IsSemisimpleModule (TrivSqZeroExt S J)
      (X ⧸ radicalPart (S := S) (J := J) (X := X)) := by
  let N := radicalPart (S := S) (J := J) (X := X)
  let Q := X ⧸ N
  letI : Module S Q :=
    Module.compHom Q (TrivSqZeroExt.inlHom S J)
  letI : RingHomSurjective (augmentation (S := S) (J := J)) :=
    ⟨TrivSqZeroExt.fst_surjective⟩
  let l : Q →ₛₗ[augmentation (S := S) (J := J)] Q :=
    { toFun := id
      map_add' := fun _ _ ↦ rfl
      map_smul' := fun r q ↦ by
        obtain ⟨x, rfl⟩ := N.mkQ_surjective q
        change N.mkQ (r • x) =
          N.mkQ ((TrivSqZeroExt.inl r.fst) • x)
        apply (Submodule.Quotient.eq N).mpr
        rw [← sub_smul]
        apply Submodule.smul_mem_smul
        · apply (mem_augmentationIdeal_iff
            (r - TrivSqZeroExt.inl r.fst)).mpr
          simp
        · exact Submodule.mem_top }
  apply (l.isSemisimpleModule_iff_of_bijective
    Function.bijective_id).mpr
  infer_instance

/-- The module Jacobson radical is exactly the augmentation-generated part. -/
theorem module_jacobson_eq_radicalPart [IsSemisimpleRing S] :
    Module.jacobson (TrivSqZeroExt S J) X =
      radicalPart (S := S) (J := J) (X := X) := by
  apply le_antisymm
  · letI : IsSemisimpleModule (TrivSqZeroExt S J)
        (X ⧸ radicalPart (S := S) (J := J) (X := X)) :=
      quotient_radicalPart_isSemisimple
        (S := S) (J := J) (X := X)
    apply Module.jacobson_le_of_eq_bot
    exact IsSemisimpleModule.jacobson_eq_bot _ _
  · change augmentationIdeal (S := S) (J := J) • ⊤ ≤
      Module.jacobson (TrivSqZeroExt S J) X
    rw [augmentationIdeal_eq_jacobson (S := S) (J := J)]
    exact Ring.jacobson_smul_top_le _ _

/-- The augmentation ideal annihilates the module Jacobson radical. -/
theorem augmentation_smul_module_jacobson_eq_zero
    [IsSemisimpleRing S]
    (r : TrivSqZeroExt S J)
    (hr : r ∈ augmentationIdeal (S := S) (J := J))
    (x : X)
    (hx : x ∈ Module.jacobson (TrivSqZeroExt S J) X) :
    r • x = 0 := by
  rw [module_jacobson_eq_radicalPart (S := S) (J := J)] at hx
  refine Submodule.smul_induction_on hx ?_ ?_
  · intro a ha y _
    rw [← mul_smul]
    have hmem : r * a ∈
        augmentationIdeal (S := S) (J := J) *
          augmentationIdeal (S := S) (J := J) :=
      Ideal.mul_mem_mul hr ha
    have hI := augmentationIdeal_sq_eq_bot (S := S) (J := J)
    rw [show (2 : ℕ) = 1 + 1 by omega,
      Ideal.IsTwoSided.pow_succ, Submodule.pow_one] at hI
    rw [hI] at hmem
    rw [hmem, zero_smul]
  · intro x y hx hy
    rw [smul_add, hx, hy, add_zero]

/-- Square-zero Nakayama: over a trivial square-zero extension with
semisimple base, a submodule fills the ambient module if and only if it fills
it modulo the module Jacobson radical.  Unlike the usual Nakayama lemma, no
finiteness hypothesis is needed here: the augmentation ideal generates the
module radical and annihilates it. -/
theorem eq_top_iff_sup_module_jacobson_eq_top
    [IsSemisimpleRing S]
    (N : Submodule (TrivSqZeroExt S J) X) :
    N = ⊤ ↔
      N ⊔ Module.jacobson (TrivSqZeroExt S J) X = ⊤ := by
  constructor
  · intro hN
    rw [hN, top_sup_eq]
  · intro hsup
    have hjac :
        Module.jacobson (TrivSqZeroExt S J) X ≤ N := by
      rw [module_jacobson_eq_radicalPart (S := S) (J := J)]
      apply Submodule.smul_le.mpr
      intro r hr x _
      have hxSup :
          x ∈ N ⊔ Module.jacobson (TrivSqZeroExt S J) X := by
        rw [hsup]
        exact Submodule.mem_top
      obtain ⟨n, hn, y, hy, hny⟩ := Submodule.mem_sup.mp hxSup
      rw [← hny, smul_add]
      rw [augmentation_smul_module_jacobson_eq_zero
        (S := S) (J := J) r hr y hy, add_zero]
      exact N.smul_mem r hn
    apply top_unique
    rw [← hsup]
    exact sup_le le_rfl hjac

/-- The action of an augmentation-ideal element descends from the module top
to the module radical.  At this generic level it is packaged additively; the
split-basic field-coordinate specialization upgrades the arrow maps to linear
maps over the ground field. -/
def radicalAction [IsSemisimpleRing S]
    (r : augmentationIdeal (S := S) (J := J)) :
    (X ⧸ Module.jacobson (TrivSqZeroExt S J) X) →+
      Module.jacobson (TrivSqZeroExt S J) X := by
  let f : X →+ X :=
    { toFun := fun x ↦ (r : TrivSqZeroExt S J) • x
      map_zero' := smul_zero _
      map_add' := fun _ _ ↦ smul_add _ _ _ }
  let f' : X →+ Module.jacobson (TrivSqZeroExt S J) X :=
    f.codRestrict _ (fun x ↦ by
      rw [module_jacobson_eq_radicalPart (S := S) (J := J)]
      exact Submodule.smul_mem_smul r.property Submodule.mem_top)
  exact QuotientAddGroup.lift
    (Module.jacobson (TrivSqZeroExt S J) X).toAddSubgroup f'
    (fun x hx ↦ by
      apply Subtype.ext
      exact augmentation_smul_module_jacobson_eq_zero
        (S := S) (J := J) r r.property x hx)

@[simp]
theorem radicalAction_mk [IsSemisimpleRing S]
    (r : augmentationIdeal (S := S) (J := J)) (x : X) :
    radicalAction r
        ((Module.jacobson (TrivSqZeroExt S J) X).mkQ x) =
      ⟨(r : TrivSqZeroExt S J) • x, by
        rw [module_jacobson_eq_radicalPart (S := S) (J := J)]
        exact Submodule.smul_mem_smul r.property Submodule.mem_top⟩ := by
  rfl

/-- The descended radical action is additive in the augmentation-ideal
coordinate. -/
def radicalActionFamily [IsSemisimpleRing S] :
    augmentationIdeal (S := S) (J := J) →+
      ((X ⧸ Module.jacobson (TrivSqZeroExt S J) X) →+
        Module.jacobson (TrivSqZeroExt S J) X) where
  toFun := radicalAction
  map_zero' := by
    ext q
    obtain ⟨x, rfl⟩ :=
      (Module.jacobson (TrivSqZeroExt S J) X).mkQ_surjective q
    change (0 : TrivSqZeroExt S J) • x = 0
    exact zero_smul _ _
  map_add' r s := by
    ext q
    obtain ⟨x, rfl⟩ :=
      (Module.jacobson (TrivSqZeroExt S J) X).mkQ_surjective q
    exact add_smul (r : TrivSqZeroExt S J)
      (s : TrivSqZeroExt S J) x

end Module

end QuotientSubmoduleEquidistribution.TrivSqZeroExtRadical
