import OpConjecture.RadicalSquareZero.TopCoverageAdapter

/-!
# Constructing top-coverage data from actual closure membership

This file removes one layer of abstract input from the radical-square-zero
endpoint.  Suppose quotient closure has already been relabeled so that its
labels are nonsimples together with simple vertices.  If membership in the
two relevant closures has the expected pointwise form, then the common core
and both exact closed-set parametrizations are canonical.

The common cores are precisely the finite nonsimple supports `C` which are
closed under nonsimple generation.  Their mandatory decoration is the set of
simple tops forced by `C`.  Thus the output is the literal
`ATopCoverageData` and `BTopCoverageData` consumed by the polynomial
endpoint, not a restatement of those structures as an assumption.
-/

set_option autoImplicit false

noncomputable section

namespace OpConjecture.RadicalSquareZeroCombinatorics
namespace CoreFamily
namespace TopCoverage

open Set

universe u v

variable {Nonsimple : Type u} {Vertex : Type v}
  [Fintype Nonsimple] [DecidableEq Nonsimple]
  [Fintype Vertex] [DecidableEq Vertex]

/-- A finite nonsimple support which contains every nonsimple generated by
that support. -/
def AdmissibleCore
    (Generates : Finset Nonsimple → Nonsimple → Prop) :=
  {C : Finset Nonsimple // ∀ y, Generates C y → y ∈ C}

noncomputable instance admissibleCoreFintype
    (Generates : Finset Nonsimple → Nonsimple → Prop) :
    Fintype (AdmissibleCore Generates) := by
  letI : Finite (AdmissibleCore Generates) :=
    Finite.of_injective Subtype.val Subtype.val_injective
  exact Fintype.ofFinite _

/-- Pointwise membership laws for a pair of original and separated quotient
closures.  The first separated simple copy is governed by the same mandatory
top support as the original closure; the second copy is genuinely free.

These are the local statements delivered by the module-theoretic part of the
separated-quiver proof. -/
structure PairedClosureMembership
    (clA : OpConjecture.SetClosure (Nonsimple ⊕ Vertex))
    (clB : OpConjecture.SetClosure
      (Nonsimple ⊕ (Vertex ⊕ Vertex))) where
  /-- Nonsimple generation depends only on the selected nonsimple support. -/
  Generates : Finset Nonsimple → Nonsimple → Prop
  /-- Simple vertices forced by a nonsimple support. -/
  forcedTop : Finset Nonsimple → Finset Vertex
  a_nonsimple_mem (S : Set (Nonsimple ⊕ Vertex)) (y : Nonsimple) :
    Sum.inl y ∈ clA S ↔ Generates (nonsimplePart S) y
  a_simple_mem (S : Set (Nonsimple ⊕ Vertex)) (v : Vertex) :
    Sum.inr v ∈ clA S ↔
      Sum.inr v ∈ S ∨ v ∈ forcedTop (nonsimplePart S)
  b_nonsimple_mem
      (S : Set (Nonsimple ⊕ (Vertex ⊕ Vertex))) (y : Nonsimple) :
    Sum.inl y ∈ clB S ↔ Generates (bNonsimplePart S) y
  b_covered_simple_mem
      (S : Set (Nonsimple ⊕ (Vertex ⊕ Vertex))) (v : Vertex) :
    Sum.inr (Sum.inl v) ∈ clB S ↔
      Sum.inr (Sum.inl v) ∈ S ∨
        v ∈ forcedTop (bNonsimplePart S)
  b_free_simple_mem
      (S : Set (Nonsimple ⊕ (Vertex ⊕ Vertex))) (v : Vertex) :
    Sum.inr (Sum.inr v) ∈ clB S ↔
      Sum.inr (Sum.inr v) ∈ S

namespace PairedClosureMembership

variable
  {clA : OpConjecture.SetClosure (Nonsimple ⊕ Vertex)}
  {clB : OpConjecture.SetClosure
    (Nonsimple ⊕ (Vertex ⊕ Vertex))}
  (D : PairedClosureMembership clA clB)

/-- The common core family canonically extracted from the pointwise closure
laws. -/
def coreFamily :
    CoreFamily (AdmissibleCore D.Generates) Vertex where
  coreSize C := C.1.card
  topSupport C := D.forcedTop C.1

omit [DecidableEq Nonsimple] [DecidableEq Vertex] in
/-- Exact original-side closedness follows from the pointwise membership
laws. -/
theorem a_isClosed_iff
    (S : Set (Nonsimple ⊕ Vertex)) :
    clA.IsClosed S ↔
      ∃ C : AdmissibleCore D.Generates,
        nonsimplePart S = C.1 ∧
          D.forcedTop C.1 ⊆ simplePart S := by
  constructor
  · intro hclosed
    have hle : clA S ⊆ S :=
      ClosureOperator.isClosed_iff_closure_le.mp hclosed
    let C₀ := nonsimplePart S
    have hstable : ∀ y, D.Generates C₀ y → y ∈ C₀ := by
      intro y hy
      apply (mem_nonsimplePart_iff S y).2
      apply hle
      exact (D.a_nonsimple_mem S y).2 hy
    let C : AdmissibleCore D.Generates := ⟨C₀, hstable⟩
    refine ⟨C, rfl, ?_⟩
    intro v hv
    apply (mem_simplePart_iff S v).2
    apply hle
    exact (D.a_simple_mem S v).2 (Or.inr hv)
  · rintro ⟨C, hpart, htop⟩
    rw [ClosureOperator.isClosed_iff_closure_le]
    intro z hz
    cases z with
    | inl y =>
        apply (mem_nonsimplePart_iff S y).1
        rw [hpart]
        apply C.2 y
        have hy := (D.a_nonsimple_mem S y).1 hz
        simpa [hpart] using hy
    | inr v =>
        rcases (D.a_simple_mem S v).1 hz with hv | hv
        · exact hv
        · apply (mem_simplePart_iff S v).1
          apply htop
          simpa [hpart] using hv

omit [DecidableEq Nonsimple] [DecidableEq Vertex] in
/-- Exact separated-side closedness follows from the same nonsimple cores and
forced top support; the second simple copy contributes no condition. -/
theorem b_isClosed_iff
    (S : Set (Nonsimple ⊕ (Vertex ⊕ Vertex))) :
    clB.IsClosed S ↔
      ∃ C : AdmissibleCore D.Generates,
        bNonsimplePart S = C.1 ∧
          D.forcedTop C.1 ⊆ bCoveredSimplePart S := by
  constructor
  · intro hclosed
    have hle : clB S ⊆ S :=
      ClosureOperator.isClosed_iff_closure_le.mp hclosed
    let C₀ := bNonsimplePart S
    have hstable : ∀ y, D.Generates C₀ y → y ∈ C₀ := by
      intro y hy
      apply (mem_bNonsimplePart_iff S y).2
      apply hle
      exact (D.b_nonsimple_mem S y).2 hy
    let C : AdmissibleCore D.Generates := ⟨C₀, hstable⟩
    refine ⟨C, rfl, ?_⟩
    intro v hv
    apply (mem_bCoveredSimplePart_iff S v).2
    apply hle
    exact (D.b_covered_simple_mem S v).2 (Or.inr hv)
  · rintro ⟨C, hpart, htop⟩
    rw [ClosureOperator.isClosed_iff_closure_le]
    intro z hz
    cases z with
    | inl y =>
        apply (mem_bNonsimplePart_iff S y).1
        rw [hpart]
        apply C.2 y
        have hy := (D.b_nonsimple_mem S y).1 hz
        simpa [hpart] using hy
    | inr z =>
        cases z with
        | inl v =>
            rcases (D.b_covered_simple_mem S v).1 hz with hv | hv
            · exact hv
            · apply (mem_bCoveredSimplePart_iff S v).1
              apply htop
              simpa [hpart] using hv
        | inr v =>
            exact (D.b_free_simple_mem S v).1 hz

/-- The actual original closure supplies the abstract original top-coverage
record used by the enumeration theorem. -/
noncomputable def toATopCoverageData :
    ATopCoverageData D.coreFamily clA where
  corePart C := C.1
  corePart_injective := Subtype.val_injective
  coreSize_eq_card _ := rfl
  isClosed_iff S := D.a_isClosed_iff S

/-- The actual separated closure supplies the abstract separated
top-coverage record, with the same canonical core family. -/
noncomputable def toBTopCoverageData :
    BTopCoverageData D.coreFamily clB where
  corePart C := C.1
  corePart_injective := Subtype.val_injective
  coreSize_eq_card _ := rfl
  isClosed_iff S := D.b_isClosed_iff S

end PairedClosureMembership

end TopCoverage
end CoreFamily
end OpConjecture.RadicalSquareZeroCombinatorics
