import Mathlib.Data.Set.Finite.Powerset
import Mathlib.Order.Closure
import Mathlib.Order.Preorder.Finite

/-!
# Closure operators with anti-exchange

This file develops the abstract closure-theoretic layer used in
`paper/op_conjecture/main.tex`.  The definitions do not assume that the
ground type is finite; finiteness enters only in the later finite convex
geometry results.
-/

open Set

namespace OpConjecture

/-- A closure operator on subsets of `E`. -/
abbrev SetClosure (E : Type*) := ClosureOperator (Set E)

namespace SetClosure

variable {E : Type*} (c : SetClosure E)

/-- Every point in a closure is already forced by a finite subset. -/
def IsFinitary : Prop :=
  ∀ ⦃X : Set E⦄ ⦃x : E⦄, x ∈ c X →
    ∃ Y : Set E, Y.Finite ∧ Y ⊆ X ∧ x ∈ c Y

/-- The anti-exchange axiom for a closure operator on subsets. -/
def IsAntiExchange : Prop :=
  ∀ ⦃C : Set E⦄ ⦃x y : E⦄, c.IsClosed C → x ∉ C → y ∉ C → x ≠ y →
    x ∈ c (insert y C) → y ∉ c (insert x C)

/-- The closure-theoretic axioms of a convex geometry.

Finiteness of the ground type is deliberately kept separate, so that the
same API also applies to the finitary closures occurring for
representation-infinite algebras.
-/
def IsConvexGeometry : Prop :=
  c.IsClosed ∅ ∧ c.IsAntiExchange

/-- The extreme points of `C`: the points not generated by the other
points of `C`. -/
def extremePoints (C : Set E) : Set E :=
  {x | x ∈ C ∧ x ∉ c (C \ {x})}

variable {c}

theorem mem_extremePoints {C : Set E} {x : E} :
    x ∈ c.extremePoints C ↔ x ∈ C ∧ x ∉ c (C \ {x}) :=
  Iff.rfl

/-- If deleting `x` from a closed set does not regenerate `x`, the
deletion is closed. -/
theorem isClosed_sdiff_singleton_of_not_mem_closure
    {C : Set E} {x : E} (hC : c.IsClosed C)
    (hx : x ∉ c (C \ {x})) :
    c.IsClosed (C \ {x}) := by
  rw [ClosureOperator.isClosed_iff_closure_le]
  intro y hy
  exact ⟨c.closure_min sdiff_subset hC hy, fun hyx ↦ hx (hyx ▸ hy)⟩

/-- For a point of a closed set, being extreme is equivalent to legal
one-point deletion. -/
theorem mem_extremePoints_iff_isClosed_sdiff_singleton
    {C : Set E} {x : E} (hC : c.IsClosed C) (hxC : x ∈ C) :
    x ∈ c.extremePoints C ↔ c.IsClosed (C \ {x}) := by
  rw [mem_extremePoints, and_iff_right hxC]
  constructor
  · exact isClosed_sdiff_singleton_of_not_mem_closure hC
  · intro hdel hx
    simp [hdel.closure_eq] at hx

/-- Every generating set contains every extreme point. -/
theorem extremePoints_subset_of_closure_eq
    {B C : Set E} (hBC : c B = C) :
    c.extremePoints C ⊆ B := by
  intro x hx
  by_contra hxB
  have hBsub : B ⊆ C \ {x} := by
    intro y hyB
    refine ⟨?_, ?_⟩
    · exact hBC ▸ c.le_closure B hyB
    · simpa [Set.mem_singleton_iff] using fun hyx : y = x ↦ hxB (hyx ▸ hyB)
  exact hx.2 (c.monotone hBsub (hBC ▸ hx.1))

/-- In a finitary anti-exchange closure with closed empty set, deleting
the generating point from its point closure leaves a closed set.

This is the key step behind complete join-irreducibility of point
closures in the manuscript.
-/
theorem isClosed_pointClosure_sdiff_singleton
    (hfin : c.IsFinitary) (hae : c.IsAntiExchange)
    (hempty : c.IsClosed ∅) (x : E) :
    c.IsClosed (c ({x} : Set E) \ {x}) := by
  let J : Set E := c ({x} : Set E)
  have hJ : c.IsClosed J := c.isClosed_closure _
  by_contra hnot
  have hxc : x ∈ c (J \ {x}) := by
    by_contra hx
    exact hnot (isClosed_sdiff_singleton_of_not_mem_closure hJ hx)
  obtain ⟨S₀, hS₀fin, hS₀sub, hxS₀⟩ := hfin hxc
  let P : Set (Set E) := {S | S ⊆ S₀ ∧ x ∈ c S}
  have hPfin : P.Finite := by
    apply hS₀fin.powerset.subset
    intro S hS
    exact hS.1
  have hPnonempty : P.Nonempty := ⟨S₀, subset_rfl, hxS₀⟩
  obtain ⟨S, hSmin⟩ := hPfin.exists_minimal hPnonempty
  have hSne : S.Nonempty := by
    rw [nonempty_iff_ne_empty]
    intro hSempty
    have : x ∈ c (∅ : Set E) := by
      simpa [hSempty] using hSmin.prop.2
    simp [hempty.closure_eq] at this
  obtain ⟨y, hyS⟩ := hSne
  have hproper : S \ {y} ⊂ S := by
    rw [Set.ssubset_iff_subset_ne]
    refine ⟨sdiff_subset, ?_⟩
    intro heq
    have : y ∈ S \ {y} := heq.symm ▸ hyS
    exact this.2 rfl
  have hxK : x ∉ c (S \ {y}) := by
    intro hx
    apply hSmin.not_prop_of_ssubset hproper
    exact ⟨sdiff_subset.trans hSmin.prop.1, hx⟩
  let K : Set E := c (S \ {y})
  have hKclosed : c.IsClosed K := c.isClosed_closure _
  have hxK' : x ∉ K := hxK
  have hyK : y ∉ K := by
    intro hy
    have hSK : S ⊆ K := by
      intro z hz
      by_cases hzy : z = y
      · simpa [hzy] using hy
      · exact c.le_closure (S \ {y}) ⟨hz, by simpa using hzy⟩
    have hxcK : x ∈ c K := c.monotone hSK hSmin.prop.2
    exact hxK' (by simpa [K] using hxcK)
  have hxy : x ≠ y := by
    intro hxy
    have hyS₀ : y ∈ S₀ := hSmin.prop.1 hyS
    have hyJdiff : y ∈ J \ {x} := hS₀sub hyS₀
    exact hyJdiff.2 (by simp [hxy])
  have hxInsert : x ∈ c (insert y K) := by
    apply c.monotone _ hSmin.prop.2
    intro z hz
    by_cases hzy : z = y
    · simp [hzy]
    · exact mem_insert_of_mem _ (c.le_closure (S \ {y}) ⟨hz, by simpa using hzy⟩)
  have hyJdiff : y ∈ J \ {x} := hS₀sub (hSmin.prop.1 hyS)
  have hyInsert : y ∈ c (insert x K) := by
    apply c.monotone _ hyJdiff.1
    exact singleton_subset_iff.mpr (mem_insert x K)
  exact (hae hKclosed hxK' hyK hxy hxInsert) hyInsert

/-- Distinct points have distinct point closures in a convex geometry. -/
theorem pointClosure_injective
    (hae : c.IsAntiExchange) (hempty : c.IsClosed ∅) :
    Function.Injective (fun x : E ↦ c ({x} : Set E)) := by
  intro x y hxy
  change c ({x} : Set E) = c ({y} : Set E) at hxy
  by_contra hne
  have hx : x ∈ c ({y} : Set E) := by
    rw [← hxy]
    exact c.le_closure {x} (mem_singleton x)
  have hy : y ∈ c ({x} : Set E) := by
    rw [hxy]
    exact c.le_closure {y} (mem_singleton y)
  have hnot := hae hempty (by simp) (by simp) hne
    (by simpa using hx)
  exact hnot (by simpa using hy)

end SetClosure

end OpConjecture
