import OpConjecture.RepresentationDirected.ClosureEffectivityForward
import OpConjecture.RepresentationDirected.EffectiveLifting
import OpConjecture.RepresentationTheory.FaithfulCore

/-!
# Closure effectivity for representation-directed skeletons

This file proves the manuscript's closure-effectivity proposition: the
additive category generated by the labels outside `D` is quotient-closed if
and only if all mixed coordinates relative to `D` are nonnegative on pairs of
indecomposable representatives.

The converse uses directed effective lifting.  If a selected sum surjects
onto an indecomposable, its effective-lifting map is epic.  Mixed-coordinate
reconstruction gives the required Hom-finrank inequalities on projective
indecomposables; those projectives detect the kernel, so the lifting map is an
isomorphism.  No concrete algebra or module classification is used.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits

namespace OpConjecture.RepresentationDirected

open OpConjecture.IndecomposableSkeleton.FaithfulCore

universe u uIota

variable (K R : Type u) [Field K] [IsAlgClosed K]
  [Ring R] [Algebra K R] [FiniteDimensional K R] [IsNoetherianRing R]
  {Iota : Type uIota} [Fintype Iota]
  (sigma : IndecomposableSkeleton.{u, uIota, u} R Iota)

attribute [local instance]
  HasFiniteBiproducts.of_hasFiniteCoproducts

omit [Fintype Iota] in
/-- A multiplicity biproduct on a finite support belongs to the additive
closure of that support.  Reindexing through `Fin` bridges the universe-zero
index built into `AddPresentation`. -/
theorem multiplicityBiproduct_inAdd
    [DecidableEq Iota]
    {S : Set Iota} (support : Finset Iota) (n : Iota → ℕ)
    (hsupport : ∀ a, a ∈ support → a ∈ S) :
    sigma.InAdd S (multiplicityBiproduct sigma.obj support n) := by
  classical
  let J := MultiplicityIndex support n
  let e : J ≃ Fin (Fintype.card J) := Fintype.equivFin J
  let label : Fin (Fintype.card J) → Iota := fun t ↦ (e.symm t).1.1
  let reindex : multiplicityBiproduct sigma.obj support n ≅
      sigma.sumOver (FintypeCat.of (Fin (Fintype.card J))) label := by
    change (⨁ fun p : J ↦ sigma.obj p.1.1) ≅
      ⨁ fun t : Fin (Fintype.card J) ↦ sigma.obj (label t)
    exact biproduct.whiskerEquiv e (fun p ↦ by
      simpa [label] using (Iso.refl (sigma.obj p.1.1)))
  exact ⟨{
    index := FintypeCat.of (Fin (Fintype.card J))
    label := label
    mem := fun t ↦ hsupport (label t) (e.symm t).1.2
    iso := reindex }⟩

omit [IsAlgClosed K] [FiniteDimensional K R] in
/-- The prescribed effective-lifting source lies in the retained additive
subcategory. -/
theorem mixedApproximationObject_inAdd
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (D : Finset Iota) (Y : FGModuleCat.{u} R) :
    sigma.InAdd {a | a ∉ D}
      (mixedApproximationObject K R sigma H D Y) := by
  letI := directedLinearOrder sigma H
  rw [mixedApproximationObject]
  apply multiplicityBiproduct_inAdd (sigma := sigma)
  intro a ha
  exact (Finset.mem_sdiff.mp ha).2

omit [IsAlgClosed K] in
/-- Pairwise nonnegativity on the indecomposable skeleton extends to every
module and every mixed-coordinate row. -/
theorem HasAcyclicNonzeroNonisomorphisms.mixedMultiplicity_nonnegative_of_obj_all
    (H : HasAcyclicNonzeroNonisomorphisms sigma) (D : Finset Iota)
    (hobj : ∀ a j,
      0 ≤ mixedMultiplicity K R sigma H D (sigma.obj j) a)
    (M : FGModuleCat.{u} R) (a : Iota) :
    0 ≤ mixedMultiplicity K R sigma H D M a := by
  obtain ⟨n, j, ⟨e⟩⟩ := sigma.decomposes M
  rw [mixedMultiplicity_iso K R sigma H D e]
  rw [mixedMultiplicity_biproduct_finite K R sigma H D]
  change 0 ≤ (∑ t, mixedMultiplicity K R sigma H D (sigma.obj (j t))) a
  rw [show (∑ t, mixedMultiplicity K R sigma H D (sigma.obj (j t))) a =
      ∑ t, mixedMultiplicity K R sigma H D (sigma.obj (j t)) a by
    exact map_sum (Pi.evalAddMonoidHom (fun _ : Iota => ℤ) a)
      (fun t ↦ mixedMultiplicity K R sigma H D (sigma.obj (j t)))
      Finset.univ]
  exact Finset.sum_nonneg fun t _ ↦ hobj a (j t)

/-- Under pairwise nonnegativity, the prescribed effective-lifting source
has no larger Hom-finrank than its target in any skeleton row. -/
theorem HasAcyclicNonzeroNonisomorphisms.homFinrankVector_mixedApproximationObject_le
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (D : Finset Iota)
    (hobj : ∀ a j,
      0 ≤ mixedMultiplicity K R sigma H D (sigma.obj j) a)
    (Y : FGModuleCat.{u} R) (a : Iota) :
    homFinrankVector K R sigma
        (mixedApproximationObject K R sigma H D Y) a ≤
      homFinrankVector K R sigma Y a := by
  letI := directedLinearOrder sigma H
  let T := mixedApproximationObject K R sigma H D Y
  have hnonnegative (b : Iota) :
      0 ≤ mixedMultiplicity K R sigma H D Y b :=
    H.mixedMultiplicity_nonnegative_of_obj_all K R sigma D hobj Y b
  have hretained (b : Iota) (hb : b ∉ D) :
      mixedMultiplicity K R sigma H D Y b =
        mixedMultiplicity K R sigma H D T b := by
    have hT := mixedMultiplicity_mixedApproximationObject_of_not_mem
      K R sigma H D D Set.Subset.rfl Y hb
    change mixedMultiplicity K R sigma H D Y b = _
    rw [show ((mixedMultiplicity K R sigma H D Y b).toNat : ℤ) =
        mixedMultiplicity K R sigma H D Y b by
      exact Int.toNat_of_nonneg (hnonnegative b)] at hT
    exact hT.symm
  have homitted (b : Iota) (hb : b ∈ D) :
      mixedMultiplicity K R sigma H D T b = 0 :=
    mixedMultiplicity_mixedApproximationObject_eq_zero
      K R sigma H D D Set.Subset.rfl Y hb
  have hcoordinates : ∀ b, b ∉ insert a D →
      mixedMultiplicity K R sigma H D Y b =
        mixedMultiplicity K R sigma H D T b := by
    intro b hb
    exact hretained b (fun hbD ↦ hb (Finset.mem_insert_of_mem hbD))
  have hrow := UpperUnitriangular.value_eq_add_coordinate_sub
    (homFinrankMatrix K R sigma) D
    (H.homFinrankMatrix_blockTriangular K R sigma)
    (H.homFinrankMatrix_diagonal K R sigma)
    (homFinrankVector K R sigma Y) (homFinrankVector K R sigma T)
    (fun b hb ↦ by
      simpa only [mixedMultiplicity] using hcoordinates b hb)
  have hrow' :
      homFinrankVector K R sigma Y a =
        homFinrankVector K R sigma T a +
          mixedMultiplicity K R sigma H D Y a -
            mixedMultiplicity K R sigma H D T a := by
    simpa only [mixedMultiplicity] using hrow
  change homFinrankVector K R sigma T a ≤
    homFinrankVector K R sigma Y a
  by_cases ha : a ∈ D
  · have hTa := homitted a ha
    have hYa := hnonnegative a
    rw [hTa, sub_zero] at hrow'
    omega
  · have hEq := hretained a ha
    rw [hEq] at hrow'
    omega

omit [IsAlgClosed K] [Fintype Iota] in
/-- Projective skeleton labels detect the kernel of an epimorphism.  Hence
the pointwise Hom-finrank inequality forces that epimorphism to be an
isomorphism. -/
theorem isIso_of_epi_of_projective_obj_hom_finrank_le
    {T Y : FGModuleCat.{u} R} (f : T ⟶ Y) [Epi f]
    (hle : ∀ p : Iota, Projective (sigma.obj p) →
      Module.finrank K (sigma.obj p ⟶ T) ≤
        Module.finrank K (sigma.obj p ⟶ Y)) :
    IsIso f := by
  classical
  obtain ⟨P⟩ := inFac_projectiveLabels sigma (kernel f)
  letI : Epi P.map := P.epi
  have hcomponent (t : P.index) :
      biproduct.ι (fun s ↦ sigma.obj (P.label s)) t ≫ P.map = 0 := by
    letI : Projective (sigma.obj (P.label t)) := P.mem t
    letI : FiniteDimensional K (sigma.obj (P.label t) ⟶ T) :=
      finiteDimensional_hom_from_obj K R sigma (P.label t) T
    letI : FiniteDimensional K (sigma.obj (P.label t) ⟶ Y) :=
      finiteDimensional_hom_from_obj K R sigma (P.label t) Y
    exact hom_kernel_eq_zero_of_projective_of_finrank_le
      (K := K) f (hle (P.label t) (P.mem t))
        (biproduct.ι (fun s ↦ sigma.obj (P.label s)) t ≫ P.map)
  have hPzero : P.map = 0 := by
    apply biproduct.hom_ext'
    intro t
    simpa only [comp_zero] using hcomponent t
  have hkernel : kernel.ι f = 0 := by
    apply (cancel_epi P.map).1
    rw [hPzero]
    simp
  letI : Mono f := Abelian.mono_of_kernel_ι_eq_zero f hkernel
  exact isIso_of_mono_of_epi f

/-- Pairwise nonnegative mixed coordinates force the retained support to be
quotient-closed. -/
theorem HasAcyclicNonzeroNonisomorphisms.qClosed_of_mixedMultiplicity_obj_nonnegative
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (D : Finset Iota)
    (hobj : ∀ a j,
      0 ≤ mixedMultiplicity K R sigma H D (sigma.obj j) a) :
    sigma.qClosure.IsClosed {a | a ∉ D} := by
  classical
  apply sigma.qClosure.isClosed_iff.2
  change sigma.qSet {a | a ∉ D} = {a | a ∉ D}
  apply Set.Subset.antisymm
  · intro j hj
    obtain ⟨P⟩ := hj
    obtain ⟨rho, hrho⟩ :=
      H.exists_effectiveLifting_of_obj_nonnegative
        K R sigma D hobj (sigma.obj j)
    have hsource : sigma.InAdd {a | a ∉ D}
        (sigma.sumOver P.index P.label) :=
      ⟨{
        index := P.index
        label := P.label
        mem := P.mem
        iso := Iso.refl _ }⟩
    obtain ⟨s, hs⟩ := (hrho _ hsource).2 P.map
    have hs' : s ≫ rho = P.map := by
      simpa only [postcompLinearMap_apply] using hs
    letI : Epi P.map := P.epi
    haveI : Epi (s ≫ rho) := hs' ▸ inferInstance
    letI : Epi rho := epi_of_epi s rho
    letI : IsIso rho :=
      isIso_of_epi_of_projective_obj_hom_finrank_le K R sigma rho (by
        intro p hp
        have hpoint := H.homFinrankVector_mixedApproximationObject_le
          K R sigma D hobj (sigma.obj j) p
        change (Module.finrank K
            (sigma.obj p ⟶
              mixedApproximationObject K R sigma H D (sigma.obj j)) : ℤ) ≤
          (Module.finrank K (sigma.obj p ⟶ sigma.obj j) : ℤ) at hpoint
        exact_mod_cast hpoint)
    have hdomain : sigma.InAdd {a | a ∉ D}
        (mixedApproximationObject K R sigma H D (sigma.obj j)) :=
      mixedApproximationObject_inAdd K R sigma H D (sigma.obj j)
    have htarget : sigma.InAdd {a | a ∉ D} (sigma.obj j) :=
      (IndecomposableSkeleton.inAdd_iff_of_iso sigma (asIso rho)).1 hdomain
    exact IndecomposableSkeleton.index_mem_of_retract_inAdd sigma
      (Retract.refl (sigma.obj j)) htarget
  · exact sigma.subset_qSet {a | a ∉ D}

/-- Closure effectivity: quotient closure of the retained support is
equivalent to pairwise nonnegativity of all mixed coordinates. -/
theorem HasAcyclicNonzeroNonisomorphisms.qClosed_iff_mixedMultiplicity_obj_nonnegative
    (H : HasAcyclicNonzeroNonisomorphisms sigma)
    (D : Finset Iota) :
    sigma.qClosure.IsClosed {a | a ∉ D} ↔
      ∀ a j, 0 ≤ mixedMultiplicity K R sigma H D (sigma.obj j) a := by
  constructor
  · intro hclosed a j
    exact H.mixedMultiplicity_obj_nonnegative_of_qClosed
      K R sigma D hclosed j a
  · exact H.qClosed_of_mixedMultiplicity_obj_nonnegative K R sigma D

end OpConjecture.RepresentationDirected
