import OpConjecture.RepresentationDirected.IyamaWordMeshCategory
import OpConjecture.RepresentationDirected.IyamaRepresentableMesh
import Mathlib.Combinatorics.Quiver.Path.Vertices
import Mathlib.LinearAlgebra.StdBasis

/-!
# Endpoint recurrence and vertexwise exactness for the word mesh category

This file proves the last-arrow recurrence for the ideal generated by the
ordinary word mesh relations.  It then evaluates the two mesh maps and the
simple quotient against each vertex source and proves exactness at the middle
and right terms.  The free-category injectivity input is obtained from unique
first-arrow factorization in the reverse word quiver.

These results are entirely abstract: no concrete algebra, quiver instance,
module enumeration, or classification is used.  Passing from the dependent
products of vertex Hom spaces here to categorical finite biproducts belongs to
the additive-hull layer.
-/

set_option autoImplicit false
noncomputable section

open scoped BigOperators
open CategoryTheory

namespace OpConjecture.RepresentationDirected.IyamaMesh.WordMeshRecurrence

open OpConjecture.CategoricalIdeal
open OpConjecture.RepresentationDirected.ARWord
open OpConjecture.RepresentationDirected.IyamaMesh.WordPath
open OpConjecture.RepresentationDirected.IyamaMesh.WordMesh

universe uK uL

variable {K : Type uK} [Field K]
variable {L : Type uL}

/-- The path basis really is the family of `pathHom`s. -/
@[simp]
theorem homPathBasis_apply
    (G : SimpleGraph L) (Q : List L)
    (x y : WordPath.Category K G Q)
    (p : Quiver.Path (WordPath.vertex G Q y) (WordPath.vertex G Q x)) :
    WordPath.homPathBasis G Q x y p = WordPath.pathHom G Q p := by
  apply (WordPath.homPathLinearEquiv G Q x y).injective
  simp [WordPath.homPathBasis, WordPath.pathHom]

/-- A nontrivial path ending at `x` factors through one incoming middle
arrow.  The only alternative is the trivial path at `x` itself. -/
theorem pathHom_eq_id_or_factor_lastMiddle
    (G : SimpleGraph L) (Q : List L)
    {z x : Fin Q.length}
    (p : Quiver.Path (WordPath.vertex G Q x) (WordPath.vertex G Q z)) :
    p.length = 0 ∨
      ∃ (y : Fin Q.length) (hyx : IsMiddle G Q y x)
        (g : WordPath.obj K G Q z ⟶ WordPath.obj K G Q y),
        WordPath.pathHom G Q p =
          g ≫ WordPath.middleArrow (K := K) G Q hyx := by
  by_cases hp0 : p.length = 0
  · exact Or.inl hp0
  · obtain ⟨c, e, p', hp, _⟩ :=
      (Quiver.Path.length_ne_zero_iff_eq_comp p).mp hp0
    subst p
    rcases c with ⟨y⟩
    rcases e with ⟨hyx⟩
    exact Or.inr ⟨y, hyx, WordPath.pathHom G Q p', by
      rw [WordPath.middleArrow, WordPath.pathHom_comp]
      rfl⟩

/-- Generators for the expected last-arrow recurrence at a fixed endpoint.
They are either a left multiple of the mesh relation at the endpoint, or an
ideal element at an incoming middle vertex followed by its middle arrow. -/
def endingGeneratorSet
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    Set (WordPath.obj K G Q s ⟶ WordPath.obj K G Q x) :=
  {f | (∃ (p : Fin Q.length) (hpx : IsPrevious Q p x)
      (a : WordPath.obj K G Q s ⟶ WordPath.obj K G Q p),
      f = a ≫ WordPath.meshRelation (K := K) G Q hAlt hpx) ∨
    ∃ (y : Fin Q.length) (hyx : IsMiddle G Q y x)
      (g : WordPath.obj K G Q s ⟶ WordPath.obj K G Q y),
      g ∈ (WordMesh.meshIdeal (K := K) G Q hAlt).hom
        (WordPath.obj K G Q s) (WordPath.obj K G Q y) ∧
      f = g ≫ WordPath.middleArrow (K := K) G Q hyx}

/-- The linear subspace prescribed by the last-arrow recurrence. -/
def endingSubmodule
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    Submodule K (WordPath.obj K G Q s ⟶ WordPath.obj K G Q x) :=
  Submodule.span K (endingGeneratorSet (K := K) G Q hAlt s x)

noncomputable instance previousFintype
    (Q : List L) (x : Fin Q.length) :
    Fintype {p : Fin Q.length // IsPrevious Q p x} :=
  Fintype.ofFinite _

/-- Explicit finite-sum form of the endpoint recurrence. -/
def HasEndingNormalForm
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x) : Prop :=
  ∃ (a : ∀ p : {p : Fin Q.length // IsPrevious Q p x},
      WordPath.obj K G Q s ⟶ WordPath.obj K G Q p.1)
    (g : ∀ y : {y : Fin Q.length // IsMiddle G Q y x},
      WordPath.obj K G Q s ⟶ WordPath.obj K G Q y.1),
    (∀ y, g y ∈ (WordMesh.meshIdeal (K := K) G Q hAlt).hom
      (WordPath.obj K G Q s) (WordPath.obj K G Q y.1)) ∧
    f =
      (∑ p, a p ≫ WordPath.meshRelation (K := K) G Q hAlt p.2) +
      ∑ y, g y ≫ WordPath.middleArrow (K := K) G Q y.2

theorem hasEndingNormalForm_zero
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    HasEndingNormalForm (K := K) G Q hAlt s x 0 := by
  refine ⟨fun _ ↦ 0, fun _ ↦ 0, ?_, ?_⟩
  · intro y
    exact (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.zero_mem
  · simp

theorem HasEndingNormalForm.add
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    {f₁ f₂ : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x}
    (h₁ : HasEndingNormalForm (K := K) G Q hAlt s x f₁)
    (h₂ : HasEndingNormalForm (K := K) G Q hAlt s x f₂) :
    HasEndingNormalForm (K := K) G Q hAlt s x (f₁ + f₂) := by
  rcases h₁ with ⟨a₁, g₁, hg₁, rfl⟩
  rcases h₂ with ⟨a₂, g₂, hg₂, rfl⟩
  refine ⟨fun p ↦ a₁ p + a₂ p, fun y ↦ g₁ y + g₂ y, ?_, ?_⟩
  · intro y
    exact (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.add_mem
      (hg₁ y) (hg₂ y)
  · simp only [Preadditive.add_comp, Finset.sum_add_distrib]
    abel

theorem HasEndingNormalForm.smul
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (k : K)
    {f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x}
    (hf : HasEndingNormalForm (K := K) G Q hAlt s x f) :
    HasEndingNormalForm (K := K) G Q hAlt s x (k • f) := by
  rcases hf with ⟨a, g, hg, rfl⟩
  refine ⟨fun p ↦ k • a p, fun y ↦ k • g y, ?_, ?_⟩
  · intro y
    exact HomIdeal.smul_mem (WordMesh.meshIdeal (K := K) G Q hAlt) k (hg y)
  · simp only [Linear.smul_comp, Finset.smul_sum, smul_add]

/-- Each generator of the recurrence span has an explicit finite-sum normal
form. -/
theorem endingGenerator_hasEndingNormalForm
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    {f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x}
    (hf : f ∈ endingGeneratorSet (K := K) G Q hAlt s x) :
    HasEndingNormalForm (K := K) G Q hAlt s x f := by
  classical
  rcases hf with ⟨p, hpx, u, rfl⟩ | ⟨y, hyx, g, hg, rfl⟩
  · let p₀ : {q : Fin Q.length // IsPrevious Q q x} := ⟨p, hpx⟩
    let a : ∀ q : {q : Fin Q.length // IsPrevious Q q x},
        WordPath.obj K G Q s ⟶ WordPath.obj K G Q q.1 :=
      fun q ↦ dite (q = p₀)
        (fun h ↦ by subst q; exact u) (fun _ ↦ 0)
    refine ⟨a, fun _ ↦ 0, ?_, ?_⟩
    · intro z
      exact (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.zero_mem
    · have hsum :
          (∑ q, a q ≫ WordPath.meshRelation (K := K) G Q hAlt q.2) =
            u ≫ WordPath.meshRelation (K := K) G Q hAlt hpx := by
        calc
          _ = a p₀ ≫ WordPath.meshRelation (K := K) G Q hAlt p₀.2 := by
            apply Finset.sum_eq_single p₀
            · intro q _ hq
              simp [a, hq]
            · intro hp₀
              exact (hp₀ (Finset.mem_univ p₀)).elim
          _ = _ := by simp [a, p₀]
      rw [hsum]
      simp
  · let y₀ : {z : Fin Q.length // IsMiddle G Q z x} := ⟨y, hyx⟩
    let g' : ∀ z : {z : Fin Q.length // IsMiddle G Q z x},
        WordPath.obj K G Q s ⟶ WordPath.obj K G Q z.1 :=
      fun z ↦ dite (z = y₀)
        (fun h ↦ by subst z; exact g) (fun _ ↦ 0)
    refine ⟨fun _ ↦ 0, g', ?_, ?_⟩
    · intro z
      by_cases hz : z = y₀
      · subst z
        simpa [g', y₀] using hg
      · simp [g', hz]
    · have hsum :
          (∑ z, g' z ≫ WordPath.middleArrow (K := K) G Q z.2) =
            g ≫ WordPath.middleArrow (K := K) G Q hyx := by
        calc
          _ = g' y₀ ≫ WordPath.middleArrow (K := K) G Q y₀.2 := by
            apply Finset.sum_eq_single y₀
            · intro z _ hz
              simp [g', hz]
            · intro hy₀
              exact (hy₀ (Finset.mem_univ y₀)).elim
          _ = _ := by simp [g', y₀]
      rw [hsum]
      simp

/-- Span induction turns the recurrence generators into an explicit normal
form. -/
theorem endingSubmodule_hasEndingNormalForm
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    {f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x}
    (hf : f ∈ endingSubmodule (K := K) G Q hAlt s x) :
    HasEndingNormalForm (K := K) G Q hAlt s x f := by
  induction hf using Submodule.span_induction with
  | mem f hf => exact endingGenerator_hasEndingNormalForm G Q hAlt s x hf
  | zero => exact hasEndingNormalForm_zero G Q hAlt s x
  | add f g _ _ hf hg => exact hf.add G Q hAlt s x hg
  | smul k f _ hf => exact hf.smul G Q hAlt s x k

/-- An explicit endpoint normal form is visibly a mesh-ideal element. -/
theorem HasEndingNormalForm.mem_meshIdeal
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    {f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x}
    (hf : HasEndingNormalForm (K := K) G Q hAlt s x f) :
    f ∈ (WordMesh.meshIdeal (K := K) G Q hAlt).hom
      (WordPath.obj K G Q s) (WordPath.obj K G Q x) := by
  rcases hf with ⟨a, g, hg, rfl⟩
  apply (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.add_mem
  · apply (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.sum_mem
    intro p hp
    exact (WordMesh.meshIdeal (K := K) G Q hAlt).precomp (a p)
      (HomIdeal.relation_mem_linearSpan
        (WordMesh.meshGeneratorSet (K := K) G Q hAlt)
        (show WordPath.meshRelation (K := K) G Q hAlt p.2 ∈
          WordMesh.meshGeneratorSet (K := K) G Q hAlt
            (WordPath.obj K G Q p.1) (WordPath.obj K G Q x) from
          ⟨p.2, rfl⟩))
  · apply (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.sum_mem
    intro y hy
    exact (WordMesh.meshIdeal (K := K) G Q hAlt).postcomp
      (WordPath.middleArrow (K := K) G Q y.2) (hg y)

/-- A two-sided composite through one mesh relation satisfies the endpoint
recurrence.  This is the load-bearing path-basis peeling step. -/
theorem meshComposite_mem_endingSubmodule
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {s a b x : Fin Q.length}
    (hab : IsPrevious Q a b)
    (u : WordPath.obj K G Q s ⟶ WordPath.obj K G Q a)
    (v : WordPath.obj K G Q b ⟶ WordPath.obj K G Q x) :
    u ≫ WordPath.meshRelation (K := K) G Q hAlt hab ≫ v ∈
      endingSubmodule (K := K) G Q hAlt s x := by
  letI : Fintype
      (Quiver.Path
        (WordPath.vertex G Q (WordPath.obj K G Q x))
        (WordPath.vertex G Q (WordPath.obj K G Q b))) :=
    Fintype.ofFinite _
  rw [← (WordPath.homPathBasis G Q
    (WordPath.obj K G Q b) (WordPath.obj K G Q x)).sum_repr v]
  simp only [Preadditive.comp_sum]
  apply Submodule.sum_mem
  intro p hp
  simp only [Linear.comp_smul]
  apply Submodule.smul_mem
  rw [homPathBasis_apply]
  rcases pathHom_eq_id_or_factor_lastMiddle (K := K) G Q p with hp0 | hfactor
  · have hv : WordPath.vertex G Q x = WordPath.vertex G Q b :=
      Quiver.Path.eq_of_length_zero p hp0
    have hxb : x = b := congrArg WordPath.ReverseWordQuiver.pos hv
    subst b
    have hp : p = Quiver.Path.nil :=
      Quiver.Path.eq_nil_of_length_zero p hp0
    subst p
    apply Submodule.subset_span
    exact Or.inl ⟨a, hab, u, by simp⟩
  · rcases hfactor with ⟨y, hyx, g, hpath⟩
    rw [hpath]
    apply Submodule.subset_span
    refine Or.inr ⟨y, hyx,
      u ≫ WordPath.meshRelation (K := K) G Q hAlt hab ≫ g, ?_, ?_⟩
    · exact HomIdeal.composite_mem_linearSpan
        (WordMesh.meshGeneratorSet (K := K) G Q hAlt) u
        (show WordPath.meshRelation (K := K) G Q hAlt hab ∈
          WordMesh.meshGeneratorSet (K := K) G Q hAlt
            (WordPath.obj K G Q a) (WordPath.obj K G Q b) from
          ⟨hab, rfl⟩) g
    · rfl

/-- Every expected endpoint-recurrence generator already lies in the mesh
ideal. -/
theorem endingSubmodule_mem_meshIdeal
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    {f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x}
    (hf : f ∈ endingSubmodule (K := K) G Q hAlt s x) :
    f ∈ (WordMesh.meshIdeal (K := K) G Q hAlt).hom
      (WordPath.obj K G Q s) (WordPath.obj K G Q x) := by
  induction hf using Submodule.span_induction with
  | mem f hf =>
      rcases hf with hmesh | hmiddle
      · rcases hmesh with ⟨p, hpx, a, rfl⟩
        simpa using
          (WordMesh.meshIdeal (K := K) G Q hAlt).precomp a
            (HomIdeal.relation_mem_linearSpan
              (WordMesh.meshGeneratorSet (K := K) G Q hAlt)
              (show WordPath.meshRelation (K := K) G Q hAlt hpx ∈
                WordMesh.meshGeneratorSet (K := K) G Q hAlt
                  (WordPath.obj K G Q p) (WordPath.obj K G Q x) from
                ⟨hpx, rfl⟩))
      · rcases hmiddle with ⟨y, hyx, g, hg, rfl⟩
        exact (WordMesh.meshIdeal (K := K) G Q hAlt).postcomp _ hg
  | zero => exact (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.zero_mem
  | add f g _ _ hf hg =>
      exact (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.add_mem hf hg
  | smul k f _ hf =>
      exact HomIdeal.smul_mem (WordMesh.meshIdeal (K := K) G Q hAlt) k hf

/-- Every mesh-ideal element ending at `x` belongs to the endpoint recurrence
subspace. -/
theorem meshIdeal_mem_endingSubmodule
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    {f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x}
    (hf : f ∈ (WordMesh.meshIdeal (K := K) G Q hAlt).hom
      (WordPath.obj K G Q s) (WordPath.obj K G Q x)) :
    f ∈ endingSubmodule (K := K) G Q hAlt s x := by
  change f ∈ HomIdeal.generatedHomSubmodule K
    (WordMesh.meshGeneratorSet (K := K) G Q hAlt)
    (WordPath.obj K G Q s) (WordPath.obj K G Q x) at hf
  induction hf using Submodule.span_induction with
  | mem f hf =>
      rcases hf with ⟨a, b, r, hr, u, v, rfl⟩
      rcases hr with ⟨hab, rfl⟩
      exact meshComposite_mem_endingSubmodule G Q hAlt hab u v
  | zero => exact (endingSubmodule (K := K) G Q hAlt s x).zero_mem
  | add f g _ _ hf hg =>
      exact (endingSubmodule (K := K) G Q hAlt s x).add_mem hf hg
  | smul k f _ hf =>
      exact (endingSubmodule (K := K) G Q hAlt s x).smul_mem k hf

/-- Exact endpoint recurrence for the generated mesh ideal. -/
theorem mem_meshIdeal_iff_mem_endingSubmodule
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x) :
    f ∈ (WordMesh.meshIdeal (K := K) G Q hAlt).hom
        (WordPath.obj K G Q s) (WordPath.obj K G Q x) ↔
      f ∈ endingSubmodule (K := K) G Q hAlt s x :=
  ⟨meshIdeal_mem_endingSubmodule G Q hAlt s x,
    endingSubmodule_mem_meshIdeal G Q hAlt s x⟩

/-- Explicit first/last-arrow recurrence: an ideal element ending at `x` is
exactly a sum of left multiples of the (at most one) mesh relation at `x`
and ideal elements at incoming middle vertices followed by their arrows. -/
theorem mem_meshIdeal_iff_hasEndingNormalForm
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x) :
    f ∈ (WordMesh.meshIdeal (K := K) G Q hAlt).hom
        (WordPath.obj K G Q s) (WordPath.obj K G Q x) ↔
      HasEndingNormalForm (K := K) G Q hAlt s x f := by
  constructor
  · intro hf
    exact endingSubmodule_hasEndingNormalForm G Q hAlt s x
      (meshIdeal_mem_endingSubmodule G Q hAlt s x hf)
  · exact HasEndingNormalForm.mem_meshIdeal G Q hAlt s x

/-! ## Evaluated incoming-arrow map in the mesh quotient -/

/-- The image in the mesh category of one incoming middle arrow. -/
def quotientMiddleArrow
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {y x : Fin Q.length} (hyx : IsMiddle G Q y x) :
    WordMesh.obj (K := K) G Q hAlt y ⟶
      WordMesh.obj (K := K) G Q hAlt x :=
  WordMesh.quotientHom (K := K) G Q hAlt
    (WordPath.middleArrow (K := K) G Q hyx)

/-- Evaluation of the incoming-arrow map against a fixed source vertex. -/
def quotientIncomingMap
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    ((y : {y : Fin Q.length // IsMiddle G Q y x}) →
      (WordMesh.obj (K := K) G Q hAlt s ⟶
        WordMesh.obj (K := K) G Q hAlt y.1)) →ₗ[K]
      (WordMesh.obj (K := K) G Q hAlt s ⟶
        WordMesh.obj (K := K) G Q hAlt x) where
  toFun g := ∑ y, g y ≫ quotientMiddleArrow (K := K) G Q hAlt y.2
  map_add' := by
    intro f g
    simp only [Pi.add_apply, Preadditive.add_comp, Finset.sum_add_distrib]
  map_smul' := by
    intro k f
    simp only [Pi.smul_apply, Linear.smul_comp, Finset.smul_sum,
      RingHom.id_apply]

/-- The diagonal simple quotient of the representable at `x`. -/
def quotientSimpleMap
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    (WordMesh.obj (K := K) G Q hAlt s ⟶
      WordMesh.obj (K := K) G Q hAlt x) →ₗ[K]
      SimpleRepresentableFiber K s x := by
  classical
  by_cases hsx : s = x
  · subst s
    exact
      { toFun := fun f _ ↦ WordMesh.selfHomLinearEquiv
          (K := K) G Q hAlt x f
        map_add' := by intros; ext i; simp
        map_smul' := by intros; ext i; simp }
  · exact 0

/-- The diagonal simple quotient is onto. -/
theorem quotientSimpleMap_surjective
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    Function.Surjective (quotientSimpleMap (K := K) G Q hAlt s x) := by
  classical
  by_cases hsx : s = x
  · subst s
    intro q
    let i₀ : Fin (if x = x then 1 else 0) := ⟨0, by simp⟩
    refine ⟨q i₀ • 𝟙 (WordMesh.obj (K := K) G Q hAlt x), ?_⟩
    funext i
    have hi : i = i₀ := by
      apply Fin.ext
      change i.val = 0
      have hiBound : i.val < 1 := by simpa [if_pos rfl] using i.isLt
      omega
    subst i
    simp [quotientSimpleMap, WordMesh.selfHomLinearEquiv_id]
  · intro q
    refine ⟨0, ?_⟩
    funext i
    exact Fin.elim0 (show Fin 0 from (by simpa [SimpleRepresentableFiber, hsx] using i))

/-- Vanishing in the mesh quotient is exactly membership in the generated
mesh ideal. -/
theorem quotientHom_eq_zero_iff
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {s x : Fin Q.length}
    (f : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x) :
    WordMesh.quotientHom (K := K) G Q hAlt f = 0 ↔
      f ∈ (WordMesh.meshIdeal (K := K) G Q hAlt).hom
        (WordPath.obj K G Q s) (WordPath.obj K G Q x) := by
  constructor
  · intro hf
    apply ((WordMesh.meshIdeal (K := K) G Q hAlt).map_eq_zero_iff f).mp
    have hf0 : WordMesh.quotientHom (K := K) G Q hAlt f =
        WordMesh.quotientHom (K := K) G Q hAlt
          (0 : WordPath.obj K G Q s ⟶ WordPath.obj K G Q x) := by
      simpa using hf
    have hmap := congrArg InducedCategory.Hom.hom hf0
    change (WordMesh.quotientFunctor (K := K) G Q hAlt).map f =
      (WordMesh.quotientFunctor (K := K) G Q hAlt).map 0 at hmap
    simpa using hmap
  · intro hf
    apply InducedCategory.hom_ext
    exact ((WordMesh.meshIdeal (K := K) G Q hAlt).map_eq_zero_iff f).mpr hf

/-- Every nontrivial path-basis class lies in the image of the evaluated
incoming-arrow map. -/
theorem quotient_pathHom_mem_range_incoming_of_ne
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {s x : Fin Q.length} (hsx : s ≠ x)
    (p : Quiver.Path (WordPath.vertex G Q x) (WordPath.vertex G Q s)) :
    WordMesh.quotientHom (K := K) G Q hAlt (WordPath.pathHom G Q p) ∈
      LinearMap.range (quotientIncomingMap (K := K) G Q hAlt s x) := by
  classical
  rcases pathHom_eq_id_or_factor_lastMiddle (K := K) G Q p with hp0 | hfactor
  · have hv : WordPath.vertex G Q x = WordPath.vertex G Q s :=
      Quiver.Path.eq_of_length_zero p hp0
    have hxs : x = s := congrArg WordPath.ReverseWordQuiver.pos hv
    exact False.elim (hsx hxs.symm)
  · rcases hfactor with ⟨y, hyx, g, hpath⟩
    let y₀ : {z : Fin Q.length // IsMiddle G Q z x} := ⟨y, hyx⟩
    let d : ∀ z : {z : Fin Q.length // IsMiddle G Q z x},
        WordMesh.obj (K := K) G Q hAlt s ⟶
          WordMesh.obj (K := K) G Q hAlt z.1 :=
      fun z ↦ dite (z = y₀)
        (fun h ↦ by
          subst z
          exact WordMesh.quotientHom (K := K) G Q hAlt g)
        (fun _ ↦ 0)
    refine ⟨d, ?_⟩
    change (∑ z, d z ≫ quotientMiddleArrow (K := K) G Q hAlt z.2) = _
    have hsum :
        (∑ z, d z ≫ quotientMiddleArrow (K := K) G Q hAlt z.2) =
          WordMesh.quotientHom (K := K) G Q hAlt g ≫
            quotientMiddleArrow (K := K) G Q hAlt hyx := by
      calc
        _ = d y₀ ≫ quotientMiddleArrow (K := K) G Q hAlt y₀.2 := by
          apply Finset.sum_eq_single y₀
          · intro z _ hz
            simp [d, hz]
          · intro hy₀
            exact (hy₀ (Finset.mem_univ y₀)).elim
        _ = _ := by simp [d, y₀]
    rw [hsum, quotientMiddleArrow, ← WordMesh.quotientHom_comp, ← hpath]
    rfl

/-- Off the diagonal, the evaluated incoming-arrow map is surjective. -/
theorem quotientIncomingMap_surjective_of_ne
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {s x : Fin Q.length} (hsx : s ≠ x) :
    Function.Surjective (quotientIncomingMap (K := K) G Q hAlt s x) := by
  intro f
  obtain ⟨v, rfl⟩ := WordMesh.quotientHom_surjective
    (K := K) G Q hAlt s x f
  letI : Fintype
      (Quiver.Path
        (WordPath.vertex G Q (WordPath.obj K G Q x))
        (WordPath.vertex G Q (WordPath.obj K G Q s))) :=
    Fintype.ofFinite _
  change (WordMesh.quotientHomLinearMap (K := K) G Q hAlt s x) v ∈
    LinearMap.range (quotientIncomingMap (K := K) G Q hAlt s x)
  rw [← (WordPath.homPathBasis G Q
    (WordPath.obj K G Q s) (WordPath.obj K G Q x)).sum_repr v]
  rw [map_sum]
  apply Submodule.sum_mem
  intro p hp
  rw [map_smul]
  apply Submodule.smul_mem
  rw [homPathBasis_apply]
  exact quotient_pathHom_mem_range_incoming_of_ne G Q hAlt hsx p

/-- The incoming-arrow image is annihilated by the diagonal simple
quotient. -/
theorem quotientSimpleMap_incoming_eq_zero
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (g : (y : {y : Fin Q.length // IsMiddle G Q y x}) →
      (WordMesh.obj (K := K) G Q hAlt s ⟶
        WordMesh.obj (K := K) G Q hAlt y.1)) :
    quotientSimpleMap (K := K) G Q hAlt s x
      (quotientIncomingMap (K := K) G Q hAlt s x g) = 0 := by
  classical
  by_cases hsx : s = x
  · subst s
    have hg : g = 0 := by
      funext y
      exact WordMesh.hom_eq_zero_of_not_le G Q hAlt
        (not_le_of_gt y.2.2.1) (g y)
    subst g
    simp [quotientIncomingMap]
  · simp [quotientSimpleMap, hsx]

/-- Exactness at the right representable term of the raw word mesh
category. -/
theorem quotient_exact_at_right
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    Function.Exact
      (quotientIncomingMap (K := K) G Q hAlt s x)
      (quotientSimpleMap (K := K) G Q hAlt s x) := by
  intro f
  constructor
  · intro hf
    by_cases hsx : s = x
    · subst s
      let i₀ : Fin (if x = x then 1 else 0) := ⟨0, by simp⟩
      have hcoord : WordMesh.selfHomLinearEquiv
          (K := K) G Q hAlt x f = 0 := by
        have hi := congrFun hf i₀
        simpa [quotientSimpleMap, i₀] using hi
      have hfzero : f = 0 := by
        apply (WordMesh.selfHomLinearEquiv (K := K) G Q hAlt x).injective
        simpa using hcoord
      subst f
      exact ⟨0, by simp [quotientIncomingMap]⟩
    · exact quotientIncomingMap_surjective_of_ne G Q hAlt hsx f
  · rintro ⟨g, rfl⟩
    exact quotientSimpleMap_incoming_eq_zero G Q hAlt s x g

/-! ## Freeness of the incoming-arrow map before quotienting -/

/-- Prefix a reverse-quiver path by the reverse of an incoming middle
arrow. -/
def prependMiddlePath
    (G : SimpleGraph L) (Q : List L)
    {s x : Fin Q.length}
    (t : Σ y : {y : Fin Q.length // IsMiddle G Q y x},
      Quiver.Path (WordPath.vertex G Q y.1) (WordPath.vertex G Q s)) :
    Quiver.Path (WordPath.vertex G Q x) (WordPath.vertex G Q s) :=
  (WordPath.reverseArrowPath G Q t.1.2).comp t.2

/-- Different incoming arrows, followed by arbitrary tails, produce
different paths. -/
theorem prependMiddlePath_injective
    (G : SimpleGraph L) (Q : List L)
    (s x : Fin Q.length) :
    Function.Injective (prependMiddlePath G Q (s := s) (x := x)) := by
  rintro ⟨y, p⟩ ⟨z, q⟩ h
  have hvertices := congrArg Quiver.Path.vertices h
  have hpqVertices : p.vertices = q.vertices := by
    simpa [prependMiddlePath, WordPath.reverseArrowPath] using hvertices
  have hyzVertex : WordPath.vertex G Q y.1 = WordPath.vertex G Q z.1 := by
    have hhead := congrArg List.head? hpqVertices
    simpa using hhead
  have hyz : y.1 = z.1 :=
    congrArg WordPath.ReverseWordQuiver.pos hyzVertex
  have hyzSubtype : y = z := Subtype.ext hyz
  subst z
  have hpq : p = q := by
    apply (Quiver.Path.comp_injective_right
      (WordPath.reverseArrowPath G Q y.2))
    simpa [prependMiddlePath] using h
  subst q
  rfl

/-- The total prefix operation as an embedding. -/
def prependMiddlePathEmbedding
    (G : SimpleGraph L) (Q : List L)
    (s x : Fin Q.length) :
    (Σ y : {y : Fin Q.length // IsMiddle G Q y x},
      Quiver.Path (WordPath.vertex G Q y.1) (WordPath.vertex G Q s)) ↪
      Quiver.Path (WordPath.vertex G Q x) (WordPath.vertex G Q s) :=
  ⟨prependMiddlePath G Q, prependMiddlePath_injective G Q s x⟩

/-- The incoming-arrow map in the free word-path category. -/
def pathIncomingMap
    (G : SimpleGraph L) (Q : List L)
    (s x : Fin Q.length) :
    ((y : {y : Fin Q.length // IsMiddle G Q y x}) →
      (WordPath.obj K G Q s ⟶ WordPath.obj K G Q y.1)) →ₗ[K]
      (WordPath.obj K G Q s ⟶ WordPath.obj K G Q x) where
  toFun g := ∑ y, g y ≫ WordPath.middleArrow (K := K) G Q y.2
  map_add' := by
    intro f g
    simp only [Pi.add_apply, Preadditive.add_comp, Finset.sum_add_distrib]
  map_smul' := by
    intro k f
    simp only [Pi.smul_apply, Linear.smul_comp, Finset.smul_sum,
      RingHom.id_apply]

/-- The product path basis on the domain of the free incoming-arrow map. -/
def pathIncomingBasis
    (G : SimpleGraph L) (Q : List L)
    (s x : Fin Q.length) :
    Module.Basis
      (Σ y : {y : Fin Q.length // IsMiddle G Q y x},
        Quiver.Path (WordPath.vertex G Q y.1) (WordPath.vertex G Q s)) K
      ((y : {y : Fin Q.length // IsMiddle G Q y x}) →
        (WordPath.obj K G Q s ⟶ WordPath.obj K G Q y.1)) :=
  Pi.basis fun y ↦ WordPath.homPathBasis G Q
    (WordPath.obj K G Q s) (WordPath.obj K G Q y.1)

/-- Each product-basis vector is sent to the corresponding prefixed path
basis vector. -/
theorem pathIncomingMap_basis
    (G : SimpleGraph L) (Q : List L)
    (s x : Fin Q.length)
    (t : Σ y : {y : Fin Q.length // IsMiddle G Q y x},
      Quiver.Path (WordPath.vertex G Q y.1) (WordPath.vertex G Q s)) :
    pathIncomingMap (K := K) G Q s x (pathIncomingBasis (K := K) G Q s x t) =
      WordPath.pathHom G Q (prependMiddlePath G Q t) := by
  classical
  rcases t with ⟨y, p⟩
  rw [show pathIncomingBasis (K := K) G Q s x ⟨y, p⟩ =
      Pi.single y (WordPath.homPathBasis G Q
        (WordPath.obj K G Q s) (WordPath.obj K G Q y.1) p) by
    exact Pi.basis_apply _ _]
  let d : (z : {z : Fin Q.length // IsMiddle G Q z x}) →
      (WordPath.obj K G Q s ⟶ WordPath.obj K G Q z.1) :=
    Pi.single y (WordPath.homPathBasis G Q
      (WordPath.obj K G Q s) (WordPath.obj K G Q y.1) p)
  change (∑ z, d z ≫ WordPath.middleArrow (K := K) G Q z.2) = _
  rw [Finset.sum_eq_single y]
  · simp [d, homPathBasis_apply, prependMiddlePath, WordPath.middleArrow,
      WordPath.pathHom_comp]
    rfl
  · intro z _ hzy
    simp [d, hzy]
  · intro hy
    exact (hy (Finset.mem_univ y)).elim

/-- The free incoming-arrow map is injective: paths have a unique last
original arrow. -/
theorem pathIncomingMap_injective
    (G : SimpleGraph L) (Q : List L)
    (s x : Fin Q.length) :
    Function.Injective (pathIncomingMap (K := K) G Q s x) := by
  apply LinearMap.injective_of_linearIndependent
    (pathIncomingBasis (K := K) G Q s x).span_eq
  have hli := (WordPath.homPathBasis G Q
    (WordPath.obj K G Q s) (WordPath.obj K G Q x)).linearIndependent.comp
      (prependMiddlePathEmbedding G Q s x)
      (prependMiddlePathEmbedding G Q s x).injective
  change LinearIndependent K (fun t ↦
    pathIncomingMap (K := K) G Q s x
      (pathIncomingBasis (K := K) G Q s x t))
  have hfamily :
      (fun t ↦ pathIncomingMap (K := K) G Q s x
        (pathIncomingBasis (K := K) G Q s x t)) =
      (fun t ↦ WordPath.homPathBasis G Q
        (WordPath.obj K G Q s) (WordPath.obj K G Q x)
        (prependMiddlePath G Q t)) := by
    funext t
    rw [pathIncomingMap_basis, homPathBasis_apply]
    rfl
  rw [hfamily]
  change LinearIndependent K (fun t ↦ WordPath.homPathBasis G Q
    (WordPath.obj K G Q s) (WordPath.obj K G Q x)
    ((prependMiddlePathEmbedding G Q s x) t)) at hli
  change LinearIndependent K (fun t ↦ WordPath.homPathBasis G Q
    (WordPath.obj K G Q s) (WordPath.obj K G Q x)
    ((prependMiddlePathEmbedding G Q s x) t))
  exact hli

/-! ## The predecessor-to-middle map and exactness at the middle term -/

/-- The first arrow `p → y` of the mesh at a repeated endpoint `x`. -/
def pathPreviousMiddleArrow
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {p y x : Fin Q.length}
    (hpx : IsPrevious Q p x) (hyx : IsMiddle G Q y x) :
    WordPath.obj K G Q p ⟶ WordPath.obj K G Q y :=
  WordPath.middleArrow (K := K) G Q
    (previous_isMiddle_of_isMiddle hAlt hpx hyx)

/-- Evaluation of the predecessor-to-middle mesh map in the free path
category. -/
def pathPreviousMap
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    ((p : {p : Fin Q.length // IsPrevious Q p x}) →
      (WordPath.obj K G Q s ⟶ WordPath.obj K G Q p.1)) →ₗ[K]
      ((y : {y : Fin Q.length // IsMiddle G Q y x}) →
        (WordPath.obj K G Q s ⟶ WordPath.obj K G Q y.1)) where
  toFun a y := ∑ p, a p ≫
    pathPreviousMiddleArrow (K := K) G Q hAlt p.2 y.2
  map_add' := by
    intro a b
    funext y
    simp only [Pi.add_apply, Preadditive.add_comp, Finset.sum_add_distrib]
  map_smul' := by
    intro k a
    funext y
    simp only [Pi.smul_apply, Linear.smul_comp, Finset.smul_sum,
      RingHom.id_apply]

/-- The composite of the two evaluated free mesh maps is the sum of left
multiples of the mesh relations at the endpoint. -/
theorem pathIncomingMap_previousMap
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (a : (p : {p : Fin Q.length // IsPrevious Q p x}) →
      (WordPath.obj K G Q s ⟶ WordPath.obj K G Q p.1)) :
    pathIncomingMap (K := K) G Q s x
        (pathPreviousMap (K := K) G Q hAlt s x a) =
      ∑ p, a p ≫ WordPath.meshRelation (K := K) G Q hAlt p.2 := by
  classical
  change (∑ y, (∑ p, a p ≫
      pathPreviousMiddleArrow (K := K) G Q hAlt p.2 y.2) ≫
        WordPath.middleArrow (K := K) G Q y.2) = _
  simp only [Preadditive.sum_comp, Category.assoc]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro p hp
  rw [WordPath.meshRelation, Preadditive.comp_sum]
  apply Finset.sum_congr rfl
  intro y hy
  rfl

/-- The first mesh arrow in the quotient category. -/
def quotientPreviousMiddleArrow
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    {p y x : Fin Q.length}
    (hpx : IsPrevious Q p x) (hyx : IsMiddle G Q y x) :
    WordMesh.obj (K := K) G Q hAlt p ⟶
      WordMesh.obj (K := K) G Q hAlt y :=
  WordMesh.quotientHom (K := K) G Q hAlt
    (pathPreviousMiddleArrow (K := K) G Q hAlt hpx hyx)

/-- Evaluation of the predecessor-to-middle map in the mesh quotient. -/
def quotientPreviousMap
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    ((p : {p : Fin Q.length // IsPrevious Q p x}) →
      (WordMesh.obj (K := K) G Q hAlt s ⟶
        WordMesh.obj (K := K) G Q hAlt p.1)) →ₗ[K]
      ((y : {y : Fin Q.length // IsMiddle G Q y x}) →
        (WordMesh.obj (K := K) G Q hAlt s ⟶
          WordMesh.obj (K := K) G Q hAlt y.1)) where
  toFun a y := ∑ p, a p ≫
    quotientPreviousMiddleArrow (K := K) G Q hAlt p.2 y.2
  map_add' := by
    intro a b
    funext y
    simp only [Pi.add_apply, Preadditive.add_comp, Finset.sum_add_distrib]
  map_smul' := by
    intro k a
    funext y
    simp only [Pi.smul_apply, Linear.smul_comp, Finset.smul_sum,
      RingHom.id_apply]

/-- Quotienting commutes with the evaluated incoming-arrow map. -/
theorem quotientHom_pathIncomingMap
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (g : (y : {y : Fin Q.length // IsMiddle G Q y x}) →
      (WordPath.obj K G Q s ⟶ WordPath.obj K G Q y.1)) :
    WordMesh.quotientHom (K := K) G Q hAlt
        (pathIncomingMap (K := K) G Q s x g) =
      quotientIncomingMap (K := K) G Q hAlt s x
        (fun y ↦ WordMesh.quotientHom (K := K) G Q hAlt (g y)) := by
  change WordMesh.quotientHomLinearMap (K := K) G Q hAlt s x
      (∑ y, g y ≫ WordPath.middleArrow (K := K) G Q y.2) = _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro y hy
  change WordMesh.quotientHom (K := K) G Q hAlt
    (g y ≫ WordPath.middleArrow (K := K) G Q y.2) = _
  rw [WordMesh.quotientHom_comp]
  rfl

/-- Quotienting commutes pointwise with the predecessor-to-middle map. -/
theorem quotientHom_pathPreviousMap
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (a : (p : {p : Fin Q.length // IsPrevious Q p x}) →
      (WordPath.obj K G Q s ⟶ WordPath.obj K G Q p.1)) :
    (fun y ↦ WordMesh.quotientHom (K := K) G Q hAlt
        (pathPreviousMap (K := K) G Q hAlt s x a y)) =
      quotientPreviousMap (K := K) G Q hAlt s x
        (fun p ↦ WordMesh.quotientHom (K := K) G Q hAlt (a p)) := by
  funext y
  change WordMesh.quotientHomLinearMap (K := K) G Q hAlt s y.1
      (∑ p, a p ≫ pathPreviousMiddleArrow (K := K) G Q hAlt p.2 y.2) = _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro p hp
  change WordMesh.quotientHom (K := K) G Q hAlt
    (a p ≫ pathPreviousMiddleArrow (K := K) G Q hAlt p.2 y.2) = _
  rw [WordMesh.quotientHom_comp]
  rfl

/-- The two evaluated mesh maps compose to zero in the quotient. -/
theorem quotientIncomingMap_previousMap_eq_zero
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length)
    (a : (p : {p : Fin Q.length // IsPrevious Q p x}) →
      (WordMesh.obj (K := K) G Q hAlt s ⟶
        WordMesh.obj (K := K) G Q hAlt p.1)) :
    quotientIncomingMap (K := K) G Q hAlt s x
      (quotientPreviousMap (K := K) G Q hAlt s x a) = 0 := by
  classical
  let w : (p : {p : Fin Q.length // IsPrevious Q p x}) →
      (WordPath.obj K G Q s ⟶ WordPath.obj K G Q p.1) :=
    fun p ↦ Classical.choose
      (WordMesh.quotientHom_surjective (K := K) G Q hAlt s p.1 (a p))
  have hw : ∀ p, WordMesh.quotientHom (K := K) G Q hAlt (w p) = a p :=
    fun p ↦ Classical.choose_spec
      (WordMesh.quotientHom_surjective (K := K) G Q hAlt s p.1 (a p))
  have ha : a = fun p ↦ WordMesh.quotientHom (K := K) G Q hAlt (w p) := by
    funext p
    exact (hw p).symm
  rw [ha]
  rw [← quotientHom_pathPreviousMap]
  rw [← quotientHom_pathIncomingMap]
  rw [pathIncomingMap_previousMap]
  apply (quotientHom_eq_zero_iff (K := K) G Q hAlt _).mpr
  apply (WordMesh.meshIdeal (K := K) G Q hAlt).hom _ _ |>.sum_mem
  intro p hp
  exact (WordMesh.meshIdeal (K := K) G Q hAlt).precomp (w p)
    (HomIdeal.relation_mem_linearSpan
      (WordMesh.meshGeneratorSet (K := K) G Q hAlt)
      (show WordPath.meshRelation (K := K) G Q hAlt p.2 ∈
        WordMesh.meshGeneratorSet (K := K) G Q hAlt
          (WordPath.obj K G Q p.1) (WordPath.obj K G Q x) from
        ⟨p.2, rfl⟩))

/-- Exactness at the middle representable term of the raw word mesh
category.  The proof combines the endpoint ideal recurrence with freeness
of the incoming-arrow map before quotienting. -/
theorem quotient_exact_at_middle
    (G : SimpleGraph L) (Q : List L)
    (hAlt : HasInteriorAlternation G Q)
    (s x : Fin Q.length) :
    Function.Exact
      (quotientPreviousMap (K := K) G Q hAlt s x)
      (quotientIncomingMap (K := K) G Q hAlt s x) := by
  classical
  intro v
  constructor
  · intro hv
    let w : (y : {y : Fin Q.length // IsMiddle G Q y x}) →
        (WordPath.obj K G Q s ⟶ WordPath.obj K G Q y.1) :=
      fun y ↦ Classical.choose
        (WordMesh.quotientHom_surjective (K := K) G Q hAlt s y.1 (v y))
    have hw : ∀ y, WordMesh.quotientHom (K := K) G Q hAlt (w y) = v y :=
      fun y ↦ Classical.choose_spec
        (WordMesh.quotientHom_surjective (K := K) G Q hAlt s y.1 (v y))
    have hq : WordMesh.quotientHom (K := K) G Q hAlt
        (pathIncomingMap (K := K) G Q s x w) = 0 := by
      rw [quotientHom_pathIncomingMap]
      have hwfun :
          (fun y ↦ WordMesh.quotientHom (K := K) G Q hAlt (w y)) = v := by
        funext y
        exact hw y
      rw [hwfun, hv]
    have hIdeal := (quotientHom_eq_zero_iff (K := K) G Q hAlt
      (pathIncomingMap (K := K) G Q s x w)).mp hq
    obtain ⟨a, g, hg, hnormal⟩ :=
      (mem_meshIdeal_iff_hasEndingNormalForm (K := K) G Q hAlt s x
        (pathIncomingMap (K := K) G Q s x w)).mp hIdeal
    have hPath : w = pathPreviousMap (K := K) G Q hAlt s x a + g := by
      apply pathIncomingMap_injective (K := K) G Q s x
      rw [map_add, pathIncomingMap_previousMap]
      change pathIncomingMap (K := K) G Q s x w =
        (∑ p, a p ≫ WordPath.meshRelation (K := K) G Q hAlt p.2) +
          ∑ y, g y ≫ WordPath.middleArrow (K := K) G Q y.2
      exact hnormal
    refine ⟨fun p ↦ WordMesh.quotientHom (K := K) G Q hAlt (a p), ?_⟩
    funext y
    have hprev := congrFun (quotientHom_pathPreviousMap
      (K := K) G Q hAlt s x a) y
    have hwy := congrFun hPath y
    have hwy' : w y =
        pathPreviousMap (K := K) G Q hAlt s x a y + g y := by
      simpa only [Pi.add_apply] using hwy
    rw [← hprev, ← hw y, hwy', WordMesh.quotientHom_add]
    have hgy : WordMesh.quotientHom (K := K) G Q hAlt (g y) = 0 :=
      (quotientHom_eq_zero_iff (K := K) G Q hAlt (g y)).mpr (hg y)
    rw [hgy, add_zero]
  · rintro ⟨a, rfl⟩
    exact quotientIncomingMap_previousMap_eq_zero G Q hAlt s x a

end OpConjecture.RepresentationDirected.IyamaMesh.WordMeshRecurrence
