import OpConjecture.RepresentationDirected.SimpleGraphCoxeter
import Mathlib.Combinatorics.SimpleGraph.Finite
import Mathlib.LinearAlgebra.Pi

/-!
# The integral geometric representation of a simple-graph Coxeter group

This file formalizes the coordinate reflection used in the paper,
its simply-laced relations, and the resulting action of the presented
Coxeter group.  The label type is finite because the reflection formula
contains a sum over all neighbors of a vertex.
-/

noncomputable section

namespace OpConjecture.RepresentationDirected.SimpleGraphCoxeter

universe u

variable {L : Type u} [Fintype L]

/-- The integral lattice freely generated by the vertices of the graph. -/
abbrev RootLattice (L : Type u) := L → ℤ

/-- The sum of the coordinates adjacent to a given graph vertex. -/
def neighborSum (G : SimpleGraph L) (i : L) (z : RootLattice L) : ℤ := by
  classical
  exact ∑ h ∈ G.neighborFinset i, z h

/-- The paper's integral simple reflection
`(s_i z)_i = -z_i + ∑_{h ~ i} z_h`, fixing all other coordinates. -/
def simpleReflection (G : SimpleGraph L) (i : L) :
    RootLattice L →ₗ[ℤ] RootLattice L := by
  classical
  refine
    { toFun := fun z j => if j = i then -z i + neighborSum G i z else z j
      map_add' := ?_
      map_smul' := ?_ }
  · intro z w
    funext j
    by_cases hji : j = i
    · subst j
      simp only [if_pos, Pi.add_apply, neighborSum, Finset.sum_add_distrib,
        neg_add_rev]
      ring
    · simp [hji]
  · intro c z
    funext j
    by_cases hji : j = i
    · subst j
      simp only [if_pos, Pi.smul_apply, smul_eq_mul, neighborSum]
      rw [← Finset.mul_sum]
      simp only [RingHom.id_apply]
      ring
    · simp [hji]

@[simp]
theorem simpleReflection_apply_self (G : SimpleGraph L) (i : L)
    (z : RootLattice L) :
    simpleReflection G i z i = -z i + neighborSum G i z := by
  classical
  simp [simpleReflection]

@[simp]
theorem simpleReflection_apply_of_ne (G : SimpleGraph L) {i j : L}
    (hji : j ≠ i) (z : RootLattice L) :
    simpleReflection G i z j = z j := by
  classical
  simp [simpleReflection, hji]

private theorem neighborSum_simpleReflection_self
    (G : SimpleGraph L) (i : L) (z : RootLattice L) :
    neighborSum G i (simpleReflection G i z) = neighborSum G i z := by
  classical
  unfold neighborSum
  apply Finset.sum_congr rfl
  intro h hh
  rw [simpleReflection_apply_of_ne]
  exact (G.ne_of_adj ((G.mem_neighborFinset i h).mp hh)).symm

/-- Every integral simple reflection is an involution. -/
theorem simpleReflection_involutive (G : SimpleGraph L) (i : L) :
    Function.Involutive (simpleReflection G i) := by
  intro z
  funext j
  by_cases hji : j = i
  · subst j
    rw [simpleReflection_apply_self, simpleReflection_apply_self,
      neighborSum_simpleReflection_self]
    ring
  · rw [simpleReflection_apply_of_ne G hji,
      simpleReflection_apply_of_ne G hji]

/-- The integral simple reflection as a linear automorphism. -/
def simpleReflectionEquiv (G : SimpleGraph L) (i : L) :
    RootLattice L ≃ₗ[ℤ] RootLattice L :=
  LinearEquiv.ofInvolutive (simpleReflection G i)
    (simpleReflection_involutive G i)

@[simp]
theorem simpleReflectionEquiv_apply (G : SimpleGraph L) (i : L)
    (z : RootLattice L) :
    simpleReflectionEquiv G i z = simpleReflection G i z := rfl

@[simp]
theorem simpleReflectionEquiv_sq (G : SimpleGraph L) (i : L) :
    simpleReflectionEquiv G i * simpleReflectionEquiv G i = 1 := by
  ext z j
  exact congrFun (simpleReflection_involutive G i z) j

private theorem neighborSum_simpleReflection_of_not_adj
    (G : SimpleGraph L) {i j : L} (hij : ¬ G.Adj i j)
    (z : RootLattice L) :
    neighborSum G i (simpleReflection G j z) = neighborSum G i z := by
  classical
  unfold neighborSum
  apply Finset.sum_congr rfl
  intro h hh
  rw [simpleReflection_apply_of_ne]
  intro hhj
  subst h
  exact hij ((G.mem_neighborFinset i j).mp hh)

/-- Reflections at distinct nonadjacent labels commute. -/
theorem simpleReflectionEquiv_mul_comm_of_ne_of_not_adj
    (G : SimpleGraph L) {i j : L} (hne : i ≠ j) (hij : ¬ G.Adj i j) :
    simpleReflectionEquiv G i * simpleReflectionEquiv G j =
      simpleReflectionEquiv G j * simpleReflectionEquiv G i := by
  ext z h
  by_cases hhi : h = i
  · subst h
    simp only [LinearEquiv.mul_apply, simpleReflectionEquiv_apply,
      simpleReflection_apply_self]
    rw [simpleReflection_apply_of_ne G hne, neighborSum_simpleReflection_of_not_adj G hij]
    rw [simpleReflection_apply_of_ne G hne, simpleReflection_apply_self]
  · by_cases hhj : h = j
    · subst h
      simp only [LinearEquiv.mul_apply, simpleReflectionEquiv_apply,
        simpleReflection_apply_self]
      rw [simpleReflection_apply_of_ne G hne.symm]
      rw [neighborSum_simpleReflection_of_not_adj G
        ((G.adj_comm i j).not.mp hij)]
      rw [simpleReflection_apply_of_ne G hne.symm, simpleReflection_apply_self]
    · simp [LinearEquiv.mul_apply, hhi, hhj]

private theorem neighborSum_simpleReflection_of_adj
    (G : SimpleGraph L) {i j : L} (hij : G.Adj i j)
    (z : RootLattice L) :
    neighborSum G i (simpleReflection G j z) =
      neighborSum G i z - 2 * z j + neighborSum G j z := by
  classical
  unfold neighborSum
  have hjmem : j ∈ G.neighborFinset i :=
    (G.mem_neighborFinset i j).mpr hij
  have herase :
      (∑ h ∈ (G.neighborFinset i).erase j, simpleReflection G j z h) =
        ∑ h ∈ (G.neighborFinset i).erase j, z h := by
    apply Finset.sum_congr rfl
    intro h hh
    rw [simpleReflection_apply_of_ne]
    exact (Finset.mem_erase.mp hh).1
  rw [← Finset.sum_erase_add (G.neighborFinset i)
    (fun h => simpleReflection G j z h) hjmem, herase,
    Finset.sum_erase_eq_sub hjmem, simpleReflection_apply_self]
  simp only [neighborSum]
  ring

/-- Reflections at adjacent labels satisfy the length-three braid relation. -/
theorem simpleReflectionEquiv_braid_of_adj
    (G : SimpleGraph L) {i j : L} (hij : G.Adj i j) :
    simpleReflectionEquiv G i * simpleReflectionEquiv G j *
        simpleReflectionEquiv G i =
      simpleReflectionEquiv G j * simpleReflectionEquiv G i *
        simpleReflectionEquiv G j := by
  have hne : i ≠ j := hij.ne
  have hji : G.Adj j i := (G.adj_comm i j).mp hij
  ext z h
  by_cases hhi : h = i
  · subst h
    simp only [LinearEquiv.mul_apply, simpleReflectionEquiv_apply]
    rw [simpleReflection_apply_self,
      simpleReflection_apply_of_ne G hne,
      simpleReflection_apply_self,
      neighborSum_simpleReflection_of_adj G hij,
      neighborSum_simpleReflection_self,
      simpleReflection_apply_of_ne G hne.symm,
      neighborSum_simpleReflection_of_adj G hji,
      simpleReflection_apply_of_ne G hne,
      simpleReflection_apply_self,
      simpleReflection_apply_of_ne G hne,
      neighborSum_simpleReflection_of_adj G hij]
    ring
  · by_cases hhj : h = j
    · subst h
      simp only [LinearEquiv.mul_apply, simpleReflectionEquiv_apply]
      rw [simpleReflection_apply_of_ne G hne.symm,
        simpleReflection_apply_self,
        simpleReflection_apply_of_ne G hne.symm,
        neighborSum_simpleReflection_of_adj G hji,
        simpleReflection_apply_self,
        simpleReflection_apply_of_ne G hne.symm,
        simpleReflection_apply_self,
        neighborSum_simpleReflection_of_adj G hji,
        neighborSum_simpleReflection_self,
        simpleReflection_apply_of_ne G hne,
        neighborSum_simpleReflection_of_adj G hij]
      ring
    · simp [LinearEquiv.mul_apply, hhi, hhj]

/-- The product of adjacent simple reflections has cube equal to one. -/
theorem simpleReflectionEquiv_mul_pow_three_of_adj
    (G : SimpleGraph L) {i j : L} (hij : G.Adj i j) :
    (simpleReflectionEquiv G i * simpleReflectionEquiv G j) ^ 3 = 1 := by
  calc
    (simpleReflectionEquiv G i * simpleReflectionEquiv G j) ^ 3 =
        (simpleReflectionEquiv G i * simpleReflectionEquiv G j *
          simpleReflectionEquiv G i) *
        (simpleReflectionEquiv G j * simpleReflectionEquiv G i *
          simpleReflectionEquiv G j) := by
      simp only [show (3 : ℕ) = 2 + 1 by omega, pow_succ, pow_zero, one_mul,
        mul_assoc]
    _ = (simpleReflectionEquiv G j * simpleReflectionEquiv G i *
          simpleReflectionEquiv G j) *
        (simpleReflectionEquiv G j * simpleReflectionEquiv G i *
          simpleReflectionEquiv G j) := by
      rw [simpleReflectionEquiv_braid_of_adj G hij]
    _ = simpleReflectionEquiv G j *
        (simpleReflectionEquiv G i *
          ((simpleReflectionEquiv G j * simpleReflectionEquiv G j) *
            (simpleReflectionEquiv G i * simpleReflectionEquiv G j))) := by
      simp only [mul_assoc]
    _ = simpleReflectionEquiv G j *
        (simpleReflectionEquiv G i *
          (simpleReflectionEquiv G i * simpleReflectionEquiv G j)) := by
      rw [simpleReflectionEquiv_sq]
      simp only [one_mul]
    _ = simpleReflectionEquiv G j *
        ((simpleReflectionEquiv G i * simpleReflectionEquiv G i) *
          simpleReflectionEquiv G j) := by
      rw [mul_assoc]
    _ = simpleReflectionEquiv G j * simpleReflectionEquiv G j := by
      rw [simpleReflectionEquiv_sq]
      simp only [one_mul]
    _ = 1 := simpleReflectionEquiv_sq G j

/-- The product of distinct nonadjacent simple reflections has square equal
to one. -/
theorem simpleReflectionEquiv_mul_pow_two_of_ne_of_not_adj
    (G : SimpleGraph L) {i j : L} (hne : i ≠ j) (hij : ¬ G.Adj i j) :
    (simpleReflectionEquiv G i * simpleReflectionEquiv G j) ^ 2 = 1 := by
  calc
    (simpleReflectionEquiv G i * simpleReflectionEquiv G j) ^ 2 =
        simpleReflectionEquiv G i *
          (simpleReflectionEquiv G j * simpleReflectionEquiv G i) *
        simpleReflectionEquiv G j := by simp only [pow_two, mul_assoc]
    _ = simpleReflectionEquiv G i *
          (simpleReflectionEquiv G i * simpleReflectionEquiv G j) *
        simpleReflectionEquiv G j := by
      rw [simpleReflectionEquiv_mul_comm_of_ne_of_not_adj G hne hij]
    _ = 1 := by
      simp only [← mul_assoc, simpleReflectionEquiv_sq, one_mul]

/-- The graph reflections satisfy every relation of the simply-laced
Coxeter matrix. -/
theorem simpleReflectionEquiv_isLiftable (G : SimpleGraph L) :
    CoxeterMatrix.IsLiftable (matrix G) (simpleReflectionEquiv G) := by
  intro i j
  by_cases heq : i = j
  · subst j
    rw [matrix_apply_self, pow_one]
    exact simpleReflectionEquiv_sq G i
  · by_cases hij : G.Adj i j
    · rw [matrix_apply_of_adj G hij]
      exact simpleReflectionEquiv_mul_pow_three_of_adj G hij
    · rw [matrix_apply_of_ne_of_not_adj G heq hij]
      exact simpleReflectionEquiv_mul_pow_two_of_ne_of_not_adj G heq hij

/-- The integral geometric representation of the graph Coxeter group. -/
def geometricRepresentation (G : SimpleGraph L) :
    Group G →* (RootLattice L ≃ₗ[ℤ] RootLattice L) :=
  (system G).lift
    ⟨simpleReflectionEquiv G, simpleReflectionEquiv_isLiftable G⟩

@[simp]
theorem geometricRepresentation_simple (G : SimpleGraph L) (i : L) :
    geometricRepresentation G ((system G).simple i) =
      simpleReflectionEquiv G i := by
  exact (system G).lift_apply_simple
    (simpleReflectionEquiv_isLiftable G) i

/-- The induced group action on the integral root lattice. -/
@[reducible]
def geometricAction (G : SimpleGraph L) :
    MulAction (Group G) (RootLattice L) where
  smul w z := geometricRepresentation G w z
  one_smul z := by
    change geometricRepresentation G 1 z = z
    rw [map_one]
    rfl
  mul_smul w v z := by
    change geometricRepresentation G (w * v) z =
      geometricRepresentation G w (geometricRepresentation G v z)
    rw [map_mul, LinearEquiv.mul_apply]

end OpConjecture.RepresentationDirected.SimpleGraphCoxeter
