import OpConjecture.CategoryTheory.HomIdeal

/-!
# Multiplication and powers of categorical Hom ideals

The product of two two-sided additive Hom ideals is generated by composites
through arbitrary intermediate objects.  This file proves the elementary
ideal arithmetic needed to state nilpotence of a categorical radical and to
deduce separation of its power filtration.
-/

set_option autoImplicit false

noncomputable section

open CategoryTheory

namespace OpConjecture.CategoricalIdeal.HomIdeal

universe v u

variable {C : Type u} [Category.{v} C] [Preadditive C]

/-- Pointwise inclusion of categorical Hom ideals. -/
def IdealLE (I J : HomIdeal C) : Prop :=
  ∀ X Y, I.hom X Y ≤ J.hom X Y

instance : LE (HomIdeal C) := ⟨IdealLE⟩

theorem le_def {I J : HomIdeal C} :
    I ≤ J ↔ ∀ X Y, I.hom X Y ≤ J.hom X Y :=
  Iff.rfl

/-- Two Hom ideals are equal when their Hom subgroups agree pointwise. -/
@[ext]
theorem ext_hom {I J : HomIdeal C}
    (h : ∀ X Y, I.hom X Y = J.hom X Y) :
    I = J := by
  cases I with
  | mk Ih Ipre Ipost =>
      cases J with
      | mk Jh Jpre Jpost =>
          simp only [HomIdeal.mk.injEq]
          funext X Y
          exact h X Y

instance : PartialOrder (HomIdeal C) where
  le := IdealLE
  le_refl I := fun _ _ ↦ le_rfl
  le_trans _ _ _ hIJ hJK := fun X Y ↦
    (hIJ X Y).trans (hJK X Y)
  le_antisymm I J hIJ hJI :=
    ext_hom fun X Y ↦ le_antisymm (hIJ X Y) (hJI X Y)

/-- The zero categorical Hom ideal. -/
def zero (C : Type u) [Category.{v} C] [Preadditive C] : HomIdeal C where
  hom := fun _ _ ↦ ⊥
  precomp := by
    intro X Y Z f g hg
    change g = 0 at hg
    subst g
    simp
  postcomp := by
    intro X Y Z f g hf
    change f = 0 at hf
    subst f
    simp

instance : Bot (HomIdeal C) := ⟨zero C⟩

@[simp]
theorem bot_hom (X Y : C) :
    (⊥ : HomIdeal C).hom X Y = ⊥ :=
  rfl

instance : OrderBot (HomIdeal C) where
  bot := ⊥
  bot_le _ := fun _ _ ↦ bot_le

/-- The whole categorical Hom ideal. -/
def whole (C : Type u) [Category.{v} C] [Preadditive C] : HomIdeal C where
  hom := fun _ _ ↦ ⊤
  precomp := by simp
  postcomp := by simp

instance : Top (HomIdeal C) := ⟨whole C⟩

@[simp]
theorem top_hom (X Y : C) :
    (⊤ : HomIdeal C).hom X Y = ⊤ :=
  rfl

instance : OrderTop (HomIdeal C) where
  top := ⊤
  le_top _ := fun _ _ ↦ le_top

/-- Composites of one morphism from `I` followed by one from `J`. -/
def compositeGenerators (I J : HomIdeal C) (X Z : C) :
    Set (X ⟶ Z) :=
  {h | ∃ (Y : C) (f : X ⟶ Y) (g : Y ⟶ Z),
      f ∈ I.hom X Y ∧ g ∈ J.hom Y Z ∧ f ≫ g = h}

/-- Product of two categorical Hom ideals: the additive subgroup generated
by composites `f ≫ g` with `f ∈ I` and `g ∈ J`. -/
def mul (I J : HomIdeal C) : HomIdeal C where
  hom X Z := AddSubgroup.closure (compositeGenerators I J X Z)
  precomp := by
    intro X Y Z a g hg
    induction hg using AddSubgroup.closure_induction with
    | mem g hg =>
        obtain ⟨M, f, b, hf, hb, rfl⟩ := hg
        apply AddSubgroup.subset_closure
        refine ⟨M, a ≫ f, b, I.precomp a hf, hb, ?_⟩
        simp only [Category.assoc]
    | zero => simp
    | add g h _ _ hg hh =>
        simpa only [Preadditive.comp_add] using add_mem hg hh
    | neg g _ hg =>
        simpa only [Preadditive.comp_neg] using neg_mem hg
  postcomp := by
    intro X Y Z f b hf
    induction hf using AddSubgroup.closure_induction with
    | mem f hf =>
        obtain ⟨M, a, g, ha, hg, rfl⟩ := hf
        apply AddSubgroup.subset_closure
        refine ⟨M, a, g ≫ b, ha, J.postcomp b hg, ?_⟩
        simp only [Category.assoc]
    | zero => simp
    | add f g _ _ hf hg =>
        simpa only [Preadditive.add_comp] using add_mem hf hg
    | neg f _ hf =>
        simpa only [Preadditive.neg_comp] using neg_mem hf

infixl:70 " ⋆ᵢ " => mul

/-- A single allowed composite belongs to the product ideal. -/
theorem comp_mem_mul
    {I J : HomIdeal C} {X Y Z : C}
    {f : X ⟶ Y} {g : Y ⟶ Z}
    (hf : f ∈ I.hom X Y) (hg : g ∈ J.hom Y Z) :
    f ≫ g ∈ (I ⋆ᵢ J).hom X Z :=
  AddSubgroup.subset_closure ⟨Y, f, g, hf, hg, rfl⟩

/-- Multiplication is monotone in both variables. -/
theorem mul_mono
    {I I' J J' : HomIdeal C}
    (hI : I ≤ I') (hJ : J ≤ J') :
    I ⋆ᵢ J ≤ I' ⋆ᵢ J' := by
  intro X Z h hh
  induction hh using AddSubgroup.closure_induction with
  | mem h hh =>
      obtain ⟨Y, f, g, hf, hg, rfl⟩ := hh
      exact comp_mem_mul (hI X Y hf) (hJ Y Z hg)
  | zero => exact zero_mem _
  | add f g _ _ hf hg => exact add_mem hf hg
  | neg f _ hf => exact neg_mem hf

/-- Every product lies in its left factor, since the left factor is closed
under postcomposition. -/
theorem mul_le_left (I J : HomIdeal C) :
    I ⋆ᵢ J ≤ I := by
  intro X Z h hh
  induction hh using AddSubgroup.closure_induction with
  | mem h hh =>
      obtain ⟨Y, f, g, hf, hg, rfl⟩ := hh
      exact I.postcomp g hf
  | zero => exact zero_mem _
  | add f g _ _ hf hg => exact add_mem hf hg
  | neg f _ hf => exact neg_mem hf

/-- Every product lies in its right factor, since the right factor is closed
under precomposition. -/
theorem mul_le_right (I J : HomIdeal C) :
    I ⋆ᵢ J ≤ J := by
  intro X Z h hh
  induction hh using AddSubgroup.closure_induction with
  | mem h hh =>
      obtain ⟨Y, f, g, hf, hg, rfl⟩ := hh
      exact J.precomp f hg
  | zero => exact zero_mem _
  | add f g _ _ hf hg => exact add_mem hf hg
  | neg f _ hf => exact neg_mem hf

@[simp]
theorem top_mul (I : HomIdeal C) :
    ⊤ ⋆ᵢ I = I := by
  apply le_antisymm (mul_le_right _ _) ?_
  intro X Y f hf
  have hcomp :
      (𝟙 X) ≫ f ∈ ((⊤ : HomIdeal C) ⋆ᵢ I).hom X Y :=
    comp_mem_mul (by simp) hf
  simpa using hcomp

@[simp]
theorem mul_top (I : HomIdeal C) :
    I ⋆ᵢ ⊤ = I := by
  apply le_antisymm (mul_le_left _ _) ?_
  intro X Y f hf
  have hcomp :
      f ≫ 𝟙 Y ∈ (I ⋆ᵢ (⊤ : HomIdeal C)).hom X Y :=
    comp_mem_mul hf (by simp)
  simpa using hcomp

@[simp]
theorem bot_mul (I : HomIdeal C) :
    ⊥ ⋆ᵢ I = ⊥ :=
  le_antisymm (mul_le_left _ _) bot_le

@[simp]
theorem mul_bot (I : HomIdeal C) :
    I ⋆ᵢ ⊥ = ⊥ :=
  le_antisymm (mul_le_right _ _) bot_le

/-- Associativity follows from associativity and bilinearity of categorical
composition; the closure induction accounts for finite additive sums. -/
theorem mul_assoc (I J K : HomIdeal C) :
    (I ⋆ᵢ J) ⋆ᵢ K = I ⋆ᵢ (J ⋆ᵢ K) := by
  apply le_antisymm
  · intro X Z h hh
    induction hh using AddSubgroup.closure_induction with
    | mem h hh =>
        obtain ⟨Y, f, g, hf, hg, rfl⟩ := hh
        induction hf using AddSubgroup.closure_induction with
        | mem f hf =>
            obtain ⟨M, a, b, ha, hb, rfl⟩ := hf
            rw [Category.assoc]
            exact comp_mem_mul ha (comp_mem_mul hb hg)
        | zero => simp
        | add f₁ f₂ _ _ hf₁ hf₂ =>
            simpa only [Preadditive.add_comp] using add_mem hf₁ hf₂
        | neg f _ hf =>
            simpa only [Preadditive.neg_comp] using neg_mem hf
    | zero => exact zero_mem _
    | add h₁ h₂ _ _ hh₁ hh₂ => exact add_mem hh₁ hh₂
    | neg h _ hh => exact neg_mem hh
  · intro X Z h hh
    induction hh using AddSubgroup.closure_induction with
    | mem h hh =>
        obtain ⟨Y, f, g, hf, hg, rfl⟩ := hh
        induction hg using AddSubgroup.closure_induction with
        | mem g hg =>
            obtain ⟨M, a, b, ha, hb, rfl⟩ := hg
            rw [← Category.assoc]
            exact comp_mem_mul (comp_mem_mul hf ha) hb
        | zero => simp
        | add g₁ g₂ _ _ hg₁ hg₂ =>
            simpa only [Preadditive.comp_add] using add_mem hg₁ hg₂
        | neg g _ hg =>
            simpa only [Preadditive.comp_neg] using neg_mem hg
    | zero => exact zero_mem _
    | add h₁ h₂ _ _ hh₁ hh₂ => exact add_mem hh₁ hh₂
    | neg h _ hh => exact neg_mem hh

/-- Right-recursive powers of a categorical Hom ideal.  The zeroth power is
the whole Hom ideal. -/
def pow (I : HomIdeal C) : ℕ → HomIdeal C
  | 0 => ⊤
  | n + 1 => pow I n ⋆ᵢ I

@[simp]
theorem pow_zero (I : HomIdeal C) : pow I 0 = ⊤ :=
  rfl

@[simp]
theorem pow_succ (I : HomIdeal C) (n : ℕ) :
    pow I (n + 1) = pow I n ⋆ᵢ I :=
  rfl

@[simp]
theorem pow_one (I : HomIdeal C) : pow I 1 = I := by
  rw [show 1 = 0 + 1 by rfl, pow_succ, pow_zero, top_mul]

/-- Powers also have the left-recursive form. -/
theorem pow_succ_eq_mul_pow (I : HomIdeal C) :
    ∀ n : ℕ, pow I (n + 1) = I ⋆ᵢ pow I n
  | 0 => by simp
  | n + 1 => by
      calc
        pow I ((n + 1) + 1) = pow I (n + 1) ⋆ᵢ I :=
          pow_succ I (n + 1)
        _ = (I ⋆ᵢ pow I n) ⋆ᵢ I := by
          rw [pow_succ_eq_mul_pow I n]
        _ = I ⋆ᵢ (pow I n ⋆ᵢ I) := mul_assoc I (pow I n) I
        _ = I ⋆ᵢ pow I (n + 1) := by rw [← pow_succ]

/-- Pointwise inclusion is preserved by every power. -/
theorem pow_mono {I J : HomIdeal C} (hIJ : I ≤ J) :
    ∀ n, pow I n ≤ pow J n
  | 0 => le_rfl
  | n + 1 => mul_mono (pow_mono hIJ n) hIJ

/-- Ideal powers form a descending chain. -/
theorem pow_succ_le_pow (I : HomIdeal C) (n : ℕ) :
    pow I (n + 1) ≤ pow I n :=
  mul_le_left _ _

/-- Larger exponents give smaller powers. -/
theorem pow_le_pow_of_le (I : HomIdeal C) {m n : ℕ}
    (hmn : m ≤ n) :
    pow I n ≤ pow I m := by
  induction hmn with
  | refl => exact le_rfl
  | @step n hmn ih =>
      exact (pow_succ_le_pow I n).trans ih

/-- The pointwise intersection of all powers. -/
def powerIntersection (I : HomIdeal C) : HomIdeal C where
  hom X Y := ⨅ n, (pow I n).hom X Y
  precomp := by
    intro X Y Z f g hg
    simp only [AddSubgroup.mem_iInf] at hg ⊢
    intro n
    exact (pow I n).precomp f (hg n)
  postcomp := by
    intro X Y Z f g hf
    simp only [AddSubgroup.mem_iInf] at hf ⊢
    intro n
    exact (pow I n).postcomp g (hf n)

@[simp]
theorem mem_powerIntersection_iff
    {I : HomIdeal C} {X Y : C} {f : X ⟶ Y} :
    f ∈ (powerIntersection I).hom X Y ↔
      ∀ n, f ∈ (pow I n).hom X Y := by
  simp [powerIntersection]

/-- A categorical Hom ideal is nilpotent if one of its powers is zero. -/
def IsNilpotent (I : HomIdeal C) : Prop :=
  ∃ N : ℕ, pow I N = ⊥

/-- Nilpotence forces the intersection of all powers to vanish. -/
theorem powerIntersection_eq_bot_of_isNilpotent
    {I : HomIdeal C} (hI : IsNilpotent I) :
    powerIntersection I = ⊥ := by
  obtain ⟨N, hN⟩ := hI
  apply le_antisymm
  · intro X Y f hf
    have hfN : f ∈ (pow I N).hom X Y :=
      (mem_powerIntersection_iff.mp hf) N
    rw [hN] at hfN
    exact hfN
  · exact bot_le

/-- Elementwise form of the same separatedness conclusion. -/
theorem eq_zero_of_mem_every_power
    {I : HomIdeal C} (hI : IsNilpotent I)
    {X Y : C} {f : X ⟶ Y}
    (hf : ∀ n, f ∈ (pow I n).hom X Y) :
    f = 0 := by
  obtain ⟨N, hN⟩ := hI
  have hfN := hf N
  rw [hN] at hfN
  simpa using hfN

end OpConjecture.CategoricalIdeal.HomIdeal
